### ISSUE TITLE
Wrongly styled header in Best Practices guide

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-documentation#1028]
@korneevaed commented on [Tue Oct 09 2018](https://github.com/cypress-io/cypress/issues/2577)

### Is this a Feature or Bug?
Bug

### Current behavior:

https://docs.cypress.io/guides/references/best-practices.html
Header "## Setting a global baseUrl" looks like paragraph text.

### Desired behavior:
It should look like a header. Please add styling

### Steps to reproduce:

1. https://docs.cypress.io/guides/references/best-practices.html
2. Scroll to the second last section

### Versions
Just docs

**Comment by richdouglasevans** [comment]
I believe this is already sorted by the community and Jennifer in #1025... all that's required is publishing.
