### ISSUE TITLE
UI - Cypress logo scaling issue

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-documentation#1032]
docs.cypress.io:
### current (css width 100px)
![image](https://user-images.githubusercontent.com/14625260/46714395-346bb700-cc29-11e8-837b-92016edf72f8.png) 
### expected (css width 102px)
![image](https://user-images.githubusercontent.com/14625260/46714495-ae9c3b80-cc29-11e8-8049-03ecbf7ee9ef.png)

docs cypress logo looks blurred because it's scaled to 100px. We should consider using an image already sized.

**Comment by Montette** [comment]
I see also something else, I think it should be vertically centered

![shu_wda2do0](https://user-images.githubusercontent.com/34797690/47201226-6ee7f900-d379-11e8-8d1c-075659b6b367.png)

 And on the screen that are exactly 769px it looks like below

![shu_k9k2919](https://user-images.githubusercontent.com/34797690/47201373-e027ac00-d379-11e8-9009-3ae8b198ac17.png)

is this the intended effect or it should be fixed? I could deal with this issue

**Comment by Bkucera** [comment]
I believe the vertical issue is solved but not the scaling issue causing a blurry looking logo

**Comment by GeraAlcantara** [comment]
Can I work on this ?

**Comment by jennifer-shehane** [comment]
@GeraAlcantara Yes!

**Comment by AndrewGorman** [comment]
This appears to be resolved. Vertical alignment looks as expected, and the logo is now 102px wide and appears to be sharp.
