### ISSUE TITLE
Document that cy.clearLocalStorage and cy.clearCookies only clears them for the current domain (including subdomain)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1034]
Open issues for this behavior to change and could be referenced:
- LocalStorage: https://github.com/cypress-io/cypress/issues/2573
- ClearCookies: https://github.com/cypress-io/cypress/issues/408

**Comment by murrutiar** [comment]
Hello, I would like to contribute by adding this to the docs.

**Comment by nids2307** [comment]
which cypress version will have this fix incorporated?
