### ISSUE TITLE
Scrollbar present / not styled on long lines of terminal commands

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#1043]
Doc: https://docs.cypress.io/guides/guides/parallelization.html#Grouping-by-spec-context

![screen shot 2018-10-11 at 4 51 45 pm](https://user-images.githubusercontent.com/1268976/46833401-8bcb6d80-cd76-11e8-9d7f-e460a1402ac4.png)

**Comment by jennifer-shehane** [comment]
I don't see this scrollbar when I view the page, even when I make the width of the page smaller. 
<img width="711" alt="screen shot 2018-10-11 at 5 41 33 pm" src="https://user-images.githubusercontent.com/1271364/46835733-131bdf80-cd7d-11e8-86be-720b5c365996.png">

**Comment by jennifer-shehane** [comment]
Closing - was specific to OS settings
