### ISSUE TITLE
Document how to cause the test to fail after catching "fail" events.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1045]
From [this comment](https://github.com/cypress-io/cypress/issues/2538#issuecomment-429213541), we should document how to have the test fail when listening to "fail" events like:

```js
Cypress.on("fail", (err, runnable) => {
  // do what you want here 
  // then fail test by returning err
  throw err 
})
```

Place to document: https://docs.cypress.io/api/events/catalog-of-events.html#Catching-Test-Failures

**Comment by beaugunderson** [comment]
This does not work; defining `Cypress.on("fail", (err, runnable) => { return err; });` still makes every test pass.

**Comment by beaugunderson** [comment]
https://github.com/cypress-io/cypress/issues/2661#issuecomment-433330674

**Comment by markadrake** [comment]
Sorry, this isn't explained very well for someone new to testing. If I use `assert.fail()` to purposely fail a test, why then does Cypress require me to catch the error myself and report it a second time? Shouldn't the test just fail as it was explicitly told to? In what situation would a web engineer or QA person write in a fail condition, but want to override it and allow the test to pass? Or for the rest of the test to execute for that matter?

Should I not use `asset.fail` from the Chai framework? What method should I use when I detect an irreconcilable condition and want to fail and finish the test?

Thanks for any clarification on what I may be doing wrong.
