### ISSUE TITLE
Issue in install Cypress from zip folder as I am accessing behind corporate network. Creating this issue with reference to #761 as solution is not working :(

### ISSUE THREAD

**Issue by Chinmayans44** [cypress-io/cypress-documentation#1069]
SET CYPRESS_INSTALL_BINARY=C:/Users/chinmaya.s/Downloads/cypress.zip && npm install cypress@3.0.0
Using above command and trying to access local C drive in which zip folder exists. But getting below error.
```
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/C:/Users/chinmaya.s/Downloads/cypress.zip?platform=win32&arch=x64
Error: getaddrinfo EAI_AGAIN download.cypress.io:443
-------------------------------------------------------------------------------------------------
```
Url is concat and it is not taking the correct url. I saw same type of issue being raised, but solution mentioned is not working for me.

**Comment by Bkucera** [comment]
@Chinmayans44 make sure your file path is 100% correct, otherwise cypress will assume it's a URL.

Is `C:/Users/chinmaya.s/Downloads/cypress.zip` supposed to have `chinmaya.s` ?

**Comment by Chinmayans44** [comment]
@Bkucera I verified the path and it is correct. I tried giving path using / and \ , both not working :(
It is accepting my local path as version i think and trying to hit url with concatenated url. Is there any other solution i can try over here? 
In this url, cypress version is replaced with my local path given and concatenated url looks like this.
URL: https://download.cypress.io/desktop/C:/Users/chinmaya.s/Downloads/cypress.zip?platform=win32&arch=x64

**Comment by Bkucera** [comment]
@Chinmayans44 can you try moving Cypress.zip to a different location?

**Comment by jennifer-shehane** [comment]
Closing this. 

This repo is only for issues relating to Cypress' documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). 

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
