### ISSUE TITLE
Document how to use ESLint plugin for Cypress

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#107]
Related to: https://github.com/cypress-io/cypress/issues/602

**Comment by chrisbreiding** [comment]
@jennifer-shehane, @brian-mann: Plugin is published: https://www.npmjs.com/package/eslint-plugin-cypress

Where/how should we document this?

**Comment by brian-mann** [comment]
We should document this in the installation guide as a blue note, and then add it to the Plugins page, since its exactly what a plugin is!

**Comment by MikeMcC399** [comment]
1. What additional information is expected for this issue above that which is already provided by [cypress-io/eslint-plugin-cypress > README](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md)?

2. `eslint-plugin-cypress` is already listed on the [Plugins list](https://docs.cypress.io/plugins#development-tools)

**Comment by chrisbreiding** [comment]
The eslint plugin is mentioned in the [Writing Your E2E First test guide](https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test#Write-your-first-test) and, as you pointed out, @MikeMcC399, it's in the plugins list already. I don't think there's anything more expected, so we can close this.
