### ISSUE TITLE
Add "Get the latest updates from Cypress" webinar to screencasts section

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-documentation#1070]
Edit https://github.com/cypress-io/cypress-documentation/blob/develop/source/_data/screencasts.yml to include the "Get the latest updates from Cypress" webinar which occurred on Tuesday, October 16, 2018.

YouTube Link: https://www.youtube.com/watch?v=FfqD1ExUGlw

**Comment by ChrisTriesToCode** [comment]
i can do it ^^
