### ISSUE TITLE
Document that Cypress.env() parses booleans

### ISSUE THREAD

**Issue by beaugunderson** [cypress-io/cypress-documentation#1087]
Given `CYPRESS_IS_TRAVIS=true cypress open`, when I run `Cypress.env()` in the developer tools it returns:

```
{
  IS_TRAVIS: true
}
```

I would expect it to instead return this based on the docs:

```
{
   IS_TRAVIS: 'true'
}
```

Because the documentation does not mention that string values like "true" are parsed into boolean values.

**Comment by beaugunderson** [comment]
I found this in the configuration docs:

> We automatically normalize both the key and the value. Cypress will strip off the CYPRESS_, camelcase any keys and automatically convert values into Number or Boolean. Make sure to prefix your environment variables with CYPRESS_ else they will be ignored.

So it is documented, but not on the page for `Cypress.env`. I think that would also be a good place for it. :)

**Comment by darellkoh** [comment]
@beaugunderson I'd love to take this issue if it's still up for grabs!

**Comment by jennifer-shehane** [comment]
Hey @darellkoh, sounds great!

**Comment by darellkoh** [comment]
@jennifer-shehane Thanks so much, I'll work on getting a PR ready and reach out if any questions arise!

**Comment by darellkoh** [comment]
Hi @jennifer-shehane,  I'm rather new to open-source, so just wanted to clarify: 
Is it more helpful to include the explanation in Q&A format under the [Notes](http://localhost:2222/api/cypress-api/env.html#Notes) section for `Cypress.env()`, or the [Example](http://localhost:2222/api/cypress-api/env.html#Examples) section? 

Thanks in advance!

**Comment by jennifer-shehane** [comment]
I would likely put this in the Examples section showing an example of the usage above and saying something like:

>We automatically normalize both the key and the value. Cypress will automatically convert values into Number or Boolean.

**Comment by isabellabrookes** [comment]
@jennifer-shehane looking to pick this up. 
Do we know if the `CYPRESS_` prefix works in the cypress.json also or is it just for command line?
