### ISSUE TITLE
Add applitools and percy to plugins

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1093]
Within [plugins](https://github.com/cypress-io/cypress-documentation/blob/develop/source/_data/plugins.yml) under 'Development Tools' need to add

- name: Percy
  description: Visual regression testing for Cypress tests with Percy.
  link: https://docs.percy.io/docs/cypress
  keywords: [screenshots, visual regression]

- name: Applitools
  description: Fast, easy and reliable visual UI testing with Cypress
  link: https://applitools.com/tutorials/cypress.html
  keyword: [screenshots, visual regression, visual-ai]

**Comment by alsargent** [comment]
Thanks @jennifer-shehane for request this change. I'd suggest using this as the Applitools/Cypress tutorial: https://applitools.com/tutorials/cypress.html

**Comment by alsargent** [comment]
Also, may I suggest another keyword for Applitools: visual-ai
