### ISSUE TITLE
Debug the moment a test fails

### ISSUE THREAD

**Issue by MickaelTH** [cypress-io/cypress-documentation#1128]
Hi,

If follow this part https://docs.cypress.io/api/events/catalog-of-events.html#Debug-the-moment-a-test-fails CY will show "ReferenceError: error is not defined"

![2018-11-08 003336](https://user-images.githubusercontent.com/26375917/48196928-92a1cc00-e386-11e8-9751-24f1d4d8c869.png)

The correct sample should be:

```
Cypress.on('fail', (error, runnable) => {
    debugger

    // we now have access to the err instance
    // and the mocha runnable this failed on

    throw error
})
```

**Comment by jennifer-shehane** [comment]
Hey @MickaelTH, I'm not experiencing this same issue with my simple example. Could you post the entire test code you ran (excluding any sensitive information)?

**Comment by jennifer-shehane** [comment]
I'm still not experiencing this issue in 3.1.1 with the on 'fail' in my support file. You'll need to produce a reproducible example of the exact test code you have. 

<img width="1379" alt="screen shot 2018-11-08 at 11 51 19 am" src="https://user-images.githubusercontent.com/1271364/48213879-c233e280-e34c-11e8-907a-0b23647ab2be.png">

**Comment by MickaelTH** [comment]
Hi Jennifer

I see on your screenshot that you use the code I provided to be changed so you confirmed it is working.

But the doc said to use err instead of error

Cypress.on('fail', (err, runnable)

If you try it as per the doc it should failed.

**Comment by jennifer-shehane** [comment]
Ahhh, yes! I see what you are saying now. I'll fix this.
