### ISSUE TITLE
Clarify that one should define cy.route() before cy.visit()

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1135]
I see this as a holdup point for many people. 

https://github.com/cypress-io/cypress/issues/2748#issuecomment-437423132

**Comment by csi-lk** [comment]
I can pick this up, did you want something like this under [Usage](https://docs.cypress.io/api/commands/route.html#Usage)?

```
{% note info %}
`cy.route()` will stub XHR requests from when it is defined, if you need to stub requests required for the page to load make sure you define them before `cy.visit()`
{% endnote %}
```

**Comment by jennifer-shehane** [comment]
@csi-lk Yes, please pick this up if you have the time! 🙌 	

I don't think that I would mention 'stubbing' - regardless of the route being stubbed or not - they should define routes that they want to *listen to* before the cy.visit(). 

Maybe something like

>To listen for XHR requests made when the application under test is loading, make sure you define the `cy.route()` before `cy.visit()`.

I don't think that everyone sees `cy.route()` as more of setting up a *listener* than the actual time the XHR request happens. We should change the verbiage to explain this better.

**Comment by jennifer-shehane** [comment]
cy.route() is now deprecated and will be removed from the docs. Closing.
