### ISSUE TITLE
Add new diagrams from public website 

### ISSUE THREAD

**Issue by anjanab96** [cypress-io/cypress-documentation#1142]
- [x] parallelization diagram 
- [x] load balancing chart 
- [x] grouping diagram

**Comment by anjanab96** [comment]
@jennifer-shehane What release should this go inside?

**Comment by jennifer-shehane** [comment]
There won't be a specific release for this - as soon as the PR looks good we'll push it out. 

Let me know if you need any help getting the docs running locally.

**Comment by anjanab96** [comment]
@jennifer-shehane I got the docs running locally without issues! Should these I be adding .png versions of these diagrams to the docs?

**Comment by jennifer-shehane** [comment]
Whatever is good quality and not too large in file size.
