### ISSUE TITLE
Incomplete statement describing default timeout values

### ISSUE THREAD

**Issue by avanslaars** [cypress-io/cypress-documentation#115]
At the bottom of the "Default Values" heading for Timeouts on the [Introduction To Cypress Guide](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Values) there is an incomplete sentence

> One of the typical anti-patterns we see is not properly

This line is cut-off at "properly".

**Comment by bahmutov** [comment]
That's when hurricane Irma cut off power in GA

**Comment by avanslaars** [comment]
Makes sense ;)
