### ISSUE TITLE
Explain how to use meta keys with .click()

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#1151]
We don't currently explain that when using `.click()` you can utilize meta keys from a previous `.type('{meta}, { release: false })`

An example of a confused user: https://github.com/cypress-io/cypress/issues/2795

In the `.click()` docs we need to give usage examples / notes of this specific use case.

We do explain this behavior in the `.type()` API, but unless you're aware of that you'll likely miss this entirely.

**Comment by mackey7** [comment]
I will take it.
