### ISSUE TITLE
Add supported OS Versions to installation docs

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#117]
The Cypress Test Runner (desktop app) supports whatever OS versions Electron supports. This should be specified in the installation docs. [Original Electron document](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md)

- Mac: macOS 10.9+
- ~Windows: Windows 7+~ (coming soon)
- Linux: Ubuntu 12.04+, Fedora 21, Debian 8

**Comment by arnazmursidp** [comment]
Hi, i want to contribute with this branch, i'm a first timer, thank you!
