### ISSUE TITLE
Table headers not expanding for full width of table

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress-documentation#1183]
Played around a bit with border-collapse and 100% width but couldn't get it quite right.
<img width="900" alt="screen shot 2018-11-30 at 4 00 28 pm" src="https://user-images.githubusercontent.com/7514489/49317202-8b6f6900-f4c1-11e8-960f-931afb07f416.png">

**Comment by jennifer-shehane** [comment]
@anjanab96 Maybe you can look into this? The table rows do not extend the full width of the table sometimes. Especially noticeable on http://docs.cypress.io/guides/references/assertions.html

**Comment by anjanab96** [comment]
@lilaconlee @jennifer-shehane Are you guys experiencing this at a specific screen width? I can't see to recreate this, it seems to extends the full width of the table on my laptop

**Comment by lilaconlee** [comment]
I'm getting it whenever the width of the table is larger than the width of the content, which for the chainable getters example seems to be 1300+ for me.

**Comment by softgengaurav** [comment]
I also want to contribute to this issue. But, I am not able to find this html or css file in the code repository of the cypress-documentation. Can you please help me out?

**Comment by jennifer-shehane** [comment]
Hey @softgengaurav of course! Let us know if you have any issues getting started.

**Comment by softgengaurav** [comment]
Hi @jennifer-shehane , after setting up the repository on my local machine (according to CONTRIBUTING.MD) , when i make changes in any file and run **npm start** , changes are not reflected in the documentation at localhost:2222.
Can you help me in this?

**Comment by jennifer-shehane** [comment]
Hey @softgengaurav, that should definitely not be the case. The localhost:2222 should update upon refresh as long as there are no errors printed to the terminal on or after running 'npm start'. Ensure no errors have been logged to the terminal.

**Comment by softgengaurav** [comment]
Should I go for **npm run build** also each time as I make change, or just npm start??
Because I am getting no error messages on terminal !!

**Comment by anjanab96** [comment]
@softgengaurav You shouldn't have to do **npm run build** and **npm start** everytime you make a change. Are you making changes to the files in the public folder? If so, it will not update on localhost:2222. Make sure you're editing the HTML and CSS in 'themes/cypress/layout/' and 'themes/cypress/source/css/_partial'

**Comment by softgengaurav** [comment]
Yes, I was making the changes in the public folder. Thank you for the solution !!
