### ISSUE TITLE
Add examples of using the optional selector argument for `cy.contains`

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#123]

**Comment by richdouglasevans** [comment]
Can this ticket be `Closed`?

**Comment by jennifer-shehane** [comment]
Yes - in the future you should be able to write in your PR comments `close #123` if you feel it completely addresses the issue. This will automatically close the issue when merged into `develop`

**Comment by richdouglasevans** [comment]
> [You] should be able to write in your PR comments close #123 if you feel it completely addresses the issue.

Wah? _:: headdesk ::_ 🤕😮:flushed:

I did not know one [could do this](https://help.github.com/articles/closing-issues-using-keywords/). Thanks for the schoolin' Jennifer... always something to learn 😄Sorry for asking you if all those tickets could be closed.

Hah! 😆😊
