### ISSUE TITLE
Show how to run Cypress for non-Node projects

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1262]
Related to https://github.com/cypress-io/cypress/issues/2999

When building projects that require non-Node environment, like Python, need to show how to use multiple Docker images - one to run the server without Cypress dependencies, but a Cypress image to run Cypress tests

good idea to add it as a test project to Cypress build pipeline

**Comment by jennifer-shehane** [comment]
This would probably be good in the Continuous Integration doc
