### ISSUE TITLE
Record key is hidden (not being escaped properly)

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#128]
![screen shot 2017-10-09 at 12 35 15 pm](https://user-images.githubusercontent.com/1268976/31348670-5eee63ca-acee-11e7-83cf-09e6aae396f0.png)

**Comment by jennifer-shehane** [comment]
Anything written with shell code like `<thing>` is not escaped properly:

example:
```shell
npm install <plugin name> --save-dev
```

![screen shot 2017-11-09 at 12 58 50 pm](https://user-images.githubusercontent.com/1271364/32621428-c2c4fbb2-c54d-11e7-9c53-695ef6504de9.png)

**Comment by jennifer-shehane** [comment]
Ok, I found an actual solution to this. it is required by HTML spec that, at least, `<` and `>` symbols should be escaped, even inside code blocks, I'm sure there's some bug in the `hexo-renderer-marked` plugin that isn't doing this properly as you can see in the HTML that is produced below:

![screen shot 2017-11-09 at 1 08 48 pm](https://user-images.githubusercontent.com/1271364/32621860-352ffeda-c54f-11e7-944c-7c7a8856d020.png)

Replacing the `<` and `>` with their respective escaped HTML chars `&lt;` and `&gt;` fixes this issue:

```shell
npm install &lt;plugin name&gt; --save-dev
```
