### ISSUE TITLE
Incorrect type definitions for `.then`

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress-documentation#1293]
According to the documentation for `.then`, `options` optionally come first: https://docs.cypress.io/api/commands/then.html
```ts
.then(callbackFn)
.then(options, callbackFn)
```

The type definitions for `.then` put options optionally after the callback.

The following code works at runtime, but has Typescript errors
```ts
const sleep = time => new Promise(resolve => setTimeout(resolve, time))

cy.wrap(5000)
  .then({ timeout: 6000 }, sleep) // TS error, but works at runtime
```

There are 2 ways to fix this:
1. Fix type definitions to be consistent with documentation and runtime. This is the easiest and has no breaking changes or modifications to runtime code. Nothing will break in the field
1. Fix runtime to have options after callback. This is consistent with other commands. To prevent breaking changes, both orders would have to be supported using runtime detection of the arguments. The type signature would remain unchanged.

**Comment by bahmutov** [comment]
so we are going with the current docs and implementation that puts `options` first, and callback second. Types fixed in https://github.com/cypress-io/cypress/pull/3105
