### ISSUE TITLE
Document how to change project access

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1301]
Give step by step directions on how to change the status of a project ('public' to 'private', etc) including pictures of UI below within https://docs.cypress.io/guides/core-concepts/dashboard-service.html#Public-vs-Private

Click into the project you'd like to change access to, then click "Settings" in the top right corner. Here you will see a section displaying "Access to Runs". Choose the appropriate access you'd like to assign for the project here.

<img width="864" alt="screen shot 2019-01-12 at 3 35 05 am" src="https://user-images.githubusercontent.com/1271364/51058426-51929600-161b-11e9-8631-155d92b6acdf.png">

<img width="852" alt="screen shot 2019-01-12 at 3 35 26 am" src="https://user-images.githubusercontent.com/1271364/51058437-58b9a400-161b-11e9-8039-bb4b5daa8ca8.png">

**Comment by karan1205** [comment]
I would like to contribute. Add me please.

**Comment by jennifer-shehane** [comment]
Great @karan1205! Check out our [Contributing guidelines](https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md) and ask any questions you have along the way.
