### ISSUE TITLE
Malformed code snippet on introduction to Cypress page

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress-documentation#1315]
Found here: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions

<img width="867" alt="screen shot 2019-01-17 at 2 53 46 pm" src="https://user-images.githubusercontent.com/7514489/51351312-9de03a80-1a4e-11e9-89eb-6b706dd0e739.png">

**Comment by bahmutov** [comment]
@jennifer-shehane you have merged https://github.com/cypress-io/cypress-documentation/pull/1319 - should this issue be closed?

**Comment by jennifer-shehane** [comment]
No, I didn't really fix the issue entirely. Code blocks within notes are still malformed and do not respect syntax highlighting appropriate with their indicated language.

**Comment by olore** [comment]
Maybe this can be closed? I can't find any broken-looking code blocks.

@jennifer-shehane if you have some specific examples, please point me at them & I will see if I can fix them. Thanks!
