### ISSUE TITLE
Could i translation to chinese?

### ISSUE THREAD

**Issue by icelemon1314** [cypress-io/cypress-documentation#1327]
Hi cypress teams:

    As the title says,i want to translation the doc to chinese.
    I'm notice this issues : https://github.com/cypress-io/cypress-documentation/issues/602.
    I follow the step to init my project and make a copy for zh-cn dir,It's correct?
    
![image](https://user-images.githubusercontent.com/4556804/51451780-e9a62300-1d71-11e9-908f-f0897897d77a.png)

**Comment by jennifer-shehane** [comment]
Hey @icelemon1314, yes, this looks correct! 👍

**Comment by icelemon1314** [comment]
Thanks for getting back to me.

Now i have a problem for how could i access the translation page through the browser?

For example,if i like to access the Why Cypress page,the url is http://localhost:2222/guides/overview/why-cypress.html

So if i want to access the translation page,what is the correct url? Is it http://localhost:2222/zh-cn/guides/overview/why-cypress.html ? 

After i build the source,i can see a public/zh-cn dir,but the html files is all empty.Should i miss some configure?

**Comment by icelemon1314** [comment]
ok,i will look it.Thanks.

**Comment by icelemon1314** [comment]
![image](https://user-images.githubusercontent.com/4556804/51971583-75c3f300-24b4-11e9-862c-e3b5ee555319.png)

After some attempts,i basically completed multi-language support.

Translation will continue to practice for a long time.How do I submit the code? Make a PR or create a new branch?

**Comment by jennifer-shehane** [comment]
@icelemon1314 🎉Please submit a pull request as outlined in our Contributing Doc https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md#committing-code

**Comment by cypress-zh** [comment]
@icelemon1314 Hi, lemon, so my buddies and I would like to join u to do some of the translating work, can we make a synchronization or distribute tasks or share ideas with QICI or weChat?

**Comment by cypress-zh** [comment]
@icelemon1314 Very great work for cypress translation:) and hope join u to do something.

**Comment by icelemon1314** [comment]
@cypress-zh Of course yes, but i am busy now, so the translation is stopped. I'm glad to see you to join us. Can u send your wechat account to my email box and i will add you.

**Comment by cypress-zh** [comment]
> @cypress-zh Of course yes, but i am busy now, so the translation is stopped. I'm glad to see you to join us. Can u send your wechat account to my email box and i will add you.

I've sent an email to ur email box, icelemon1024@gmail.com, looking forward ur reply.

**Comment by jennifer-shehane** [comment]
I've merged these in. There are likely still more improvements that can be made. Please comment here for any improvements you need: https://github.com/cypress-io/cypress-documentation/issues/1686

**Comment by viraxslot** [comment]
> After i build the source, i can see a public/zh-cn dir, but the html files is all empty. Should i miss some configure?

@icelemon1314 Hi, I have the same problem when try to add a new language and I don't understand why. I did all the steps from "contributing" document, but still nothing. Could you please help?

**Comment by jennifer-shehane** [comment]
Great! I will add this to the Readme. It's a WIP 👍
