### ISSUE TITLE
Show how to pass several environment variables via CLI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1329]
For https://github.com/cypress-io/cypress/issues/3178

We only show a single variable, need to show how to pass several

<img width="884" alt="screen shot 2019-01-21 at 4 28 11 pm" src="https://user-images.githubusercontent.com/2212006/51499796-a364ba00-1d99-11e9-8802-f0224b83655f.png">

```shell
# pass strings
npx cypress run --env x=foo,y=bar
# pass numbers, and they will be automatically converted to numbers
npx cypress run --env x=1,y=2
# pass an object using JSON
npx cypress run --env obj='{"foo":"bar"}'
```

**Comment by nathan5x** [comment]
@bahmutov - Can you help support this?
https://github.com/cypress-io/cypress/issues/3178#issuecomment-1646236354

**Comment by bahmutov** [comment]
I’m afraid I am not the best person to add this Sent from my iPhoneOn Jul 24, 2023, at 16:16, Sabarinathan Masilamani ***@***.***> wrote:﻿
@bahmutov - Can you help support this?
cypress-io/cypress#3178 (comment)
