### ISSUE TITLE
Add {home} and {end} to supported sequences in cy.type()

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1344]
Add to https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/type.md#L44

Dependent on PR being released: https://github.com/cypress-io/cypress/pull/3071

**Comment by silviuavram** [comment]
I can take this one, since it's following up my changes.

**Comment by silviuavram** [comment]
Created the PR, @jennifer-shehane . Please take a look. Can you also tell me why for Up/Arrow it says that the cursor does not move, but we actually move it? What am I missing there?

**Comment by Bkucera** [comment]
@silviuavram good find, our docs need to be updated, since the up/down arrow **does** move the cursor as of 3.0.3

you could go ahead and update that if you want

**Comment by silviuavram** [comment]
pushed the changes.
