### ISSUE TITLE
Document how to support custom commands for Intelligent Code Completion (TypeScript)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1354]
Instructions from: https://github.com/cypress-io/cypress/issues/2293#issuecomment-412034813

**Comment by dwilches** [comment]
For people coming here searching for the docs, they are on this page:
https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Triple-slash-directives

**Comment by jennifer-shehane** [comment]
Yah, this is also covered here: https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands
