### ISSUE TITLE
Update parallelization page with ci build id and specs explanation

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1356]
## Part 1

In https://docs.cypress.io/guides/guides/parallelization.html#CI-Build-ID-environment-variables-by-provider under environment variables we need to add example how to override the default value. For example for Jenkins we use `BUILD_NUMBER` but some people might think `BUILD_TAG` is better, so we should show

```
cypress run --record --parallel --ci-build-id $BUILD_TAG
```

There is a link with a single mention of `ci-build-id` above

<img width="865" alt="screen shot 2019-01-28 at 9 30 50 am" src="https://user-images.githubusercontent.com/2212006/51842726-8a02c700-22df-11e9-8331-8d869a0ff4ae.png">

## Part 2

A user has asked how the dashboard gets the list of specs to load balance - and I had to explain that the test runner is sending them on the start. I don't see it explained in the page, so we should mention that the first thing the test runner does is sending them to the service.

**Comment by bahmutov** [comment]
For second part, the confusion is from the way the first steps is described in

<img width="800" alt="screen shot 2019-01-28 at 1 15 18 pm" src="https://user-images.githubusercontent.com/2212006/51856898-ddd0d880-22fe-11e9-9d97-695319c0c5a8.png">

I mean, what is "CI machines contact the Cypress Dashboard Service to indicate which spec files to run in the project."

**Comment by kusumkappdirect** [comment]
Can cypress parallelization work with argo-cd ?
