### ISSUE TITLE
Clarify that cy.route and cy.server do not support non-XHR network requests

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress-documentation#1391]
I was trying to use cy.route to stub out a page load, couldn't figure out why it wasn't working. Then I 
 asked Ben why my code wasn't working out and he informed me that cy.route only intercepts XHR's.

Right now, the following warning is displayed on the route and server API pages:

![image](https://user-images.githubusercontent.com/1151760/52243098-a639d180-28a6-11e9-916a-52bf4f8aff5f.png)

To me, this reads "cy.route does not support fetch requests, but it DOES support every other type of network request". 

This should probably be rephrased to say "cy.route will only intercept XmlHttpRequests. Requests using the fetch API and other types of network requests such as loading images or pages will not be intercepted." to be clearer to new users

It might also be useful to show users how to use the Network tab to tell if they're sending XHRs, since users don't always grasp the distinction between XHRs and other types of requests

**Comment by bahmutov** [comment]
Good observation, would be nice to change the warning then

**Comment by jennifer-shehane** [comment]
Related issue: https://github.com/cypress-io/cypress-documentation/issues/1297

**Comment by bahmutov** [comment]
@flotwig we have the same `fetch` warning in 3 places I think (route, server, network guide) and it would be nice to update them all. I think at this point to avoid code duplication just switch it to partial - we have some partials already defined, like https://github.com/cypress-io/cypress-documentation/blob/develop/source/_partial/then_should_difference.md
