### ISSUE TITLE
Add good presentation to the list of slide decks

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1407]
Really good presentation http://briebug.github.io/presentations/ng-meetup/2018/10/cypress/ that we need to include in our https://docs.cypress.io/examples/media/blogs-media.html

Second add - https://github.com/briebug/cypress-schematic should be added https://docs.cypress.io/plugins/index.html#framework-tooling this is another Angular CLI addition that can install Cypress

**Comment by bahmutov** [comment]
and while we are at it, into the development tools https://docs.cypress.io/plugins/#development-tools

- https://github.com/bahmutov/cly 
- @Bkucera https://github.com/Bkucera/cypress-plugin-retries

**Comment by louise-hayes** [comment]
I'd like to work on this as a first timer contributing to open source.

**Comment by bahmutov** [comment]
👍

**Comment by reddysridhar53** [comment]
Is this still open? If so can I take it up...?
