### ISSUE TITLE
Add really good talk and slides

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1415]
The video and slides from https://twitter.com/nikolalsvk/status/1095409664005689344

**Comment by jennifer-shehane** [comment]
@bahmutov Try to add the `first-timers-only` label to stuff like this. Sometimes people pick them up. :D

**Comment by bahmutov** [comment]
That’s true and good idea, I will do it

**Comment by marieram** [comment]
Hi @bahmutov, I'd like to help. I'm fairly new, but with a bit of direction, I think I can knock this out.

**Comment by bahmutov** [comment]
Absolutely Mary, go ahead, and you can do this by example from existing talks

**Comment by marieram** [comment]
@bahmutov could you link me to the file that requires the change?

**Comment by bahmutov** [comment]
@marieram the talks are all just leave in https://github.com/cypress-io/cypress-documentation/blob/develop/source/_data/talks.yml You can add the new talk there and will be used to create HTML talks page
