### ISSUE TITLE
Add warning and example how to pass arguments to Cypress when using npm run script

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1418]
I see this problem pretty often: user is trying to `npm run cy:run --record ...` without separating arguments with `--` (should be `npm run cy:run -- --record ...`)

- https://github.com/cypress-io/cypress/issues/3467

We need to put this warning in several places, because people not familiar with NPM's quirks will get stuck and frustrated. I see a couple of places where this warning could be added

- https://docs.cypress.io/guides/getting-started/installing-cypress.html#Adding-npm-scripts
- https://docs.cypress.io/guides/getting-started/installing-cypress.html#Run-binary
- https://docs.cypress.io/guides/guides/continuous-integration.html#To-record-tests
- https://docs.cypress.io/guides/references/configuration.html#Command-Line

In the existing https://docs.cypress.io/guides/guides/command-line.html#How-to-run-commands warning, we need to stress this point by adding "important"

It would be nice to create reusable warning template that we can include on demand, just like @flotwig has done with network stubbing warning in this commit https://github.com/cypress-io/cypress-documentation/commit/50c4c7112c0faff34e564686655a70ee155a34e5

I have existing NPM run warning here: https://github.com/cypress-io/cypress-documentation/blob/develop/source/guides/guides/command-line.md#how-to-run-commands

Maybe we could have a shorter version of the above warning that can be inserted into more places

**Comment by bahmutov** [comment]
I think for `cypress open` cases we could show passing one of the options that `cypress open` allows see https://github.com/cypress-io/cypress-documentation/blob/develop/source/guides/guides/command-line.md#cypress-open

something like

```
npm run cy:open -- --config baseUrl=http://localhost:4400
```

**Comment by nupurgrover** [comment]
@bahmutov I would like to work on this, if this is still up for grabs

**Comment by nupurgrover** [comment]
Great! I'll submit a PR

**Comment by bhayward93** [comment]
I could do this if its still needed @jennifer-shehane

**Comment by jennifer-shehane** [comment]
@bhayward93 Yes, feel free to pick up.
