### ISSUE TITLE
Travis CI cache example only works when script is precisely "npm ci"

### ISSUE THREAD

**Issue by cxcorp** [cypress-io/cypress-documentation#1425]
## I'm submitting a...

<pre><code>
[ ] Bug report 
[x] Content update
[ ] Process update (build, deployment, ... )
</code></pre>

## Type of bug / changes

In the [Travis section](https://docs.cypress.io/guides/guides/continuous-integration.html#Travis), the following is said:

```yml
cache:
  npm: true # this cashes ~/.npm folder on Travis
```

However, according to Travis' [current documentation](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm):

> ```yml
> cache: npm
> ```
> 1. This caches `$HOME/.npm` precisely when `npm ci` is the default `script` command. (See above.)
> 2. In all other cases, this will cache `node_modules`. Note that `npm install` will still run on every build and will update/install any new packages added to your `package.json` file.
> 
> Even when script is overridden, this shortcut is effective.

I would interpret the documentation to mean that `$HOME/.npm` literally only cached when `.travis.yml` has a line like this:
```
script:
  - npm ci
```
meaning that when a custom shell script is run, `~/.npm` is not cached.

My interpretation might be wrong and I could be using `cache: - $HOME/.npm` for nothing, but it might be a good idea to mention this detail from the Travis documentation in Cypress' documentation as well.

**Comment by Bkucera** [comment]
@cxcorp good catch! we should update the documentation
