### ISSUE TITLE
Tweak debugging page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1430]
## I'm submitting a...

<pre><code>
[ ] Bug report 
[x] Content update
[ ] Process update (build, deployment, ... )
</code></pre>

## Type of bug / changes

Our debugging page http://on.cypress.io/debugging is very good. Recently I wrote a section on debugging for testing workshop https://github.com/cypress-io/testing-workshop-cypress/blob/master/slides/15-debugging/PITCHME.md with a few clarifications, which we can bring back into this page

- debugging with `DEBUG=` per package
- how to disable `DEBUG` messages in the browser
- isolating the problem by splitting
- debugging thrown error
- using `cypress-failed-log` plugin

**Comment by samsonyuwono** [comment]
May I take this one?

**Comment by jennifer-shehane** [comment]
@samsonyuwono 	That would be great!

**Comment by samsonyuwono** [comment]
@jennifer-shehane 
Just to clarify would you like for me to add to the What you'll learn section like this?
![screen shot 2019-02-26 at 2 24 27 pm](https://user-images.githubusercontent.com/25911721/53440500-a6734b80-39d2-11e9-8167-eafd67ac6cbd.png)

Then add a section related to the new additions- like this?
![screen shot 2019-02-26 at 2 24 38 pm](https://user-images.githubusercontent.com/25911721/53440532-b9861b80-39d2-11e9-8fa1-cc0ba690e748.png)

**Comment by bahmutov** [comment]
Let me review this when I have a little bit of time, probably next week. Thank you @samsonyuwono for doing this 👏

**Comment by bahmutov** [comment]
@samsonyuwono I have made local edits to your PR, can you allow me to edit your fork, please? You need to check this setting in your PR

https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork
