### ISSUE TITLE
Expand the testing workshop contents list

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1434]
## I'm submitting a...

<pre><code>
[ ] Bug report 
[x] Content update
[ ] Process update (build, deployment, ... )
</code></pre>

We have a lot more content in the testing workshop https://github.com/cypress-io/testing-workshop-cypress#content- so we should update the documentation page

**Comment by Wizdave97** [comment]
How can I help

**Comment by devguru876** [comment]
How can I help with this issue?
