### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#145]
And ignore it, but set exact NPM version option in `.npmrc`

**Comment by jennifer-shehane** [comment]
Why are we getting rid of this? Did we have another solution to dependency's dependencies updating without us knowing?

**Comment by bahmutov** [comment]
no, and now I see that I have added the stupid lock file in https://github.com/cypress-io/cypress-documentation/issues/56 so I am going to keep it. Every time we add dependencies the package-lock needs to be updated :(
