### ISSUE TITLE
Mention Mocha/Chai globals in TypeScript doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1524]
## I'm submitting a...

```
[ ] Bug report 
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

As @bahmutov mentioned here: https://github.com/cypress-io/cypress/issues/3828#issuecomment-477157958 We should probably mention this in the TypeScript doc.

**Comment by tiago-yotta** [comment]
I never got the chance to do this, sorry 😅 

It seems like the documentation has this now that Cypress comes built-in with TypeScript:
https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json

```
The "types" will tell the TypeScript compiler to only include type definitions from Cypress. This will address instances where the project also uses @types/chai or @types/jquery. Since Chai and jQuery are namespaces (globals), incompatible versions will cause the package manager (yarn or npm) to nest and include multiple definitions and cause conflicts.

You can find an example of Jest and Cypress installed in the same project using a separate tsconfig.json file in the cypress-io/cypress-and-jest-typescript-example repo.
```

Should be good enough to close this issue 👍
