### ISSUE TITLE
Document Dashboard Roles & Permissions

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-documentation#1527]
Documentation around the available Roles & Permission on the Dashboard should exist :) 

|Permission | member | admin | owner
-- | -- | -- | --
See test recordings of private projects | ✅  | ✅ | ✅
See users invited to org |   | ✅ | ✅
Resend invitation to invited user |   | ✅ | ✅
Invite member to Organization |   | ✅ | ✅
Invite admin to Organization |   | ✅ | ✅
Invite owner to Organization |   |   | ✅
See requests from users to join org |   | ✅ | ✅
Accept requests from users to join org |   | ✅ | ✅
Remove member from org |   | ✅ | ✅
Remove admin from org |   | ✅ | ✅
Remove owner from org |   |   | ✅
Edit member in org |   | ✅ | ✅
Edit admin in org |   | ✅ | ✅
Edit owner in org |   |   | ✅
Add, edit, delete member in default org |   |   | ✅
Access billing information |   | ✅ | ✅
Manage billing information |   | ✅ | ✅
Transfer project to another Organization |   |   | ✅
Delete project |   |   | ✅
Edit project name |   | ✅ | ✅
Edit project status (priv/pub) |   | ✅ | ✅
Add or delete record keys |   | ✅ | ✅
Edit org name |   |   | ✅
Delete org when no projects |   |   | ✅
Edit/delete 'default' org

**Comment by DarkMattR** [comment]
I'm happy to pick this one up

**Comment by jennifer-shehane** [comment]
@DarkMattR Great! Let us know if you have any questions.

**Comment by DarkMattR** [comment]
Hi, I have made the changes on a local branch but I am getting the bellow error:
ERROR: Permission to cypress-io/cypress-documentation.git denied to DarkMattR.
fatal: Could not read from remote repository.

Can I please have permissions to commit? 
Thanks

**Comment by jennifer-shehane** [comment]
Hey @DarkMattR, we have a guide on contributing here: https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md#pull-requests

You will need to [fork the repository](https://guides.github.com/activities/forking/) - make commits to a branch on the forked repository and then [open a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) from there. You will not have permissions to commit directly to commit.

**Comment by DarkMattR** [comment]
PR is open
