### ISSUE TITLE
Add awaiting wrapped object section to Retry-ability guide

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#1542]
The Retry-ability guide demonstrates assertions on DOM elements, but the concept of retrying assertions also applies to regular objects via `cy.wrap`. Example:

```js
  it('waits for changed property value', () => {
    const o = { foo: 20 }

    // changes property "foo" after delay
    setTimeout(() => {
      o.foo = 42
    }, 100)

    // "expect" syntax does NOT work
    // because it is not retried!
    // expect(o).to.have.property('foo', 42)

    // wrapping an object and using "should" syntax retries
    // the assertion until the "o.foo = 42" runs and the assertion passes
    cy.wrap(o).should('have.property', 'foo', 42)
  })
```
>  🔗  [Source and more examples](https://github.com/cypress-io/cypress-example-recipes/blob/e897efdfd94a50c1991fa825e9306adf69c89a3c/examples/unit-testing__application-code/cypress/integration/wait-for-object-property-spec.js)

This ability should also be stated in this guide. We already seen a large user create work-arounds because they did not know about using `cy.wrap` to wait on object changes.

**Comment by bahmutov** [comment]
also this blog post that talks about Redux store might point it out explicitly https://github.com/cypress-io/cypress-example-recipes#blogs "Testing Redux Store"

AND it needs link to the actual blog post https://www.cypress.io/blog/2018/11/14/testing-redux-store/ !! And we need to call attention to automatic retrying of `cy.window().its('STORE_NAME').should('exist')`
