### ISSUE TITLE
Add docs around file watching rules. 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#159]
Users ask about file watching and how the rules work quite frequently and There is not documentation to point them to.

**Comment by jennifer-shehane** [comment]
Related: https://github.com/cypress-io/cypress-documentation/issues/97

**Comment by richdouglasevans** [comment]
Can I work on this one @jennifer-shehane ? It's assigned to @chrisbreiding who might have written a sweet guide already thus my asking instead of diving right in.

**Comment by jennifer-shehane** [comment]
@richdouglasevans Oh, sure. @chrisbreiding originally wrote most of the code for file watching, but I'm sure he and I would be happen to review any contribution you make. 😄

**Comment by richdouglasevans** [comment]
In light of #829 being merged can this ticket be Closed? Steer me if there's more work to be done and I'll get it sorted.

**Comment by jennifer-shehane** [comment]
👍
