### ISSUE TITLE
Cypress Trade Offs

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#162]
- fact: There are specific tradeoffs.
    summary: "With all this new power comes very specific trade-offs which separates Cypress from other testing tools. It's important to understand why these exist. Many of these restrictions are arguably beneficial in that they prevent you from writing bad tests and typical anti patterns.

    <h3>Cypress is not a generic automation tool</h3>
    Cypress is a hyper focused specialized tool that does one thing really well. You should not use Cypress for things it's not designed for - like crawling the web. There are already excellent tools that are optimized for doing that. You shouldn't use Cypress to script against sites you don't control - trust us, it won't work well. Cypress is built to be used by you while you develop your own applications. It's meant for developers and QA engineers, not manual testers or exploratory testing.

    <h3>There are browser feature restrictions</h3>
    Cypress will never support switching between multiple tabs. Don't worry, it is easy to work around. You shouldn't be testing the browsers native behavior anyway - just test the source of what causes the browser to behave this way. Do you really need to click the link with target='_blank' to verify it opened a tab? No. Just test that it has that attribute and you can assume the browser would do the right thing.<br /><br />
    This principle applies to all kinds of things. Do you need to test that a browser prompts you when trying to download a file? No, you just need to test the underlying mechanism that causes it. You could use cy.request() to verify the server sends the right content-disposition headers, or even programmatically download the file and read off the bytes later. Avoid trying to test difficult things in the browser when you have a more reliable mechanism at your disposal.<br /><br />
    Cypress will also never support driving more than 1 browser at a time. It is possible to synchronize Cypress with another backend process (like Selenium) to drive multiple browsers, but we believe this is completely unnecessary. If you're trying to test a chat application with two users, you can easily stub or programatically control the other user without needing an entire browser. Cypress gives you much more control over your application which avoids the need to create all the physical conditions that replicate multiple users.

    <h3>You are bound to a single origin per test</h3>
    Each test is limited to only visiting a single superdomain. Different subdomains are fine, but it is not possible to navigate from google.com to apple.com in the same test. This limitation exists due to the way Cypress is bound to a single superdomain origin per test. Fortunately, there is never a situation where it is actually useful to transition between domains. All browsers have a security model bound to origin; sites are completely isolated from one another. In the unusual situation where an action *does* affect another origin, you can simply use cy.request() to programatically interact with the other site. Imagine submitting a form on your web application which ends up updating some value in Github. The thing is, you don't need to navigate to the other website to verify this. You could just programatically interact with the other sites' APIs. So, while this restriction may initially seem counter-intuitive, it is actually a fundamentally good best practice. Testing or visiting applications you don't control is a recipe for flake and disaster.<br /><br />
    With that said, there are situations where you may need to nagivation between two origins and you control both parts. This regularly occurs with Single Sign On (SSO). This is very easy to test in Cypress and we even have recipes showing you how.
    "

**Comment by lgandecki** [comment]
> Cypress will also never support driving more than 1 browser at a time. It is possible to synchronize Cypress with another backend process (like Selenium) to drive multiple browsers, but we believe this is completely unnecessary. If you're trying to test a chat application with two users, you can easily stub or programatically control the other user without needing an entire browser. Cypress gives you much more control over your application which avoids the need to create all the physical conditions that replicate multiple users.

Is this a technical challenge, or decision based on preventing an anti-pattern/pointing to a "better way"?

**Comment by brian-mann** [comment]
It is both. We'll try to publish a full explanation of "Trade Offs" in the docs soon.

**Comment by brian-mann** [comment]
This was fixed a little while ago by https://github.com/cypress-io/cypress-documentation/pull/224
