### ISSUE TITLE
Suggestion:  Add config examples to module API documentation

### ISSUE THREAD

**Issue by JonFranchi** [cypress-io/cypress-documentation#1671]
## I'm submitting a...

```
[ ] Bug report
[ X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
https://docs.cypress.io/guides/guides/module-api.html

The module API is a little unclear where settings would go that relate to configuration, or rather, which things count as configuration and which do not.  I was struggling to figure out how to disable video when initiating a test run from the module API.  Maybe a clearer demonstration of what types of things can be nested under `config` versus top level `options` would be helpful, and something that links those to the settings button in the test runner.

**Comment by bahmutov** [comment]
so something like linking the current line `config | Specify configuration` to https://on.cypress.io/configuration? Adding `video` to the code example?

```js
cypress.run({
  reporter: 'junit',
  browser: 'chrome',
  config: {
    baseUrl: 'http://localhost:8080',
    chromeWebSecurity: false,
    video: false
  },
  env: {
    foo: 'bar',
    baz: 'quux',
  }
})
```

**Comment by JonFranchi** [comment]
I'm not seeing the current part you're referring to, but the example looks good.  I think my point is that knowing reporter and browser go at the top level and video gets nested under config is not intuitive.
