### ISSUE TITLE
Mention that baseUrl is used to check your server in cypress run now too

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1694]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

In 'Best Practices' when mentioning why to set a `baseUrl`:

<img width="669" alt="Screen Shot 2019-05-20 at 8 51 41 PM" src="https://user-images.githubusercontent.com/1271364/58028710-52938100-7b41-11e9-9d51-ee8b51c52b06.png">

**Comment by ricardorojass** [comment]
Hi everyone ✋, I would like to help. Could you provide more detail? Thanks.

**Comment by jennifer-shehane** [comment]
@ricardorojass That would be great! 

It should be listed as one of the reasons to set a `baseUrl` in this section: https://docs.cypress.io/guides/references/best-practices.html#Setting-a-global-baseUrl

There is an 'improve this doc' button at the top of the page that will take you to the appropriate GitHub markdown file. 

It's good to add the screenshot also!
