### ISSUE TITLE
precommit lint tasks take WAY too long to run... only run lint tasks on prepush OR staged changes

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#1711]
It currently takes nearly 1 minute to run the linting tasks on every commit. There's no reason to do this - we could run these linting tasks either on `pre-push` (so it happens only once) or perhaps better yet only run the linting takes on the `staged` changes, so it'll finish almost instantly.

There are slightly different ramifications so I'm not sure how often these linting rules change to know the best option. All I know is `pre-commit` is absurdly slow.

**Comment by bahmutov** [comment]
ok, I will move them into pre-push hook. For now you can commit with `-n` flag to skip pre-push hooks. Also I do not see this problem, for me pre-commit hooks finishes in a few seconds tops. Maybe use a terminal to do git commit
