### ISSUE TITLE
No supported version of node specified in documentation

### ISSUE THREAD

**Issue by clarmso** [cypress-io/cypress-documentation#1725]
## I'm submitting a...

```
[ ] Bug report
[X ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The "Getting Started" page does not specify which version of node that Cypress currently supports.  Many organizations may not run the latest version or bleeding edge of node.

Directing the new users to use the LTS versions of node is a good choice.

**Comment by brian-mann** [comment]
Cypress actually comes bundled with it's own version of node - so the one that's installed on your system does not matter.

I think we mention this somewhere in the docs, but I could be mistaken. Regardless do you think this is worth mentioning in the getting started doc?

**Comment by clarmso** [comment]
Now I see Cypress come with its version of node: https://github.com/cypress-io/cypress/blob/c3397dceb254e1c79b969cccd0df915c9b9494c5/package.json#L8

How about npm?  Without npm we cannot run "npm install" initially.  Some users may be new to the node environment.

**Comment by brian-mann** [comment]
I looked and all of this is explained in the Getting Started guide...

We even offer a direct download for users who don't have npm installed.

https://docs.cypress.io/guides/getting-started/installing-cypress.html#Direct-download

**Comment by clarmso** [comment]
@brian-mann Thanks for clarifying my concerns. Let me close this issue.
