### ISSUE TITLE
The multiple FAQ documents are not readily discoverable

### ISSUE THREAD

**Issue by chris-morgan** [cypress-io/cypress-documentation#1761]
I am a prospective user.

I was interested in what browsers Cypress supported. Not seeing the answer in the first few places I looked, I reached for the “FAQ” link in the header. That took me to https://docs.cypress.io/faq/questions/using-cypress-faq.html. I didn’t see the answer there at all. I hunted around in a few more places, before giving up and using DuckDuckGo, whence I found the answer.

What I failed to discover at that time (and only discovered when doing more involved poking and prodding in preparation for filing a bug requesting that my question be added to the FAQs document) was that there were *multiple FAQ documents*, and the second one, https://docs.cypress.io/faq/questions/general-questions-faq.html, answered my question.

When you’re not used to the site structure, that sidebar on the left is invisible; it looks like a local TOC widget, and is out of the normal flow of the page, so a typical user simply won’t notice it. I didn’t.

I’m used to the idea of there being *one* FAQs document. When there are more than one, it would be a good idea to either draw attention to that fact in the main column of the text, or make the FAQ link be a new page that lists the four sub-documents, which a sentence summarising the contents of each. Such a new page is my strong recommendation.

I may also add that new or prospective users are most likely to want the General Questions document, while existing users are most likely to want the Using Cypress document.

**Comment by jennifer-shehane** [comment]
Yeah, I can see this. This could be consolidated into 1 FAQ page with headers for each section I think.

We also have search in the docs themselves in the very top right hand corner
