### ISSUE TITLE
Add example of using alias with cy.request() to cy.request() and alias doc.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1779]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

As per https://github.com/cypress-io/cypress/issues/3827 we need example of how to access an alias from `cy.request()`.

```js
it('cy.request() - make an XHR request', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')

  cy.request('https://jsonplaceholder.cypress.io/comments').as('comments')

  cy.get('@comments').should((response) => {
    expect(response.status).to.eq(200)
    expect(response.body).to.have.length(500)
    expect(response).to.have.property('headers')
    expect(response).to.have.property('duration')
  })
})
```

**Comment by ryanpedersen42** [comment]
I'd love to help! First-time-caller here, I read the contribution guidelines, but also want to make sure I'm following what I need to be doing correctly. 

Was this supposed to be [here](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Requests), [here](https://docs.cypress.io/api/commands/request.html#Method-and-URL ?), or both?

**Comment by jennifer-shehane** [comment]
Oh, I already added this to the docs. So sorry for not closing this properly. :(

We have some other first-timer issues open though if you'd like to pick another one up. https://github.com/cypress-io/cypress-documentation/labels/first-timers-only
