### ISSUE TITLE
Add page with links to all our webinars

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1782]
Our webinars are special and have very good content. We should have a page with just them and each webinar should have video and slides and a short description

- circleci
- percy
- applitools
- cypress in a nutshell
- godaddy
- saltstack

Similar to page https://docs.cypress.io/examples/media/courses-media.html

**Comment by bahmutov** [comment]
and parallelization webinar we did

**Comment by jennifer-shehane** [comment]
@bahmutov Where is this parallelization webinar? I had our YouTube channel given to me as the source of our webinars, but I don't see one about parallelization there. https://www.youtube.com/c/Cypressio

**Comment by bahmutov** [comment]
The parallelization video is at https://www.youtube.com/watch?v=FfqD1ExUGlw

**Comment by jennifer-shehane** [comment]
K, that one is on there 👍
