### ISSUE TITLE
If a tag is at the top of the sentence, it will cause the ## rendering to fail

### ISSUE THREAD

**Issue by icelemon1314** [cypress-io/cypress-documentation#1786]
## I'm submitting a bug.

In the variables-and-aliases.md file.
If the url tag is at the top of the sentence, it will cause the following ## rendering to fail.

This is ok:
The {% url `cy.get()` get %} command is capable of accessing aliases with a special syntax using the `@` character:

This is not ok:
{% url `cy.get()` get %} command is capable of accessing aliases with a special syntax using the `@` character:

```
[.] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

![image](https://user-images.githubusercontent.com/4556804/59668625-663b1180-91eb-11e9-8efd-10c38111db3d.png)

**Comment by jennifer-shehane** [comment]
Closing as stale - moving to new docs next week.
