### ISSUE TITLE
Header for CLI docs is in chineese

### ISSUE THREAD

**Issue by OskarDamkjaer** [cypress-io/cypress-documentation#1791]
First of all thanks for the lovely documentantion! <3 I found a page that seems to use the wrong language :) 

## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
![image](https://user-images.githubusercontent.com/10564538/59751041-2114ef00-9280-11e9-8eee-4c21c46570da.png)

This is the direct url: https://docs.cypress.io/guides/guides/command-line.html#Installation

**Comment by mccataldo** [comment]
Also seeing the same. Appears to be Chinese despite Language set to `English`

**Comment by bahmutov** [comment]
thank you @OskarDamkjaer for noticing and opening an issue, should be fixed in https://github.com/cypress-io/cypress-documentation/pull/1793
