### ISSUE TITLE
Do not duplicate english markdown files in separate languages

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#1795]
Rather than duplicate the same english `.md` docs for the japanese and chinese languages - can we just handle this automatically at the build process level?

For instance, if a language is supported but does not yet have the translated docs - can it use the english ones by default?

I **really** don't like the idea of duplicating these documents for each language - it has already caused problems and confusion and it will without a doubt continue to cause more issues.

See here: https://github.com/cypress-io/cypress-documentation/pull/1792

This is not sustainable. Instead we should write some build process code that automatically copies the english markdown files to the other language when generating the static site - but keep them out of source control.

Nobody is going to want to update X number of versions of (english) markdown documents for other languages - that's crazy.

Alternatively we could even automatically create symlinks to the english files to backfill them (so they show up in the file tree).

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress-documentation/issues/1686
