### ISSUE TITLE
data not loading on UI in cypress run

### ISSUE THREAD

**Issue by ssamaji** [cypress-io/cypress-documentation#1816]
when i am running my tests using cypress run, data is not loading on UI but the same test working fine with cypress open.

attaching logs and video
[UpdateHistory.log](https://github.com/cypress-io/cypress-documentation/files/3330787/UpdateHistory.log)

https://drive.google.com/file/d/1nAwo--mEHP_Cew1_GV14vct_ifXu_60F/view?usp=sharing

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Just looking at the issue though, there is not enough information provided. Please provide information on what you are expecting or what a passing test should look like. I don't see any evidence of a bug from what is provided.
