### ISSUE TITLE
Add example of checking native HTML5 form validation message

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1824]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Add an example of how to check that a form's HTML form validation is shown when an input is invalid. 

Maybe this should go in common assertions? https://docs.cypress.io/guides/references/assertions.html#Common-Assertions

Or our FAQ? I'm not sure.

```js
it('check validation message on invalid input', () => {
  cy.get('input:invalid').should('have.length', 0)
  cy.get('[type="email"]').type('not_an_email')
  cy.get('[type="submit"]').click()
  cy.get('input:invalid').should('have.length', 1)
  cy.get('[type="email"]').then(($input) => {
    expect($input[0].validationMessage).to.eq('I expect an email!')
  })
})
```

**Comment by ryanpedersen42** [comment]
Feeling like this might be best in FAQ because that Common Assertions section is really focused on using the assertions listed before with `.should()`. Maybe a new "How can I check that a form's HTML form validation is shown when an input is invalid?" is the right call?

**Comment by jennifer-shehane** [comment]
@ryanpedersen42 Yah, I agree!

**Comment by ryanpedersen42** [comment]
I'm on it!

**Comment by konekoya** [comment]
Sorry for commenting on a closed issue. But I'm not sure if this is a bug or I have missed something? With the following setup:

A simple form
```html
 <form action="">
      <input type="text" id="name" name="name" required />
      <button type="submit">Submit</button>
</form>
```

And the spec
```javascript
describe("Element", () => {
  before(() => {
    cy.visit("/");
  });

  it("it should have user value", () => {
    cy.get("input:invalid").should("have.length", 0);
  });
});
```

I'm getting an AssertionError of __AssertionError: Timed out retrying: Too many elements found. Found '1', expected '0'.__

If I however remove the `required` attribute from that input, it will pass. But shouldn't that attribute should be there and when users click on the submit button without filling the field then the input will display a native error message?

**Comment by rathorevaibhav** [comment]
Getting the same error as @konekoya 

Any help would be appreciated.

**Comment by jennifer-shehane** [comment]
@konekoya @rathorevaibhav The test is failing as intended in your situation. The input is required, meaning it requires some value to be present in the input. With the test you've written, there is no value in the input, so the test fails since your test is testing that there are no invalid elements present. 

If the input is empty, the test fails, as designed, since the input is required

<img width="755" alt="Screen Shot 2021-01-11 at 11 00 13 AM" src="https://user-images.githubusercontent.com/1271364/104147328-33bfbd80-53fc-11eb-9868-43d7e60dc330.png">


If you fill out the required input, the test passes

<img width="755" alt="Screen Shot 2021-01-11 at 10 59 23 AM" src="https://user-images.githubusercontent.com/1271364/104147307-1854b280-53fc-11eb-927d-d94a0eeabbda.png">

The example in the FAQ is wrong basically, the assertions are backwards. I'll update the example.

**Comment by jennifer-shehane** [comment]
Sorry, the example in the FAQ is *misleading* since it doesn't show the required fields for the example. I'll update it nonetheless.

**Comment by jennifer-shehane** [comment]
Opened a PR here: https://github.com/cypress-io/cypress-documentation/pull/3480

**Comment by NimashaMySendle** [comment]
Hi,
I want to know how to write a test for HTML5 built-in popup validation error in Cypress TypeScript.

This is the message I get when I click on the submit button:
![Screenshot 2023-05-26 135811](https://github.com/cypress-io/cypress-documentation/assets/134607248/42446608-502a-4ec3-a173-c63d136e843a)

I tried to add the below code, but then I got an error like this.
![Screenshot 2023-05-26 135715](https://github.com/cypress-io/cypress-documentation/assets/134607248/8b982de1-1d30-490c-b1b3-4fb715cc235b)

Email field code (inspect):
`<input type="text" name="Email" id="UserEmail" class="form-control" placeholder="E-mail" required autofocus style="margin-bottom:14px;">`

**Comment by NimashaHatake** [comment]
Hi,
I want to know how to write a test for HTML5 built-in popup validation error in Cypress TypeScript.

This is the message I get when I click on the submit button:
![Screenshot 2023-05-26 135811](https://github.com/cypress-io/cypress-documentation/assets/118599669/75a6f752-2a78-4e17-a660-80cda2f2fe92)


I tried to add the below code, but then I got an error like this.
![Screenshot 2023-05-26 135715](https://github.com/cypress-io/cypress-documentation/assets/118599669/ae20990a-e9d1-45c5-9a2e-e9039a8fbf01)


Email field code (inspect):
`<input type="text" name="Email" id="UserEmail" class="form-control" placeholder="E-mail" required autofocus style="margin-bottom:14px;">`

**Comment by MikeMcC399** [comment]
@NimashaMySendle 

Adding a comment to this closed issue, which was about adding an example to the documentation, is not the best place for your question.

For questions about how to use Cypress you can go to 

  <a href="https://on.cypress.io/discord">
    <img src="https://img.shields.io/badge/chat-on%20Discord-brightgreen" alt="Discord chat"/>
  </a>

and use the` i-need-help` channel.

If you believe that you have found a bug in Cypress, you can open a [new issue](https://github.com/cypress-io/cypress/issues) in the main [Cypress](https://github.com/cypress-io/cypress) repository.

**Comment by NimashaHatake** [comment]
> @NimashaMySendle
> 
> Adding a comment to this closed issue, which was about adding an example to the documentation, is not the best place for your question.
> 
> For questions about how to use Cypress you can go to
> 
> [ ![Discord chat](https://camo.githubusercontent.com/2a85a51f7a1b7a1f35aca577da0eedf98d445a1036907adab5d74c49cf91bd5b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636861742d6f6e253230446973636f72642d627269676874677265656e) ](https://on.cypress.io/discord)
> and use the` i-need-help` channel.
> 
> If you believe that you have found a bug in Cypress, you can open a [new issue](https://github.com/cypress-io/cypress/issues) in the main [Cypress](https://github.com/cypress-io/cypress) repository.

I'm new to cypress automation. thank you so much for your response

**Comment by seanwarmanshine** [comment]
The above solutions test whether the validation message exists within the elements but it doesn't test whether the message is viewable to the user.

For example, I am calling the method `form.reportValidity()` to trigger the validation in my code because I don't actually use the native html form submission. In this case doing `expect($input[0].validationMessage).to.eq('I expect an email!')` will pass every time even if the message isn't actually showing.

Another solution I found was to spy on the `reportValidity` function and check if it has been called:

```javascript
    cy.get('form').then(($form) => {
      cy.spy($form[0], 'reportValidity');

      fillFormWithMissingFields();

      cy.get('@save-button').click();

      cy.get('form').then(($form) => {
        expect($form[0].reportValidity).to.have.been.called;
      });
    });

```
