### ISSUE TITLE
Mismatch between documentation and code of `.wait()`

### ISSUE THREAD

**Issue by Lakitna** [cypress-io/cypress-documentation#1838]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

[The documentation of the `.wait()` command](https://docs.cypress.io/api/commands/wait.html#Rules) states that `.wait()` must be chained directly of `cy`, but this is not the case as you can [see in the source code](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/waiting.coffee#L160). Calling wait in a chain is no problem:

```javascript
// This works just fine
cy.get('foo')
  .wait(100);
```

This should probably be fixed in the documentation.

See https://github.com/cypress-io/eslint-plugin-cypress/issues/21 for how I found out.

**Comment by jennifer-shehane** [comment]
While not absolutely necessary, we have discussed enforcing the requirements, so we want to encourage people to follow the requirements as much as possible. 

Chaining off of something other than `cy`, we believe, introduces confusion into the test code - since `cy.wait()` does not have any access to the previous command it is chained off of.

**Comment by Lakitna** [comment]
So if I understand you correctly this will be fixed in the source code by forcing `.wait()` to be chained of off `cy` by setting `prevSubject: false`?

**Comment by jennifer-shehane** [comment]
Hmm, ok, yeah I see. `.wait()` does yield the previous subject, so it can be used to pass along a subject to the next command. Although the wait command doesn't change anything about the previous subject. I'll have to think about this 'requirements' heading again. We decided this nomenclature a while ago, but I do see that the `.wait()` may not necessarily be used off of `cy`, but....we also don't really recommend the use of `.wait()` with time either.

**Comment by Lakitna** [comment]
> we also don't really recommend the use of .wait() with time either.

That's a very good point. The only reason I use it here is that I don't see any other way of getting a stable test. I generally consider it very bad practice and would generally like to slap anyone who uses arbitrary waits :) That's also why I opened this issue https://github.com/cypress-io/eslint-plugin-cypress/issues/21.

At the same time, I don't think it's a good idea to have a deliberate mismatch between documentation and implementation. Adding an example to the docs using `.wait('@route')` in a chain might work here, but I can't come up with a situation where you would want to use wait like that.
