### ISSUE TITLE
Make documentation of `Cypress.log` great again

### ISSUE THREAD

**Issue by Svish** [cypress-io/cypress-documentation#1839]
The current documentation of `Cypress.log` over at https://docs.cypress.io/api/cypress-api/cypress-log.html is really not helpful. It does _list_ its options, but only _one_ of them has a description, and it mentions _nothing at all_ about the object that's returned from calling it.

---

**Re the options**

* What specifically is `$el` used for, what should I set it to, and should I set it?
* Where is `name` vs `displayName` used?
* Why is `message` an array, and where is it used?
* Why is `consoleProps` a function, when is it called, and what should one keep in mind with that?

**Re the returned object**

It has the following type according to typescript types (but no documentation there either...):

```ts
  interface Log {
    end(): Log
    finish(): void
    get<K extends keyof LogConfig>(attr: K): LogConfig[K]
    get(): LogConfig
    set<K extends keyof LogConfig>(key: K, value: LogConfig[K]): Log
    set(options: Partial<LogConfig>): Log
    snapshot(name?: string, options?: { at?: number, next: string }): Log
  }
```

* What's the difference between `end` and `finish`, and how are they used?
* What exactly does `snapshot` do, and how/when should I use it? What is `name`, `at` and `next` for, and how do I use those?

---

I've _sort of_ managed to guess and deduce what _some_ of these things do, but seriously, I really shouldn't have to do that. To make it easy to write good and proper custom commands, `Cypress.log` should be properly documented. Both the options and the log interface.

**Comment by flotwig** [comment]
The Typescript declarations have now surpassed the docs for `Cypress.Log`:

https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L4314-L4324

Improvement is still needed for both though, there's a ton of undocumented functionality.

**Comment by Svish** [comment]
@flotwig Only for the `LogConfig` interface though, which is definitely helpful, but the `Log` interface is what I'm really curious about. Can kiiind of guess what most of the stuff in `LogConfig` does (it would just be helpful with docs that meant I didn't have to guess. The `Log` interface on the other hand... No idea what `end` or `finish` is supposed to do, and definitely no clue how to use the `snapshot` functionality. 😕

**Comment by NicholasBoll** [comment]
I might have to take a stab at this. I'm writing a blog post for the anatomy of a Custom Command which includes information about Command.

I've written [cypress-pipe](https://github.com/NicholasBoll/cypress-pipe) and much of [@testing-library/cypress](https://github.com/testing-library/cypress-testing-library/) both of which use features outside of what is documented. I was getting annoyed with the red squiggles and jumping to the Typescript definitions says I wrote them...

Perhaps it is finally time to fix them!
