### ISSUE TITLE
PR: Add ci https example for webpack (or create react app)

### ISSUE THREAD

**Issue by goldylucks** [cypress-io/cypress-documentation#1849]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update (kinda)
[x] Question before PR :)
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I'm using create react app in https mode, and it took me 15 minutes to get it working:

```
    "start": "HTTPS=true PORT=3001 react-app-rewired start",
    "cy:run": "cypress run",
    "cy:ci": "START_SERVER_AND_TEST_INSECURE=1 start-server-and-test start https-get://localhost:3001 cy:run",
```

it could have been 10 seconds if it was mentioned in the docs :)

Shall I prepare a PR to append this?

I think here would be a good place: https://docs.cypress.io/guides/guides/continuous-integration.html#Solutions

What do you guys think?

**Comment by bahmutov** [comment]
I think this is more of the question to the `start-server-and-test`, no? Which when you look at the README there has this https://github.com/bahmutov/start-server-and-test#disable-https-certificate-checks

But yeah, I think it is a common question with local HTTPS development, so mentioning it would be helpful, mind opening a PR @goldylucks ?
