### ISSUE TITLE
Missing link retry-ability

### ISSUE THREAD

**Issue by eperedo** [cypress-io/cypress-documentation#1867]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Hi :wave:  looks like there is a missing link to the retry ability page in the [should page](https://docs.cypress.io/api/commands/should.html#Timeouts)

![ra](https://user-images.githubusercontent.com/461124/61152697-c0f42000-a4ae-11e9-98e6-3936f8ab7145.png)

If you pointed me in the right direction I can make a PR for this.

**Comment by flotwig** [comment]
Hi @eperedo, thanks for offering to help! The source for `should` is in https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/should.md

See the contributing doc for guidelines: https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md

**Comment by eperedo** [comment]
Ok, the timeouts function was missing the render method that generate the links.

PR here: https://github.com/cypress-io/cypress-documentation/pull/1871
