### ISSUE TITLE
How to assert XHR response

### ISSUE THREAD

**Issue by Oznaprazzi** [cypress-io/cypress-documentation#1878]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
How do I assert the DOM at this specific moment of the GET XHR response
<img width="393" alt="Screen Shot 2019-07-16 at 4 40 55 pm" src="https://user-images.githubusercontent.com/7484124/61271801-eb184b80-a7e8-11e9-8b78-bfe6cf4e13db.png">
<img width="203" alt="Screen Shot 2019-07-16 at 4 41 02 pm" src="https://user-images.githubusercontent.com/7484124/61271802-ebb0e200-a7e8-11e9-8aeb-b03fc2a806f8.png">
It seems that asserting it using .then() is not correct as the DOM has already changed after that moment. So how would I assert the DOM at this particular moment?

I also tried 
` cy.route({
                method: 'GET',
                url: url,
                delay: 500,
                onResponse: (xhr) => {
                    cy.log("XHR", xhr);
                    cy.get('load').should('be.visible');
                }
             });`
but no hope either

**Comment by jennifer-shehane** [comment]
Ok, if you want to test that a loading spinner is showing, you probably want to set the `delay` options in `cy.route()` - so that the test can sit and see the loading spinner for a bit. https://docs.cypress.io/api/commands/route.html#Use-delays-for-responses

**Comment by Oznaprazzi** [comment]
@jennifer-shehane Did you see the code I tried using, mentioned at the bottom of the comment?

**Comment by jennifer-shehane** [comment]
@Oznaprazzi 500 ms is pretty short, have you tried increasing this?
