### ISSUE TITLE
Updates for spec parralelization / per spec changes.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#189]
- we will direct / document common solutions for things like aggregating multiple reporter output (JSON, JUnit, etc)
- document how to use multiple reporters
- document reducing the default minimum of snapshots from 50, down to 5.
- We'll modify the workflow and documentation to suggest iterating on a spec and not trying to run all tests from the Test Runner.

**Comment by brian-mann** [comment]
parallelization is a hard word to spill

**Comment by jennifer-shehane** [comment]
Moving to #461
