### ISSUE TITLE
Document keyboard shortcuts for Test Runner

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1904]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

As per https://github.com/cypress-io/cypress/pull/3943 there will be new keyboard shortcuts in the Test Runner. 

- Press `r` to rerun tests
- Press `s` to stop tests
- Press `f` to focus on the specs window

This should be documented in the Test Runner doc: https://github.com/cypress-io/cypress-documentation/edit/develop/source/guides/core-concepts/test-runner.md

**Comment by RenatoViana01** [comment]
Hey, can I pick this up?

**Comment by jennifer-shehane** [comment]
@RenatoViana01 	Sure!

**Comment by JaimeCardenas176** [comment]
@jennifer-shehane hi!, is it still needed?

**Comment by jennifer-shehane** [comment]
@JaimeCardenas176 	Yes!

**Comment by mishabruml** [comment]
cool, I'll take it!

**Comment by jenniferabowd** [comment]
@jennifer-shehane Do you still need help with this?

**Comment by jennifer-shehane** [comment]
No, thanks!
