### ISSUE TITLE
Add selecting element by name attribute to best practices

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1906]
Because users struggle writing `cy.get()` by name attribute selector we should include it as example in our best practices table

<img width="777" alt="Screen Shot 2019-07-24 at 11 46 24 AM" src="https://user-images.githubusercontent.com/2212006/61808949-63df5f00-ae0a-11e9-9e6e-57e5701519a8.png">

probable better than `#main` but worse than text

**Comment by jennifer-shehane** [comment]
I like it 😍

**Comment by bahmutov** [comment]
I have added a test to show this https://github.com/cypress-io/cypress-example-kitchensink/commit/a57892820c592a0272d69a58678c0bd808e5c104

**Comment by jennifer-shehane** [comment]
@bahmutov 	Where did you make this table - like, did you already make a PR for this somewhere?
