### ISSUE TITLE
Add example of `parseSpecialCharSequences: false`

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#1926]
Add it here: https://docs.cypress.io/api/commands/type.html#Key-Combinations

We mention this (which is great) but don't provide a single example.

**Comment by jennifer-shehane** [comment]
Added in https://github.com/cypress-io/cypress-documentation/pull/1927

![Screen Shot 2019-07-31 at 10 56 14 AM](https://user-images.githubusercontent.com/1271364/62183945-1e7ade80-b382-11e9-8432-ada66a56e91a.png)
