### ISSUE TITLE
Improve aliases and references doc

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#194]
Indicate improper use of `let` or `const` assignment.

Talk about aliasing as `this`.

Sharing context between hooks + tests.

Call out some of these things as Anti Patterns with link to the doc explaining it all.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress-documentation/pull/220.

**Comment by iankpconcentricsky** [comment]
> Usually, replaying previous commands will return what you expect, but not always

Why's that?  Can this be elaborated on?

What's the difference between:

> cy.get('#nav header .user').as('user')  (good)
and
> cy.get('#nav').find('header').find('.user').as('user')
during

it isn't clarified.  Just left as a breadcrumb of an unsolved mystery.  How would, by grouping the retry, the latter fail where the original succeeds?  This seems like it would be an overall best-practice even unrelated to variables?
