### ISSUE TITLE
Add robots.txt to limit Google crawler to English documents

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1940]
Currently because of the way we have partially completed translations from English to Chinese and Japanese docs, Google text search can find English text on a Japanese page, leading to less optimal result. 

We should add [robots.txt](https://support.google.com/webmasters/answer/6062608?hl=en) to limit the Google crawler from indexing non-English translations for now

**Comment by jennifer-shehane** [comment]
I feel like implementing some of these best practices is more ideal than just completely ignoring translated files from search indexing. https://support.google.com/webmasters/answer/189077?hl=en&visit_id=637002396938016733-1976776371&rd=1

**Comment by bahmutov** [comment]
Sure, implementing the SEO optimizations for translations could be step 2

**Comment by jennifer-shehane** [comment]
yeah, I was convinced also of this in the standup. I made a not of it in the translation optimizations https://github.com/cypress-io/cypress-documentation/issues/1686
