### ISSUE TITLE
Add "noEmit" directive in tsconfig.json example to prevent the error messages "Cannot write file ... because it would overwrite input file"

### ISSUE THREAD

**Issue by schl3ck** [cypress-io/cypress-documentation#1965]
## I'm submitting a...
```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```
## Type of bug / changes

In the [Intelligent Code Completion - Reference type declerations with `tsconfig`](https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-tsconfig) section you give an example how to activate intelligent code completion. But when I create and save the file (with some additions), it gives me multiple copies of the error "Cannot write file ... because it would overwrite input file".

This is my file:

```json
{
	"compilerOptions": {
		"allowJs": true,
		"strict": true,
		"baseUrl": "../node_modules",
		"target": "es5",
		"module": "commonjs",
		"lib": [
			"es5",
			"dom"
		],
		"types": [
			"cypress"
		]
	},
	"include": [
		"**/*.*"
	]
}
```

And the error in VS Code: 
![tsconfig-error](https://user-images.githubusercontent.com/42554556/62521990-0945fa00-b831-11e9-9544-0a9a571ff916.png)

But after adding `"outDir": "./out"` in `"compilerOptions"` the errors disappeard. This directory doesn't have to exist, because the code is never compiled by TypeScript.

I suggest to add this property in the documentation to help newcomers as they may get the same error (I coudln't find anything useful within 5 minutes on Google).

**Comment by Svish** [comment]
Unless you actually need the compiled files, maybe `"noEmit": true,` instead?

**Comment by csonuryilmaz** [comment]
Thanks @Svish  `"noEmit": true` is a better solution if you are using TS just for type checking only. This will tell TS that it shouldn't worry about compilation, therefore no file will be over written and no warning will be triggered.

**Note:** In my case it doesn't make any effect until I restart VS Code. After file save and restart, all warnings are disappeared.

**Comment by alexandermckay** [comment]
Setting `"noEmit": true` is not an option with `create-react-app`.

From the Cypress [blog](https://www.cypress.io/blog/2019/05/13/code-create-react-app-v3-and-its-cypress-tests-using-typescript/):
_For example we need to actually emit the transpiled code for Cypress to work:_

Setting up my `tsconfig.json` file like this removes the type error and allows me to run Cypress:

```json
{
  "extends": "../tsconfig.json",
  "include": ["../node_modules/cypress", "*/*.ts"],
  "exclude": ["../node_modules/cypress/index.js"],
  "compilerOptions": {
    "noEmit": false,
    "isolatedModules": false 
  }
}
```
`"isolateModules": false` __is optional__
