### ISSUE TITLE
Refactor cy.route "Use delays for responses" copy to avoid wait antipattern

### ISSUE THREAD

**Issue by csi-lk** [cypress-io/cypress-documentation#1967]
## I'm submitting a proposal change to the cy.route docs

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Currently in the [cy.route](https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/route.md) documentation [under the header of "Use delays for responses"](https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/route.md#L351-L362
) reads like so:

> This can be useful for testing loading states, like loading spinners, in the DOM before the request responds.

As per my understanding of [Unnecessary Waiting](https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting) I feel like we should be discouraging this approach of asserting during a delay due to it potentially causing race conditions. Instead, would it be better to suggest the user use `onRequest` / `onResponse` to do these 'loading state' assertions?

I'd like to propose removing this section and replacing it with something like:

```md
### Use `onRequest` / `onResponse` for testing loading states

You can pass in a `onRequest` option that will fire when the route is requested by the browser and an `onResponse` option that fires when it is resolved. This can be useful for testing loading states, like loading spinners, in the DOM before the request responds.

The example below will test that the `.spinner` is visible when the XHR is requested and is no longer shown when the request responds (much like a 'loading' button).
```

```javascript
cy.route({
  method: 'PATCH',
  url: '**/activities/*',
  response: {},
  onRequest: () => {
     cy.get('.spinner').should('be.visible')
  }
  onResponse: () => {
    cy.get('.spinner').should('not.be.visible')
  }
})
```

---

~If you're happy with this approach i'll throw it in a PR :)~

Added PR for proposal: https://github.com/cypress-io/cypress-documentation/pull/1968

**Comment by jennifer-shehane** [comment]
@csi-lk Have you run this code yourself? I'm trying to update some of our tests that are using `delay` to this new `onRequest` and `onResponse` suggestion and it's not working. The route seems to never resolve. 

Do you have a working example I could see?

**Comment by csi-lk** [comment]
Hey @jennifer-shehane, sorry I haven't run the specific code example of both using `onRequest` and `onResponse` that I added above, i'll have a look at this.

I have however been using `onRequest` on it's own to check for 'loading states' and that seems to resolve

I'll create a repo with examples when I get time (hopefully tomorrow)

Thanks for having a look

**Comment by flotwig** [comment]
`cy.route()` was removed in Cypress 12, closing this issue.
