### ISSUE TITLE
language button disappears when zooming 110% into the page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1969]
100% for https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell - the translation button (the language switch) is visible

<img width="1400" alt="Screen Shot 2019-08-06 at 2 54 09 PM" src="https://user-images.githubusercontent.com/2212006/62567955-42469480-b85a-11e9-9257-6b3a8aa855fb.png">

zoom to 110% - and the button disappears completely

<img width="1398" alt="Screen Shot 2019-08-06 at 2 54 14 PM" src="https://user-images.githubusercontent.com/2212006/62567977-4bcffc80-b85a-11e9-841d-877c353435b0.png">

Same effect in Chrome and Firefox

**Comment by jennifer-shehane** [comment]
Yeah, it's switching to new media queries for smaller screens that hide the button.

**Comment by bahmutov** [comment]
yeah, it is a little bit too aggressive
