### ISSUE TITLE
Set page titles from translation document

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#1973]
Currently, our markdown files have the title of the page in the metadata above it. For example "Why Cypress" page comes from `why-cypress.md` with the title

```
---
title: Why Cypress?
---
```

<img width="838" alt="Screen Shot 2019-08-07 at 10 59 01 AM" src="https://user-images.githubusercontent.com/2212006/62633641-79708080-b902-11e9-9bd3-1bf283ca9bbe.png">

When we translate this page, the metadata is also translated, for example the Chinese translation has which is correctly displayed

```
---
title: 为什么选择Cypress?
---
```

<img width="855" alt="Screen Shot 2019-08-07 at 11 00 34 AM" src="https://user-images.githubusercontent.com/2212006/62633714-9b6a0300-b902-11e9-89fb-ab2e942ba797.png">

But for untranslated pages, the English title is displayed. Here is the Japanese translation

<img width="793" alt="Screen Shot 2019-08-07 at 11 01 21 AM" src="https://user-images.githubusercontent.com/2212006/62633797-be94b280-b902-11e9-946a-9ff3c29d0079.png">

Note that we actually have Japanese translation for this title in file `themes/cypress/languages/ja.yml`

```
sidebar:
  guides:
    overview: 概要
    why-cypress: なぜCypress?
```

We should pull these titles for untranslated documents and use them instead of the metadata (if there is no metadata)

**Comment by jennifer-shehane** [comment]
Part of https://github.com/cypress-io/cypress-documentation/issues/1686
