### ISSUE TITLE
remove `cy.window().its('angular')` from its doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1976]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I don't believe this works in newer versions of Angular - furthermore, we shouldn't give examples for the cy.window() that are reliant on outside frameworks - our examples should access props that we know are accessible regardless of 3rd parties.

**Comment by bahmutov** [comment]
yeah, this is old AngularJS 1.x
