### ISSUE TITLE
Automate redeployment upon Contentful changes

### ISSUE THREAD

**Issue by KateAbramova** [cypress-io/cypress-documentation#1982]
Add Middleman or Jekyll sh script and a build step in circle.yml file 

according to 
https://www.contentful.com/developers/docs/ruby/tutorials/automated-rebuild-and-deploy-with-circleci-and-webhooks/

**Comment by amirrustam** [comment]
@KateAbramova I think we can simplify by using the CircleCI trigger: https://www.contentful.com/developers/marketplace/circle-ci-trigger-build/

It would be optimal for the docs to only be redeployed only if docs related content types are changed. If necessary, it's ok for the docs to get its own Contentful workspace.

**Comment by KateAbramova** [comment]
@amirrustam @jennifer-shehane 

The web-hook is ready
https://www.contentful.com/developers/marketplace/circle-ci-trigger-build/
and set up to be triggered by topBanner changes only. 

Now you need to set up the counterpart for the web-hook on circle-ci
And after the setting is complete we'll change the entity to docTopBanner, it's ready on Contentful.

**Comment by amirrustam** [comment]
@KateAbramova I believe you have access to CircleCI to finalize this issue. Ping me if you have difficulties with Circle. Thanks.

**Comment by KateAbramova** [comment]
@amirrustam 
Although the webhook is ready and working, triggering the entire deploy workflow to production via API is impossible at this stage, API is not working and constantly getting permission denied. Confirmed with Gleb.

**Comment by bahmutov** [comment]
@KateAbramova why did you re-open this issue? Is empty commit against the `master` branch via GitHub API not working?

**Comment by KateAbramova** [comment]
@bahmutov 
Opened a separate issue here:
https://github.com/cypress-io/cypress-documentation/issues/2104
