### ISSUE TITLE
Scrolling on mobile is not a good user experience with marketing banner

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1991]
## Type of bug / changes

Scrolling on mobile is quite unusable since adding the new marketing banner. As originally noted by this person: https://twitter.com/nunoancruz/status/1159388002281512960?s=21

The only portion that is scrollable is the portion below the main nav, which is just frustrating at best. This is a place our users should feel comfortable reading technical documentation for as long as necessary to find their answer.

<image src="https://user-images.githubusercontent.com/1271364/62760557-4668f100-baaa-11e9-8b28-05050b6d8b9f.gif" height="500"/>

Some possible solutions:

1. Add an `x` button to close the marketing banner. 
2. Do not have the banner stick to top of page on scroll, instead, hide on scroll.
3. Update the design so that the scrollable area of the screen is much more than 50% height.
4. Suggestions?

**Comment by KateAbramova** [comment]
@jennifer-shehane 
4. Suggestions
Reduce top and bottom margins for the top banner and not make it stick to top of the page when scrolling down. When scrolling up the banner will appear again
