### ISSUE TITLE
Outside PRs are failing

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1993]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

PRs from outside contributors are failing. See:

- https://github.com/cypress-io/cypress-documentation/pull/1974
- https://github.com/cypress-io/cypress-documentation/pull/1990#

It's failing on `cy.readFile()` to find the `banners.yml`. 

```
  1) Contentful driven banners displays all current banners with proper info:
     CypressError: Timed out retrying: cy.readFile("source/_data/banners.yml") failed because the file does not exist at the following path:

/root/cypress-documentation/source/_data/banners.yml
```

It's also failing trying to click on the table of contents - notice the contentful banner is not displaying in the screenshot as well. 

![Table of Contents -- scrolls to right position on click -- displays header text on click (failed)](https://user-images.githubusercontent.com/1271364/62768728-82598180-babd-11e9-9ec6-7bba2ac3d009.png)

**I suspect this has to do with forked PRs not having access to our CircleCI env vars as documented here: https://github.com/cypress-io/cypress/issues/1193 @bahmutov**

Previous solution was to detect when in a forked PR using https://github.com/bahmutov/is-fork-pr and change behavior based on that.

**Comment by KateAbramova** [comment]
@jennifer-shehane 

Expected behavior:
readFile works as readFileMaybe from the example

https://docs.cypress.io/api/commands/task.html#Command

using this approach we get:
![photo_2019-08-09 14 27 25](https://user-images.githubusercontent.com/49243310/62775965-ebd39300-bab1-11e9-936b-b62e53093ba9.jpeg)

**Comment by jennifer-shehane** [comment]
Yeeeeah, this is not a great example in our docs - it's missing the module.export portion. I will open a separate issue to fix this example. The code should be:

```js
const fs = require('fs')

module.exports = (on, config) => {
  on('task', {
    readFileMaybe (filename) {
      if (fs.existsSync(filename)) {
        return fs.readFileSync(filename, 'utf8')
      }
  
      return null
    }
  })
}
```
