### ISSUE TITLE
Title links in webinar page are linking to it's own page instead of outside link. 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1998]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

<img width="840" alt="Screen Shot 2019-08-09 at 10 28 38 AM" src="https://user-images.githubusercontent.com/1271364/62793870-a4242a00-baf8-11e9-9430-c7cb6163449c.png">

**Comment by CypressCecelia** [comment]
@jennifer-shehane I believe this is no longer an issue, correct? The links appear to be working properly. Ok to close?

**Comment by jennifer-shehane** [comment]
yah I think I fixed this at some point.
