### ISSUE TITLE
The documentation should indicate where to download a cypress archive and how to download it in a specific version.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#200]
**Noted in [cypress #866](https://github.com/cypress-io/cypress/issues/866):**

The [documentation](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Advanced) should indicate **where** to download a cypress archive and **how** to download it in a specific version. 
A devops could have to build a CI for projects running a different cypress version then `@latest`.

Related to [this issue](https://github.com/cypress-io/cypress/issues/701).

**Comment by bahmutov** [comment]
I had code snippet in the old version of install doc what showed how to use `curl -O` to download, but did not explain our CDN

https://github.com/cypress-io/cypress-documentation/commit/d807f91cc0e06cca94a916b8fc84177838d54af0
