### ISSUE TITLE
[Docs] Visual testing Percy (Incorrect blog URL)

### ISSUE THREAD

**Issue by pgroot91** [cypress-io/cypress-documentation#2006]
The URL for one of the blogpost is not existing

https://docs.cypress.io/guides/tooling/visual-testing.html#Percy

![image](https://user-images.githubusercontent.com/6934501/62943154-1a1ae080-bdda-11e9-8152-989f1cd23850.png)

https://www.cypress.io/blog/2019/04/19/webinar-recording-cypress-and-percy-end-to-end-functional-and-visual-testing-for-the-web/

**Should be:**
https://www.cypress.io/blog/2019/04/19/webinar-recording-cypress-io-percy-end-to-end-functional-and-visual-testing-for-the-web/

**Comment by jennifer-shehane** [comment]
![](https://media.giphy.com/media/ANbD1CCdA3iI8/source.gif)

key diff being `cypress-and-percy` versus `cypress-io-percy`

**Comment by CypressCecelia** [comment]
This is resolved.
