### ISSUE TITLE
Add notice to translated docs that they may be out of sync with English doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2008]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[x] Process update (build, deployment, ... )
```

## Type of bug / changes

In order to clean up the process of writing docs / not having to maintain changes to translated docs unless actually translating - we'd like to show a notice at the top of translated docs mentioning that the translated docs may have fallen out of sync with our official English docs - and if they would like, check the associated English doc (with a link to it).

Part of https://github.com/cypress-io/cypress-documentation/issues/1686

**Comment by jugalj05hi** [comment]
Hello there, I am new to the vast world of open source. This would be my first open-source contribution. Can I take up this issue?

**Comment by jennifer-shehane** [comment]
@jugalj05hi yes, we're open to contributions.

**Comment by MikeMcC399** [comment]
This issue has the label https://github.com/cypress-io/cypress-documentation/labels/good-first-time-issue however according to the Cypress [5.2.0](https://docs.cypress.io/guides/references/changelog#5-2-0) changelog (Sep 15, 2020)

> Removed unmaintained languages. English docs is the only supported language by the Cypress team. We greatly appreciate the contributions from the community for other languages, but these docs are largely stale, unmaintained, and partial. The Cypress team will seek out more scalable docs internalization implementation in the future

Therefore this issue would be obsolete if there is no longer any non-English language documentation.
