### ISSUE TITLE
Missing command log screenshot in "cy.url" page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2013]
Bug on https://docs.cypress.io/api/commands/url.html#Command-Log

<img width="798" alt="Screen Shot 2019-08-14 at 8 25 12 PM" src="https://user-images.githubusercontent.com/2212006/63064912-b5db4800-bed1-11e9-87d0-92fb45c12b8c.png">

**Comment by jennifer-shehane** [comment]
This image exists and is linked to the proper location, using the correct `imgTag` as well. 

The only thing I can think is that something when wrong with the build or `RevAll` to where is it not referencing the correct version of the file with the appended cachebusting values.

<img width="791" alt="Screen Shot 2019-08-15 at 11 41 35 AM" src="https://user-images.githubusercontent.com/1271364/63071409-c4694400-bf51-11e9-8499-794e5c1c02ab.png">

**Comment by CypressCecelia** [comment]
This is working, closing issue.
