### ISSUE TITLE
Switch npx vs $(npm bin)/cypress open commands in the install docs.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2030]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Do people use npm < 5.2? Should probably look up and see how popular this is somehow and maybe switch this recommendataion of how to run cypress open to just suggest npx cypress open first. 

https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opening-Cypress

<img width="947" alt="Screen Shot 2019-08-20 at 4 24 17 PM" src="https://user-images.githubusercontent.com/1271364/63381628-143b7700-c367-11e9-8cb6-34acc4b12efd.png">

**Comment by clarmso** [comment]
Yes, some people do still use an older version of Node/npm. I just took a quick look at the page. It's not wrong to leave the content as is.  The latest npm version is 6.11.3.

**Comment by jennifer-shehane** [comment]
This was done recently

**Comment by MikeMcC399** [comment]
- This was resolved by https://github.com/cypress-io/cypress-documentation/pull/5388 in Jul 2023
