### ISSUE TITLE
out.json if populated but I am unable to create a cobertura.xml from it

### ISSUE THREAD

**Issue by fasatrix** [cypress-io/cypress-documentation#2047]
## I'm submitting a...

```
[x] Content update
```

## Type of bug / changes

Hi,

I find a little bit hard to understand from the documentation  (https://docs.cypress.io/guides/tooling/code-coverage.html#Install-the-plugin) how to create different coverage reports (format) after the  `out.json` file has been created under the standard  `.nyc_output` once that all tests have been run by cypress.

The online doc states that "The `@cypress/code-coverage` plugin generates the HTML report automatically" but  even if the "coverage" folder has been created each file under it seems to be just a placeholder/scaffold with no information in it. The only file that has been populated correctly with the coverage information is the `out.json`. Is this coverage folder supposed to be populated with relevant info about the coverage in HTML format by default?

Reading further, the doc states "You can also call nyc report to generate other reports, for example, sending the coverage information to 3rd party services".. Can you please explain how?

So far I have used the following all equivalents commands without much success (the cobertura file is created but empty)?
```
npx nyc report --reporter=cobertura --temp-dir .nyc_output/
npx nyc report --reporter=cobertura 
npx npx nyc report --reporter=cobertura --temp-dir .nyc_output/ --report-dir coverage/
'
```
From the helper I read that  "--temp-dir"   is the directory to read raw coverage information from and I am guessing as raw data it referes to the `out.json` in the `.nyc_output` ?

Thanks for for the info

**Comment by bahmutov** [comment]
I believe your issue was `nyc` simply skipped TypeScript files, thus generating empty reports. I have added a note to code-coverage README https://github.com/cypress-io/code-coverage#typescript-users
