### ISSUE TITLE
Need support for CI/CD using bamboo

### ISSUE THREAD

**Issue by Brad19** [cypress-io/cypress-documentation#206]
First of all. This tool offers many cool features and breaks the contemporary traditional automation testing limitations. Kudos to the team !!!

I've been going through the features and experimenting it. Currently i'm not sure if we can implement CI/CD using Atlassian Bamboo as there is no concept of grid here. Can you please advise on this as our CI/CD server is with Bamboo. Your response might help us to have a quick win over deciding the Automation tool in our environment.

**Comment by bahmutov** [comment]
Can I ask what you mean by the grid in the testing environment?

**Comment by brian-mann** [comment]
I think he means - how does he load balance or parallelize our tests across
multiple instances / nodes.

The answer is - you use our Module API today (example here)
https://github.com/cypress-io/cypress/issues/416#issuecomment-337400871

...or you wait and in another couple weeks we'll have load balancing built
first class into Cypress. We have been working hard on this feature!

**Comment by Brad19** [comment]
I mean you can configure and run multiple instances in Bamboo without issues. For eg., i've more than 1 plan configured in Bamboo.

**Comment by Brad19** [comment]
@brian-mann / @bahmutov 
Could you pls let me know if you have any updates for the above. Thanks!!!

**Comment by brian-mann** [comment]
I'm confused. Per your response it sounds like you are asking a question: "Can you configure and run multiple instances in Bamboo without issues?". 

The answer is yes - unless there is an issue I'm not aware of. Are you having an issue? What issue?

**Comment by samfrach** [comment]
I think he is asking : is there a plugin to integrate Cypress in Atlassian Bamboo ?
I know there are for Jenkins but in Bamboo, it's not obvious to launch test plans with Cypress.

**Comment by bahmutov** [comment]
I don't understand the problem. Is Cypress NOT working on Bamboo CI? Or is there additional integration that can make the test runner more useful?

**Comment by henriollik** [comment]
For anyone with the same problem, there's also a docker image available with all cypress dependencies already installed.

https://hub.docker.com/r/cypress/base

**Comment by Elif5757** [comment]
I need also help. 
I have deposited in my script : 
`"cy:run": "cypress run",
"cy:test": "start-server-and-test start http://localhost:4300 cy:run"` 

After that I've added a task in bamboo to run my cypress tests - using the command  "run cy:test" 
That's working but is there a possibility to say bamboo if a test failed then the build break up and suchlike that ?

What options do I have to act with failed test, generally in bamboo ?

**Comment by humayunrana786** [comment]
> I need also help.
> I have deposited in my script :
> `"cy:run": "cypress run", "cy:test": "start-server-and-test start http://localhost:4300 cy:run"`
> 
> After that I've added a task in bamboo to run my cypress tests - using the command "run cy:test"
> That's working but is there a possibility to say bamboo if a test failed then the build break up and suchlike that ?
> 
> What options do I have to act with failed test, generally in bamboo ?

Hello I need detail steps - hw can I run cypress n bamboo. Can you please guide me?
humayunrana786@gmail.com
