### ISSUE TITLE
Need to trigger single job to build and deploy docs to production

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2069]
Whenever Contentful changes, it needs to trigger production build and deploy. Currently it triggers `build` job against the `master` branch, but it needs to trigger "build + docs-test + deploy-docs-production".

First, try to trigger a job by name. If we can do that, then we can write a single job where build + docs-test + deploy-docs-production would be just commands. 

Q: Does this mean docs-test will run inside a single container? Probably

**Comment by TonySynenko** [comment]
contentful webhook get 201 response and circle-ci build failed with
https://circleci.com/gh/cypress-io/cypress-documentation/15929
