### ISSUE TITLE
Duplicate links in section Podcasts

### ISSUE THREAD

**Issue by brunopulis** [cypress-io/cypress-documentation#2074]
The latest podcasts on the list titled "[Dave Beck with Foundry 45 and Brian Mann with Cypress.io](https://businessradiox.com/podcast/atlanta-business-radio/dave-beck/)" and "[Cypress.io](https://businessradiox.com/podcast/atlanta-business-radio/dave-beck/)" are being directed to the same link.

**Comment by GSKSan** [comment]
Hello! Can I work on this issue? I am a first timer

**Comment by Raynobrak** [comment]
I don't exactly understand what the issue is, could you give more details ?
I'm interested in taking care of this issue as it doesn't seem to be too complicated and I'm a first timer :)
