### ISSUE TITLE
Explain partial selector for CSS classes

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2092]
Need to show CSS selector for https://twitter.com/WebWhizJim/status/1175524256790261761

<img width="925" alt="Screen Shot 2019-09-22 at 3 36 58 PM" src="https://user-images.githubusercontent.com/2212006/65393464-ddce8e80-dd4e-11e9-8752-ee30165fc0ab.png">

Should show `attribute*=` and prefix and suffix, which I think is like `attribute^=` for example

**Comment by JimTheMan** [comment]
^ For sure I think this would be useful... I didn't even know this was the syntax until Gleb responded to my tweet on Twitter! 😆

**Comment by jennifer-shehane** [comment]
Maybe just add an example to this doc https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/get.md
