### ISSUE TITLE
One possibly ambiguous item re: yielding primitive values

### ISSUE THREAD

**Issue by brettz9** [cypress-io/cypress-documentation#2097]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Regarding the text in `/source/guides/core-concepts/introduction-to-cypress.md`:

> Cypress cannot yield you primitive values

...isn't this a bit of an overgeneralization as one can using`Cypress.$`?

I know the DOM isn't really primitive, but it seems like this section is suggesting one cannot get at the underlying values. I think it might help to clarify.

**Comment by jennifer-shehane** [comment]
Yeeeaaah...I think the intent of this section is to say that everything is a Promise so you can't expect to just pull out and know a value of one tiny piece of your cypress command chain. So if this can be explained better, then we're open to suggestions.

**Comment by brettz9** [comment]
How about this:

> Cypress very much tends to avoid returning or resolving to primitive values and objects isolated from other commands (`Cypress.$` being one exception, and it is not the favored default approach). That is because most Cypress commands act internally like an asynchronous stream of data that only resolve after being affected and modified by other commands. This means we will not typically yield you discrete values in chunks because we either have to know everything about what you expect before handing off a value or to wait longer to avoid timing issues.

(I also attempted to clarify that it seems with cypress it is not only the dependence on other commands as it simply may be of waiting longer.)
