### ISSUE TITLE
Declare variables for stage and master environment

### ISSUE THREAD

**Issue by KateAbramova** [cypress-io/cypress-documentation#2119]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update
[Х] Process update (build, deployment, ... )
```

## Type of bug / changes

For a proper deploy process declare env variables as token with a prefix.

**Comment by amirrustam** [comment]
@KateAbramova this issue is not clear or detailed enough. Please elaborate further with full details so that all stakeholders can stay informed.

**Comment by KateAbramova** [comment]
@amirrustam , when we added the change of GATSBY_CONTENTFUL_ENVIRONMENT based on process.env.NODE_ENV the fact that GATSBY_CONTENTFUL_ACCESS_TOKEN varies for different environments was missed, that's why changes are required.
