### ISSUE TITLE
Describe how to solve "cached binary not found" error on CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2140]
Dominic Elm, our ambassador had this problem in branch https://travis-ci.org/d3lm/ngx-drag-to-select/jobs/594782686 where `yarn` would not install Cypress binary. The docs in https://docs.cypress.io/guides/references/error-messages.html#A-Cached-Cypress-Binary-Could-not-be-found are less than clear. I think we can put an additional section there telling to:

- upgrade `yarn` or `npm` version to avoid their bugs
- trigger clean rebuild by telling CI to clean its cache and rebuild
- run install with `DEBUG=cypress:cli` environment variable to see what is going with the installation
- run `npx cypress cache path` and `npx cypress cache list` to see installed binary versions
- maybe add `npx cypress install` command to ensure the binary is there, even if the `postinstall` hook is not triggered by some reason

**Comment by bahmutov** [comment]
Maybe link to https://github.com/bahmutov/yarn-cypress-cache as another example

**Comment by amirrustam** [comment]
@bahmutov is this still valid?

**Comment by fchandebois** [comment]
Same for me @amirrustam  & @elvishuges ? did you figured out this issue ? thanks ;)

**Comment by EMazzaglia** [comment]
+1 here 

`Run npm run e2e

> xpo-go-member-portal@0.1.0 e2e
> cypress run --headless

The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/8.7.0/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 8.7.0
npm ERR! code 1
npm ERR! path /home/runner/work/go-plus-pipeline/go-plus-pipeline
npm ERR! command failed
npm ERR! command sh -c cypress run --headless

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-18T15_30_28_539Z-debug.log
Error: Process completed with exit code 1.`

**Comment by MikeMcC399** [comment]
- This issue was resolved through https://github.com/cypress-io/cypress-documentation/pull/5928

See https://docs.cypress.io/app/references/advanced-installation#Troubleshoot-installation
