### ISSUE TITLE
Add Stefano's ReacJSDays workshop on the workshop page

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#2142]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Add the following ReachJS Days testing workshop to the [workshop](https://docs.cypress.io/examples/examples/workshop.html) page of the docs.

Link: https://noriste.github.io/reactjsday-2019-testing-course
Title: ReactJSDay 2019 Testing Course
Published on Github by [Stefano Magni](https://twitter.com/NoriSte)

**Comment by bahmutov** [comment]
it is beautiful workshop site

**Comment by Diegoafv** [comment]
Can I help with this one?

**Comment by amirrustam** [comment]
@Diegoafv Sure thing, and thank you. Request my review on the PR.
