### ISSUE TITLE
Explain consequences of exposing a record key

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2151]
**Add this content to https://docs.cypress.io/guides/dashboard/projects.html#Record-key likely within the 'note warning section.**

Anyone that has access to both the `projectId` and the record `key` of your project will be able to record runs to your organization in the Dashboard. 

Typically, you would not want people outside of your team running tests for a few reasons:

1. This could drive up the number of tests you've run. Since Cypress bills based on the number of tests - this would mean they could use up all allotted tests and there would be consequences to that.
2. They can write any data they want to your Cypress Dashboard. They could edit the test suite so that the tests that are recorded record very different things than the original project's tests. This could including visiting different websites and generating videos of visiting those websites, for example.

If a record key was exposed you can delete and regenerate a new record key. Deleted keys will be invalid and if the project is run with a deleted key, it will no longer be able to record.

**Comment by torgeadelin** [comment]
Hi!, I'd like to work on this!

**Comment by torgeadelin** [comment]
@jennifer-shehane any updates on this?
