### ISSUE TITLE
--arg not writing `--` when in inline code blocks

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2196]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

When typing `--arg` in the docs, it formats it as `-arg`

<img width="880" alt="Screenshot 2019-10-25 11 52 42" src="https://user-images.githubusercontent.com/1271364/67587599-3a441580-f722-11e9-948f-d921128c30f4.png">

It appears this hacky fix is no longer working: https://github.com/cypress-io/cypress-documentation/pull/935

**Comment by jennifer-shehane** [comment]
This is fixed in `marked` 0.5.1 - this is a dep of `hexo-renderer-marked`, so this needs to likely be updated.

**Comment by jennifer-shehane** [comment]
Updating these deps is a nightmare. A more temporary fix would be to insert this replacement algorithm into our changelog rendering: 

## Replacements needed

https://github.com/cypress-io/cypress-documentation/blob/develop/lib/tags/note.js#L46

## Changelog rendering

https://github.com/cypress-io/cypress-documentation/blob/develop/lib/tags/changelog.js#L28

**Comment by andrew-codes** [comment]
@jennifer-shehane are we aware of any other places that also need this type of substitution? I am trying to determine if we can add it to `rawRender` directly instead of adding it in `changelog.js` (as well as already having it in `note.js`)

**Comment by jennifer-shehane** [comment]
I believe it's anytime we call hexo directly to render. This is the only place I saw. The other place in note is using `renderSync` though.

Ideally updating all of the packages *should* fix this, but it's a nightmare chain of breaking changes that would take a while.
