### ISSUE TITLE
Update the webinars page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2229]
Webinars page https://docs.cypress.io/examples/media/webinars-media.html could benefit from:
1. Add circleci video and slides https://slides.com/bahmutov/circleci-cypress-orb https://www.youtube.com/watch?time_continue=59&v=J-xbNtKgXfY
2. we need a call to action there - sign up to get notified about upcoming webinars, watch live, ask questions, receive a link to the video and slides when they get published, etc.

**Comment by JasonFairchild** [comment]
Yes, please do this. I want a for sure way to be notified about live webinars and get other information about this. Is the best in the meantime to just subscribe to the cypress.io youtube channel?

**Comment by CypressCecelia** [comment]
I can add the CircleCI video/slides.

@magnolia-triplett is there an existing URL to subscribe for upcoming webinar notifications? Or do you have input on what the CTA should be? 

Thanks!

**Comment by magnolia-triplett** [comment]
Users can [subscribe](https://go.cypress.io/subscribe) to Cypress marketing emails, which include webcast announcements. 

If they'd rather not subscribe to email comms, the best way to stay informed about webcasts would be to follow us on [Twitter](https://twitter.com/Cypress_io).
