### ISSUE TITLE
Add page with links to open source projects using Cypress

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2267]
People ask to see what large open source projects are using Cypress. Typical example

<img width="527" alt="Screen Shot 2019-11-27 at 9 37 59 AM" src="https://user-images.githubusercontent.com/2212006/69732441-a0450380-10f9-11ea-999a-db652695c9ca.png">

Some candidates:
- https://github.com/getredash/redash/tree/master/client/cypress/integration
- https://github.com/mermaid-js/mermaid/tree/master/cypress
- https://github.com/withspectrum/spectrum/tree/alpha/cypress

**Comment by amirrustam** [comment]
We can add this page under the "Examples" section with side-menu label of "Projects":

<img width="754" alt="Screen Shot 2019-12-02 at 12 38 16 PM" src="https://user-images.githubusercontent.com/334337/69981837-1fbf4200-1501-11ea-9bf7-f3f7d915db34.png">

The initial implementation can be similar to our courses page: https://docs.cypress.io/examples/media/courses-media.html

We can aggregate the initial list of example projects within this issue.

**Comment by amirrustam** [comment]
Some other examples:

- Vue Storefront: https://github.com/DivanteLtd/vue-storefront/tree/master/test/e2e

- Netlify CMS: https://github.com/netlify/netlify-cms/tree/master/cypress

- NGX Bootstrap: https://github.com/valor-software/ngx-bootstrap/tree/development/cypress

- Octokit: https://github.com/octokit/rest.js/tree/master/test
