### ISSUE TITLE
cy.exec can't find npm when using cypress.run()

### ISSUE THREAD

**Issue by foxdoubt** [cypress-io/cypress-documentation#2285]
## I'm submitting a...

```
[X] Bug report
```

## Type of bug

I have an `npm` script that uses `cypress.run()` in code. The Cypress tests it runs have begun failing in the last few days.  

The first time Cypress tries to execute an `npm` command via `exec` it chokes: 
```
CypressError: cy.exec('npm run <anything>') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
/bin/bash: npm: command not found
```

However, after choking on the first test using `cy.exec`  all subsequent tests that use `cy.exec` run _without issue_. In other words, Cypress can in fact find `npm` after failing to find it once. 

To try to isolate the problem, I stripped out all my actual tests (and my entire application) and replaced them with 4 very simple ones that do basically nothing except use `cy.exec`. Here's the isolated example repo: https://github.com/foxdoubt/cypress-demo. 

Running in debug mode, `DEBUG=cypress:server`, I see that for the first (failing) test, it's trying to source my bash profile:

```
cypress:server shell /bin/bash profile ~/.bash_profile +0ms
cypress:server cy.exec found shell /bin/bash +1ms
cypress:server and is running command: npm run cypress:test +0ms
cypress:server in folder: /Users/Dan/Documents/commons +0ms
```
For all subsequent (passing) tests, it already has my bash profile sourced: 

```
  cypress:server shell /bin/bash profile ~/.bash_profile +2s
  cypress:server profile has already been sourced +1ms
  cypress:server cy.exec found shell /bin/bash +0ms
  cypress:server and is running command: npm run cypress:test +0ms
  cypress:server in folder: /Users/Dan/Documents/commons +0ms
```

To further confound me, if I run my tests from the CLI with `cypress run`, `cy.exec` _does not choke at all_. Debug server output is identical. 

And [here's the full output](https://gist.github.com/foxdoubt/b57205e22d173012b853ded5e6de1f1d) of running with `DEBUG=cypress:*`
 
### Versions
Cypress 3.6.1 and 3.7.0
MacOS 10.14.6

### UPDATE

After a lot more investigation, I found the source of this bug: 

[packages/server/lib/util/shell.js](https://github.com/cypress-io/cypress/blob/4c194fca32038365af260a81bc80bf407080024a/packages/server/lib/util/shell.js#L79)

```
return `source ${profilePath} > /dev/null 2>&1; ${cmd}`
```
This string is what `sourceShellCommand` returns when it's called in the first Cypress test that uses `cy.exec`. However, in subsequent tests, if the `shell.js` module has already sourced the shell command, it just returns `cmd`, which is why it passes the second time and every time after that. What a colleague and I found was that if the command you wanted `cy.exec` to execute just happened to live in `usr/local/bin`, the command executes without issue. But if the executable is not in `usr/bin/local` – like in my case – it fails, but only that first time. For some reason, sourcing my profile causes this to choke, but there was nothing obvious in my `.bash_profile` that would have caused that:

`.bash_profile`
```
#   1. ENVIRONMENT CONFIGURATION

#   Change Prompt

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] => "

#   Set Paths
export PATH="/usr/local/bin/:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/git/bin:/sw/bin/:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

#   Add color to terminal
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# git autocomplete
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi


```

The only way we got this fixed was to symlink `npm` from where NVM installs it to `usr/local/bin` which finally got `cy.exec` working the first time. The reason this only became a problem a few days ago is that I switched to a new laptop then, and installed node via NVM. I don't remember how I installed it previously, but the previous laptop did have a `node` and `npm` in `usr/local/bin`. 

I believe this issue should be addressed, because a lot of people are using NVM these days to install and manage Node versions, and those folks may end up getting snagged by this.

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
