### ISSUE TITLE
Add a few links to cy.click API page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2293]
I was looking at Gitter and messages like this one always 💔

<img width="768" alt="Screen Shot 2019-12-09 at 9 31 01 AM" src="https://user-images.githubusercontent.com/2212006/70443774-b8584380-1a66-11ea-9bdc-cf381f830231.png">

Why can't the users find the docs and examples for `click`?
- each command needs to have a link to its API page, probably when you click on it in the test runner, this is part of our general command and error UI improvement, whenever that gets shipped
- if the users have not scaffolded a new project and have not looked at the examples, then THEY HAVE NO IDEA ABOUT https://example.cypress.io/commands/actions even if they find https://on.cypress.io/click

Ughh.

I think we need to include link to the example page from `cy.click` and other relevant commands in our docs.

Also, a good idea is to include a few blog posts there, like https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/

**Comment by jennifer-shehane** [comment]
I think the examples in `click` just need to be expanded to show more css selectors, all of the examples are `cy.get('button').click()`, should just need to throw in more examples like `cy.get('.nav > a').click()` and `cy.get('[id^=btn]').click`
