### ISSUE TITLE
How to Go to Function Defination of Cypress Command in VSC

### ISSUE THREAD

**Issue by mohitsingla1** [cypress-io/cypress-documentation#2296]
cy.absenceReason();

if I click on absenceReason() cypress command,unable to go to its Defination

------------------------------------------------------------------------------
**I have created absenceReason in one JS file**
Cypress.Commands.add('DeleteAbsenceReason',(absenceReason)=>{
   cy.SelectElementFromListOfElements(absenceReasonLocator.AbsenceReasonNames,absenceReason);
    cy.Click(absenceReasonLocator.TrashButton);
    cy.Click(absenceReasonLocator.DeleteConfirm);
})

**Comment by mohitsingla1** [comment]
Resolved  by Adding a Plugin Cypress Helper in VSC.
You can right click(mouse) on Custom Command and select Go to Command Defination

**Comment by jennifer-shehane** [comment]
Link to plugin for others https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper
