### ISSUE TITLE
link "submit your own plugin" get a 404 page.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress-documentation#2300]
## I'm submitting a...

```
[ ] Bug report
[v] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
I want to learn how to submit plugin, and click link "submit your own plugin" on https://docs.cypress.io/plugins/

<img width="1017" alt="截屏2019-12-12上午9 58 50" src="https://user-images.githubusercontent.com/22906174/70676144-26e70c80-1cc6-11ea-9132-76e318770133.png">

I got a 404 page:

https://github.com/cypress-io/cypress-documentation/blob/develop/.github/CONTRIBUTING.md#adding-plugins

<img width="861" alt="截屏2019-12-12上午10 04 59" src="https://user-images.githubusercontent.com/22906174/70676362-e50a9600-1cc6-11ea-8d04-87c44b8e9d3c.png">

**Comment by jennifer-shehane** [comment]
This will be fixed in this PR. https://github.com/cypress-io/cypress-documentation/pull/2310
