### ISSUE TITLE
https://docs.cypress.io/run-tags 404s

### ISSUE THREAD

**Issue by cyrus-eh** [cypress-io/cypress-documentation#2318]
## I'm submitting a...

```
[] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

![image](https://user-images.githubusercontent.com/57228046/71028126-89267f80-20c1-11ea-90d7-08eb9750e709.png)

**Comment by jennifer-shehane** [comment]
Thanks for opening this bug report. I'll shoot this over to our Dashboard team since their linking is incorrectly routing from https://on.cypress.io/run-tags. This should go to https://docs.cypress.io/guides/guides/command-line.html#cypress-run-tag-lt-tag-gt

**Comment by jennifer-shehane** [comment]
This has been fixed!
