### ISSUE TITLE
Explain how to keep record key secret when warning to keep it secret. 

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2323]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

We explain to people that it's very important to not expose their record key in this section, but then we do not explain to them HOW to keep it secret. 

- Section: https://docs.cypress.io/guides/dashboard/projects.html#Record-key should link to https://docs.cypress.io/guides/guides/continuous-integration.html#Environment-variables

**Comment by Priyanka-Bnsl** [comment]
what exactly has to be done?

**Comment by jennifer-shehane** [comment]
In this section: https://docs.cypress.io/guides/dashboard/projects.html#Create-new-record-key we should link to this other section that explains how to set your Record Key as an environment variable. https://docs.cypress.io/guides/guides/continuous-integration.html#Environment-variables

**Comment by wolframalexa** [comment]
I can take this one, if it hasn't been claimed yet!

**Comment by jennifer-shehane** [comment]
@wolframalexa Sure!

**Comment by wolframalexa** [comment]
Just created a pull request - let me know what you think!
