### ISSUE TITLE
Doc: `request.body` is used instead of `requestBody`

### ISSUE THREAD

**Issue by deerawan** [cypress-io/cypress-documentation#2325]
## I'm submitting a...

- [x] Bug report
- [ ] Content update
- [ ] Process update (build, deployment, ... )

## Type of bug / changes

in network request https://docs.cypress.io/guides/guides/network-requests.html#Assertions, there is a code snippet regarding request body

```js
cy.get('@new-user') // yields the same XHR object
  .its('request.body')
  .should('deep.equal', {
    id: '101',
    firstName: 'Joe',
    lastName: 'Black'
  })
```

`request.body` is used instead of `requestBody` since I got autocomplete for that. Is using `request.body` expected in this case?

**Comment by jennifer-shehane** [comment]
Yes, good catch 👍
