### ISSUE TITLE
Can't start cypress documentation fork because of eslint-plugin-cypress-dev

### ISSUE THREAD

**Issue by viraxslot** [cypress-io/cypress-documentation#2333]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```
## Type of bug / changes
Hi, I can't start my fork with cypress documentation because of the error:
```
65601 verbose stack Error: eslint-plugin-cypress-dev@3.0.2 postinstall: `node ./deprecated --renamed @cypress/eslint-plugin-dev --message 'you may also need to rename cypress-dev -> @cypress/dev in your .eslintrc'`
65601 verbose stack Exit status 1
```
I've tried to:
- delete node_modules and `npm i` again
- update npm
- install only eslint-plugin-cypress-dev

Nothing helps and I have to idea how to solve it. Could you help please?
You can get the branch here, all changes are made: [cypress docs fork](https://github.com/viraxslot/cypress-documentation)

Log:
[cypress-docs-installation.log](https://github.com/cypress-io/cypress-documentation/files/4000842/cypress-docs-installation.log)

**Update:** I can't start origin documentation as well from `develop` branch
**Update 2:** I've changed node/npm version as written in contributing.md. Same result.
$ node -v; npm -v
v8.6.0
5.10.0

**Comment by jennifer-shehane** [comment]
I do also receive this warning, but this does not exit the install process for me. I've opened a PR to fix the deprecation warning https://github.com/cypress-io/cypress-documentation/pull/2342
