### ISSUE TITLE
Add dedicated search page

### ISSUE THREAD

**Issue by NoelDeMartin** [cypress-io/cypress-documentation#2351]
As far as I know, there is currently no way to perform searches other than using the search input on the top navigation bar. It would be useful to have a url such as `https://docs.cypress.io/search/?q={search}`.

I'm sure there are more scenarios where this can be useful, but one in particular is to integrate [Duck Duck Go bangs](https://duckduckgo.com/bang) with the cypress documentation (specially because !cy and !cypress are currently available).

I see the documentation is implemented using hexo, so I'd be willing to create a pull request adding the page. But I'd like to get an OK from some of the maintainers first :).

[I already did this](https://github.com/vuejs/vuejs.org/pull/1488) for the Vue documentation a while ago, so you can take a look at that to see what I'm talking about.

**Comment by jennifer-shehane** [comment]
@NoelDeMartin Yes, we would be open to accepting this work. We use hexo and algolia also, so the implementation should be similar. Be a bit patient with the PR review turnaround as we don't have as many resources on the docs team as our product atm.
