### ISSUE TITLE
Sidebar categories not expanding on docs site.

### ISSUE THREAD

**Issue by bhayward93** [cypress-io/cypress-documentation#2354]
### Current behavior:

Links on the sidebar are note expanding to navigate content. Tested Chrome, Chromium and Firefox.

![image](https://user-images.githubusercontent.com/18596813/63453938-a912a300-c441-11e9-977a-ce7f8a6b39cf.png)

### Desired behavior:

Sidebar items should should expand on click.

### Steps to reproduce: (app code and test code)

Visit https://docs.cypress.io/guides/overview/why-cypress.html
Try to click a category on the sidebar, e.g. Getting Started

### Versions

Chrome, Chromium and Firefox

**Comment by MagedAhmad** [comment]
It works fine for me ! (Firefox)

**Comment by CypressCecelia** [comment]
@jennifer-shehane @bhayward93 I believe this is resolved, can you confirm if I'm missing something? Thanks!

**Comment by jennifer-shehane** [comment]
Yah, I'm not sure I was able to reproduce this ever.

**Comment by CypressCecelia** [comment]
Closing as unable to reproduce.

**Comment by bhayward93** [comment]
Hey, sorry for the lack of response; yeah it appears to be fixed properly for me

**Comment by bhayward93** [comment]
Out of curiosity @CypressCecelia I was wondering if you knew where BrowserStack integration sits on your roadmap?
