### ISSUE TITLE
Update overriding env variables wording to be clearer

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#236]
> Values in here will overwrite conflicting values in cypress.json.

From discussion on https://github.com/cypress-io/cypress/issues/909, this should really say:

> Values in here will overwrite conflicting environment variables in cypress.json.

**Comment by clairecliu** [comment]
I would like to give this a try.

**Comment by danverde** [comment]
The [docs](https://docs.cypress.io/guides/references/configuration.html#Environment-Variables) currently say:

> You can also use environment variables to override configuration values. This is especially useful in Continuous Integration or when working locally. This gives you the ability to change configuration options without modifying any code or build scripts.
> 
> By default, any environment variable that matches a corresponding configuration key will override the cypress.json value.

From what I understood of [cypress-io/cypress#909](https://github.com/cypress-io/cypress/issues/909) this is incorrect & needs to be updated.
