### ISSUE TITLE
Add links / examples for localStorage in our docs

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2385]
So users don't have to hunt like in this question: https://twitter.com/amro_kaza/status/1216325458410770432

```
@Cypress_io
 can any one help me to how to set local storage i searched 
in document and didn't find it just found how to clear storage 
only,however i tray 
cy.localStorage.setItem('ip_address', 'http://xx.xx:8008') 
but receive error when run script
```

- from https://docs.cypress.io/api/commands/clearlocalstorage.html#See-also add links to https://example.cypress.io/commands/local-storage and plugin "cypress-localstorage-commands" from https://on.cypress.io/plugins
- expand https://example.cypress.io/commands/local-storage with setting and getting local storage and explanation of async vs sync command
- expand cypress-example-todomvc to show setting and getting local storage in the TodoMVC app

Should `localStorage` guide be its own thing in our docs? It is a browser feature that many web apps are likely to use, and our docs really don't mention anything about it

**Comment by jennifer-shehane** [comment]
>Should localStorage guide be its own thing in our docs? It is a browser feature that many web apps are likely to use, and our docs really don't mention anything about it

If it were to be a full guide, I would recommend a guide involving all browser storage mechanisms, which is a common problem for users. Cookies, localStorage, sessionStorage, etc. Explaining which ones are automatically cleared by Cypress - how to work with them in general, any special settings around them such as whitelisting.
