### ISSUE TITLE
Not able to fetch the data from json file kept under fixture

### ISSUE THREAD

**Issue by barun-upb** [cypress-io/cypress-documentation#2404]
In one of my test case am trying to load data from fixtures but unable to do so. 
Error: username undefined

**loading the testData from testData.json**:

before(function()
 {
    cy.fixture('testData').then(function(testData)
    {
       this.testData = testData
    })
});

**passing the username value stored in testData.json**
cy.get('someWebElement').type(this.testData.username)

**testData.json**
{
    "username": "something"
}

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
