### ISSUE TITLE
How to verify the value in api Response Array

### ISSUE THREAD

**Issue by Kishorekumar2789** [cypress-io/cypress-documentation#2457]
Hi @jennifer-shehane, How can I verify an email id in api response which(email-id) is created from UI.

Response return as an array but how to compare the created email id with response data?

Sample Code:
cy.server();
cy.route('GET', 'ENDPOINT').as('userlist');
/*email id created in UI/
cy.wait('@userlist').then(function(res) {
cy.log('Response: ' + res.responseBody);
});

Sample Response:
[
{"id":"id1",
"emailid":"emailid1"
},
{"id":"id2",
"emailid":"emailid2"
}
]

![image](https://user-images.githubusercontent.com/42167657/73647323-8684e700-467b-11ea-9191-581d0110c4ba.png)

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.

**Comment by Kishorekumar2789** [comment]
Fine @jennifer-shehane  I have created the same issue in link which you shared above!
