### ISSUE TITLE
Update 'cannot be chained' to state that it 'makes no sense to chain'

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress-documentation#2508]
### Current behavior:

This code works.
```js
cy.clearCookies({ domain: null })
    .visit('/');
```

### Desired behavior:

Well, the documentation says that _clearCookies_ can not be chained.

<img width="632" alt="docs about clearCookies 1" src="https://user-images.githubusercontent.com/58426925/74443025-c9f90580-4e72-11ea-8182-b7ae2099df55.png">

<img width="898" alt="docs about clearCookies 2" src="https://user-images.githubusercontent.com/58426925/74443030-cb2a3280-4e72-11ea-8701-863f4b827870.png">

**However** it does not make any sense to forbid users from chaining next cypress commands.
I suggest to update docs and explain that clearCookies does not yield subject but it can be chained further with cy commands.

**Eventually, make _clearCookies_ yield list of cleared cookies.**

### Test code to reproduce

```js
cy.clearCookies({ domain: null })
    .visit('/');
```

### Versions

The latest and previous versions.

**Comment by shwarcu** [comment]
Thanks for moving it to the correct place. 
Could you consider updating this command to yield a list of deleted cookies?

**Comment by jennifer-shehane** [comment]
@shwarcu Please open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new) if you want the functionality of the Cypress command to change. This would be a new feature.
