### ISSUE TITLE
Add cy.request to network requests page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2538]
`cy.request` for making cross-domain XHR calls definitely needs to be added to "See also" section of the page https://docs.cypress.io/guides/guides/network-requests.html#Assertions

<img width="1171" alt="Screen Shot 2020-02-24 at 7 33 43 PM" src="https://user-images.githubusercontent.com/2212006/75203779-17138c00-573d-11ea-966e-7e2ea8000022.png">

**Comment by jennifer-shehane** [comment]
yeah...this whole doc is about XHR requests with route, etc though. I guess you're saying they don't even know cy.request exists or its usage in this doc? 

Honestly it should probably use a shoutout at the beginning of the docs like, 'note that if you're looking to do this....look at cy.request()' cause it's not mentioned *at all* on this entire page.

**Comment by bahmutov** [comment]
Yeah - the start of the page could be good. It is just weird to not list the way the test can make its own network requests in the guide to network requests
