### ISSUE TITLE
cy.wait timeout and passing multiple aliases

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress-documentation#2573]
## I'm submitting a...

```
[X] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

`cy.wait()` [can be passed an array of aliases](https://docs.cypress.io/api/commands/wait.html#Arguments). This is good. However, it is not clear what the impact on the [timeout](https://docs.cypress.io/api/commands/wait.html#Timeouts) is. `cy.wait()` has 2 timeouts, `requestTimeout` and `responseTimeout`.

I guess that if before `requestTimeout` all aliases have matched, then `cy.wait()` will be happy. But what if only a few of the aliases have matched while others have not matched yet?

**Comment by DamienCassou** [comment]
From my experiment, passing several aliases to `cy.wait()` means:

> "I want all requests to be sent before `requestTimeout`"

This makes sense but I was expecting a completely different semantics:

> "I don't want to wait more than `requestTimeout` between a response is received and the next request is sent".

More information about my context: https://github.com/cypress-io/cypress/issues/6563.

**Comment by jennifer-shehane** [comment]
Yes, your assessment is correct. When using `cy.wait(['@alias1', '@alias2'])` Cypress will wait for *all* requests to complete within the given `requestTimeout` and `responseTimeout`.

I also do not like this behavior personally as it generally caused me to pull everything out into their own `cy.wait()` which just seems unnecessary. Feel free to open an issue to change this behavior in the `cypress` repo. 

This should definitely be clarified better in the docs. Probably in one or both of these sections:

- https://docs.cypress.io/api/commands/wait.html#Aliases
- https://docs.cypress.io/api/commands/wait.html#Timeouts

**Comment by DamienCassou** [comment]
done

**Comment by DamienCassou** [comment]
Thank you!
