### ISSUE TITLE
cy.url() retuns null

### ISSUE THREAD

**Issue by saranyas72** [cypress-io/cypress-documentation#2575]
cy.url() in scripts hangs. If we use 

```js
let currentURL

cy.url().then(url => {
  currentURL = url.toString()
});
```

and print `currentURL`, it prints 'null'

Please fix this and improve documentation here - https://on.cypress.io/url

**Comment by SandroMiguel** [comment]
Maybe you should wait for some request.

**Comment by jennifer-shehane** [comment]
@saranyas72 `cy.url()` does yield the the url value as shown in my example below. 

Likely you are trying to access the `currentUrl` before the value has been set (in a synchronous way). See this section of our docs for a full explanation. https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code

```js
it('url', () => {
  cy.visit('https://www.wikipedia.org/')
  cy.url().then((url) => {
    console.log(url)
  })
})
```

<img width="488" alt="Screen Shot 2020-03-05 at 12 59 23 PM" src="https://user-images.githubusercontent.com/1271364/75955026-76af2b80-5ee3-11ea-8ac1-efec22a85bc9.png">
