### ISSUE TITLE
Typo in code screenshot for Commands are Asynchronous in docs

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2604]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

There is a typo in the word "immediately" in the code snippet here: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous

![image (1)](https://user-images.githubusercontent.com/60482585/76553609-b8534f80-646a-11ea-8773-66807da16b8d.png)

**Comment by jennifer-shehane** [comment]
This is not a screenshot, this is inline code displaying with these styles, so you can just edit the text in the document. I completely murdered that word 😆 

https://github.com/cypress-io/cypress-documentation/blob/develop/source/guides/core-concepts/introduction-to-cypress.md#L407:L407

**Comment by jennifer-shehane** [comment]
Fixed in https://github.com/cypress-io/cypress-documentation/commit/06171681ba3250e8fa186a0c1e2ffd67c763268e
