### ISSUE TITLE
Documentation website is slow pages taking ~ 30 seconds to load

### ISSUE THREAD

**Issue by noobling** [cypress-io/cypress-documentation#2616]
### Current behavior:
Visit https://docs.cypress.io/ and page loads take a very long time ~ 30 seconds

### Desired behavior:
Visit https://docs.cypress.io/ and pages take  < 5 seconds to load

**Comment by jennifer-shehane** [comment]
I am not experiencing this slowness in load time of the documentation site. Can you confirm if this is still happening and/or if this is localized to a problem on your network?

**Comment by gabrielferreirapro** [comment]
@jennifer-shehane I took some test performance for the docs and everything seems to be right.
So, the results are pretty good.
![Screenshot from 2020-04-09 23-16-28](https://user-images.githubusercontent.com/4117683/78956288-3467a400-7ab8-11ea-9087-30134f3d98ef.png)

I think that issue can be closed :+1:
