### ISSUE TITLE
Offer workaround for CSS hover or state that there is none

### ISSUE THREAD

**Issue by Treppenhouse** [cypress-io/cypress-documentation#2617]
In https://github.com/cypress-io/cypress-documentation/issues/2412 you updated the docs, stating that the trigger() workaround does not affect any CSS triggers, which is great!

Unfortunately, for people in need to test exactly that feature the information ends right there.

It would be great if you could either 

1. Offer a workaround (or a link to a workaround, respectively) or
2. State that there (currently) is no workaround and that such a behaviour is impossible to test with Cypress

Thank you!

**Comment by bahmutov** [comment]
Yeah, the best workaround, for now, is described here https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__chrome-remote-debugging
