### ISSUE TITLE
Cypress tutorial is broken and difficult to follow

### ISSUE THREAD

**Issue by AniaMakes** [cypress-io/cypress-documentation#2626]
### Current behavior:
When following the video https://docs.cypress.io/examples/examples/tutorials.html#1-Project-setup I run into a number of obstacles that make following the tutorial a very frustrating experience that is not accessible to newcomers.

I've only gone through the first video and the list is as follows:
- `npm run dev` fails. This issue has been raised a year ago https://github.com/cypress-io/cypress-tutorial-build-todo/issues/3 and hasn't been fixed - although the last comment on that issue fixes the problems. 
- the video instructs the user to clone and run the repo. However the master branch contains finished exercise rather than the initial state. Only upon further investigation one can discover the other branches which are the various steps of the tutorial. 
- the video instructs the user to write the input-form test and tun `npm run cypress` and launch the integration test (3:22 mark). 
**What the video shows should happen**
![Screenshot 2020-03-18 at 10 08 38](https://user-images.githubusercontent.com/31079643/76949489-80338d00-6900-11ea-8516-cfc268b10162.png)
**What actually happens**
![Screenshot 2020-03-18 at 10 06 36](https://user-images.githubusercontent.com/31079643/76949524-8f1a3f80-6900-11ea-9e0c-0535d61db84f.png)

### Desired behavior:
Should be able to follow the tutorial without "this isn't running, why", and "the code I just cloned doesn't match the one the video talks about, why", and "I'm following the instructions to the letter and my screen is showing completely different thing".

I understand it's time consuming to produce up-to-date videos, but adding a notes before / after the video to check out the step 1 branch before following the video and making sure once a month that the tutorial code actually runs without issues would be good intermediate steps. 

On the note of accessibility, a transcript would be welcome, as it took me a few tries to pause the video in the right place to see what command to run (and yes, some people will want to see the commands written).

### Test code to reproduce

Follow the instructions at https://docs.cypress.io/examples/examples/tutorials.html#1-Project-setup to the word. You'll have issues with 'npm run dev' working and the code on master not matching what the video is talking about. 

### Versions

Node 12.14.1
Mac OS Mojave

**Comment by bahmutov** [comment]
I have started work to update the tutorial repo a while ago but did not finish. It needs CI testing, periodic dependency updates, etc https://github.com/cypress-io/cypress-tutorial-build-todo-starter/tree/add-ci

**Comment by a-onkar** [comment]
> ### Current behavior:
> When following the video https://docs.cypress.io/examples/examples/tutorials.html#1-Project-setup I run into a number of obstacles that make following the tutorial a very frustrating experience that is not accessible to newcomers.
> 
> I've only gone through the first video and the list is as follows:
> 
> * `npm run dev` fails. This issue has been raised a year ago [cypress-io/cypress-tutorial-build-todo#3](https://github.com/cypress-io/cypress-tutorial-build-todo/issues/3) and hasn't been fixed - although the last comment on that issue fixes the problems.
> * the video instructs the user to clone and run the repo. However the master branch contains finished exercise rather than the initial state. Only upon further investigation one can discover the other branches which are the various steps of the tutorial.
> * the video instructs the user to write the input-form test and tun `npm run cypress` and launch the integration test (3:22 mark).
>   **What the video shows should happen**
>   ![Screenshot 2020-03-18 at 10 08 38](https://user-images.githubusercontent.com/31079643/76949489-80338d00-6900-11ea-8516-cfc268b10162.png)
>   **What actually happens**
>   ![Screenshot 2020-03-18 at 10 06 36](https://user-images.githubusercontent.com/31079643/76949524-8f1a3f80-6900-11ea-9e0c-0535d61db84f.png)
> 
> ### Desired behavior:
> Should be able to follow the tutorial without "this isn't running, why", and "the code I just cloned doesn't match the one the video talks about, why", and "I'm following the instructions to the letter and my screen is showing completely different thing".
> 
> I understand it's time consuming to produce up-to-date videos, but adding a notes before / after the video to check out the step 1 branch before following the video and making sure once a month that the tutorial code actually runs without issues would be good intermediate steps.
> 
> On the note of accessibility, a transcript would be welcome, as it took me a few tries to pause the video in the right place to see what command to run (and yes, some people will want to see the commands written).
> 
> ### Test code to reproduce
> Follow the instructions at https://docs.cypress.io/examples/examples/tutorials.html#1-Project-setup to the word. You'll have issues with 'npm run dev' working and the code on master not matching what the video is talking about.
> 
> ### Versions
> Node 12.14.1
> Mac OS Mojave

Follow below steps:

Repo: git clone https://github.com/cypress-io/cypress-tutorial-build-todo-starter.git
Run cmd: npm install
Run cmd: npm update
Run cmd: npm audit fix
Run cmd: npm run dev

Open any browser & enter url: localhost:3030
