### ISSUE TITLE
Add documentation about resolution size when running headlessly

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2702]
## I'm submitting a...

```
[ ] Bug report
 X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

There seems to be some confusion around viewport size vs resolution when running headlessly, and how to override the default setting (Recently updated from 800x600 to 1280x720 in 4.1.0.)

We should add documentation around the difference and include instructions for overriding this setting,  as described in https://github.com/cypress-io/cypress/issues/6210#issuecomment-583269127.

- [ ] Add note to cy.viewport clarifying it only applies to the GUI/Test Runner when using `cypress open`

- [ ] Add FAQ for "how do I update the resolution when running headlessly?"

**Comment by bahmutov** [comment]
More information in https://github.com/cypress-io/github-action/issues/88 and live example implemented in https://github.com/cypress-io/github-action/pull/98

**Comment by jennifer-shehane** [comment]
I updated the docs here today: https://github.com/cypress-io/cypress-documentation/pull/3035 Maybe this could be referenced in more sections of the docs though.

**Comment by joshribakoff** [comment]
The docs should still call out that Cypress uses `xvfb` under the hood auto-magically, and that the hard coded dimensions of 1280px (or whatever the value is) place an upper bound on the maximum effective size of the screenshots, in my opinion, thanks!

PS > would be super great to expose options/configurations to end users of Cypress to configure this. I ended up forking / using `patch-package`.

**Comment by jennifer-shehane** [comment]
Yeah, it is pretty complicated. I feel like this could be built into product.
