### ISSUE TITLE
Is there a way to make the 'run:end' event available for plugins?

### ISSUE THREAD

**Issue by gilgold** [cypress-io/cypress-documentation#2715]
Hey, 
I saw that there is a `run:end` event available if we are using the Module API, however, is there a way to listen to that event from a a plugin?
We have a reporter that reports test results to our internal dashboard and we need a way to detect when all tests have finished. the mocha `end` event fires for each spec that runs and we need to detect when all specs are done

**Comment by jennifer-shehane** [comment]
This is not an available event in the current version of Cypress. You can see all events documented here: https://docs.cypress.io/api/events/catalog-of-events.html

You're likely referring to the events that are planned to be made available here: https://github.com/cypress-io/cypress/issues/2840

This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

If you have a question about how to use Cypress, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
