### ISSUE TITLE
Stubs, Spies, Clocks guide has formatting issue

### ISSUE THREAD

**Issue by eppsilon** [cypress-io/cypress-documentation#2722]
## I'm submitting a...

```
[X] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The formatting of this page is messed up: https://docs.cypress.io/guides/guides/stubs-spies-and-clocks.html#Clock

Starting at the code block after "you can control time by ticking it ahead by milliseconds".

Looks similar to #1655.

**Comment by jennifer-shehane** [comment]
😞
