### ISSUE TITLE
Add Cypress Equivalent of Selenium getText() with an opportunity to set it to variable

### ISSUE THREAD

**Issue by kay4444** [cypress-io/cypress-documentation#2725]
I want to get text and use it somewhere else in my script.
Like:
const var = cy.get('button').text()
var == 'My button name'

Because current implementation is useless (like: cy.get(publication_link).then(($link) => {cy.log(`Link is: ${$link.text()}`)})

**Comment by jennifer-shehane** [comment]
There are examples on how to get the text content of an element here: https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-get-an-element%E2%80%99s-text-contents

There is also a proposal for a `.text()` command you can follow on our main project here: https://github.com/cypress-io/cypress/issues/630

This repo is used solely for issues related to Cypress documentation.
