### ISSUE TITLE
Document difference between cy.get(x).contains(y) and cy.contains(x, y)

### ISSUE THREAD

**Issue by Floriferous** [cypress-io/cypress-documentation#2752]
In the `contains` documentation, some of the examples use `cy.get(x).contains(y)`, and some use the more complete version of contains: `cy.contains(x, y)`.

By reading the docs, it seems like there is no difference between them, however some examples are confusing.

For example, it is not clear why you would want to do
```js
cy.get('form')
  .contains('form', 'Proceed')
  .submit()
```

When you could simply do

```js
cy.contains('form', 'Proceed')
  .submit()
```

In my experience, the `get(x).contains(y)` is more robust, as it will always work when `cy.contains(x, y)` does. However the opposite is not true. I mainly use `should('exist')` assertions chained with `.contains`:

```js
// Works all the time
cy.get(x).contains(y).should('exist');

// Works sometimes
cy.contains(x, y).should('exist');
```

It would be helpful if the documentation could clear this up, and maybe even specify the best practice, since they seem to be interchangeable to me.

**Comment by jennifer-shehane** [comment]
This is covered in the notes under "Scopes" https://docs.cypress.io/api/commands/contains.html#Scopes

**Comment by Floriferous** [comment]
I'm afraid the Scopes chapter doesn't answer my question. According to exactly those docs, it seems obvous to me that:

`cy.get('#checkout-container').contains('Buy Now')`

and

`cy.contains('#checkout-container', 'Buy Now')`

Would yield the exact same result.

**Comment by jennifer-shehane** [comment]
Passing a selector changes the yielded subject as explained in https://docs.cypress.io/api/commands/contains.html#Selector Contains has an element preference that it will prefer when yielding the element: https://docs.cypress.io/api/commands/contains.html#Preferences

So, if you pass `cy.get('#checkout-container').contains('Buy Now')`, Cypress will follow the default element preference and yield the element it finds containing 'Buy Now' (maybe it's a button). 

If you pass `cy.contains('#checkout-container', 'Buy Now')` - it will **ALWAYS** yield the `#checkout-container` element that contains the text 'Buy Now'.

**Comment by aidantorrence** [comment]
why is cy.contains scoped to the previous cy.get even though it's not chained?

**Comment by alinaberlin** [comment]
Why you should use a chain commands @Floriferous when you can just use cy.contains.
Very well explained here https://www.youtube.com/watch?v=VSIaDbv4GyE
