### ISSUE TITLE
New FAQ entry on data sent when using Test Runner

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#2774]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

We need to create a new FAQ entry that details what data is or isn't sent when only using the Test Runner (inspired by this [Tweet](https://twitter.com/marvinirwin7/status/1257344687226175494)), with the answer explaining that the Test Runner is local, so no data is sent aside from exception data, which they can opt out of [here](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opt-out-of-sending-exception-data-to-Cypress).

**Comment by CypressCecelia** [comment]
Can also link to the security page https://www.cypress.io/security/

**Comment by CypressAlexander** [comment]
@magnolia-triplett @CypressCecelia can you please provide exact copy of question and answer of this entry? And what FAQ section should it be in?

**Comment by CypressCecelia** [comment]
Question: What information is captured or transmitted when using the Cypress Test Runner?

Answer: The Cypress Test Runner runs locally, so no data is sent to Cypress aside from exception data, which can be disabled using [the instructions here](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Opt-out-of-sending-exception-data-to-Cypress).
