### ISSUE TITLE
Add FAQ with link to GraphQL workarounds

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2781]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

This issue has multiple GraphQL workarounds but there is currently no mention in our docs. Need to add an FAQ so it is searchable, however a better solution for the future is still needed (Linking to GitHub issue is not ideal).

https://github.com/cypress-io/cypress-documentation/issues/122

**Comment by CypressCecelia** [comment]
There are additional workarounds in this thread as well https://github.com/cypress-io/cypress/issues/687#issuecomment-642071123

Not sure if we will need this anymore with full network stubbing coming out though. @jennifer-shehane should I hold off?

**Comment by jennifer-shehane** [comment]
That will come out as experimental pretty soon and the docs for that mention to use the new experimental feature from `cy.route()` so maybe not https://github.com/cypress-io/cypress-documentation/pull/2854/files#diff-e82e0eb85a12faaaea4008db1c7a0e96

**Comment by amirrustam** [comment]
No longer needed due to `cy.intercept`. @kevinold is also diving into GraphQL examples
