### ISSUE TITLE
FAQ Entry For "Handling Test Flakiness"

### ISSUE THREAD

**Issue by CypressHarry** [cypress-io/cypress-documentation#2794]
## I'm submitting a...

```
[ ] Bug report
[✅] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Add section to Troubleshooting Guide with approaches for debugging test flakiness.

Notes:

- Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion.
-  If there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other
- Because of this, we recommend asserting on as many required steps as possible
- this also helps later to isolate where the exact failure is when debugging on an actual bug.

**Comment by CypressCecelia** [comment]
Also add info about Analytics with the Cypress Dashboard, which can show which tests are most flaky
