### ISSUE TITLE
Add Auth0 blog post to logging in recipes or FAQ

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2797]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Add link to https://sandrino.dev/blog/writing-cypress-e2e-tests-with-auth0

**Comment by amirrustam** [comment]
Check out the new guide we have on Auth0: http://on.cypress.io/auth0
