### ISSUE TITLE
Ongoing: Add new articles to examples

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#28]
There are some pieces of material others have created in the community that mention Cypress. 🎉  

We would love to include these in our [Media](https://on.cypress.io/blogs-media). Please take note of the categories we have in terms of media: [Blogs](https://on.cypress.io/blogs-media), [Screencasts](https://on.cypress.io/screencasts-media), [Talks](https://on.cypress.io/talks-media), and [Podcasts](https://on.cypress.io/podcasts-media) and make sure to place it in the correct category. When in doubt, just ask!

There are instructions on how to add new links here: https://github.com/cypress-io/cypress-documentation/blob/develop/CONTRIBUTING.md#adding-examples

Check off any links from the list after adding it to the examples. Reference the PR to this issue #315.

**Links to material mentioning Cypress:**

Internal spreadsheet of links: https://app.smartsheet.com/sheets/v5255vR5vCGj46gxgRxhxmXc2QX98jJhrH389Jg1?view=grid

- [x] https://applitools.com/blog/test-vuejs-cypress-io-applitools
- [x] https://blog.you54f.com/2019/05/16/the-new-chromium-based-microsoft-edge-for-mac-has-been-leaked%e2%80%8a-%e2%80%8aand-it-works-with-cypress-and-now-you-can-test-it-too/
- [x] http://www.testplus.at/2017/07/cypress-io-ersetzt-diese-neue-automations-engine-selenium/
- [x] https://x-team.com/blog/integration-testing-selenium-phantomjs-and-cypress/
- [x] https://mo.github.io/2017/07/20/javascript-e2e-integration-testing.html
- [x] https://dashbouquet.com/blog/frontend-development/cypressio-and-docker-the-ultimate-e2e-stack
- [x] https://dev.to/antonfrattaroli/cant-wait-for-windows-cypress
- [x] https://medium.com/wehkamp-techblog/integration-testing-with-cypress-101-2524d3244bb4
- [x] https://devchat.tv/adv-in-angular/aia-155-cypress-io-end-end-testing-gleb-bahmutov
- [x] https://medium.com/@darioghilardi/end-to-end-testing-on-a-react-redux-app-10f5a26f2f61
- [x] https://dev.to/adventuresinangular/aia-155-cypressio-and-endtoend-testing-with-gleb-bahmutov
- [x] https://medium.com/@otavio/ferramentas-de-testes-de-aceitação-uma-odisséia-8eff4c96da9e
- [x] https://www.youtube.com/watch?v=D20nX2zAypk&feature=youtu.be
- [x] https://medium.com/@kobvel/cypress-io-vs-protractor-e2e-testing-battle-d124ece91dc7
- [x] https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa
- [x] https://www.simplethread.com/unblock-rails-ui-testing-cypress/
- [x] https://medium.com/oke-software-poland
- [x] https://joecolantonio.com/testtalks/177-cyrpress-io-brian-mann-gleb-bahmutov/
- [x] https://blog.callstack.io/testing-react-app-with-cypress-246a7732ee63
- [x] http://blog.xebia.com/visual-regression-testing-cypress/
- [x] https://youtu.be/rICGz5qrYJU?t=1h14m46s
- [x] https://www.joecolantonio.com/2017/11/16/cypress-io-vs-selenium-test-automation/
- [x] https://www.youtube.com/watch?v=bSpLEJ-CrGk
- [x] https://mabrique.lafamillebn.net/blog/2017/10/27/cypress/
- [x] https://medium.com/bratislava-angular/up-and-running-with-cypress-and-typescript-5b9065eedbd3
- [x] https://frontsidethepodcast.simplecast.fm/
- [x] https://www.youtube.com/watch?v=zTHQqiu_y0Q&list=PLkp6BbeMCOm3TYAIPYkv1R8ESme8xlHVV&index=4
- [x] https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2018-f68950900bc3
- [x] https://medium.com/@NicholasBoll/cypress-io-scaling-e2e-testing-with-custom-commands-6b72b902aab
- [x] https://github.com/goncy/cypress-lesson
- [x] https://www.youtube.com/watch?v=D-h3bhzauKo&feature=youtu.be&t=11383
- [x] http://codingitwrong.com/2018/03/04/comparing-vue-component-testing-tools.html
- [x] https://www.youtube.com/watch?v=5XQOK0v_YRE&t=0s&index=4&list=PLZ66c9_z3umNSrKSb5cmpxdXZcIPNvKGw
- [x] https://www.youtube.com/watch?v=5FnalKRjpZk&t=0s&index=5&list=PLZ66c9_z3umNSrKSb5cmpxdXZcIPNvKGw
- [x] https://techbeacon.com/9-top-open-source-testing-automation-frameworks-how-choose
- [x] https://blog.manifold.co/testing-sucks-here-is-how-to-make-it-better-7af1ff93cc9
- [x] https://medium.com/@NicholasBoll/cypress-io-use-the-log-api-with-custom-commands-b4bffca0d4c5
- [x] https://medium.com/@NicholasBoll/using-jest-matchers-in-cypress-5e8e7281f5dd
- [x] https://joecolantonio.com/testtalks/195-javascript-testing-using-jest-with-kent-c-dodds/
- [x] https://www.grafikart.fr/formations/javascript-unit-test/cypress
- [x] https://www.youtube.com/watch?v=w8liCoPsDIU
- [x] https://wetainment.com/wid-2018-04-11/
- [x] https://youtu.be/nq_WRILIFTw
- [x] https://www.youtube.com/watch?v=k-4pwQZRCN4&feature=youtu.be
- [x] https://www.youtube.com/watch?v=Eakp29J38YA&feature=youtu.be&t=48m54s
- [x] https://www.youtube.com/watch?v=AddBNz1T08U
- [x] https://www.youtube.com/watch?v=lgurVvQsOTY
- [x] https://medium.com/@mikenikles/what-if-your-e2e-tests-generated-your-user-documentation-baefe3ebaee9
- [x] https://automationrhapsody.com/cypress-vs-selenium-end-era/
- [x] https://www.youtube.com/watch?time_continue=29&v=dpB0YgnFyZQ
- [x] https://www.youtube.com/watch?v=UpBfQ6mdb8U&amp=&feature=youtu.be
- [x] https://medium.com/js-dojo/end-to-end-testing-a-vuejs-hackernews-clone-23b9415fd5c5
- [x] https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd
- [x] https://testdriven.io/testing-angular-with-cypress-and-docker
- [x] https://www.youtube.com/watch?v=Sth0bGfFOMw&feature=youtu.be
- [x] https://www.youtube.com/watch?v=Tu9FI5gQX-k&feature=youtu.be
- [x] http://committed.software/posts/cypress/cypress/
- [x] https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd
- [x] http://slides.com/brandonb927/testing-web-applications-with-cypress#/
- [x] https://medium.com/@wataruoguchi/running-e2e-tests-with-selenium-and-cypress-1de69b95d936
- [x] https://blog.bitsrc.io/testing-react-apps-with-cypress-658bc482678
- [x] https://offering.solutions/blog/articles/2018/05/27/end-to-end-testing-with-angular-cypress/
- [x] https://blog.manifold.co/secure-secrets-in-cypress-with-the-manifold-cli-6cd144b3be69
- [x] https://auth0.com/blog/cypress-write-automated-tests-to-validate-web-applications/
- [x] https://medium.com/@shivambharadwaj/https-medium-com-shivambharadwaj-why-you-should-switch-to-cypress-for-modern-web-testing-5d3739a19e6
- [x] https://www.endgame.com/blog/technical-blog/how-we-built-our-automated-ui-testing-framework
- [x] https://applitools.com/blog/comparing-javascript-browser-automation-frameworks
- [x] https://www.youtube.com/watch?v=GhyE3Y5oS_0
- [x] https://www.linkedin.com/pulse/unleash-test-automation-power-cypressio-kushan-shalindra-amarasiri-/
- [x] https://www.youtube.com/watch?v=7N63cMKosIE
- [x] https://www.youtube.com/watch?v=LFUm9qV_Gjo
- [x] https://www.youtube.com/watch?v=zTHQqiu_y0Q
- [x] https://crossbrowsertesting.com/blog/test-automation/selenium-vs-cypress/
- [x] https://www.businesswire.com/news/home/20180626005183/en/Cypress.io-Raises-4-Million-Front-Automated-Testing
- [x] https://youtu.be/UJICwHNb4BQ
- [x] https://thewebplatformpodcast.com/164-cypressio
- [x] https://www.linkedin.com/pulse/spend-more-time-coding-less-testing-our-investment-michael-droesch
- [x] https://www.youtube.com/watch?v=NTanPba9mZM&feature=youtu.be
- [x] https://blog.johnnyreilly.com/2018/07/cypress-and-auth0.html
- [x] https://medium.com/@johnryancottam/integrate-an-awesome-software-testing-tool-cypress-io-into-a-react-app-in-less-than-5-minutes-b4c8bbf1f71c
- [x] https://www.recallact.com/presentation/automated-testing-modern-web
- [x] https://blog.kylegalbraith.com/2018/08/14/how-to-run-browser-tests-via-cypress-in-your-cicd-pipeline-with-aws-codebuild/
- [x] https://medium.com/@ondrej.janosik42/setting-up-bitbucket-pipelines-with-proper-caching-of-npm-and-cypress-74d033888186
- [x] https://medium.com/@grant.glidewell/testing-with-cypress-io-10ca7e4984e0
- [x] https://blog.manifold.co/secure-secrets-in-cypress-with-the-manifold-cli-6cd144b3be69
- [x] https://medium.com/@er_17361/our-investment-in-cypress-io-bc974155838d
- [x] https://www.sitefinitysteve.com/blog/code/2018/07/20/testing-functionality-with-cypress-io
- [x] https://www.youtube.com/watch?v=jijOIqtBGYg
- [x] https://medium.com/@nickdenardis/getting-cypress-js-to-interact-with-ckeditor-f46eec01132f
- [x] https://youtu.be/1PMxLTfh6lo?t=1
- [x] https://medium.com/coveryourads/slack-bot-testing-e7ba6f91a98e
- [x] https://css-tricks.com/an-intro-to-web-app-testing-with-cypress-io/
- [x] https://hashrocket.com/blog/posts/where-am-i-url-assertions-with-cypress
- [x] https://www.c-sharpcorner.com/article/getting-started-with-cypress-io/
- [x] https://blog.hasura.io/improving-our-cypress-test-automation-time-by-3x-e79f21313610
- [x] https://deliciousbrains.com/cypress-testing/
- [x] https://applitools.com/blog/cypress-vs-selenium-webdriver-which-is-better-for-you
- [x] https://realtalkjavascript.simplecast.fm/e03e32ef
- [x] https://blog.codepen.io/2018/10/16/195-cypress/
- [x] http://dev.topheman.com/cypress-io-advanced-setup/
- [x] https://www.gravitywell.co.uk/labs/using-cypress.io
- [x] https://palmer.net/blog/test-driven-form-development-with-cypress
- [x] https://medium.com/strava-engineering/stravas-new-end-to-end-testing-setup-18b541727555
- [x] https://youtu.be/K445DtQ5oHY?t=1434
- [x] https://medium.com/elements/building-an-optimised-e2e-flow-system-with-cypress-be119025c476
- [x] https://techcrunch.com/2018/11/07/circleci-launches-orbs-a-package-manager-for-software-delivery-automation/
- [x] https://www.youtube.com/watch?time_continue=63&v=J-xbNtKgXfY
- [x] https://devchat.tv/js-jabber/jsj-341-testing-in-javascript-with-gil-tayar/
- [x] https://snipcart.com/blog/frontend-testing-cypress
- [x] https://youtu.be/CkGQ0fFH3yE
- [x] https://www.youtube.com/watch?v=HMv365RRwtA
- [x] https://www.testingexcellence.com/capture-network-traffic-xhr-cypress/
- [x] https://www.youtube.com/watch?v=vBZaDqMmDH0
- [x] https://www.concrete.com.br/2019/01/24/cypress-com-cucumber-nos-testes-e2e/
- [x] https://imasters.com.br/front-end/testes-e2e-com-cypress-no-quasar-framework?fbclid=IwAR0v65Hhir3i1ITo6UWi4OK6ulBfPQ5ABBjdikmMPEBFtMX-3AHQjqhVyXg
- [x] https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0
- [x] https://levelup.gitconnected.com/what-ive-learnt-using-cypress-io-for-the-past-three-weeks-c1597999cd2f
- [x] https://blog.irontec.com/introduccion-automatizacion-tests-e2e-cypress-io/
- [x] https://medium.com/joolsoftware/unittesting-angular-components-with-cypress-202a38d9f81a
- [x] https://medium.freecodecamp.org/how-to-make-and-test-your-own-react-drag-and-drop-list-with-0-dependencies-6fb461603780
- [x] https://mariocardinal.wordpress.com/2019/03/05/configuring-cypress-in-ci-with-azure-devops-pipelines/
- [x] https://www.youtube.com/watch?v=hk4qtXgL12k
- [x] https://www.youtube.com/watch?v=8pcx0XitUCc
- [x] https://humble.dev/testing-an-email-workflow-from-end-to-end-with-cypress
- [x] https://youtu.be/BzRAYt7BHRw?t=1466
- [x] https://medium.com/@levz0r/how-to-poll-a-gmail-inbox-in-cypress-io-a4286cfdb888
- [x] https://medium.com/ngconf/angular-adding-cypress-ui-tests-to-your-devops-pipeline-c7613e67d37d
- [x] https://medium.freecodecamp.org/the-right-way-to-test-react-components-548a4736ab22
- [x] https://testdriven.io/blog/running-cypress-tests-in-parallel
- [x] http://engineering.solarmonkey.nl/blog/integrating-cypress-into-solar-monkey/
- [x] http://tom-jaeschke.blogspot.com/2019/02/i-saw-jesse-sanders-speak-at-angularmn.html
- [x] https://fosdem.org/2019/schedule/event/e2e_tests_cypress/
- [x] https://medium.com/@thiagogrespi/tend%C3%AAncias-para-a-%C3%A1rea-de-quality-assurance-em-2019-51c61b36e955
- [x] https://testdriven.io/blog/modern-frontend-testing-with-cypress/
- [x] https://stuartsandine.com/cypress-on-aws-lambda-part-1/
- [x] https://stuartsandine.com/cypress-on-aws-lambda-part-2/
- [x] https://www.youtube.com/watch?v=IADSsClWVtA&list=PLz8Iz-Fnk_eTpvd49Sa77NiF8Uqq5Iykx&index=2&t=0s
- [x] https://medium.com/@toastui/pragmatic-front-end-testing-strategies-3-969469349043
- [x] https://www.monterail.com/blog/end-to-end-testing-with-cypress
- [x] https://medium.com/executeautomation/visual-ui-testing-with-percy-io-cypress-graph-pdf-dom-ui-changes-can-now-be-automated-186aafb53517?sk=310a6345ec7d4245eaa808a9b100b642
- [x] https://valor-software.com/articles/cypress-parallelization-case-study-results.html
- [x] https://chipcullen.com/how-to-create-and-use-fixtures-in-cypress-tests/
- [x] https://youtu.be/EuwLdbCu3DE?t=1879
- [x] https://medium.com/@klmlfl/cypress-io-a-hands-on-overview-ad4d498944ee
- [x] https://www.youtube.com/watch?v=-tE0SQ0cR4c&amp=&feature=youtu.be
- [x] https://www.youtube.com/watch?v=tM2KRTE3F6Y
- [x] https://speakerdeck.com/stefanjudis/frontend-development-2018-whats-in-your-stack
- [x] https://speakerdeck.com/d3lm/changing-the-game-with-cypress
- [x] https://speakerdeck.com/mrcube42/next-level-e2e-testing-with-cypress-at-webdeveloper-stammtisch-saar-37
- [x] https://slides.com/simonhen/cypress
- [x] https://confluence.xpand-it.com/display/public/XRAY/Testing+using+Cypress+in+JavaScript

**Comment by Mrashes** [comment]
Hi jenifer-shehane,
Do you still need help with this?  it looks like all but on have been added.
-mrashes

**Comment by jennifer-shehane** [comment]
Hi, yes, I keep the list in the issue up to date with the current docs - so always an open issue. That last article hasn't been added to the docs.

**Comment by jennifer-shehane** [comment]
We may need to add a new section for 'Screencasts' to fit in:
- https://www.youtube.com/watch?v=w8liCoPsDIU
- https://www.grafikart.fr/formations/javascript-unit-test/cypress

**Comment by jennifer-shehane** [comment]
Hey @ValerieThoma, try and keep up with checking off the urls in the main comment after being added. Thanks!

**Comment by JLeneau** [comment]
https://davidjeddy.com/?p=714 
this link is 404 not found, fyi

**Comment by sunsheeppoplar** [comment]
https://applitools.com/blog/test-vuejs-cypress-io-applitools which is first on the checklist right now is the same blog as this: https://github.com/cypress-io/cypress-documentation/blob/develop/source/_data/blogs.yml#L212-L218

**Comment by sunsheeppoplar** [comment]
Second link  https://blog.you54f.com/2019/05/16/the-new-chromium-based-microsoft-edge-for-mac-has-been-leaked%e2%80%8a-%e2%80%8aand-it-works-with-cypress-and-now-you-can-test-it-too/ was added in this [PR](https://github.com/cypress-io/cypress-documentation/commit/c6d9ab65ec4760bec03ad44641ff7b6074d3c998)

@jennifer-shehane

**Comment by jennifer-shehane** [comment]
We don't actively maintain adding examples to the docs at this time. Closing since the initial list of examples has been added. 

Adding outside blogs, etc will be pending however @cypress-io/dx decides to handle these in the future.
