### ISSUE TITLE
[documentation] - Elaborate the configuring ESLint parts & link to eslint-plugin-cypress

### ISSUE THREAD

**Issue by revelt** [cypress-io/cypress-documentation#280]
Currently, documentation tells to use Mocha plugin: https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-an-ESLint-plugin-for-Cypress-or-a-list-of-globals

Yes, but that's only _assertions_ part.

Firstly, `cy.` in spec file will get flagged and it's not part of Mocha. We need to exclude it from being flagged up:

![error](https://user-images.githubusercontent.com/8344688/33274502-282b9e6e-d388-11e7-880a-1468bcc81d08.png)

Secondly, we should mention [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) which allegedly should solve `cv.` issue of being flagged up, but I can't get it working. That's a separate issue, but this documentation should link to `eslint-plugin-cypress` nonetheless.

Thirdly, documentation should share a complete ESLint setup config file with all the trimmings in one place (both Mocha, Sinon, Cypress and whatnot bits). Aforementioned one-liner is too little — majority of users will need to set up ESLint.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress-documentation/pull/281
