### ISSUE TITLE
Unclear example of Cypress.log

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress-documentation#2800]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

In the example usage of Cypress.log https://docs.cypress.io/api/cypress-api/cypress-log.html#Examples
there is a line:
```js
const log = Cypress.log({
...
```
It's not explained why is Cypress.log used this way.
Why is it not used this way?
```js
Cypress.log({
...
```
Please provide some explanation.

**Comment by jennifer-shehane** [comment]
Yeah, there's not any reason for this. Persisted from some copy/pasta.
