### ISSUE TITLE
Passing an array for testFiles in cli as documented does not work

### ISSUE THREAD

**Issue by jerryhaolin** [cypress-io/cypress-documentation#2801]
### Current behavior:
- Passing an array for testFiles and ignoreTestFiles in cli is parsed as a string instead of an array in the cypress runner. This causes the argument to not work.

Command used taken directly from documentation : 
https://docs.cypress.io/guides/references/configuration.html#Command-Line
`cypress open --config watchForFileChanges=false,testFiles=["**/*.js","**/*.coffee"]`

screenshot from Configuration:
<img width="229" alt="Screen Shot 2020-05-09 at 6 34 07 PM" src="https://user-images.githubusercontent.com/44203435/81486590-b23bde00-9223-11ea-9892-e038cfc7a054.png">

### Desired behavior:
testFiles should be parsed as an array. For example, if i was to set the testFiles in the cypress environment file, it would show up as an array in the configurations as shown below
![Screen Shot 2020-05-09 at 7 33 22 PM](https://user-images.githubusercontent.com/44203435/81487529-f6cb7780-922b-11ea-9203-92ca073b8cbd.png)

### Versions

Tried on Cypress version 4.2.0 and 4.5.0

**Comment by jerryhaolin** [comment]
Thank you so much for help !! Not pretty but it works 😄

**Comment by Nervniyak** [comment]
JSON solution https://github.com/cypress-io/cypress-documentation/pull/2802 doesn't seem to work in 2021 anymore:

![image](https://user-images.githubusercontent.com/34353798/135447795-8649c0f7-c7bb-4687-bc22-da1d774c17ff.png)
