### ISSUE TITLE
GitHub Actions guide?

### ISSUE THREAD

**Issue by dandv** [cypress-io/cypress-documentation#2859]
## I'm submitting a question / documentation request

Hi, I'm new to Cypress, loving it so far for running tests locally!

I'm reading the [CI guide](https://docs.cypress.io/guides/guides/continuous-integration.html) and noticed GitHub Actions isn't mentioned. Seems like a pretty popular CI provider, but also newer than others, so maybe no docs yet? Or does it simply fall under the [Advanced setup](https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup) section?

**Comment by jennifer-shehane** [comment]
Yeah, I think initially it was beta released, and then it being more stable crept up on us. This probably should be documented. cc @bahmutov

**Comment by dandv** [comment]
For those who land here from a search,

* https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/
* https://github.com/cypress-io/github-action

**Comment by amirrustam** [comment]
We now have a guide for GitHub Actions: http://on.cypress.io/github-actions
