### ISSUE TITLE
Link 'integrations' issue into Roadmap

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#287]
@jennifer-shehane commented on [Wed Nov 29 2017](https://github.com/cypress-io/cypress.io/issues/158)

https://github.com/cypress-io/cypress/issues/981

**Comment by brian-mann** [comment]
Isn't this just like.... a single line on the roadmap? Like literally, one line. ;-P

**Comment by brian-mann** [comment]
Now that I look at the Dashboard roadmap I can see this is actually already on here as an existing issue...

https://github.com/cypress-io/cypress/issues/578

![screen shot 2017-11-29 at 12 25 55 pm](https://user-images.githubusercontent.com/1268976/33389319-7a0901c6-d500-11e7-944a-f087ab0348ce.png)

**Comment by jennifer-shehane** [comment]
Yeah, but it's linking to an older issue, not the proposal

**Comment by lanceweatherby** [comment]
Updated road map. https://github.com/cypress-io/cypress-documentation/pull/303
