### ISSUE TITLE
Document logging in with identity providers (Firebase Auth, Auth0, Okta)

### ISSUE THREAD

**Issue by dandv** [cypress-io/cypress-documentation#2872]
## I'm submitting a recipe documentation request

This request is similar to #2859. I was trying to test pages protected by login via Auth0. Couldn't find anything at https://docs.cypress.io/examples/examples/recipes.html#Logging-In, and there seem to be [no plugins](https://docs.cypress.io/plugins/#authentication) for logging in with Firebase Auth, Okta, AWS Cognito, or Auth0. These are widely used identity providers. Am I missing something, perhaps a login plugin named differently that supports these flows?

**Comment by sandrinodimattia** [comment]
@dandv this guide should help testing Auth0 for all types of applications (regular web applications and SPA): https://sandrino.dev/blog/writing-cypress-e2e-tests-with-auth0

**Comment by amirrustam** [comment]
Check out the new "Testing Strategies" section within the docs. We're currently covering: Okta, Auth0, Cognito, and Google
