### ISSUE TITLE
Add Dashboard Overview video to docs

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#2878]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Need to add the [Cypress Dashboard Overview video](https://www.youtube.com/watch?v=ezp60FUnjGg) to the docs, @amirrustam any suggestions on the best place for this?

**Comment by amirrustam** [comment]
This update is getting deployed. Closing.
