### ISSUE TITLE
Document Cypress.platform and Cypress.arch constants

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#288]
For https://github.com/cypress-io/cypress/pull/986

(also link BDD assertions to Chai docs) https://docs.cypress.io/guides/references/assertions.html#BDD-Assertions

**Comment by jennifer-shehane** [comment]
I would assume these will go as new pages in the Cypress API section as `arch` and `platform`? 
<img width="267" alt="screen shot 2017-12-01 at 9 22 15 am" src="https://user-images.githubusercontent.com/1271364/33486750-36f58862-d679-11e7-92da-47d539755034.png">

**Comment by jennifer-shehane** [comment]
Also, I'm realizing I have no earthly idea what `arch` means or what it would return.

**Comment by bahmutov** [comment]
Yes, I will need them here in Cypress API - and I just noticed that we do not document `Cypress.version` there :( 

See links and explanations for these in https://github.com/cypress-io/cypress/blob/8e21f8752620e447f01224bc5fad0ca4ffe02588/cli/index.d.ts#L96
