### ISSUE TITLE
Experiments Page [Typo]

### ISSUE THREAD

**Issue by williebsweet** [cypress-io/cypress-documentation#2893]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of change - Typo

There is a typo on the **Experiments** page (source/guides/references/experiments.md). Under Shadow DOM (H1), the last sentence of the first paragraph reads, "You can enable _component testing_ by setting the experimentalShadowDomSupport configuration to true."

This sentence should read, "You can enable `shadow DOM` by setting the experimentalShadowDomSupport configuration to true."

**Comment by jennifer-shehane** [comment]
derp

**Comment by bahmutov** [comment]
You found an Easter egg - every experimental flag also turns on component testing
