### ISSUE TITLE
Security vulnerability: ejs 2.3.4

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#290]
`npm ls ejs`

```
└─┬ hexo-generator-seo-friendly-sitemap@0.0.21
  └── ejs@2.3.4 
```

**Comment by brian-mann** [comment]
There are no site vulnerabilities in the docs because its static. Impossible for there to be problems. Just ignore these or turn them off. There is no webserver.

**Comment by jennifer-shehane** [comment]
Did you turn them off? Cause it's gone

**Comment by brian-mann** [comment]
I did not.

**Comment by jennifer-shehane** [comment]
It doesn't appear that you can turn these off per repository atm.
