### ISSUE TITLE
Document better how to restore synthetic clock

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2910]
Really hard to find https://docs.cypress.io/api/commands/tick.html#Yields

- clock page
- stubs and clocks page

```js
it('restores', () => {
  cy.clock(+ new Date())
  cy.visit('http://localhost:3000/sudoku')
  // make sure the application has rendered
  // and the synthetic clock started working
  cy.get('.game__cell--filled').should('have.length', 45)

  cy.tick(600 * 1000) // 10 minutes
  cy.contains('.status__time', '10:00')

  // resume the clock
  cy.tick().then(clock => {
    clock.restore()
  })
  // the clock is restored to original value
  // thus the timer will start measuring again
  // from the original date passed to "cy.clock"
  cy.contains('.status__time', '00:03')
})
```

People cannot find it: https://twitter.com/huchenme/status/1275225026531225600

Related https://github.com/cypress-io/cypress-example-kitchensink/issues/429

**Comment by huchenme** [comment]
Thanks for this. Can I suggest to have a `cy.restoreClock()` or `cy.clockRestore()` with implementation of below?

```js
cy.tick().then(clock => {
   clock.restore();
})
```

**Comment by bahmutov** [comment]
Shorthand
```
cy.tick().invoke('restore')
```

But still a dedicated command would be superior

**Comment by huchenme** [comment]
For some reason the trick [does not work for me](https://dashboard.cypress.io/projects/wrmpdh/runs/40/failures/ce4c9cc9-9566-4738-851d-c5116e5c1c3b?utm_source=github), I have to call `.invoke('restore')` on last `tick()` to make it work: https://github.com/huchenme/hacker-tab-extension/pull/47/commits/13bef19e828b7a49c75f5e61c89c3830ab8d50d1
