### ISSUE TITLE
Borken link in server page

### ISSUE THREAD

**Issue by konekoya** [cypress-io/cypress-documentation#2970]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
In this page: https://docs.cypress.io/api/commands/server.html#No-Args
"pass through to the server. link is broken

Could you help put the correct link back?

**Comment by jennifer-shehane** [comment]
Yah this section was renamed recently. Should link to https://docs.cypress.io/guides/guides/network-requests.html#Use-Server-Responses

Opened PR here: https://github.com/cypress-io/cypress-documentation/pull/2972
