### ISSUE TITLE
Search function is not working in the doc

### ISSUE THREAD

**Issue by uLucasFraga** [cypress-io/cypress-documentation#3029]
## I'm submitting a...

```
[ ] Bug report
[ x ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

When we try to find the blog for: "**Lucas Fraga**" and press the **search** button, practically nothing happens and it doesn't seem to work.

_Example_:
![search](https://user-images.githubusercontent.com/23031781/88804282-0f409380-d184-11ea-91db-9ba412de7049.png)

**Comment by bencodezen** [comment]
Hi @uLucasFraga! The reason nothing is happening is because you are already on the page that the search item is linking to. If you search for Lucas in the browser search, you'll find that the content is further down the page. 

Hope this helps!
