### ISSUE TITLE
Changing screen size docs are "wrong"

### ISSUE THREAD

**Issue by joshribakoff** [cypress-io/cypress-documentation#3034]
### Current behavior:

https://docs.cypress.io/api/plugins/browser-launch-api.html#Set-screen-size-when-running-headless-Chrome has no effect on screenshots generated when running `cypress run`

### Desired behavior:

Docs should be correct for the environment Cypress actually uses by default. It would also be helpful if it specified in which file this snippet has to go (`plugins/index.js`). I'm not sure if the current docs are just out of date? for example:

In `plugins/index.js` place the following:

```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'electron' && browser.isHeadless) {
      launchOptions.preferences.width = 2493;
      launchOptions.preferences.height = 1309;
      return launchOptions;
    }
  });
};
```

It also required to patch the package & override the `xvfb` options in addition to this. Ideally the documentation would have the complete info in one place. At the very least, it can recommend the correct `browser.name` and make it clear how to override the launch preferences when running on mac/linux & getting electron as the default, which appears to be the case

### Test code to reproduce
```js
it('empty test', () => {
  cy.visit('http://howbigismybrowser.com/');
  cy.wait(1000);
  cy.screenshot();
});
```

cypress.json
```json
{
  "viewportWidth": 2493,
  "viewportHeight": 1309
}
```

plugins/index.js
```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name === 'chrome' && browser.isHeadless) {
      launchOptions.args.push('--window-size=1400,1200')

      return launchOptions
    }
  })
}
```

**Comment by jennifer-shehane** [comment]
>It also required to patch the package & override the xvfb options in addition to this.

@joshribakoff Can you explain what you mean by this? I'm not seeing this as being necessary. Running on Mac - the screenshot and video both reflect the sizes passed through the plugins file. 

I added the options for Electron and Firefox and improved the doc in general here: https://github.com/cypress-io/cypress-documentation/pull/3035 Feedback is welcome.

**Comment by joshribakoff** [comment]
@jennifer-shehane What I mean is you all hard code Cypress to detect if there is no display & launch `xvfb` with hard code dimensions (1280px wide if I recall). Most modern web apps need to support larger viewport sizes, like 1920 or even 4k. It was therefore necessary to use the `patch-package` for us to consume Cypress in a way where the screenshots have parity with our end users. We had to do 3 things

- set the viewport
- override the launch sizes (had to reverse engineer the wrong docs)
- patch xvfb (again had to reverse engineer this, and no configs are surfaced, requiring a patch, not obvious)
