### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by prazdevs** [cypress-io/cypress-documentation#3037]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I was thinking about translating the documentation in French since I'm native French. I'm starting to work on it, if this is fine?
It'd be my first open source contribution.

**Comment by bencodezen** [comment]
Hi @prazdevs! At the moment we are in the midst of some updates to the docs and wouldn't want to waste your efforts in translating just yet. Can we reach back out when we're ready for help with translations?

**Comment by prazdevs** [comment]
Sure thing!
