### ISSUE TITLE
Always display scrollbar in left nav

### ISSUE THREAD

**Issue by joshribakoff** [cypress-io/cypress-documentation#3045]
## I'm submitting a...

```
[ x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Can't scroll the nav

![Screen Shot 2020-07-31 at 10 42 33 AM](https://user-images.githubusercontent.com/4021306/89062084-accdcb80-d31a-11ea-814e-4f843ca4048b.png)

My screen is a 4k monitor, and literally I cannot read the docs because all of the items do not fit on my screen, and I cannot scroll. Chrome 84 on mac.

**Comment by jennifer-shehane** [comment]
You *should* be able to scroll the lefthand nav independently from the content - when your mouse is hovered over the lefthand navigation - using a scroll-wheel, touchpad scroll, or keyboard navigation. 

Not really able to reproduce this on my mac 😞 

![](http://g.recordit.co/CYTSf1cg7w.gif)

**Comment by joshribakoff** [comment]
I don’t use any of those devices I use a Wacom tablet because of my disability. As a user I determined (maybe incorrectly) that I cannot scroll because there is no scroll bar to grab. I also did not try clicking and using arrow keys because there was no UI element to indicate that was possible, I’ve been using computers for 25+ years and I couldn’t figure it out (maybe with a mouse or track pad it’s more intuitive)

**Comment by joshribakoff** [comment]
FYI I did confirm clicking into that DOM element explicitly to focus it does it work, however it does not show it is focused or not, and there is no scroll bar, I would say its not accessible, but feel free to close this if you disagree. PS > here's an example of a docs page with a scrollbar on the sidebar: https://redux-observable.js.org/ There's also 3rd party libs to render scrollbars if you're going to disable the native one, like https://github.com/Grsmto/simplebar

**Comment by jennifer-shehane** [comment]
Yeah, I agree we should display the scrollbar. I'm not sure why it's hidden by default really.
