### ISSUE TITLE
Update section on 'Debugging flake' to recommend they try 'Test Retries' and add 'Analytics' blog post

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#3068]
https://docs.cypress.io/guides/guides/debugging.html#Debugging-flake

Update section to include link to Test Retries guide and Cypress Dashboard Analytics blog post.

https://cypress.io/blog/2020/08/11/keep-your-test-suite-in-tip-top-shape-with-cypress-test-analytics/

**Comment by jennifer-shehane** [comment]
The test retries doc won't be released until after 5.0.

**Comment by amirrustam** [comment]
All of this is getting refactored.
