### ISSUE TITLE
Add FAQ for infinite scrolling apps with link to RWA

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#3070]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

We get support questions related to apps with infinite scroll/lazy load data. 

Example request:

> Hi, I have a page that has data loading as we scroll the page. I want it to keep scrolling until the desired data is found. Help with this would be appreciated! Thanks.

We have pagination tests in the RWA for the infinite scroll list of transactions - https://github.com/cypress-io/cypress-realworld-app/blob/develop/cypress/tests/ui/transaction-feeds.spec.ts#L160

We should add an FAQ to "Using Cypress" that addresses this question and points to the RWA

**Comment by amirrustam** [comment]
We're going to push for limiting the growth of a General FAQ page in favor of being able to search for the content in a contextual place.
