### ISSUE TITLE
Configuration page references to supportFile and supportFolder are inconsistent

### ISSUE THREAD

**Issue by cjcrandall** [cypress-io/cypress-documentation#3180]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The [Folders/Files section](https://docs.cypress.io/guides/references/configuration.html#Folders-Files) includes an entry for `supportFile`, but the [Node version section](https://docs.cypress.io/guides/references/configuration.html#Node-version) references `supportFolder`.

From search results in the Cypress code, it looks like both configuration options do actually exist, so I think that just means `supportFolder` needs to be added to the table that currently only includes `supportFile`.

**Comment by jennifer-shehane** [comment]
The `supportFolder` option was removed from Cypress a long time ago, so any mention of its current use should be removed. https://docs.cypress.io/guides/references/error-messages.html#Support-file-missing-or-invalid
