### ISSUE TITLE
Document type-safe fixtures / factory functions

### ISSUE THREAD

**Issue by dgreene1** [cypress-io/cypress-documentation#3194]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I really love what Cypress provides for fixtures, however they're not always the best approach (especially if the development team is concerned about type safety or bloat). Since `cy.route` allows developers to pass in an object as opposed to a fixture name, I think it would be extremely valuable for the documentation to put a strong emphasis on alternatives to fixture files.

For your convenience, I have detailed the problems with the fixture approach and I also recommend alternatives in this article: https://dev.to/dgreene1/don-t-use-fixtures-in-cypress-and-unit-tests-use-factories-5cnh

## Expected Outcome

I would updated the documentation for fixtures and cy.route to emphasize that you can utilize type-safe objects or factory functions instead of not type-safe fixture files.

**Comment by jennifer-shehane** [comment]
Yah I would agree that fixtures don't work in all situations, especially when your tests grow substantially larger. And we should probably think about documenting some more flexible solutions like you've outlined.
