### ISSUE TITLE
Docs: Improve 'Debugging'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#32]
@brian-mann commented on [Tue Jul 04 2017](https://github.com/cypress-io/cypress-monorepo/issues/259)

**Comment by saschwarz** [comment]
It would be very helpful if you could add to this section: https://docs.cypress.io/guides/guides/debugging.html#Using on using `debug()`. Specifically how do I access the current subject in the console and test assertions against it?

**Comment by richdouglasevans** [comment]
Legit suggestion there @saschwarz : I've opened a PR that hopefully addresses your suggestion.

**Comment by richdouglasevans** [comment]
@jennifer-shehane What else can be done to improve the `Debugging` guide? I was surfing backwards through the open tickets looking at the oldest ones and thus happened on this one.

If you can suggest improvements then I'll crack 'em out and we can get this ticket closed ✅
