### ISSUE TITLE
Erroneous ENV variable naming for CircleCI

### ISSUE THREAD

**Issue by svensson-david** [cypress-io/cypress-documentation#3205]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

It seems the name of the environment variable containing the current build number in CircleCI is erroneous in the parallelization docs.

File: source/guides/guides/parallelization.md
Line: 248

From what I can tell the correct variable name is `CIRCLE_BUILD_NUM`

Thanks!

**Comment by jennifer-shehane** [comment]
Yah, I do see it should be NUM instead of NUMBER
