### ISSUE TITLE
Introduction pages confuse the left-side navigation menu

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#3208]
Really funny bug: because there are two pages called `introduction.html` (in dashboard and in component testing guides), when you click on one, both are highlighted in the left navigation menu

- open https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell
- click "Component Testing" to expand it
- click "Introduction"

See two Introduction pages shown

See video below

![introduction2](https://user-images.githubusercontent.com/2212006/94860237-c4512f80-0403-11eb-9091-62b1be7622c9.gif)

**Comment by KirankumarAmbati** [comment]
@bahmutov I am able to replicate this bug. Please can you let me know if it's okay if we modify the link to **/component-testing/introduction-to-component-testing.html** from **/component-testing/introduction.html** and update its references ? If yes, I can go ahead, make the change and raise a PR. Please let me know. Thanks!

**Comment by jennifer-shehane** [comment]
You need to pick a unique name. We already have an Introduction page and I doubt this is worth spending the time addressing.

**Comment by KirankumarAmbati** [comment]
@jennifer-shehane Please can you verify my comment above and tell me if that sounds good. Thanks!

**Comment by jennifer-shehane** [comment]
If we change the name of the file itself to `introduction.html` then there may be conflicts with any other files named `introduction.html`. We use these filenames for generated shortlinks like https://on.cypress.io/introduction.

**Comment by KirankumarAmbati** [comment]
We can rename it to **introduction-to-component-testing.html**
