### ISSUE TITLE
Please document is url in cy.route() case-sensitive?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [cypress-io/cypress-documentation#3237]
### Current behavior
On page https://docs.cypress.io/api/commands/route.html#Arguments 
in description 
url (String, Glob, RegExp) 
for string and glob it will be good to specify, are they case-sensitive and, if yes, is it possible to make them  case-insensitive.

I understand, that in  RegExp it can be done.

**Comment by flotwig** [comment]
`cy.route()` was removed in Cypress 12, closing this issue.
