### ISSUE TITLE
Clarify that route Without-Stubbing can be used to reset after stubbing

### ISSUE THREAD

**Issue by MNF** [cypress-io/cypress-documentation#3249]
## I'm submitting a...
[ ] Content update Suggestions

## Type of bug / changes

On page 
https://docs.cypress.io/api/commands/route.html#Without-Stubbing

It will be good to explain, when call route without stubbing will be useful.
	1. For spying using alias.
	Example https://github.com/cypress-io/cypress-example-recipes/blob/c0e2883b7bc13d807c36ba65c7bc1751dc413f33/examples/server-communication__xhr-assertions/cypress/integration/spec.js#L20
	2. For reset after stubbing, e.g.
	cy.route('POST', '/posts',’mocked response’);
	cy.get('#load').click();
	cy.route('POST', '/posts');// reset to call real service
	cy.get('#load').click();
      3. Any other use cases?
	
In particular, I was looking for the option to reset the route after stubbing and initially didn’t find it.

Also I didn’t find relevant example in the link [Check out our example recipe using cy.route() to POST for login in HTML web forms](https://docs.cypress.io/examples/examples/recipes.html#Logging-In).
I’ve tried [HTML Web Forms](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/logging-in__html-web-forms) | Log in with a basic HTML form
And the   tests in [cypress/integration/logging-in-html-web-form-spec.js](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__html-web-forms/cypress/integration/logging-in-html-web-form-spec.js)  do not have cy.route example

**Comment by flotwig** [comment]
`cy.route()` was removed in Cypress 12, closing this issue.
