### ISSUE TITLE
Revise Test Retries guide to highlight new Flaky Test Management features in the Dashboard

### ISSUE THREAD

**Issue by trydionel** [cypress-io/cypress-documentation#3264]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The "Dashboard" section of the Test Retries guide is outdated.

<img width="1440" alt="Screen Shot 2020-10-20 at 9 47 46 AM" src="https://user-images.githubusercontent.com/104908/96595125-58067500-12b9-11eb-8031-d9fcbaab6a81.png">

**Comment by CypressCecelia** [comment]
Add screenshots highlighting Test Retries tab with Flaky tests filtered, show Attempt artifacts, Attempt errors, and Flake Rate chart. Also link to Flake Detection and Flake Alerting in the Flaky Test Management guide.

https://docs.cypress.io/guides/dashboard/flaky-test-management.html#Flake-Detection
