### ISSUE TITLE
Typo in docs on "Introduction to Cypress" page 

### ISSUE THREAD

**Issue by harlik** [cypress-io/cypress-documentation#3265]
### Current behavior

In https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Some-commands-cannot-be-chained section it's said "Some commands cannot be chained:"

Although all the examples after it definitely **can** be chained.
### Desired behavior

Replace "Some commands cannot be chained:" with "Some commands can be chained:"

**Comment by harlik** [comment]
Ok. Thanks )

**Comment by jennifer-shehane** [comment]
This is meant to read as a partial sentence for the sections below. 

- Some commands cannot be chained...from cy only, meaning they do not operate on a subject: cy.clearCookies().
- Some commands cannot be chained...from commands yielding particular kinds of subjects (like DOM elements): .type().
- Some commands cannot be chained...from both cy or from a subject-yielding command: cy.contains().

This could definitely be clearer

**Comment by jennifer-shehane** [comment]
Ok yah, this should also be backwards saying *can*
