### ISSUE TITLE
cy.wrap...as cy.get alias stopped to work

### ISSUE THREAD

**Issue by vsix27** [cypress-io/cypress-documentation#3282]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```
[using latest version of cypress - 5.4.0]

## Type of bug / changes
![image](https://user-images.githubusercontent.com/10351245/97038651-20a5fb80-1539-11eb-9162-647ed13cfe28.png)

cypress is unable to resolve an alias (despite the fact that it shows that alias is created - see pic): 

```
  const nn = [number1, number2];
  // read it later as cy.get("@numbers") or this.numbers  - does not work ???
  cy.wrap(nn).as("numbers");
  cy.get("@numbers").then((xx) => {
    cy.log(`..............${xx}`);
  });

  //cy.wait("@numbers").then((xx) => {cy.log(`..............${xx}`);});
```
If I uncomment cy.wait  - also has interesting message: 
![image](https://user-images.githubusercontent.com/10351245/97038974-a5911500-1539-11eb-86c6-c5d5ca48f2a5.png)

**Comment by jennifer-shehane** [comment]
This repo is only for issues relating to Cypress documentation. If you want to open an issue on our main project, you can open it [here](https://github.com/cypress-io/cypress/issues/new). This issue will be closed in this repository.

Also, check out our [community chat](https://gitter.im/cypress-io/cypress), it can be helpful for debugging issues or just answering questions you have about Cypress.
