### ISSUE TITLE
Cypress `find()` unsupported parameter `options`, conflict with online documentation.

### ISSUE THREAD

**Issue by jeff00docusign** [cypress-io/cypress-documentation#3286]
## I'm submitting a...

```
[X] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

https://docs.cypress.io/api/commands/find.html#Syntax

Document for `find()` indicates that it accepts `options`, **which would be helpful** but it does not.

**Comment by jennifer-shehane** [comment]
`.find()` does support options as defined here: https://docs.cypress.io/api/commands/find.html#Arguments

For example, all of these options work fine. 

```js
it('test', () => {
  cy.visit('https://example.cypress.io')
  cy.get('div').find('div', {log: false}) // doesn't log
  cy.get('div').find('foo', {timeout: 10000}) // changes time it waits
})
```
