### ISSUE TITLE
Add to plug-in list popularity indicator.

### ISSUE THREAD

**Issue by MNF** [cypress-io/cypress-documentation#3295]
## I'm submitting a...

```
[ ] Content update suggestion  on https://docs.cypress.io/plugins/index.html
```

## Type of bug / changes

As the number of listed plug-ins is big, it will be useful to see some indicator of popularity.
It can be number of stars on GitHub, number of downloads on npm or some combined indicator created by your team and described on the page.  E.g.  I maybe don’t want to open any  plug-in that has less than 3* on GitHub and such indicator will help me to understand does plug-in mature enough to consider for use

**Comment by amirrustam** [comment]
Great idea and feedback. We're in the process of refactoring that page, so this will be considered. Thank you.
