### ISSUE TITLE
Add version info when feature/api came into existence, and upon new/breaking changes to existing features

### ISSUE THREAD

**Issue by govindrai** [cypress-io/cypress-documentation#3304]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Cypress retries only became available in 5.0.0. However the cypress docs don't mention that except in the changelog or some blog articles. Instead it would be very helpful to annotate documentation to include cypress version numbers when a feature became available and also breaking changes that may have been introduced in a later version. I spent a good three hours trying to get test retries to work on 4.5.0--the config didn't complain either. 

This is an example of how Node.js does it:
<img width="488" alt="Change log example" src="https://user-images.githubusercontent.com/13859249/98004925-bb120480-1dad-11eb-90af-997ccbe30b95.png">

**Comment by jennifer-shehane** [comment]
Our docs do have History tables for many of the pages, especially our API documentation. https://docs.cypress.io/api/commands/request.html#History

<img width="892" alt="Screen Shot 2020-11-04 at 3 17 26 PM" src="https://user-images.githubusercontent.com/1271364/98089470-2bee1500-1eb1-11eb-9cf2-f60a61282803.png">


But our docs are not fully versioned and will always reflect the reality of the most recent version of Cypress. Having versioned docs would be ideal. 

What doc were you on where you were stuck? Test Retries? Cause we could add the History table to the bottom of that indicating when it was added. https://docs.cypress.io/guides/guides/test-retries.html#Introduction

**Comment by govindrai** [comment]
Adding the history table to the bottom of test retries would be good, but then there are also other similar pages (i..e parallelism) that wouldn't have them. It might cause inconsistency and added work to maintain, so I'm okay closing this. You can make a better judgement call here, on what you'd want to do. 

The ideal, correct solution is versioned docs--I understand it might be too late for that--but if you ever decided to heavily revamp the docs, please keep versioned docs in mind!

**Comment by jennifer-shehane** [comment]
I agree. I'd prefer versioned docs as well. We're in the middle of migrating our docs to a whole new system, so maybe it will be considered there.
