### ISSUE TITLE
Proposal: Add Cypress Communities Section to Docs 

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#3307]
## I'm submitting a...

```
[ ] Bug report
[ x ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Proposing to add a section to the docs that lists all of the known Cypress Online Communities, including:

**Non-Ambassador Groups:**

- [Cypress Test Automation Group](https://www.linkedin.com/groups/12276472/) (LinkedIn)
- [Cypress Test Automation](https://www.linkedin.com/groups/10510113/) (LinkedIn)
- [Cypress Test Automation](https://www.facebook.com/groups/cypresstestautomation/) (Facebook)

**Ambassador-Affiliated Groups**

- [Cypress.io UK Community](https://www.meetup.com/Cypress-io-UK-Community/) (Meetup.com)
- [Cypress South East Europe](https://www.meetup.com/Cypress-South-East-Europe/) (Meetup.com)
- [Cypress.io Thailand](https://www.facebook.com/groups/cypressiothailand/) (Facebook)

**Comment by CypressAlexander** [comment]
@magnolia-triplett do you want it to be a new page with link in header to it? If no, what page should it be added to?
