### ISSUE TITLE
Raw markdown rendered in site

### ISSUE THREAD

**Issue by slikts** [cypress-io/cypress-documentation#3334]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Content shows up as raw Markdown instead of rendered as HTML.

https://docs.cypress.io/guides/tooling/reporters.html#Custom-reporter

![image](https://user-images.githubusercontent.com/137872/99699632-d6159180-2a9a-11eb-8834-0dd2cc865b59.png)

**Comment by jennifer-shehane** [comment]
😞
