### ISSUE TITLE
All links to example recipes repo are broken.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#334]
For example, clicking on 'FizzBuzz' header goes to:
- https://github.com/cypress-io/cypress-example-recipes/blob/master/cypress/integration/unit_test_application_code_spec.js

But these recipes have been moved into their own folder structure, so this link should be here:
- https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/unit-testing__application-code/cypress/integration/unit_test_application_code_spec.js

**Comment by brian-mann** [comment]
This is not the case. You're clicking on an old link for a page which doesn't exist anymore - and the redirect rules weren't picking it up.
