### ISSUE TITLE
cy.intercept / cy.wait - Undocumented breaking changes in Cypress 6

### ISSUE THREAD

**Issue by shwarcu** [cypress-io/cypress-documentation#3397]
## I'm submitting a...

```
[X] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Documentation of cy.intercept and cy.wait doesn't mention that now in Cypress 6.X.X returned subject doesn't support form data.
Body is returned as plain string instead of an object as it was previously. Therefore testing such request is not possible in a way it was so far, I have to find workaround and refractor such tests.

Before changes we could test request in a simple manner:
```js
      cy.wait('@postRequest').then(postRequest => {
        const requestBody = postRequest.requestBody;
        expect(requestBody.get('field1')).to.equal(expectedField1Value);
        expect(requestBody.get('field2')).to.equal(expectedField2Value);
      });
```

This is how request body looks now in the subject 
<img width="1364" alt="Screenshot 2020-12-15 at 09 35 33" src="https://user-images.githubusercontent.com/58426925/102190983-0e9d6500-3eb9-11eb-9d04-00b8947e86c1.png">

**Comment by flotwig** [comment]
Currently cy.intercept only automatically parses JSON request and response bodies #9280 :

https://github.com/cypress-io/cypress/blob/74b8048f70fe0d105eac51bf63617b2b730a940b/packages/driver/src/cy/net-stubbing/events/utils.ts#L10-L20

It would make sense to make it automatically support `multipart/form-data` as well, maybe [`multiparty`][multiparty] could be added in the server to automatically parse multipart/form-data, but that would be a breaking change.

[multiparty]: https://github.com/pillarjs/multiparty

**Comment by emilyrohrbough** [comment]
We are on v12.7.0 at this point. Closing on stale.
