### ISSUE TITLE
Offer the opposite command

### ISSUE THREAD

**Issue by googol7** [cypress-io/cypress-documentation#3416]
For each command the opposiite command should also be listed in the documentation. For example: [contains](https://docs.cypress.io/api/commands/contains.html
):

`cy.contains("xyz")`

vs.

`cy.contains("xyz").should("not.exist")`

**Comment by bahmutov** [comment]
I am not sure I understand what is missing in the documentation? Would you like to add a bunch of negative assertion examples for every command?

**Comment by googol7** [comment]
Maybe it’s just a complete beginner's question what’s the best way to make negative assertions.

**Comment by bahmutov** [comment]
Gotcha. I don't think we have a document with best practice for negative assertions but here are more examples of assertions:
- https://on.cypress.io/assertions
- https://glebbahmutov.com/cypress-examples/6.2.0/commands/assertions.html
- https://docs.cypress.io/guides/references/migration-guide.html#Non-existent-element-assertions

**Comment by googol7** [comment]
I thought it would be nice to have a section "The opposite assertion" for every assertion for a quick convenient reference.
