### ISSUE TITLE
Was behavior of cy.state() changed?

### ISSUE THREAD

**Issue by Threnos** [cypress-io/cypress-documentation#3417]
## I'm submitting a...

```
[X] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )

Not actually sure if it is a bug or intended.
```

## Type of bug / changes

I used undocumented method cy.state() for a long time to check that specified api call did not happen after user actions. After updating to 6,1.0 the behavior of method changed, and I could not get a list of all xhr requests at any point of test. I made a bit of checking and found that cy.state() returns a list of requests just once, containing all that happened during before() hook.

Was that change intentional? If yes, than am I able to use something else to collect all xhr requests that happened on a page, just like it was before?
If not, then, please, tell me what additional information you need to post an actual bug report.

Here I put a console.log(cy.state('requests')) into beforeEach hook, and my spec has 5 tests. The results are what was collected during application page visit in before() hook. 
![image](https://user-images.githubusercontent.com/30055497/102499720-312fa980-4084-11eb-9beb-373f6c71c095.png)

**Comment by flotwig** [comment]
The behavior of `cy.state('requests')` shouldn't have changed in 6.1.0, is it possible that something else has changed in your tests?

Cypress tests using `cy.state('requests')` still passes: https://github.com/cypress-io/cypress/blob/61cd21eb4718d4167e8d9f521c44d36ab2673657/packages/driver/cypress/integration/commands/xhr_spec.js#L483-L485
