### ISSUE TITLE
Incorrect documentation regarding the location of tsconfig.json file

### ISSUE THREAD

**Issue by phao5814** [cypress-io/cypress-documentation#3438]
In the documentation [here](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json), it mentions the following:

> We recommend the following configuration in a tsconfig.json inside your cypress folder.

However, placing the `tsconfig.json` file in the `cypress` directory does not seem to work. This is also backed up by this [SO post](https://stackoverflow.com/q/64141729/7489488).

It appears the only valid location the `tsconfig.json` file can reside is in the root directory of the project. I believe the documentation should be amended to reflect this.

On a related sidenote, is there anyway to specify a custom location for the `tsconfig.json` file?

**Comment by kevinold** [comment]
@phao5814 Please provide a GitHub repo with the configuration you are using and details of why and what does not work for your situation.

 For working examples, please refer to the following projects: 

https://github.com/cypress-io/cypress-realworld-app
https://github.com/cypress-io/cypress-and-jest-typescript-example
