### ISSUE TITLE
Misleading documentation for `then` method

### ISSUE THREAD

**Issue by jugglinmike** [cypress-io/cypress-documentation#3446]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The signature of the `then` method makes it impossible to use with JavaScript language features such as `await` ([previously reported here](https://github.com/cypress-io/cypress/issues/1417)) and built-in APIs such as `Promise.all`, `Promise.race`, etc.

[The documentation currently states](https://docs.cypress.io/api/commands/then.html):

> `.then()` is modeled identically to the way Promises work in JavaScript.

The subsequent text substantiates this claim, but it does not include any caveats for the ways Cypress's objects are incompatible with the idiomatic "thenable" interface.

Improving the documentation would mitigate the issue somewhat. For instance, the documentation could have some explanation about how the `.then` method does *not* conform to the language's assumptions. Also, it could avoid leading with a generalization as strong as "identically."

(Changing the API to use a different method name would avoid subverting expectations about the interface, but that's clearly a much more drastic solution.)

**Comment by leesei** [comment]
+1 seeing the `.then()` API and documentation I was expecting Promise-compatibility and `await`-tability.
And it took me hours to figure out "cypress commands are not promises and you can't use async/await in Cypress tests".
https://github.com/NoriSte/cypress-wait-until/issues/158#issuecomment-648573944

Not being Promise-compatibile is not the issue, the issue is that the API and documentation suggest it is.

**Comment by SalahAdDin** [comment]
> +1 seeing the `.then()` API and documentation I was expecting Promise-compatibility and `await`-ability. And it took me hours to figure out "cypress commands are not promises and you can't use async/await in Cypress tests". [NoriSte/cypress-wait-until#158 (comment)](https://github.com/NoriSte/cypress-wait-until/issues/158#issuecomment-648573944)
> 
> Not being Promise-compatible is not the issue, the issue is that the API and documentation seems to hint it is.
> 
> Actually these two sections are conflicting. Now that Promise is part of standard JavaScript spec please keep it in that context. `then()`-able API is not Promise. https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Commands-Are-Promises https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Commands-Are-Not-Promises

It still says they are promises.

**Comment by jennifer-shehane** [comment]
This language has since been updated
