### ISSUE TITLE
Map over element has order (i, el), not (el, i)

### ISSUE THREAD

**Issue by fcole90** [cypress-io/cypress-documentation#3452]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

In https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Explicit-Subjects, there's an example which uses a map as follows:

```js
cy
  .get('p')
  .should(($p) => {
    // massage our subject from a DOM element
    // into an array of texts from all of the p's
    let texts = $p.map((el, i) => {
      return Cypress.$(el).text()
    })

    // jQuery map returns jQuery object
    // and .get() converts this to an array
    texts = texts.get()

    // array should have length of 3
    expect(texts).to.have.length(3)

    // with this specific content
    expect(texts).to.deep.eq([
      'Some text from first p',
      'More text from second p',
      'And even more text from third p'
    ])
  })
```

However it will fail, producing a list of empty strings. This is because the arguments in the `map` are inverted, (they are `(el, i)` but should be `(i, el)`) so it needs to be as follows:

```js
cy
  .get('p')
  .should(($p) => {
    // massage our subject from a DOM element
    // into an array of texts from all of the p's
    let texts = $p.map((i, el) => {
      return Cypress.$(el).text()
    })

    // jQuery map returns jQuery object
    // and .get() converts this to an array
    texts = texts.get()

    // array should have length of 3
    expect(texts).to.have.length(3)

    // with this specific content
    expect(texts).to.deep.eq([
      'Some text from first p',
      'More text from second p',
      'And even more text from third p'
    ])
  })
```

Map in jQuery: https://api.jquery.com/map/#map-callback

Cypress version: 6.2.0

**Comment by fcole90** [comment]
Short Fiddle example: https://jsfiddle.net/vud84zoe/9/

**Comment by jennifer-shehane** [comment]
Yeah, this was actually originally correct but then changed based of of the wrong map docs. Should have ran the code. https://github.com/cypress-io/cypress-documentation/pull/1570

Should match https://api.jquery.com/map/ signature.

**Comment by jennifer-shehane** [comment]
PR https://github.com/cypress-io/cypress-documentation/pull/3453
