### ISSUE TITLE
Copy/paste error in cy.intercept documentation

### ISSUE THREAD

**Issue by crfrolik** [cypress-io/cypress-documentation#3496]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

https://docs.cypress.io/guides/references/migration-guide.html#Match-against-url-and-path

The "After" code section still uses `cy.route`, but it should be using `cy.intercept`, right?

**Comment by jennifer-shehane** [comment]
I'm not seeing what you mean, could you provide a screenshot of the area that's incorrect?

**Comment by crfrolik** [comment]
Odd, I am not seeing it now either. I am going to close this.
