### ISSUE TITLE
Cypress studio page links to a non existing page

### ISSUE THREAD

**Issue by piyukore06** [cypress-io/cypress-documentation#3502]
## I'm submitting a...

```
[] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

[Cypress studio documentation page](https://docs.cypress.io/guides/core-concepts/cypress-studio.html) links to a [test](https://github.com/cypress-io/cypress-realworld-app/cypress/tests/demo/cypress-studio.spec.ts) in Cypress Real world app.

![image](https://user-images.githubusercontent.com/17766092/105165050-239f9080-5b16-11eb-95fb-ddc70f779d2d.png)

That links to a non-existing page. It seems like Cypress Real World App is not yet updated to Cypress 6.3.0

**Comment by jennifer-shehane** [comment]
@piyukore06 Thanks for opening this - checking with the RWA team to see what's up here.
