### ISSUE TITLE
Feature request: add cmd + k keyboard shortcut for search

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress-documentation#3522]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
[x] Feature request 🙊
```

## Type of bug / changes
In  [TailwindCSS](https://tailwindcss.com/) documentation, there’s this really cool feature for searching through docs. Wherever you are on page, you use the keyboard shortcut `cmd + K` (I assume it’s `ctrl + K` for windows), and your search pops right out. So you can just start typing for whatever you need.

It might be a really nice addition for Cypress docs as well.

**Comment by bahmutov** [comment]
I would support this, good feature to make documentation search faster and easier.

**Comment by filiphric** [comment]
released, thanks @bahmutov and @matthamil

**Comment by NsdHSO** [comment]
Hy @bahmutov  @filiphric I have this line of code for fancy search `cy.get('body').type('{meta}+k')` and it is never triggered, Please can you help?
