### ISSUE TITLE
Difference between --tag and --group

### ISSUE THREAD

**Issue by DamienCassou** [cypress-io/cypress-documentation#3537]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I don't understand the difference between `--tag` and `--group`:

- https://docs.cypress.io/guides/guides/command-line.html#cypress-run-group-lt-name-gt
    > Group recorded tests together under a single run.
- https://docs.cypress.io/guides/guides/command-line.html#cypress-run-tag-lt-tag-gt:
    > Add a tag or tags to the recorded run. This can be used to help identify separate run when displayed in the Dashboard.

I understand that grouping is used for parallelization but I'm not sure exactly how. I feel that there is something that could be clarified somewhere.

**Comment by jennifer-shehane** [comment]
@DamienCassou They're really mostly properties to set on the recorded run that will affect how they are displayed in the Dashboard. In a single `cypress run`, so a single url in the Dashboard you could have specs grouped however you want. There's some more explanation here: https://docs.cypress.io/guides/guides/parallelization.html#Grouping-test-runs

For tags, its just adding a searchable tag to the entire run, so you could more easily search for that run in the Dashboard in the future. Maybe you want to find your 'production' runs or 'nightly' runs or want to tag each run by the commiters name and search by that. Just makes it convenient to find later.

<img width="192" alt="Screen Shot 2021-02-05 at 4 37 08 PM" src="https://user-images.githubusercontent.com/1271364/107019739-6af17680-67d0-11eb-823d-3f76218d350e.png">

**Comment by DamienCassou** [comment]
Thank you for your explanation @jennifer-shehane. I feel stupid but I still don't really understand. It seems like there is some kind of overlap between these 2 concepts and I'm not sure when to use which.
