### ISSUE TITLE
Add course to courses page 

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#3555]
## I'm submitting a...

```
[ ] Bug report
[ x ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Add Marie Drake's [Intro to Cypress Course](https://www.ministryoftesting.com/dojo/courses/introduction-to-cypress) to Courses Page

**Comment by CypressAlexander** [comment]
@magnolia-triplett it's already on the [Courses](https://docs.cypress.io/examples/media/courses-media.html) page.
