### ISSUE TITLE
How to include existing translation maintained by the Brazilian community?

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [cypress-io/cypress-documentation#3558]
The Brazilian community is actively translating and keeping cypress-documentation updated to Brazilian Portuguese.
We found this issue (#3084) talking about the lack of support for translations and ended up creating the translation in its own repository (not a fork).
We want to know how we can make the PT-BR translation part of https://docs.cypress.io.

**Repository with translation:** https://github.com/pedrohyvo/cypress-docs-pt-br

@jennifer-shehane

**Comment by jennifer-shehane** [comment]
Very nice! Right now we've put a pause on offering translations of our docs until we can find a way to support everything we want to offer. cc @amirrustam

**Comment by amirrustam** [comment]
Translations are definitely something we want to do but need to do in a maintainable way. This is something the team will revisit. Thank you
