### ISSUE TITLE
footer shrunk in Firefox on windows

### ISSUE THREAD

**Issue by da-vaibhav** [cypress-io/cypress-documentation#363]
![screenshot-2018-1-9](https://user-images.githubusercontent.com/1468518/34728031-b3950842-f57e-11e7-8c53-c6b5105a043f.png)

**Comment by jennifer-shehane** [comment]
Good catch. Thanks for opening this :)

**Comment by jennifer-shehane** [comment]
@da-vaibhav Hey, can you see if this is fixed after refreshing? I was a little thrown off by your screen size in the screenshot looking a lot wider than where I was able to reproduce it at. Let me know if there are still issues.

**Comment by da-vaibhav** [comment]
@jennifer-shehane  I can still see it shrunken on FF windows but not on Mac FF. I am using normal size laptop. It's reproducible on 1280x768 too. I'll try fixing it and will let you know.

**Comment by jennifer-shehane** [comment]
Yeah, I couldn't recreate it in my windows virtual machine, who knows. If only I could test this in Cypress :upside_down_face: Thanks for fixing!
