### ISSUE TITLE
Bold text does not work in an 'alert'

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#3633]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Trying to bold text in an alert with asterisks does not bold the text. I think we want the font-weight to  be 600.

<img width="688" alt="Screen Shot 2021-03-03 at 10 53 04 AM" src="https://user-images.githubusercontent.com/1271364/109832798-b4d24e80-7c0e-11eb-8f6a-422673b72c46.png">

<img width="539" alt="Screen Shot 2021-03-03 at 10 52 57 AM" src="https://user-images.githubusercontent.com/1271364/109832843-c156a700-7c0e-11eb-9033-4607814d6049.png">

<img width="681" alt="Screen Shot 2021-03-03 at 10 54 49 AM" src="https://user-images.githubusercontent.com/1271364/109833015-e8ad7400-7c0e-11eb-863d-a65032874cf8.png">

**Comment by matthamil** [comment]
Thanks! #3648 should take care of this.
