### ISSUE TITLE
<alerts> with blank lines around them and <alerts> without have different text size.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#3635]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I don't think the spacing of the markdown should change the styles. If we can't get around this - then there should at least be a linter that enforces this.

<img width="845" alt="Screen Shot 2021-03-03 at 2 53 49 PM" src="https://user-images.githubusercontent.com/1271364/109863975-4a320a80-7c30-11eb-8c1e-b1ab8a2be1b3.png">

<img width="840" alt="Screen Shot 2021-03-03 at 2 53 09 PM" src="https://user-images.githubusercontent.com/1271364/109863948-41d9cf80-7c30-11eb-8d25-0108a18a0c3a.png">

**Comment by matthamil** [comment]
This is a limitation of nuxt-content, see [this docs page](https://content.nuxtjs.org/writing/#html).

I'm taking a look to see if theres anyway we can get a linter set up to warn about this behavior.
