### ISSUE TITLE
Update example for module-based test execution

### ISSUE THREAD

**Issue by Djspaceg** [cypress-io/cypress-documentation#3661]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The code example in the following page seems like it needs to be updated to reflect the current API.
https://docs.cypress.io/guides/guides/module-api.html#Handling-errors

The page shows the following:
```ts
if (result.failures) {
```

And instead it should show the following:
```ts
if (result.status === 'failed') {
```

The documentation in the component itself [reflects this already](https://github.com/cypress-io/cypress/pull/8604/commits/b993130e09bf1d1f91db8df063ff93c6913354c7#diff-1961c785b4523b36516a2cb55556dffe7c39b4dd4aa3e6cf19e413c7c76f4b25R298).

**Comment by jennifer-shehane** [comment]
This section is about Handling Errors - that means a state where the Cypress running errored and could not finish running, so exiting with some kind of error. NOT when the test runner has test failures.

**Comment by Djspaceg** [comment]
Thanks for commenting, @jennifer-shehane. This report is specifically about the documentation needing an update to reflect the current code. The actual code seems to work just fine; I was suggesting the example code in the documentation should be updated.
