### ISSUE TITLE
Highlighting syntax in docs-next very difficult to see

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress-documentation#3694]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

In the below image I want to copy paste the snippet. I highlighted it, but it's very difficult to tell what is actually highlighted.

![image](https://user-images.githubusercontent.com/19196536/111092465-e2f64d80-8581-11eb-89dd-f5b2ab62261d.png)

Ideally we should use a different, lighter color to make it clear what is highlighted.

**Comment by matthamil** [comment]
Ty for catching this. I changed it to look a bit more readable
![image](https://user-images.githubusercontent.com/11802078/112693959-829fbf80-8e4f-11eb-9f3f-3cb6e27bc394.png)
