### ISSUE TITLE
Husky error when using git GUI to commit

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#3697]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I can't use a git GUI to commit on this repo for the next docs. 

<img width="481" alt="Screen Shot 2021-03-15 at 9 45 20 AM" src="https://user-images.githubusercontent.com/1271364/111163531-8ee46c80-8573-11eb-80cf-190e3c1c32f4.png">

**Comment by jennifer-shehane** [comment]
Bumping because this is extremely annoying to my workflow. @cypress-io/dx

**Comment by amirrustam** [comment]
Prioritized: DX-52
