### ISSUE TITLE
404 after click on the link in documentation (Cross Browser Testing)

### ISSUE THREAD

**Issue by hermape7** [cypress-io/cypress-documentation#3735]
## I'm submitting a...

```
[x] Bug report
```

## Type of bug / changes

There is a 404 redirect after clicking to `Test Configuration` on this [page](https://docs.cypress.io/guides/guides/cross-browser-testing#Running-Specific-Tests-by-Browser) at the very bottom in the list "See Also"

<img width="990" alt="cypress doc 404" src="https://user-images.githubusercontent.com/13590260/112324889-826abd00-8cb3-11eb-93fa-27e14ea8d4c3.png">

**Comment by matthamil** [comment]
@hermape7 Does this link still 404 for you? It seems to work fine on my end.
