### ISSUE TITLE
Links in the changelog page are not displayed properly

### ISSUE THREAD

**Issue by PierrickG34** [cypress-io/cypress-documentation#3746]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
Hi, links in [cypress changelog](https://docs.cypress.io/guides/references/changelog) page are broken with some `{% xxx %}`, see this image for example : 
![image](https://user-images.githubusercontent.com/12444077/112819340-c9c2c600-9084-11eb-90cd-c60702e99815.png)

**Comment by matthamil** [comment]
Thank you for catching this!
