### ISSUE TITLE
Issue on Bitbucket Pipelines Page

### ISSUE THREAD

**Issue by GregLahaye** [cypress-io/cypress-documentation#3747]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

On both the Bitbucket Pipelines and AWS CodeBuild pages, it seems that the templates have not been built and are instead displaying raw.

![image](https://user-images.githubusercontent.com/16643647/112823962-83895900-90bc-11eb-9148-aa14a1a817d9.png)

https://docs.cypress.io/guides/continuous-integration/bitbucket-pipelines
https://docs.cypress.io/guides/continuous-integration/aws-codebuild

**Comment by GregLahaye** [comment]
Actually it seems like this is happening in other places, as seen on https://github.com/cypress-io/cypress-documentation/issues/3746

**Comment by GregLahaye** [comment]
You can see some more places this is happening: https://www.google.com.au/search?q=site%3Adocs.cypress.io+%7B%25

**Comment by matthamil** [comment]
Thanks for reporting this
