### ISSUE TITLE
Outdated OSS images

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress-documentation#3765]
## I'm submitting a request to update the images in the OSS Plan page and Requesting OSS Plan instructions

[ ] **Outdated Content:**
_1. OSS Plan page Dashboard image states there are 5 users/ Unlimited Tests_

<img width="688" alt="dashboard_oss_plan" src="https://user-images.githubusercontent.com/73494347/113147385-ba678800-91fe-11eb-9ce3-47f0a2ab79f1.png">

_2. Step 3 Requesting OSS Plan instructions image references legacy plans (Seed, Sprout, Tree, and Forest)_

<img width="740" alt="step3_requesting_oss_plan_for_an_org" src="https://user-images.githubusercontent.com/73494347/113147457-c9e6d100-91fe-11eb-905d-6043e703df46.png">

[ ] **Content Update:**
_1. OSS Plan includes 10 users/ 100k Tests per month_
_2. Refer to new plans (Free, Team, Business, Enterprise)_

**Comment by jennifer-shehane** [comment]
Can you link to the page where this first image is found in the docs? Thanks.

Second image in this section: https://docs.cypress.io/guides/dashboard/organizations#Requesting-OSS-plan-for-an-org

**Comment by shawnhelps** [comment]
Image Link: https://www.cypress.io/oss-plan/ 

When searching in Google for "Cypress OSS", I can find this link, but the page may have been deprecated and is just lingering on Google. 

If I type that url in, sometimes I get a 404 error, sometimes I am redirected. 

<img width="1792" alt="no404_oss-plan" src="https://user-images.githubusercontent.com/73494347/113156728-416d2e00-9208-11eb-8247-896e2caa4d57.png">
<img width="1792" alt="404_oss-plan" src="https://user-images.githubusercontent.com/73494347/113156725-40d49780-9208-11eb-931a-94d209a62fb8.png">
<img width="1792" alt="redirect_oss-plan" src="https://user-images.githubusercontent.com/73494347/113156732-4205c480-9208-11eb-9e26-e7733e39d85b.png">

**Comment by jennifer-shehane** [comment]
@shawnhelps Thanks! We'll take a look at it.

**Comment by shawnhelps** [comment]
@jennifer-shehane 
When impersonating a user, the UI also has the outdated information for tests and users. [Zendesk Ticket](https://cypressio.zendesk.com/agent/tickets/948) with internal notes
