### ISSUE TITLE
The "Migration guide" link destination in the 7.0.0 release notes is wrong (404)

### ISSUE THREAD

**Issue by slaweet** [cypress-io/cypress-documentation#3787]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
The "Migration guide" link destination in the 7.0.0 release notes is wrong:
![cypress-broken-link](https://user-images.githubusercontent.com/1254342/113667567-4707bf80-96b1-11eb-9958-80eb887df676.gif)

It feels like I'm opening an issue in a wrong repo, but the other options in https://github.com/cypress-io/cypress/issues/new/choose felt even more wrong. So sorry about that.

**Comment by emilyrohrbough** [comment]
This is no longer an issue.
