### ISSUE TITLE
Wrong create-cypress-tests command option in @cypress/react

### ISSUE THREAD

**Issue by ZeRego** [cypress-io/cypress-documentation#3805]
## I'm submitting a...

```
[ ] Bug report
[ ] Content update
[x] Process update (build, deployment, ... )
```

## Type of bug / changes

In the @cypress/react README [1] we mention the following command:
`npx create-cypress-tests --component-testing`

And based on the create-cypress-tests README [2] it should be:
`npx create-cypress-tests --component-tests`

[1] https://www.npmjs.com/package/@cypress/react
[2] https://www.npmjs.com/package/create-cypress-tests

**Comment by MikeMcC399** [comment]
- This issue is obsolete because the text referred to was already corrected and in any case it was removed by PR https://github.com/cypress-io/cypress/pull/22538
