### ISSUE TITLE
Link to the "E2E API testing" blog post is broken

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#3822]
Should lead to the blog post

<img width="809" alt="Screen Shot 2021-04-10 at 4 22 53 PM" src="https://user-images.githubusercontent.com/2212006/114283703-127d6600-9a19-11eb-94a9-67eb2b1cdb3e.png">

**Comment by Abhijith2893** [comment]
All the blog links are broken, possibly because of a domain mismatch (docs.cypress Vs cypress.io)

<img width="2121" alt="Screen Shot 2021-04-10 at 8 17 48 PM" src="https://user-images.githubusercontent.com/29356468/114289001-03f37680-9a3a-11eb-80f0-4b1c5fe61373.png">

**Comment by matthamil** [comment]
Yep, I introduced this bug. Oops. Fixing this now.
