### ISSUE TITLE
delete `develop` branch

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-documentation#3838]
seems like we're not using it. it would be nice to just delete since I branched off develop not knowing it was a stale branch

**Comment by matthamil** [comment]
Thanks, yes this should be deleted. I'll go ahead and do that. This was updated in the [CONTRIBUTING.md](https://github.com/cypress-io/cypress-documentation/blob/master/CONTRIBUTING.md#pull-requests) but alas the actual branch lives on. Sorry about that

**Comment by matthamil** [comment]
Actually, there is no `develop` branch on GitHub. Your `develop` branch must be a stale local copy.
