### ISSUE TITLE
Weird number highlights when using shell code block

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#3851]
See the page https://docs.cypress.io/guides/guides/command-line#cypress-version

<img width="695" alt="Screen Shot 2021-04-16 at 9 40 43 AM" src="https://user-images.githubusercontent.com/2212006/115033058-face3380-9e97-11eb-82b2-4e67ff12e78f.png">

**Comment by matthamil** [comment]
These should be converted to comments, i.e. prefixed with `#`. This should fix the highlighting and make it more explicit that these values are outputs of each command rather than arguments.
