### ISSUE TITLE
Trouble to see what we select in the code part

### ISSUE THREAD

**Issue by kud** [cypress-io/cypress-documentation#3856]
Hello!

I know I'm a bit colourblind but, it's really hard to see what you select/want to copy in a code part of the documentation:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/655838/115127849-20635600-9fda-11eb-8c90-4c09e2b3fcbe.png">

Could you change the colour of the background when selecting? Thanks 😊

**Comment by bahmutov** [comment]
Thank you for reporting this, it is our fault for this bug, we will try to fix it ASAP next week

**Comment by kud** [comment]
Thank you! :)
