### ISSUE TITLE
Links in route() deprecation note respond with 404 error

### ISSUE THREAD

**Issue by slaweet** [cypress-io/cypress-documentation#3866]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Links in route() deprecation note respond with 404 error
 https://github.com/cypress-io/cypress-documentation/blob/0ca752997360a06162092a373f55dd263db86b2a/scripts/partials.js#L89 are broken
![cypress-broken-links](https://user-images.githubusercontent.com/1254342/115722219-11382b80-a37f-11eb-88e4-3f8ebf407df6.gif)

**Comment by matthamil** [comment]
Interesting that you hit this error, we have a cloudflare redirect that should remove all `.html` extensions from URLs that you land on. I'll take a look at the PR

**Comment by matthamil** [comment]
For context, the `.html` extensions are a relic of our previous documentation website before we migrated to nuxt
