### ISSUE TITLE
Typo in "Writing and organizing tests" page

### ISSUE THREAD

**Issue by rafael-nogueras** [cypress-io/cypress-documentation#3875]
## I'm submitting a...

```
[ ] Bug report
```

## Type of bug / changes

The "Allowed config value" section (https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Allowed-config-values) of the "Writing and organizing tests" page has the following typo:

`The following configuration values can be changed via per test configuration:` should be `The following configuration values can be changed via test configuration:`

**Comment by emilyrohrbough** [comment]
This no longer exists on this page.
