### ISSUE TITLE
.as is incorrectly italicized in code blocks

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress-documentation#3909]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

Take this code block:

```js
cy.intercept('GET', '/users').as('getAllUsers')
cy.intercept('POST', '/users').as('createUser')
```

Look at `as`: 

![image](https://user-images.githubusercontent.com/1151760/117041156-2f484900-acfa-11eb-8d4e-83d2b542a929.png)

Presumably since it's a keyword (`import { foo as bar }`, i think?) it gets italicized.

Looks weird since we use `.as` everywhere.

**Comment by matthamil** [comment]
Yep, I can try to fix this. It's definitely picking it up as a keyword.
