### ISSUE TITLE
Embedded videos do not work on Firefox

### ISSUE THREAD

**Issue by panzarino** [cypress-io/cypress-documentation#3936]
Embedded videos do not work properly on Firefox (but seem to be working perfectly fine in Chrome)

For example on the following page - https://docs.cypress.io/guides/continuous-integration/introduction

I get an error that looks like this:

<img width="864" alt="Screen Shot 2021-05-20 at 00 24 18" src="https://user-images.githubusercontent.com/7033952/118919029-c10ea380-b901-11eb-9aad-c938e4fa4017.png">

**Comment by admah** [comment]
@panzarino which version of FF are you using? I tested in v89.0b10  and v89.0b13 with the result below:
 
<img width="943" alt="Screen Shot 2021-05-20 at 10 14 32 AM" src="https://user-images.githubusercontent.com/2184114/119004470-3905b980-b954-11eb-80ea-cac753985eff.png">

**Comment by panzarino** [comment]
@admah Interesting, I'm right in the middle at `89.0b12`. Before filing the issue I had done a test in Private mode with no extensions and was still getting the issue. After just now trying again in troubleshoot mode (previously called safe mode) I was able to see the video just fine so I guess this is just an issue on my end somewhere.
