### ISSUE TITLE
Search UI on https://docs.cypress.io/api has broken styling

### ISSUE THREAD

**Issue by jjkavalam** [cypress-io/cypress-documentation#3958]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The search box that pops up on API documentation pages appears broken in terms of styles. Please see screenshot below.

![image](https://user-images.githubusercontent.com/4114293/120094898-97514a00-c155-11eb-9f65-4e0045271efb.png)

Steps to reproduce:

- In a browser, open https://docs.cypress.io/api
- Click on the "Search" box at the top right (or use a key board shortcut - Cmd + K on Mac)

**Comment by jjkavalam** [comment]
Update: Tested on Safari ... appears to be alright.

![image](https://user-images.githubusercontent.com/4114293/120095118-aa184e80-c156-11eb-9a6a-aa599bfb8e26.png)

**Comment by mcampbell** [comment]
Working ok for me on [Firefox](https://i.imgur.com/44t4zQh.png)

**Comment by matthamil** [comment]
Can't repro, closing

**Comment by matthamil** [comment]
I could repro with Chrome 91 but not 90. Resolved with https://github.com/cypress-io/cypress-documentation/pull/3970
