### ISSUE TITLE
testFiles vs. ignoreTestFiles: one matching a path, the other only a filename?

### ISSUE THREAD

**Issue by krisztian-romek** [cypress-io/cypress-documentation#3971]
From https://docs.cypress.io/guides/references/configuration:

Option | Default | Description
--------| -------- | -------------
`testFiles` | `**/*.*` | A String or Array of glob patterns of the test files to load
`ignoreTestFiles` | `*.hot-update.js` | A String or Array of glob patterns used to ignore test files...

So the first seems to match a pattern, the second only a file name. But that's not true, e.g. this SO answer definitely uses a path:

https://stackoverflow.com/questions/57873167/cypress-ignoretestfiles-is-not-ignoring-tests

Seemingly simple, yet easy to misconfigure. The default value is deceiving IMO. If I don't think carefully, then I just end up making that mistake, even though it's easy to figure out. Are these paths relative to the `integrationFolder`? I assume so, but it's not documented very well either. Probably worth doing. Feel free to correct me if I'm wrong.

**Comment by jennifer-shehane** [comment]
Yeah, the default is pretty strange, but this is accurate to what the default in the product is, so we can't change the documentation of the default. 

We could probably provide some better examples of using the `ignoreTestFiles` to indicate that it accepts a glob or array of globs for matching any paths, not just single files. 

I do believe these paths are relative to the `integrationsFolder` and would be worthy to note here as well.
