### ISSUE TITLE
Clicking on 'arrow' for side navigation doesn't expand sidebar

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#3982]
## Type of bug / changes

You have to click on the left 3/4 of the link, you can't click on the arrow to expand the left sidebar. 

![](http://g.recordit.co/cSo2CneLKw.gif)

**Comment by jennifer-shehane** [comment]
Chrome 91.0.4472.101. Happens with extensions disabled and incognito. 🤔

**Comment by jennifer-shehane** [comment]
It's not doing it today on Chrome 91.0.4472.106. 👀 I don't know I've been experiencing weird behavior in Chrome lately, maybe it's just me.

**Comment by jaffrepaul** [comment]
This was a z-index issue and had a quick fix here https://github.com/cypress-io/cypress-documentation/pull/4319

There could be more robust exploration when the library the docs site is built on is updated, which we hope to do.
