### ISSUE TITLE
Table of Contents should be clickable.

### ISSUE THREAD

**Issue by moazam00** [cypress-io/cypress-documentation#3987]
The table of content under api is not clickable.

[https://docs.cypress.io/api/table-of-contents]
**Screenshot attached**
![table of content is not clickable](https://user-images.githubusercontent.com/44158154/122478607-28903f80-cfe3-11eb-84a6-e1bb2d1143bd.PNG)

**Comment by moazam00** [comment]
Should i get reward for raising that issue?


Muhammad Moazam

**Comment by jennifer-shehane** [comment]
@moazam00 No, we don't offer rewards for alerting us to issues.
