### ISSUE TITLE
Is the search scraping still working?

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#4002]
Trying to search by subtitle name - nothing comes up from the docs, as the video below shows

https://user-images.githubusercontent.com/2212006/123640586-5188af80-d7ef-11eb-99c0-ffd139af06aa.mp4

**Comment by jennifer-shehane** [comment]
Yah, someone mentioned to DX team that searching for 'Studio' returns no results, which they said they'd look into. So yah, something isn't updating.

**Comment by admah** [comment]
@bahmutov @jennifer-shehane yes, this is definitely something we're looking into. Thanks for surfacing it!

**Comment by admah** [comment]
![](http://g.recordit.co/5eNKqUMU50.gif)

We've updated the script that handled this and the search index has been updated.
