### ISSUE TITLE
cy.route documentation claims that glob matching will match non-origin urls

### ISSUE THREAD

**Issue by sgoel** [cypress-io/cypress-documentation#403]
https://docs.cypress.io/api/commands/route.html#Matches claims that `cy.route('/users/*')` will match `/https://google.com/users/3`. That is not the case when I run 
```javascript
Cypress.minimatch('https://google.com/users/3', '/users/*') // false
````

**Comment by jennifer-shehane** [comment]
Thanks so much, this should help a lot of confused people!
