### ISSUE TITLE
Validate readonly fields

### ISSUE THREAD

**Issue by pedromatos47** [cypress-io/cypress-documentation#405]
Since Cypress doesn't support `readonly` attribute validation as of now, is there any way to work around it?

And would it be to much of a hassle to add this feature?

Cheers

**Comment by jennifer-shehane** [comment]
Hi @pedromatos47, this repo is for the Cypress documentation only. Can you open this issue on our main repo here: https://github.com/cypress-io/cypress/issues/new

**Comment by pedromatos47** [comment]
Sorry @jennifer-shehane, my bad! Will do, thanks.
