### ISSUE TITLE
documentation for screenshot and API mismatch

### ISSUE THREAD

**Issue by activedecay** [cypress-io/cypress-documentation#4064]
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes
The documentation for screenshot, underneath the "Clip" heading, linked below, does not contain the correct API call in the example code

https://docs.cypress.io/api/commands/screenshot#Clip

The example is wrong `cy.screenshot({ x: 20, y: 20, width: 400, height: 300 })`
It should be `cy.screenshot({clip: { x: 20, y: 20, width: 400, height: 300 }})`

**Comment by StephNathai** [comment]
Hi, can I grab this?
