### ISSUE TITLE
Update docs on Page Object Pattern

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-documentation#416]
Update [FAQ on Page Object Pattern](https://gitter.im/cypress-io/cypress?at=586f3155c02c1a3959f202de) to ensure it includes information covered in [Gitter](https://gitter.im/cypress-io/cypress?at=586f3155c02c1a3959f202de) **or** possibly consider separate content to address Page Object Pattern

**Comment by ValerieThoma** [comment]
closing in favor of #554
