### ISSUE TITLE
Update all "LayerCI" references to "webapp.io"

### ISSUE THREAD

**Issue by magnolia-triplett** [cypress-io/cypress-documentation#4198]
### Subject

Update all "LayerCI" references to "webapp.io" due to rebrand

### Description

References to LayerCI to be changed to "webapp.io" are as follows: 

- docs: https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#Guides
- github example: https://github.com/bahmutov/cypress-example-layerci |

**Comment by jennifer-shehane** [comment]
This was already done
