### ISSUE TITLE
Documentation examples should follow best practices

### ISSUE THREAD

**Issue by marcandre** [cypress-io/cypress-documentation#4227]
In particular, selecting arguments by ID/class is [explicitly recommended](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) to be used only "sparingly", yet [many](https://docs.cypress.io/guides/overview/why-cypress#End-to-end) [examples](https://docs.cypress.io/guides/getting-started/writing-your-first-test#Step-4-Make-an-assertion), including the [best practices](https://docs.cypress.io/guides/references/best-practices#1-Combine-into-one-test) use those.

Docs should follow best practices and *always* use `contains` or `get("[data-attr-cy='...']")` where appropriate.

**Comment by jaffrepaul** [comment]
1. Using IDs or classes in the examples should be updated for consistency with data-*, per the best practices docs.
2. There is a larger conversation kicking off to revise the best practice docs around selectors to consider things like `cy.contains()` in examples, accessibility (using aria roles,labels,etc) and RTL style selectors.

**Comment by jennifer-shehane** [comment]
This seems to have been addressed
