### ISSUE TITLE
Broken links in changelog for already merged issues

### ISSUE THREAD

**Issue by martin-pikalek** [cypress-io/cypress-documentation#4266]
When I am looking on changelog I can see links for issue on github where issue is described. But when issue is merged, link is different and old link is not functional. 

For example link for issue #17496 in screenshot. Link is [#17496](https://github.com/cypress-io/cypress/issues/17496) but that link already not exists. It exists probably as pull request https://github.com/cypress-io/cypress/pull/17496 as it was already merged.

![Screenshot 2021-12-10 at 12 33 09](https://user-images.githubusercontent.com/57229273/145568149-6c4ee447-8919-4a51-9111-18a7a8cc7b35.png)
s

Desired behaviour: I would like to see functional link to description of issue even when fix was merged for that issue and issue was closed.

**Comment by emilyrohrbough** [comment]
This has been fixed.
