### ISSUE TITLE
Global mode documentation

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-documentation#427]
While we currently [recommend](https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install) installing Cypress via `npm`, the direct download (global mode) shouldn't be treated as a second-class citizen. As such, we need some documentation on working with global mode

- [ ] How global mode is different
- [ ] Tradeoffs when using global mode (e.g. https://github.com/cypress-io/cypress/issues/1131)
- [ ] When to use global mode
- [ ] How to tell if you're running global mode
- [ ] Adding projects
- [ ] Removing projects
- [ ] Upgrading global mode installation

**Comment by brian-mann** [comment]
Yeah so when you setup a project to record on the dashboard - when we give you the "success" message we need to instead of saying `cypress run` in the terminal provide you a message to the docs that says: hey you need to install the npm module!!

**Comment by jennifer-shehane** [comment]
> I think it'd be a good idea to put in a note in the "Direct Download" section that Cypress won't run headless if you download directly and try to run the binary.

**Comment by jennifer-shehane** [comment]
Bump

**Comment by ViggoV** [comment]
Is there a global mode?! I was about to completely write off Cypress as I try to keep my projects as clean as possible and the installer was downloading binaries and creating tons of sample files inside my project. I've literally been googling 'cypress global install' for hours and all I found until I combed the Issues page was an earlier, closed issue with someone who couldn't get it to work.

So in other words: +1

**Comment by jennifer-shehane** [comment]
You cannot record to the Dashboard with only downloading the zip - you'd have to use npm package as described here: https://github.com/cypress-io/cypress/issues/756#issuecomment-380916201
