### ISSUE TITLE
Better define concept of "project"

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress-documentation#428]
We need to do a better job of defining a "project" within the context of both the Test Runner and Dashboard. In addition, we need to better describe how a user must create a project locally within the Test Runner in order to get a project to appear on the Dashboard.

The current documentation makes the assumption that users will be adding Cypress to their codebase; however, this isn't necessarily required. Especially if running Cypress in global mode.

**Comment by brian-mann** [comment]
Even in global mode they add cypress tests to their repo.

What do you propose? Can you aggregate all the verbiage around the onboarding process. Like what exactly we say in the docs / dashboard. And suggest what changes need to be made to what content.
