### ISSUE TITLE
Cypress's Chrome crash report references outdated documentation

### ISSUE THREAD

**Issue by phiggins** [cypress-io/cypress-documentation#4338]
This is using Cypress 8.7.0 in Circle-CI.

When Chrome crashes during a cypress run, this error message is printed:

```
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed
```

That links to this documentation page: https://docs.cypress.io/guides/references/error-messages#The-browser-process-running-your-tests-just-exited-unexpectedly

The fix referenced leads to this github issue: https://github.com/cypress-io/cypress/issues/350

According to one of the last comments in that thread, the issue was fixed in Cypress 7.0.1: https://github.com/cypress-io/cypress/issues/350#issuecomment-814959972

That outdated github thread is also referenced in this section of documentation: https://docs.cypress.io/guides/continuous-integration/introduction#In-Docker

Ideally, references to this thread would be removed or a warning that the fix mentioned is not necessary for recent versions of cypress. The Chrome crash message should most likely have that link removed in version of Cypress that are not affected by the bug.

**Comment by brandon-leapyear** [comment]
The docs now reference [this open issue](https://github.com/cypress-io/cypress/issues/349), so I think this issue can be closed

**Comment by emilyrohrbough** [comment]
thanks for checking @brandon-leapyear
