### ISSUE TITLE
Collapse left nav while in API docs

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#437]
**Problem:** The API docs are continuing to grow - and due to the length of Cypress commands - many "sections" are hidden wayyyyyyy down below.

**Proposal:** collapse the left side menu and do the right arrow / down arrow collapse expand system.

When hitting a page directly - automatically expand the section it's in.

**Example:**

- Collapse all sections by default
- If navigating directly to `cy.request` API docs - expand the "Commands" section

We could also save their selection in local storage so that the state of the collapsed / expanded sections would persist.

This would enable us to continue to grow the documents without overwhelming the user. It may also make navigating more self exploratory - and users would discover other parts of the API.

This is just a suggestion though - it may be time to start looking at how other documentation deals with this problem.

**Comment by jennifer-shehane** [comment]
Yeah, we should likely implement collapsible docs everywhere - I see this more frequently in library documentation - and more often in library docs that users *really* like.

**Comment by brian-mann** [comment]
An idea - instead of completely hiding the left nav - we should show a "preview" of the docs underneath it like the first 2-3 items with the 3rd item partially hidden - to give a hint to a user that there's content below...
