### ISSUE TITLE
Docs about running cypress in headless mode

### ISSUE THREAD

**Issue by santoshyadavdev** [cypress-io/cypress-documentation#4380]
Doc mentions https://www.cypress.io/blog/2019/01/17/using-nrwl-nx-to-add-cypress-to-your-angular-development-workflow/#running-tests

Adding --headless will run the tests in the headless mode.

But when I run it I see the message 

Option "headless" is deprecated.
NOTE:
You can now remove the use of the '--headless' flag during 'cypress run' as this is the default for all browsers.

If is it changed, let me know I will open a PR

**Comment by jordanpowell88** [comment]
Thanks for creating this @santoshyadavdev. You are correct in that you no longer need to pass the `--headless` flag. Did you want to create the PR for this?

**Comment by santoshyadavdev** [comment]
Sure will do it 👍
