### ISSUE TITLE
Check Links CI Job is Silently Failing

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress-documentation#4389]
### Description

I keep adding "broken" links to the changelog list. I mentioned I should create a link rule to verify the paths aren't using an cypress on link or a relative link. When looking at the CI setup, I noticed we have a job, but it's silently failing.

### URL of Issue(s)

https://app.circleci.com/pipelines/github/cypress-io/cypress-documentation/19166/workflows/5e08215b-1d8d-4c6e-93cf-5bd294fe6652/jobs/48295

### Steps to replicate

1. Make a change in a changelog file
2. Run in CI and see failure.

**Comment by jennifer-shehane** [comment]
This has been addressed recently
