### ISSUE TITLE
Wrong key property for Mouse-Events from a specific button

### ISSUE THREAD

**Issue by fjtrujy** [cypress-io/cypress-documentation#4442]
### Subject

guides

### Description

Triggering a mouse down from a specific button is using the wrong key. 
The documentation says `button` however the proper value looks to be `buttons`.

https://github.com/cypress-io/cypress-documentation/blob/114a261f0ad54e19218d21080aa59b42db14f525/source/api/commands/trigger.md#trigger-a-mousedown-from-a-specific-mouse-button

It actually fits with the `MouseEvent` documentation:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

Thanks

**Comment by emilyrohrbough** [comment]
@fjtrujy Thank you for reporting this documentation issue. I took a look. Both `button` and `buttons` are supported keys.
