### ISSUE TITLE
Address testing strategies section

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress-documentation#4499]

**Comment by AtofStryker** [comment]
addressed in https://github.com/cypress-io/cypress-documentation/pull/4883, https://github.com/cypress-io/cypress-documentation/pull/4882, https://github.com/cypress-io/cypress-realworld-app/pull/1293, and https://github.com/cypress-io/cypress-realworld-app/pull/1292

**Comment by debrisapron** [comment]
Also addressed in #4895
