### ISSUE TITLE
Document adding `./cypress.config.ts` to `tsconfig.exclude` to avoid conflicts with Jest

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress-documentation#4559]
### Subject

Guides - component testing troubleshooting

### Description

We should update the [Cypress Types Conflict with Jest](https://docs.cypress.io/guides/component-testing/component-test-troubleshooting#Cypress-Types-Conflict-with-Jest
) section of the docs to reflect the [solution outlined here](https://github.com/cypress-io/cypress/issues/22059#issuecomment-1148921141) by @ZachJW34 to the issue reported in https://github.com/cypress-io/cypress/issues/22059.

It's also been suggested in that issue to surface this in the migration guide, which I think is not a bad idea.

I'm creating this issue in the docs so that we can close the issue in the main repo and add the information to our main docs.

**Comment by Yberion** [comment]
Hello,

Just to clarify, it's not only `Jest`, we have the same problem on Angular with `Jasmine`

**Comment by bchen1029** [comment]
@marktnoonan would you mind help this PR #4600 merged? thx
