### ISSUE TITLE
documentation has "called.with" instead of "calledWith"

### ISSUE THREAD

**Issue by maboesanman** [cypress-io/cypress-documentation#4560]
### Subject

documentation/guide page has incorrect syntax for assertion

### Description

https://docs.cypress.io/guides/component-testing/events-vue#Assert
<img width="692" alt="Screen Shot 2022-06-08 at 10 43 57 AM" src="https://user-images.githubusercontent.com/3190108/172645894-0b6bf19e-4613-435f-af5c-9712e04ab6a7.png">

this is a little urgent because it leads to false positive tests

**Comment by jaffrepaul** [comment]
This has been updated on the master branch 👍
