### ISSUE TITLE
Incorrect reference to pluginsFile in the configuration guide for Cypress 10

### ISSUE THREAD

**Issue by mbolotov** [cypress-io/cypress-documentation#4576]
### Subject

Guides

### Description

As the `pluginsFile` property has been removed in Cypress 10, there should be no reference to it. 
See https://docs.cypress.io/guides/references/configuration#Node-version
![image](https://user-images.githubusercontent.com/19785715/174294568-c551911e-0d0a-466d-99be-83beb3fbe8a1.png)

**Comment by jennifer-shehane** [comment]
nodeVersion has been removed entirely in 13, so this is no longer relevant
