### ISSUE TITLE
menuspy not working precisely

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#46]
@lorennorman commented on [Fri May 26 2017](https://github.com/cypress-io/cypress-monorepo/issues/99)

I've noticed a few things weird about menuspy:
- click a link on the right, page jumps to the right place, but the incorrect link is highlighted on the right
- sometimes the highlighted link on the right does not match the anchor tag in the URL

Example:
![cypress io documentation - error messages 2017-05-26 11-55-15](https://cloud.githubusercontent.com/assets/17697/26502795/374edfea-420c-11e7-981a-8d9c85abbb1f.png)

---

@jennifer-shehane commented on [Thu Jul 06 2017](https://github.com/cypress-io/cypress-monorepo/issues/99#issuecomment-313131839)

This issue was difficult to track down. Sometimes menuspy was accurate and sometimes not. 

After some use, it seems to be most off when images are included on the page, so we suspect that menuspy is not properly calculating the height of images into it's scrolling algorithm. This is likely because the images have not loaded yet. 

Can we calculate after the `onload` event? Does the `onload` event call before all images are loaded? Each image fires it's own `load` event, so you could check all images `load` event. 

To test this, throttle the network in devtools.

**Comment by richdouglasevans** [comment]
Can this issue be `Closed` in light of the recent merge of #844 ?

**Comment by jennifer-shehane** [comment]
Oh boy - yeah - this is old.
