### ISSUE TITLE
Dead links for kitchensink examples (/cypress/integration/)

### ISSUE THREAD

**Issue by nedredmond** [cypress-io/cypress-documentation#4656]
### Description

When I click `.click() examples in kitchensink app`, I expect to be taken to the examples in github; instead, I see 404.

### URL of Issue(s)

https://docs.cypress.io/api/commands/click#See-also

### Steps to replicate

1. Go to [click() "See Also" section](https://docs.cypress.io/api/commands/click#See-also)
2. Click on 'click() examples in kitchensink app'
3. See error

### Browser

Chrome 103

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Looks like any links to `https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/integration/...` just need to be replaced with `https://github.com/cypress-io/cypress-example-kitchensink/tree/master/cypress/e2e/...`

**Comment by emilyrohrbough** [comment]
This is no longer a broken link.
