### ISSUE TITLE
Example about GitHub Action parallelization will not even run

### ISSUE THREAD

**Issue by mwskwong** [cypress-io/cypress-documentation#4724]
### Subject

Guides

### Description

According to the [guide](https://docs.cypress.io/guides/continuous-integration/github-actions#Parallelization), users should create two jobs. And for the worker job, users should specify `install: false` because the install job is supposed to have handled the installation already.

However, the reality is, that by setting `install: false`, the worker job will always fail because `cypress` is not installed. 

In fact, even the RWA doesn't have `install: false` set in the worker job. 
https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml#L99

**Comment by jennifer-shehane** [comment]
This doesn't appear to be relevant anymore
