### ISSUE TITLE
`cy.session` option `cacheAcrossSpecs` is documented but not supported in all versions

### ISSUE THREAD

**Issue by monkpit** [cypress-io/cypress-documentation#4820]
![Screen Shot 2022-10-28 at 11 24 15 AM](https://user-images.githubusercontent.com/5297293/198686098-032006db-8233-4bfc-937f-ab61b93091da.png)

https://docs.cypress.io/api/commands/session#Arguments

I found the `cacheAcrossSpecs` option in the docs for `cy.session`, added it to my test case with Cypress v9.7.0, and got an error message saying that the only valid option was `validate`.

![image](https://user-images.githubusercontent.com/5297293/198686282-c40e2fea-8e29-4959-bafd-00e6327e0463.png)

The docs should be updated to warn the user that the option requires some minimum version of Cypress (not sure which version it is? I checked `git blame` for files containing `cacheAcrossSpecs` and I think it might be v10.11.0, but I am not confident about this.

**Comment by juanpposada** [comment]
Hi bro, only available from cypress 10.9, for access to this feature i migrate from 9.6 to 11.2 and the cacheAcrossSpecs it's working fine!
