### ISSUE TITLE
searching for testIsolation doesn't lead you to the config options page

### ISSUE THREAD

**Issue by modern-sapien** [cypress-io/cypress-documentation#4888]
### Subject

config options

### Description

searching for testIsolation doesn't lead you to the config options page

**Comment by MikeMcC399** [comment]
@modern-sapien 

This is quite an old issue, however it seems to have resolved itself!

![image](https://github.com/user-attachments/assets/f29d0daf-7cfa-4020-91a9-0351fbcbb371)

in the full set of search results

![image](https://github.com/user-attachments/assets/08ac8560-8524-4103-8d7d-0a3ba6837c1a)
