### ISSUE TITLE
404 on https://docs.cypress.io/guides/core-concepts/introduction-to-cypress 

### ISSUE THREAD

**Issue by nemanjaglumac** [cypress-io/cypress-documentation#4906]
### Description

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress returns 404

### URL of Issue(s)

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress

### Steps to replicate

1. Go to https://docs.cypress.io/guides/core-concepts/introduction-to-cypress
2. Open a network tab
3. See that `GET` request to https://docs.cypress.io/guides/core-concepts/introduction-to-cypress returns 404

### Browser

all major browsers, no cache involved

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

It seems that some kind of a redirect happens because I can see the page in my browser, but it definitely returns 404 initially. Adding an anchor to the link will not work.

Try https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Chains-of-Commands. It will stay at the top of the page.

**Comment by jaffrepaul** [comment]
The Docs site was migrated to a new platform this month and this looks like it's no longer an issue.
