### ISSUE TITLE
Document how "invoke" automatically waits for promises to resolve

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#495]
If invoked function returns a promise, `cy.invoke` automatically waits for it - need to document it!

See https://github.com/cypress-io/cypress-example-recipes/issues/133 and example in commit https://github.com/cypress-io/cypress-example-recipes/commit/b5629b3cb6d76e8d13a2f8597533a696cdacd105

**Comment by 8BitJonny** [comment]
With the branch merged and the updated documentation online, this issue can be finally closed @bahmutov @jennifer-shehane right?

**Comment by jennifer-shehane** [comment]
Yes, thanks!
