### ISSUE TITLE
Add Cypress Equivalent of Selenium getText()

### ISSUE THREAD

**Issue by ValerieThoma** [cypress-io/cypress-documentation#496]
Cypress user's are frequently asking (*in Gitter*) for Cypress's equivalent of Selenium's `getText()`. 
Adding this to the first topic `How do I get an element's text content?` in **Using Cypress FAQ**.

**Comment by jimsmith1562** [comment]
i see this was closed, but don't see an answer. struggling with this myself at the moment, can't find answer

**Comment by jennifer-shehane** [comment]
It is in the FAQ, findable through our documentation's search.

https://on.cypress.io/using-cypress-faq#How-do-I-get-an-element%E2%80%99s-text-contents

**Comment by Abhilash-Srinivasa** [comment]
There is a great solution at https://github.com/cypress-io/cypress/issues/630#issuecomment-403257798
