### ISSUE TITLE
Broken links in https://docs.cypress.io/guides/guides/environment-variables#Setting

### ISSUE THREAD

**Issue by harlik** [cypress-io/cypress-documentation#4992]
### Description

When I click on a link, I expect the page to be scrolled to the related heading/section, but it doesn't.

### URL of Issue(s)

https://docs.cypress.io/guides/guides/environment-variables#Setting

### Steps to replicate

1. Go to https://docs.cypress.io/guides/guides/environment-variables#Setting
2. Click on [Create a cypress.env.json](https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json) or [Pass in the CLI as --env](https://docs.cypress.io/guides/guides/environment-variables#Option-4-env)

Expected: the page is scrolled to the related section
Actual: no scrolling happens

Comment: the links are different from the ones in the 'index' on the right side.

### Browser

Microsoft Edge Version 108.0.1462.46 (Official build) (64-bit)

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by emilyrohrbough** [comment]
Fixed in https://github.com/cypress-io/cypress-documentation/pull/4998
