### ISSUE TITLE
Document longpress event

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#501]
Add as an example to `trigger` doc from https://github.com/cypress-io/cypress/issues/1487

```js
 cy.get(`.target`).trigger('mousedown')
 cy.wait(1000)
 cy.get(`.target`).trigger('mouseleave')
```

**Comment by marzann** [comment]
Is this issue available to claim as a first-time contribution?

**Comment by jennifer-shehane** [comment]
@marzann Yes! File to update: https://github.com/cypress-io/cypress-documentation/edit/develop/source/api/commands/trigger.md

**Comment by marzann** [comment]
Great, I will work on it. Thank you.
