### ISSUE TITLE
Testing with Cypress Docker Images Docs can be updated

### ISSUE THREAD

**Issue by jaffrepaul** [cypress-io/cypress-documentation#5013]
### Subject

Guides

### Description

The Cypress docs on [Testing in Chrome and Firefox with Cypress Docker Images](https://docs.cypress.io/guides/continuous-integration/github-actions#Testing-in-Chrome-and-Firefox-with-Cypress-Docker-Images) need review.

Either this section should be updated or removed.

Both Chrome and Firefox are included as standard in [GitHub runner images](https://github.com/actions/runner-images), so the question arises why it would be advised to use a Docker container when this is not necessary.

**Comment by jennifer-shehane** [comment]
This has been updated
