### ISSUE TITLE
Update the Command Line `cypress run` doc to describe the new flag and its options

### ISSUE THREAD

**Issue by elylucas** [cypress-io/cypress-documentation#5023]
- [cypress run doc](https://docs.cypress.io/guides/guides/command-line#cypress-run)
- [Clickup task covers these options](https://app.clickup.com/t/18033298/PM-1764)

**Comment by elylucas** [comment]
PR: https://github.com/cypress-io/cypress-documentation/pull/5033

**Comment by emilyrohrbough** [comment]
@elylucas can this be closed?
