### ISSUE TITLE
Styles are not building correctly

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#506]
<img width="1396" alt="screen shot 2018-04-10 at 10 22 22 am" src="https://user-images.githubusercontent.com/2212006/38562655-153cfa5c-3ca9-11e8-8ac0-617ea196276f.png">

I see errors

```
INFO  Hexo is running at http://localhost:2222. Press Ctrl+C to stop.
Error: Invalid CSS after "    li:not(": expected selector, was "'.toc-item') {"
ERROR Asset render failed: css/cypress.css
Error: Invalid CSS after "    li:not(": expected selector, was "'.toc-item') {"
    at options.error (/Users/gleb/git/cypress-documentation/node_modules/node-sass/lib/index.js:291:26)
Error: Invalid CSS after "    li:not(": expected selector, was "'.toc-item') {"
ERROR Asset render failed: css/cypress.css
```

**Comment by bahmutov** [comment]
running `npm run build` first and then `npm start` still shows empty page

<img width="1018" alt="screen shot 2018-04-10 at 10 25 25 am" src="https://user-images.githubusercontent.com/2212006/38562846-800994e4-3ca9-11e8-8a9d-f7a6cb55d485.png">

How to detect this error by itself? Preferably during the build process.

**Comment by bahmutov** [comment]
Installing `npm i node-sass@4.7.2` and running `npm start` again solves the problem - so the problem might be

```
$ npm ls node-sass
cypress-documentation@0.0.0 /Users/gleb/git/cypress-documentation
├─┬ hexo-renderer-scss@1.0.3 (github:cypress-io/hexo-renderer-scss#39f042c3c05aae485f9a8758e6a51a25a7c6d728)
```
But https://github.com/cypress-io/hexo-renderer-scss/blob/master/package.json has `node-sass` with fuzzy range

```
"dependencies": {
    "node-sass": "^4.5.3",
    "node-sass-magic-importer": "5.0.0-alpha.8"
  }
```

Need to lock it down

**Comment by jennifer-shehane** [comment]
I was running into more issues with css building and updated to the latest `hexo-renderer-scss`. Works great now with the package-lock.json being used in the docs - going to delete our hexo-rendere-scss fork as it's no longer being used. https://github.com/cypress-io/cypress-documentation/pull/705
