### ISSUE TITLE
Document pnpm support

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/cypress-documentation#5064]
### Subject

Supported Package Manager

### Description

Cypress supported pnpm but the only mention of this is in our changelog. We need call this out specifically for users considering Cypress that use pnpm. 

Ref:
- https://pnpm.io/installation
- `pnpm install cypress`

**Comment by MikeMcC399** [comment]
This has been documented in

https://docs.cypress.io/guides/getting-started/installing-cypress#pnpm-add

- https://github.com/cypress-io/cypress-documentation/pull/5402
