### ISSUE TITLE
Error: Webpack Compilation Error, Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by nemonemi** [cypress-io/cypress-documentation#5127]
### Description

Everything worked fine up until I extracted a library from the app at NX. 

### URL of Issue(s)

Hard to reproduce it.

### Browser

Chrome Version 110.0.5481.177 (Official Build) (64-bit) Ubuntu

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

![image](https://user-images.githubusercontent.com/77624664/225959596-9a462f2d-9f06-4fa4-8529-89859619f6fc.png)

![image](https://user-images.githubusercontent.com/77624664/225966774-2d585004-1d3d-4c34-b3fa-9f2e11564a7a.png)

However, there are no missing dependencies or syntax errors. Builds pass without any issues, and the runtime also works as it should.

**Comment by shryzhang** [comment]
same problem

**Comment by MikeMcC399** [comment]
@nemonemi / @shryzhang 

If you think you have found a bug in Cypress then the best place to submit this is https://github.com/cypress-io/cypress/issues where you are prompted for detailed version information. The original posting was for an older version of Cypress `12.8.0` and generally if there is a suspicion of a bug, the Cypress.io engineering team will ask you to check that it is reproducible on the latest version (currently Cypress `13.8.0`).

If you are looking for community support there is an active Cypress community on [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

The documentation repo here is for reporting errors in the documentation or pages on the documentation website which are not working.
