### ISSUE TITLE
Electron examples link is broken

### ISSUE THREAD

**Issue by kingyue737** [cypress-io/cypress-documentation#5131]
### Description

The link in "Can I test my Electron app" section is broken

### URL of Issue(s)

https://docs.cypress.io/faq/questions/using-cypress-faq#Can-I-test-my-Electron-app

### Steps to replicate

1. Visit the URL provided above
2. Go to 'Can I test my Electron app" section'
3. Click on 'here'
4. Page not found

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by AshwanthramKL** [comment]
Hey @nagash77, can I work on this?

**Comment by nagash77** [comment]
@AshwanthramKL we would love help on fixing this issue.  Thanks for the help!
