### ISSUE TITLE
Non working links to Cypress Cloud for CI providers

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5149]
### Subject

CI Provider Examples

## Problem

Multiple Cypress Cloud projects not viewable when links selected on page [CI Provider Examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples).

CI provider | Project ID | Viewable
--- | --- | ---
CircleCI | [7s5okt](https://dashboard.cypress.io/projects/7s5okt) | yes
GitHub Actions | [tpys4j](https://dashboard.cypress.io/projects/tpys4j) | no
BitBucket | [q1ovwz](https://dashboard.cypress.io/projects/q1ovwz) | no
GitLab CI | [woih1m](https://dashboard.cypress.io/projects/woih1m) | no
AWS CodeBuild | [zx15dm](https://dashboard.cypress.io/projects/zx15dm) | no

## Suggestion

Review Project ID and public access to Cypress Cloud for CI providers marked as not viewable.

Also, all links are using the legacy `dashboard` instead of https://cloud.cypress.io/.

### CircleCI

  url="https://dashboard.cypress.io/projects/7s5okt"
  callout="See CircleCI + Cypress Cloud in action"

callout="RWA CircleCI configuration"
url="https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml"

Only CI provider with no issue.

### GitHub Actions

  url="https://dashboard.cypress.io/projects/tpys4j"
  callout="See GitHub Actions + Cypress Cloud in action"

callout="RWA GitHub Actions configuration" 
url="https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml"

`CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}`

### BitBucket

  url="https://dashboard.cypress.io/projects/q1ovwz"
  callout="See BitBucket Pipelines + Cypress Cloud in action"

callout="RWA BitBucket Pipelines configuration"
url="https://github.com/cypress-io/cypress-realworld-app/blob/develop/bitbucket-pipelines.yml"

### GitLab CI

  url="https://dashboard.cypress.io/projects/woih1m"
  callout="See GitLab CI + Cypress Cloud in action"

callout="RWA GitLab CI configuration" url="https://github.com/cypress-io/cypress-realworld-app/blob/develop/.gitlab-ci.yml"

### AWS CodeBuild

  url="https://dashboard.cypress.io/projects/zx15dm"
  callout="See AWS CodeBuild + Cypress Cloud in action"

callout="RWA AWS CodeBuild configuration"
url="https://github.com/cypress-io/cypress-realworld-app/blob/develop/buildspec.yml"

**Comment by MikeMcC399** [comment]
If all these links are coming from the [cypress-io/cypress-realworld-app (RWA)](https://github.com/cypress-io/cypress-realworld-app), then I suggest it would be better to maintain the list of links in the [cypress-io/cypress-realworld-app (RWA)](https://github.com/cypress-io/cypress-realworld-app) repo itself, for instance, in its [README](https://github.com/cypress-io/cypress-realworld-app/blob/develop/README.md) file instead of here in the docu repo.

**Comment by chrisbreiding** [comment]
Thanks for reporting this! I've update the Cloud projects to have public access, so the links should all work now regardless of authentication.

> If all these links are coming from the [cypress-io/cypress-realworld-app (RWA)](https://github.com/cypress-io/cypress-realworld-app), then I suggest it would be better to maintain the list of links in the [cypress-io/cypress-realworld-app (RWA)](https://github.com/cypress-io/cypress-realworld-app) repo itself, for instance, in its [README](https://github.com/cypress-io/cypress-realworld-app/blob/develop/README.md?rgh-link-date=2023-04-17T14%3A47%3A14Z) file instead of here in the docu repo.

I see your point, but I think we want to keep the CI provider examples as they are in the docs instead of linking out to a README. It's a bit more accessible and searchable having it in the docs.

**Comment by chrisbreiding** [comment]
> The GitLab CI has been disabled, so it doesn't belong in the list [docs.cypress.io/guides/continuous-integration/ci-provider-examples](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples) of active examples.

Good callout! I created a PR to address that and to update the Cloud links: https://github.com/cypress-io/cypress-documentation/pull/5240
