### ISSUE TITLE
Travis CI example workflows do not work

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5158]
### Subject

CI Provider Examples

### Description

[Continuous Integration > CI Provider Examples > Examples > TravisCI](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#TravisCI) links to Travis CI workflows on [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink).

These workflows no longer work. (See also issue https://github.com/cypress-io/cypress-example-kitchensink/issues/602.) The response from @lmiller1990 indicated that a migration from the disabled `travis-ci.org` to [travis-ci.com](https://www.travis-ci.com/) will probably not take place.

If that is the final decision, then the reference to the Travis CI non-working workflows on [Continuous Integration > CI Provider Examples > Examples > TravisCI](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#TravisCI) should be removed.

## Reference

https://docs.travis-ci.com/user/migrate/open-source-repository-migration states

"Starting June 2021 travis-ci.org is disabled and therefore no longer supported. Please use travis-ci.com."

Q. Will Travis CI be getting rid of free users? #
A. Travis CI will continue to offer a free tier for public or open-source repositories on travis-ci.com and will not be affected by the migration.

**Comment by lmiller1990** [comment]
In an ideal world, we'd migrate, but I think we (Cypress team & external contributors alike) have more high value things to do than supporting a fairly obsolete CI runner. I used to love Travis but a couple of data breaches and significant reliability issues make it hard to recommend them. 

Let's get some input from some others, maybe @elylucas, but I'm of the opinion we can drop them from our docs. People can still *use* Cypress on Travis, we just won't list it, since we haven't been maintaining the Travis infra we've already got.

**Comment by MikeMcC399** [comment]
I need to qualify this issue. 

The examples on [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) are a mixture of live CI examples and documentation-only examples.

The live CI examples are generally triggered by `push` or `pull_request` commits and they are shown with their passing or failing status badge. This is the category that Travis CI originally belonged to.

The majority of examples on the [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) repo are however just scripts which are intended to assist users in starting up with a particular CI provider. There is no guarantee that they actually run, although probably when they were written they would have been working.

The Travis CI scripts could just move to the second category of being documentation-only, with no live status badge showing whether they work or not. That is unless Cypress.io decides that Travis CI should not be mentioned or promoted anymore.

**Comment by MikeMcC399** [comment]
- https://github.com/cypress-io/cypress-example-kitchensink/issues/602 is resolved by https://github.com/cypress-io/cypress-example-kitchensink/pull/624, so I no longer see any practical problem with Travis CI.

Withdrawing this documentation issue now.
