### ISSUE TITLE
Allure report not attaching screenshot automatically for failed tests after upgrading to 12.9.0 from 9.6.1

### ISSUE THREAD

**Issue by Shikharnigam87** [cypress-io/cypress-documentation#5169]
### Description

When Cypress tests fail, I expect allure reports to have failed screenshot automatically attahed

### URL of Issue(s)

N/A

### Steps to replicate

List of dependencies and versions used on Microsoft Windows 10 machine:
```
cypress: 12.9.0
shelex/cypress-allure-plugin: 2.22.0
allure-commandline: 2.13.8
cypress-multi-reporters: 1.6.3
mocha-junit-reporter: 2.0.2
```

Node: 16.16.0

After upgrading to Cypress 12.9.0 and node 16.16.0 allure reports are not attaching screenshots for failed tests automatically

Pre-requisites - 
`shelex/cypress-allure-plugin` is configured as per latest Cypress documentation
`allure-commandline` is installed on machine

Steps to reproduce issue:
1) Execute tests in Run mode using command
npx cypress run --env allure=true --browser chrome --headed --spec 'test file path'
2) Fail one or 2 tests intentionally
3) Navigate to results folder after execution is finished, and verify that screenshots are saved inside 'screenshots' folder (This is happening properly for me as well)
4) allure-results folder is also created inside parent project folder
5) Generate allure report using command
allure generate allure-results --clean -o results/allure-report
6) Navigate to results/allure-report folder and open index.html. In failed tests no screenshots attached 
(Expected behaviour - To have failed tests screenshots attached in the report)
7)  results/allure-report/attachment folder seems to be empty (Which was not the case with earlier version which i was using)

Note: I have not used or added any additional env variables which affect allure reports within cypress configuration file

And also seeing that if I try to change or modify path for allure results folder using env allureResultsPath within Cypress.config.json file, it is always defaulting to allure-results folder

Can someone please look into this issue, or provide suggestions to resolve this.

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by kwangecs** [comment]
Any update on this I am seeing the same with https://www.npmjs.com/package/allure-cypress?activeTab=readme

version beta 3

**Comment by jennifer-shehane** [comment]
This is an issue with allure. See this thread and make sure to update their package: https://github.com/cypress-io/cypress/issues/27113#issuecomment-2037525601
