### ISSUE TITLE
Component Testing: getting started

### ISSUE THREAD

**Issue by marktnoonan** [cypress-io/cypress-documentation#5178]
### Subject

Consolidate CT "Getting Started" instructions

### Description

The initial steps to get started with component testing using the CT Setup wizard are all the same across different frameworks, so we can make these docs easier to understand and easier to maintain by consolidating those instructions.

That core process can link to framework-specific next steps. This means you don't have to pick a framework to get an overview of how CT works, and instead you can see that it works very much in the same way for all supported frameworks.

This would take the form of a new "Getting Started" page after "Component Testing > Overview" in the docs navigation.

**Comment by elylucas** [comment]
This sounds like a great idea

**Comment by jordanpowell88** [comment]
Consider potential findings from https://docs.google.com/document/d/1BUDOJbNQlOsZ1NIVSC7tSL3tWkGGbRImD_Swf8e-7R8/edit#heading=h.wgf2j86tscsj
