### ISSUE TITLE
Document how to run same test on multiple urls

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#521]
```
viewports = ['mobile', 'tablet', 'desktop']

it ...loop through viewports to create title of test
  cy.viewport(i)
  assertions here
```

Track down where this has been done successfully in cypress issues

**Comment by jennifer-shehane** [comment]
```js
let urls = [];

before(() => {
  urls = ['https://docs.cypress.io', 'https://www.cypress.io']
});

describe('Logo', () => {
  urls.forEach(url => {
    it('Should display logo on ' + url, () => {
      cy.visit(url)
      cy.get('.logo').should('have.attr', 'src').and('include', 'cypress-logo.png')
    })
  })
})
```

**Comment by jennifer-shehane** [comment]
The screenshot of the commands might be cool to add to, to show it dynamically filled in the test titles

<img width="660" alt="screen shot 2018-04-18 at 3 04 16 pm" src="https://user-images.githubusercontent.com/1271364/38952476-d093dcdc-4319-11e8-9c04-a4ea952d0d09.png">

**Comment by jennifer-shehane** [comment]
And because I just remembered this was originally about doing a dynamic test on multiple viewports, here is that code:

```js
const sizes = ['iphone-6', 'ipad-2', [1024, 768]]

describe('Logo', () => {
  sizes.forEach((size) => {
    it(`Should display logo on ${size} screen`, () => {
      if (Cypress._.isArray(size)) {
        cy.viewport(size[0], size[1])
      } else {
        cy.viewport(size)
      }
      
      cy.visit('https://www.cypress.io')
      cy.get('#logo')
    })
  })
})
```

<img width="417" alt="screen shot 2018-04-18 at 3 13 43 pm" src="https://user-images.githubusercontent.com/1271364/38952899-1e2056d2-431b-11e8-8ba4-018868ffa7f4.png">

**Comment by ValerieThoma** [comment]
Should this example be documented within the [viewport](https://docs.cypress.io/api/commands/viewport.html#Syntax) doc or would it be a better and more versatile discovery in `FAQ` like, *"Can I dynamically test multiple viewports?"* and *"Can I run the same tests on multiple subdomains?"* and then show examples of both?

**Comment by jennifer-shehane** [comment]
For the viewport one - I would put this in cy.viewport() and then have the question also put the question in the FAQ and have the answer link back to the example in cy.viewport()

For the multiple urls one - I would just put this in the FAQ I guess. The cy.visit doc is already kind of busy.

**Comment by csodcreativeteamdevs** [comment]
I was trying to do this using `beforeEach` but it was only loading the last value in my viewport array. I know this must be a closure issue but I couldn't figure out how to get it to work! Can you post the above example (https://github.com/cypress-io/cypress-documentation/issues/521#issuecomment-382498110) using `beforeEach`?

**Comment by onetwothreebutter** [comment]
I tried to do this using `beforeEach`, but I couldn't get it going... it was using the last value in my viewport array. I'm sure this is a closure issue, but I couldn't get it working. Can you post the above example (https://github.com/cypress-io/cypress-documentation/issues/521#issuecomment-382498110) using `beforeEach`?

**Comment by RiZKiT** [comment]
The problem is that the tests are only definitions. So code in a forEach loop here, is parsed only, but executed later, except if you use function calls in between like console.log().

You can add a console output at the beginning of forEach and at the end, they will be executed first, afterwards the tests.

**Comment by melibe23** [comment]
> I tried to do this using `beforeEach`, but I couldn't get it going... it was using the last value in my viewport array. I'm sure this is a closure issue, but I couldn't get it working. Can you post the above example ([#521 (comment)](https://github.com/cypress-io/cypress-documentation/issues/521#issuecomment-382498110)) using `beforeEach`?

I am not using beforeEach, and still, get the same error.

This is my code:

`const urls = [
  "https://www.getapp.com/hr-employee-management-software/a/findmyshift/compare/",
  "https://www.getapp.com/hr-employee-management-software/a/findmyshift/compare/quinyx/",
  "https://www.getapp.comhr-employee-management-software/a/findmyshift/compare/quinyx-vs-cakehr/,
  "https://www.getapp.com/hr-employee-management-software/a/findmyshift/compare/quinyx-vs-cakehr-vs-lanteria-hr/"
];

describe("Compare page - Side nav", () => {
  urls.forEach(url => {
    it(`Sidenav is present on ${url}`, () => {
      cy.visit(url);
      cy.xpath('//*[@id="__next"]/div/div/div[1]/div/div/nav').should(
        "be.visible"
      );
    });

  after(() => {
  cy.end();
   });
`

It only takes into account the last URL in the array. 

What I am doing wrong?

**Comment by paulovicenteSpeakap** [comment]
I got some problems using before() and after() as well. I've just removed both, and everything is working correctly. 
Would be nice to see an example with both methods working.

Any idea?

**Comment by k2589** [comment]
Sadly,  when im using
```
for (i = 1; i < 10; i++) {
it(`Opens OP list item #${i}`, () => {
cy.visit('http://localhost:3000/op');
cy.xpath(`//* [@id="allOpportunity"]/div/ul/li[${i}]`).click();

etc...
```
On cy.xpath im always getting 10 in ${i}

**Comment by prakash-nwea** [comment]
Cypress doesn't launch the test at all if the "viewports array" is loaded within before hook at runtime.
Can someone pls help me on this.

**Comment by tiec7** [comment]
is it just me, or if I do

```
describe('my tests', () => {
    // some more work with my urls
    let urls = filterUrls(rawUrls)    // a function that removes unuseful urls

    urls.cities.forEach(url=> {
      it(`TEST loop`, () => {
        console.log('yayyy', url)
        cy.visit(url)
      })
    })
})
```

and I run it with yarn open, the runner "restarts" twice before executing?

**Comment by Julia-Casciato** [comment]
> ```js
> const urls = ['https://docs.cypress.io', 'https://www.cypress.io']
> 
> describe('Logo', () => {
>   urls.forEach((url) => {
>     it(`Should display logo on ${url}`, () => {
>       cy.visit(url)
>       cy.get('#logo img')
>         .should('have.attr', 'src')
>         .and('include', 'logo')
>     })
>   })
> })
> ```

This works really well for me, but is there a way to pass the URLs from a fixture file?
