### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by CypressLover** [cypress-io/cypress-documentation#5215]
### Description

test

### URL of Issue(s)

test

### Steps to replicate

2. Click on '...'
3. Scroll down to '...'

### Browser

test

### Device

- [ ] PC
- [X] Mac
- [X] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

test

**Comment by nagash77** [comment]
test close

**Comment by CypressLover** [comment]
test to revive ticket
