### ISSUE TITLE
Add yarn installation instructions to Installing-Cypress doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#524]
```
yarn add cypress --dev
```

**Comment by ashley-hu** [comment]
Hi, 
May I work on this issue?

**Comment by brian-mann** [comment]
Per my [comments on the other issue](https://github.com/cypress-io/cypress/pull/1576#issuecomment-381167180) I'm not really sure we want to add this to the Installing Cypress docs.

There is already a boat load of content, and adding more text which is arguably unnecessary is not a good idea. It's not like we have to do anything special for `yarn`. It's just an alternative `npm install`. 

Everyone who is already using `yarn` knows that and doesn't need it pointed out. For users **not familiar** with `yarn` it could end up being confusing. We have a lot of new developers / QA people that use Cypress and I'm concerned we'll misdirect or overwhelm them.

**Comment by smerling-coremedia** [comment]
It's just a line of code and a short info, not a new chapter. I came here looking for any specialties using it with yarn. So I think it's a valuable addition to the docs.

**Comment by oherik** [comment]
I came here from a Google search, when I wanted to make sure no extra commands were needed when adding Cypress via Yarn. I agree it would be nice to have it in the official documentation.

**Comment by jennifer-shehane** [comment]
I'm going to add it as it's own small section - this way the first, main installation instructions are `npm` focused, but `yarn` is searchable and listed as an install option (on the same level as direct download) - but I do not believe it is distracting in this separate section. 

![screen shot 2018-06-29 at 11 52 54 am](https://user-images.githubusercontent.com/1271364/42102163-242b572e-7b93-11e8-9a7a-e9d0127c0846.png)

**Comment by smerling-coremedia** [comment]
Thank you!
