### ISSUE TITLE
Add documentation for troubleshooting system notifications

### ISSUE THREAD

**Issue by astone123** [cypress-io/cypress-documentation#5280]
### Subject

Guides

### Description

Add a guide for helping users troubleshoot why they are not seeing system notifications on their operating system.

Some potential issues might include:

- windows - cannot turn notifications back ON after turning them OFF. Currently no known issue - we could say "Windows support is coming in the future". Related: https://github.com/cypress-io/cypress/issues/26786.
- macos/linux - are there any known issues? document how to turn on/off notifications in these operating systems (including screenshots if needed)

**Comment by lmiller1990** [comment]
https://github.com/cypress-io/cypress-documentation/pull/5327

**Comment by lmiller1990** [comment]
@elylucas will pick this one up and get it over the line.

**Comment by warrensplayer** [comment]
The work in the [linked PR](https://github.com/cypress-io/cypress-documentation/pull/5327) is being considered if it will be incorporated into the work done with this PR: https://github.com/cypress-io/cypress-documentation/pull/5348
