### ISSUE TITLE
No Chai

### ISSUE THREAD

**Issue by arizonatribe** [cypress-io/cypress-documentation#531]
I've gone through the docs and I see no mention of this, so perhaps someone might have an answer: can you use Cypress without having to use Chai for assertions? I have an irrationally high amount of distaste for Chai assertions and [it's deep chains of dotted paths](https://haacked.com/archive/2009/07/14/law-of-demeter-dot-counting.aspx/), and I was very happy when Jasmine moved away from that style of API a few years ago. Is it possible to just install a better assertion library and use that instead?

**Comment by jennifer-shehane** [comment]
Nicholas Boll wrote a blog around using Jest matchers to replace Mocha. I haven't personally tried this and it's not really something that Cypress is looking to support nor document at the moment, but you could give that a try to replace it with what you want. https://medium.com/@NicholasBoll/using-jest-matchers-in-cypress-5e8e7281f5dd
