### ISSUE TITLE
lint commands dont match files and weirdness..

### ISSUE THREAD

**Issue by 0neMiss** [cypress-io/cypress-documentation#5325]
### Description

When i ran the lint commands I expected it to match files and lint the project. instead it said it cant find any files matching that pattern

### URL of Issue(s)

relates to a locally ran script

### Steps to replicate

1. Fork and Clone repo
2. `npm i`
3.  `npm run lint:markdown` or any of the lint related commands
4. receive below error
```
PS C:\Users\jorda\cypress-documentation> npm run lint

> cypress-docusaurus-ts@0.0.0 lint
> npm run lint:markdown


> cypress-docusaurus-ts@0.0.0 lint:markdown
> prettier --check '**/*.{md,mdx}'

Checking formatting...
[error] No files matching the pattern were found: "'**/*.{md,mdx}'".
All matched files use Prettier code style!
```

I was able to get the command to work by replacing
```json
"lint:markdown:fix": "prettier --write '**/*.{md,mdx}'",
```

with 

```json
 "lint:markdown:fix": "prettier --write **/*.{md,mdx}",
```
however after running `npm run lint-fix`  with the updated command I'm showing over 250 files of diff.
![image](https://github.com/cypress-io/cypress-documentation/assets/56180519/128f8d8a-0b63-4a76-a9e3-57b349299b85)

Even stranger, after checking what prettier had modified. I see no observable changes in any of the files. 

Curious if I should make a pr to fix these 4 commands

```json
{
     ...
     "lint": "npm run lint:markdown",
    "lint:fix": "npm run lint:markdown:fix",
    "lint:markdown": "prettier --check '**/*.{md,mdx}'",
    "lint:markdown:fix": "prettier --write '**/*.{md,mdx}'",
     ....  
 }
```

### Browser

N/A

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Some extra crap that might be useful if its not reproducable for everyone.

node and npm versions:
![image](https://github.com/cypress-io/cypress-documentation/assets/56180519/e2ae43b8-e9ca-42fc-bc5c-a71b1e8fbb0d)

OS:
![image](https://github.com/cypress-io/cypress-documentation/assets/56180519/19d1eca2-7d6a-4aee-8830-64c12a023a1e)

**Comment by MikeMcC399** [comment]
@0neMiss 

The `prettier` linting under Windows is awkward and the changes it makes are whitespace changes only if you run it on the unchanged `main` branch.

The restrictions of running lint under Windows should probably be mentioned in the [CONTRIBUTING](https://github.com/cypress-io/cypress-documentation/blob/main/CONTRIBUTING.md) guide.

I personally use Ubuntu if I need to run lint on the repo, where it works fine.

I do not see the issue on Windows that no files are found by `npm run lint` when I use a `git bash` terminal window. Which type of terminal window were you using?

**Comment by 0neMiss** [comment]
Thats what I ended up doing as well. Just pointing prettier to write the file I edited specifically. 

Not sure why its behaving this way on my machine, even looking at the docs of powershell it seems like this should be working.

![image](https://github.com/cypress-io/cypress-documentation/assets/56180519/b288720c-2b16-4c7b-ae5c-73ebf6d62a59)

I'm good to close this out pending the potential update to the contributing guide. I feel like it might be good to have a section on lint commands and this behavior it has on non POSIX compatible operating systems.

**Comment by mike-plummer** [comment]
@0neMiss Since we don't have a specific recommendation to add to the CONTRIBUTING guide here, and the fact that the majority of our contributors are on POSIX systems, I'm going to close this out. If you do figure out what was going on with your Powershell setup I'm happy to reopen and consider adding a hint to the guide
