### ISSUE TITLE
Bug: Sidebar Nav does not always show items

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress-documentation#5326]
Bug in docusaurs, or our config? Note that after a bunch of click/refreshing, the items under "integrations" do not show up.

https://github.com/cypress-io/cypress-documentation/assets/19196536/1ec08d1d-ed52-4616-be9e-be7182567e2c

**Comment by elylucas** [comment]
I see it in your video, but haven't been able to reproduce it myself. Are there certain steps to reproduce it or is it random?

**Comment by lmiller1990** [comment]
Not sure - I think it's random / race condition.

**Comment by elylucas** [comment]
@lmiller1990 looks like you had reduced motion turned on, could you check again to see if it was fixed in #5370?

**Comment by lmiller1990** [comment]
Looks good!
