### ISSUE TITLE
Can I override ignoreTestFiles by passing a --config flag? 

### ISSUE THREAD

**Issue by ValerieThoma** [cypress-io/cypress-documentation#535]
**Guides > Configuration >  Global** 
After setting `ignoreTestFiles` to a string or array of glob patterns in `cypress.json`
**Guides > Configuration > Overriding Options > Command Line** ostensibly suggests that 
passing a `--config` flag would/could override `cypress.json` by passing arguments directly to `ignoreTestFiles` from the CLI. 

This does not seem to work, however, I feel like it should. If this is not a utility of the option, we should explicitly document it.

**Comment by jennifer-shehane** [comment]
Did you try to test this behavior to ensure it doesn't work from the CLI?

**Comment by ValerieThoma** [comment]
Yes

**Comment by aboyer1013** [comment]
@ValerieThoma I was the user from the Gitter post. I can confirm this didn't work as expected. However, perhaps the question is like you pointed out, if the expectation was incorrect to begin with.

**Comment by jtwite** [comment]
@ValerieThoma I work with @aboyer1013 and we have also tried passing it in via the cypress module api, which doesn't seem to work either.  Also, thank you for looking into this!

**Comment by xvyslo05** [comment]
Any progress or ETA to Cypress on this thread?

**Comment by jennifer-shehane** [comment]
No, I'd suggest tracking this issue for any fixes https://github.com/cypress-io/cypress/issues/1696
