### ISSUE TITLE
Link to Cloud notifications troubleshooting fails

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5364]
### Description

When I click on the link [Troubleshoot](https://on.cypress.io/notifications-troubleshooting) in the Cypress app "Desktop notifications" section 

"Not receiving notifications? You might need to allow notifications from Cypress in your computer's system preferences. [Troubleshoot](https://on.cypress.io/notifications-troubleshooting)"

it shows  "404 Page Not Found"

### URL of Issue(s)

https://on.cypress.io/notifications-troubleshooting

### Steps to replicate

`npx cypress open` on Ubuntu
Settings > Device Settings > Desktop notifications
Click on Troubleshooting link

https://docs.cypress.io/guides/cloud/cypress-app-integration#Troubleshooting

404 Page Not Found

### Browser

Chrome 114

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

![notifications troubleshoot](https://github.com/cypress-io/cypress-documentation/assets/66998419/e05499ca-c20a-427f-b9b4-cf2b62f3c3b0)

links to https://on.cypress.io/notifications-troubleshooting

which forwards to
https://docs.cypress.io/guides/cloud/cypress-app-integration#Troubleshooting

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/aa7af713-4af0-4031-8ac6-887c353a7d69)

Possibly this should be forwarding to
https://docs.cypress.io/guides/cloud/recorded-runs#Troubleshooting-Notifications instead?

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/5fda8d01-e86d-415b-8799-c24443d439c3)

**Comment by elylucas** [comment]
Have a [PR](https://github.com/cypress-io/cypress-services/pull/6028) (private repo) in to update the onlink to the correct part in the docs

**Comment by elylucas** [comment]
This is resolving to the correct place now.
