### ISSUE TITLE
Document global hooks running from support file

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#537]
You can define your `cy.route()` definitions in a `beforeEach` within any of the `cypress/support` files:
```
beforeEach(function () {
  cy.log("I run before every test in every spec file!!!!!!")
})
```

<img width="662" alt="screen-shot-2018-04-13-at-12 38 36-pm" src="https://user-images.githubusercontent.com/1271364/38949944-03f8d620-4312-11e8-9628-7995d4285a93.png">

**Comment by jennifer-shehane** [comment]
```
  before(function() {
    // runs once before all tests in the block
  })

  after(function() {
    // runs once after all tests in the block
  })

  beforeEach(function() {
    // runs before each test in the block
  })

  afterEach(function() {
    // runs after each test in the block
  })
```

**Comment by jennifer-shehane** [comment]
Caveat being that setting things in global hooks will make it less flexible for changes later or testing the behavior of that thing later.

**Comment by mightyiam** [comment]
Where are they documented, please?
