### ISSUE TITLE
cy.request throws Client network socket disconnected before secure TLS connection was established for TLS 1.2

### ISSUE THREAD

**Issue by taufiqpirjade** [cypress-io/cypress-documentation#5398]
### Description

When i doing cy.request to API which is having TLS1.2 then i getting the [11:23 AM] Redkar, Krunal  Error: Client network socket disconnected before secure TLS connection was established

### URL of Issue(s)

https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Seeding-data

### Steps to replicate

2. Click on '...'
3. Scroll down to '...'

### Browser

Headless

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by MikeMcC399** [comment]
@taufiqpirjade 

This doesn't look like it is an issue with the Cypress documentation.

You may be able to get some help from the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button)
