### ISSUE TITLE
CT Supported Frameworks with wildcard "+" version

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5412]
### Subject

Component Testing > Overview > Supported Frameworks

### Description

[Supported Frameworks](https://docs.cypress.io/guides/component-testing/overview#Supported-Frameworks) lists framework versions with a base version and a "+" to indicate later versions. 

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/345be5d5-c487-4f7b-9dfc-7498d33123d9)

This is not consistent with the way that Cypress detects frameworks, which works on discrete versions, rather than minimum versions.

~~For instance, Svelte with Vite lists `Svelte 3+`, which implies also Svelte 4, however Cypress `12.17.3` displays a message saying that svelte `4.1.2` is not supported.~~ Edit: Outdated comment, since Svelte 4 is now supported. The general problem raised is however still relevant.

![image](https://github.com/cypress-io/cypress/assets/66998419/b517749d-bdfb-47ea-ae37-5fe2788f0192)

The version list should be aligned to the way that Cypress determines which framework versions are supported. If there is a minimum and maximum version permitted, then this should be listed in the table.

Currently the table is misleading.

**Comment by MikeMcC399** [comment]
Cypress source code [packages/scaffold-config/src/dependencies.ts](https://github.com/cypress-io/cypress/blob/develop/packages/scaffold-config/src/dependencies.ts) is related to the framework dependencies which are supported.

**Comment by jordanpowell88** [comment]
Are you proposing we document the versions differently? If so, what do you suggest?

**Comment by MikeMcC399** [comment]
@jordanpowell88 

The suggestion would be to replace the "+" notation with version ranges, for example

Create React App 4+ | React 16+ | Webpack 4+

would become

Create React App 4-5  | React 16-18 | Webpack 4-5

so that the table mirrors the versions which the Cypress app displays during scaffolding.

Svelte 3+ would be changed to Svelte 3 and when 4 is supported it would be changed to Svelte 3-4.

**Comment by MikeMcC399** [comment]
The table, with no upper bound for supported versions, continues to be misleading as new frameworks are released without Cypress providing support.

Currently the following issues are requesting updated support:

- https://github.com/cypress-io/cypress/issues/28347
- https://github.com/cypress-io/cypress/issues/28185
