### ISSUE TITLE
Generate reports of specs run through "cypress open" app

### ISSUE THREAD

**Issue by Subru92** [cypress-io/cypress-documentation#5423]
### Description

Generate reports of specs run through "cypress open" app

### URL of Issue(s)

https://docs.cypress.io/guides/tooling/reporters#Examples

### Steps to replicate

2. Click on '...'
3. Scroll down to '...'

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

I have reporter (mochawesome) set in cypress.json.

The thing is that this reporter is generating report .json and html files only when i run tests with "cypress run" command.

Is there a way to get reports for tests run via Cypress gui app ("cypress open") after clicking each individual test?

**Comment by MikeMcC399** [comment]
@Subru92 

Unfortunately you are in the wrong place to get help for your question as this issue list is about correcting errors in the documentation.

You may like to reach out to the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button)

to discuss how to meet your needs.

**Comment by nagash77** [comment]
Sorry @Subru92 I do not understand your replication steps.  Can you please elaborate on what you are reporting to us?  It is unclear to me with what was provided.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
