### ISSUE TITLE
Conflicting information for minimum Chrome version 64 or 80

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5446]
### Subject

[Guides > Launching Browsers > Chrome Browsers](https://docs.cypress.io/guides/guides/launching-browsers#Chrome-Browsers)

### Description

In the section [Guides > Launching Browsers > Chrome Browsers](https://docs.cypress.io/guides/guides/launching-browsers#Chrome-Browsers) it states:

> All Chrome* flavored browsers will be detected and are supported above Chrome 64.

This contradicts the information in [Guides > Launching Browsers > Browser versions supported](https://docs.cypress.io/guides/guides/launching-browsers#Browser-versions-supported) in a previous section on the same page which says:

> Cypress supports the browser versions below:
>
> Chrome 80 and above.

The documentation is therefore inconsistent and should be changed to state the same minimum Chrome version in all places - either `64` or `80`.

---

In terms of how Cypress is actually operating:

https://github.com/cypress-io/cypress/blob/0f9a150647146c3e63e14d298d7fcf7ad5c92b66/packages/launcher/lib/known-browsers.ts#L3-L10 shows:

```ts
// Chrome started exposing CDP 1.3 in 64
export const MIN_CHROME_VERSION = 64

// Firefox started exposing CDP in 86
export const MIN_FIREFOX_VERSION = 86

// Edge switched to Blink in 79
export const MIN_EDGE_VERSION = 79
```

so it appears that a minimum version of Chrome `64` is enforced in Cypress `13.x`, not a minimum version of `80`.

**Comment by MikeMcC399** [comment]
- See also https://github.com/cypress-io/cypress-documentation/issues/5479 for related maximum version of Google Chrome `116` for older versions of Cypress.

**Comment by jennifer-shehane** [comment]
I feel like there is a restriction that doesn't allow it to function after Chrome 80 that was introduced in v10. I can't remember exactly what it was nor can I find it. I'm fine with 80 though.

Our previous strategy was to put the minimum version that Cypress will work - like we KNOW it breaks and doesn't function before that. 

If we want our strategy to be moreso - 'we will not support issues from these older browsers and work with you on it', then we could put a later Chrome version. Honestly the instances of issues I've seen on really old browsers feels pretty small, or nonexistent though....so I'm not sure this is an active problem.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- It's true that there is very little activity on older browsers, however the recent issue #5887 highlighted the confusion.

- I suggest to deprecate Chrome < 80 in the changelogs of the next release e.g. `13.14.0` and add that information consistently to the documentation.

**Comment by MikeMcC399** [comment]
- https://github.com/cypress-io/cypress-documentation/pull/5104#issuecomment-1614637130 provides an explanation about the different levels of support for Chrome 64 and Chrome >= 80

**Comment by jennifer-shehane** [comment]
Yes! There it is!
