### ISSUE TITLE
Fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by S-Tornqvist** [cypress-io/cypress-documentation#5452]
### Subject

Guides (CONTRIBUTING.md)

### Description

The sentence "If you make changes to an npm package that can't be published until the binary is also updated, you should make a pull request against specifying this is not be merged until the scheduled Cypress app release date." in file [CONTRIBUTING.md](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) is hard to understand because of incorrect grammar.

**Comment by MikeMcC399** [comment]
@S-Tornqvist 

This is about [CONTRIBUTING.md > Committing code](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#committing-code) in the https://github.com/cypress-io/cypress repo, so the issue should perhaps be moved there.

I would assume that there are some words missing in the sentence. Maybe it is trying to say something like the following?

 "If you make changes to an npm package that can't be published until the main Cypress binary is also updated, you should make a pull request against the `develop` branch specifying that the PR is not be merged until the scheduled Cypress app release date."

**Comment by S-Tornqvist** [comment]
Thanks for the feedback, @MikeMcC399. I was not able to create an issue of the proper type within the code repo, because only issues of types 🐛Bug report, ⬇️ Issue during install, ✨ Feature and ❄️ Flaky test in `cypress-io/cypress` repository are allowed. Would a work around be creating a bug report then changing the contents once posted?

**Comment by MikeMcC399** [comment]
@S-Tornqvist 

Your suggestion is what I have done in the past when I reported problems in the CONTRIBUTING.md file on the main repository. Use the bug report and modify it accordingly.
