### ISSUE TITLE
Add more detail to Contributing doc so users can easily contribute

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#55]
- [ ] Add section about testing the documentation (with Cypress)
- [ ] Explain process of adding a new page 
  - Adding to `sidebar.yml`
  - Adding translation to `en.yml`
  - Adding `{name}.md` file
  - Adding hexo

**Comment by richdouglasevans** [comment]
I just had to do all of these for a recent issue so I'm primed to do this one.

> The `Adding translation to en.yml` one stumped me for a bit so these docs would have been useful.

I'll pick it up and push a PR later unless `internal docs` means it's one for the core Cypress team only 😄

**Comment by richdouglasevans** [comment]
Is there anything else I can add to `CONTRIBUTING.md` ? Or can this ticket be `Closed`?

**Comment by jennifer-shehane** [comment]
Nope - looks good in terms of what this issue was asking for!
