### ISSUE TITLE
Add caching via Redis for external link validation

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#550]
Checking external links to be live in https://github.com/cypress-io/cypress-documentation/blob/3a2fc9629cd07f3bcb9673996911fca33cadebdf/lib/url_generator.js#L76 is slow. We should throw result of the check into external Redis with expiration, something like 1 day and reuse it. This will make local and CI documentation deploys faster

**Comment by brian-mann** [comment]
We should honestly just move this whole thing to another process altogether... there are already good systems out there for indexing / spidering all of the links to ensure none of them are broken. You can use node for that, JSDOM, etc...

**Comment by brian-mann** [comment]
This was kind of a hack / quick fix when I put it together a long time ago and we've largely outgrown it...

**Comment by bahmutov** [comment]
I think it is fine to do ourselves, we just have to use redis instead of local transient object.

**Comment by jennifer-shehane** [comment]
::@bahmutov goes off and publishes a new npm package for spidering links 😀::
