### ISSUE TITLE
Bug:Lot of grammatical errors in Contributing and code of conduct page.

### ISSUE THREAD

**Issue by abhisar-yadav** [cypress-io/cypress-documentation#5522]
### Subject

The contributing and code of conduct page have grammatical errors.

### Description

We need to update the Contributing and Code of Conduct page's content to remove all the typos in it

**Comment by abhisar-yadav** [comment]
I can fix this issue. please assign me this issue

**Comment by MikeMcC399** [comment]
@abhisar-yadav 

---
Are you referring to problems in [CONTRIBUTING.md](https://github.com/cypress-io/cypress-documentation/blob/main/CONTRIBUTING.md) in this repository?

Could you give an example of a grammatical error in this document?

---
The [CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress-documentation/blob/main/CODE_OF_CONDUCT.md) document in this repository is simply a link to [cypress-io/cypress > CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md) so I don't believe that there is anything that can be corrected in this repository. 

If you are referring instead to [cypress-io/cypress > CODE_OF_CONDUCT.md](https://github.com/cypress-io/cypress/blob/develop/CODE_OF_CONDUCT.md) could you also give an example of a grammatical error in that document?

**Comment by MikeMcC399** [comment]
- See https://github.com/cypress-io/cypress/pull/27988

**Comment by mschile** [comment]
Closing, as this issue pertains to the `cypress` repo not `cypress-documentation`. Will just use the [PR](https://github.com/cypress-io/cypress/pull/27988) in the `cypress` repo to represent the issue.
