### ISSUE TITLE
Specify lack of current support for Saucelabs / Browserstack

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#553]
- should update last line of 'Sauce Labs' section in General Questions
- should just add a question to FAQ asking about our support and say it does not currently work right now.

**Comment by ValerieThoma** [comment]
These lines already exist in the 'Sauce Labs' section of General Questions:
>Cypress’s API is written to be completely compatible with Sauce Labs, even though our API is not Selenium based at all. We will be offering better integration with Sauce Labs in the future.

Should this just be expounded on? Should this be moved to the final lines? 
I don't think we discussed in detail _what_ should be added, only that it need be explicitly understood that Sauce Labs integration was not currently available. 

I have submitted a WIP PR that requires some feedback. 
Thank you!

**Comment by ValerieThoma** [comment]
🙏perfected by @brian-mann, thank you!
