### ISSUE TITLE
"taskTimeout" is configurable per test but is not listed in the Test Configuration Options

### ISSUE THREAD

**Issue by hammzj** [cypress-io/cypress-documentation#5532]
### Subject

Guides

### Description

See this page: https://docs.cypress.io/guides/references/configuration#Test-Configuration

The `taskTimeout` is configurable per individual tests but is not listed as a configurable option in "Test Configuration".

## Examples
I have an example using the Cucumber preprocessor: https://github.com/hammzj/cypress-testing/tree/dev/cypress-issue/task-timeout-option

> Run `yarn cypress:cucumber:open`
>
> Run the feature named `tag.testing.feature`

<details>
<summary>Feature</summary>

<img width="1434" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/ab5e360b-800b-4809-94a6-95fd5af5041b">
</details>

<details>
<summary>Testrunner</summary>

<img width="1552" alt="Screenshot 2023-10-10 at 2 52 56 PM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/d9613df1-1354-4c6e-9df3-7b8eabf44125">
</details>

**Comment by jennifer-shehane** [comment]
@hammzj We're open to a pull request to update this.

**Comment by hammzj** [comment]
@jennifer-shehane Added
