### ISSUE TITLE
Still remaining in firefox: cypresserror: `cy.task()` must only be invoked from the spec file or support file.

### ISSUE THREAD

**Issue by wyattpuckett** [cypress-io/cypress-documentation#5533]
### Description

Same as https://github.com/cypress-io/cypress/issues/27099, I am seeing this error when executing tasks within my commands.js file, but only in firefox. Currently using 13.2, but has happened since 12.15

### URL of Issue(s)

NA

### Steps to replicate

1. Use cypress version 12.15 or higher
2. Have cy.task used within your commands.js file
3. Execute the test in firefox
4. Notice this error: cypresserror: `cy.task()` must only be invoked from the spec file or support file.

Example code from commands.js:
    cy.contains('Sign in').click()
    cy.task("generateOTP", 'example').then(token => {
        cy.get("element").type(token);
        cy.get('element').click()
      })

### Browser

Firefox 118.0.2

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by MikeMcC399** [comment]
@wyattpuckett 

The [cy.task() > Usage example](https://docs.cypress.io/api/commands/task#Usage) worked correctly for me on Cypress `13.2.0` and `13.3.0` running on Ubuntu 22.04 with Firefox 118 

```js
// in test
cy.task('log', 'This will be output to the terminal')
```

`cypress.config.js`

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message)

          return null
        },
      })
    },
  },
})
```

This is actually the issue list for documentation and as far as I can see, the documentation https://docs.cypress.io/api/commands/task is correct.

If you need to report a bug with Cypress itself, that would belong in the https://github.com/cypress-io/cypress/issues list.

**Comment by wyattpuckett** [comment]
Sounds good. My bad, didn't realize i had this in the documentation list
I'll dig in more to see what could be causing the issue, and if I find anything I'll get it over to the issues list
Thanks for the help
