### ISSUE TITLE
 AWS CodeBuild Cypress Cloud example stopped running in July 2023

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5538]
### Subject

Guides CI examples

### Description

The example [AWS CodeBuild recording to Cypress Cloud](https://github.com/cypress-io/cypress-realworld-app/blob/develop/buildspec.yml) from the [Cypress RWA](https://github.com/cypress-io/cypress-realworld-app) last ran on Jul 13, 2023.

- View the [Cypress Cloud project `zx15dm`](https://cloud.cypress.io/projects/zx15dm) to see the history and the last entry for the [AWS CodeBuild project](https://cloud.cypress.io/projects/zx15dm).

[Continuous Integration > CI Provider Examples > Guides](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples) lists the following live examples:

| Provider       | Link                                     | Last run     |
| -------------- | ---------------------------------------- | ------------ |
| CircleCI       | https://cloud.cypress.io/projects/7s5okt |Dec 7, 2023 |
| GitHub Actions | https://cloud.cypress.io/projects/tpys4j | Nov 14, 2023 |
|  AWS CodeBuild | https://cloud.cypress.io/projects/zx15dm | Jul 13, 2023 |

[Continuous Integration > CI Provider Examples > Guides > AWS CodeBuild](https://docs.cypress.io/guides/continuous-integration/ci-provider-examples#AWS-CodeBuild) shows the link:

[See AWS CodeBuild + Cypress Cloud in action](https://cloud.cypress.io/projects/zx15dm), linking to https://cloud.cypress.io/projects/zx15dm which last worked on Jul 13, 2023. 

## Suggestion

1. If the AWS CodeBuild recording to Cypress Cloud is supposed to still work then remedy the issue that it has stopped.
2. If it has been stopped on purpose, then remove the entry of this example from https://docs.cypress.io/guides/continuous-integration/ci-provider-examples

**Comment by MikeMcC399** [comment]
There has not been any feedback or resolution for this issue so far.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 We don't intend to continue supporting running the AWS CodeBuild

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> We don't intend to continue supporting running the AWS CodeBuild

Thank you for confirming that the AWS CodeBuild example has been deliberately disabled.

- PR #5644 proposes to remove the section in the documentation which refers to the now-inactive example.
