### ISSUE TITLE
Add example of Page Object Pattern in Selenium -> Cypress

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#554]
- Find a *simple* page object pattern example in Selenium (preferably with a simple html to map it to)
- Recreate their page objects into 'helper' functions in cypress (make sure to run it against the html
- Add the example to the FAQ question about page object patterns.

**Comment by bahmutov** [comment]
Good blog post we can include: https://medium.com/reactbrasil/deep-diving-pageobject-pattern-and-using-it-with-cypress-e60b9d7d0d91

also: my opinion and slides about Page Objects vs other ways of doing helper functions: https://slides.com/bahmutov/page-objects-in-cypress?token=xg8cPO4X
