### ISSUE TITLE
cy.intercept() and cy.visit()

### ISSUE THREAD

**Issue by mayinlu** [cypress-io/cypress-documentation#5549]
### Subject

cypress use

### Description

Hello, I am writing login logic using cypress. I used cy.request in beforeEach to obtain the token, and used cy.intercept to place the token in the authorization attribute of the header of all interfaces in test. test. com/api/* */*. Then I use cy.visit in it to request that the homepage product. product page has a default request to obtain data and load the product page. But these requests were all reported incorrectly. I checked that the header in Matched 'cy. intercept()' has authorization. But there is no authorization in the actual request headers. May I ask what I should do. thanks.

**Comment by jennifer-shehane** [comment]
Duplicate https://github.com/cypress-io/cypress-documentation/issues/5550
