### ISSUE TITLE
the commands added with Cypress.Commands.add are missing on the traceback

### ISSUE THREAD

**Issue by zodman** [cypress-io/cypress-documentation#5570]
### Description

I have a test with a lot of cypress commands, calling multiple times

### URL of Issue(s)

https://docs.cypress.io/api/cypress-api/custom-commands

### Steps to replicate

write multiple commands

command1, command2

create a test with repeated:

command1
command2
command1

if the command1 fail where the error comes ? from the first call or the second call?

the trace back only will tell you the command1 fail! 

to avoid this problem instead of using commands. convert my command to a function.

**Comment by jennifer-shehane** [comment]
@zodman This is the documentation repo. If you have an issue with Cypress, provide a reproducible example of code we can run in an issue in the cypress repo. https://github.com/cypress-io/cypress
