### ISSUE TITLE
Multiple linked external blog posts do not display

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5581]
### Subject

[Examples > Media > Blogs](https://docs.cypress.io/examples/media/blogs-media) 

### Description

[Examples > Media > Blogs](https://docs.cypress.io/examples/media/blogs-media) contains links to external blog posts which no longer display the original content. Instead, error messages are displayed.

There are currently 49 problematic links in the blog post list, for example:

- [Sanity Check Script](https://www.gerrypass.com/sanity-check-script) - Error 404 Page not found
- [My Thoughts on Cypress.io](https://watirmelon.blog/2019/07/06/my-thoughts-on-cypress-io/) - NET::ERR_CERT_COMMON_NAME_INVALID
- [Running Cypress tests with TestContainers for a Spring Boot with Thymeleaf application](https://wimdeblauwe.wordpress.com/2019/06/15/running-cypress-tests-with-testcontainers-for-a-spring-boot-with-thymeleaf-application/) - wimdeblauwe.wordpress.com is no longer available. The authors have deleted this site
- [FEXCO Technology Solutions](https://techblog.fexcofts.com/) - Error 403 - This web app is stopped.
- [Testing React app with Cypress](https://blog.callstack.io/testing-react-app-with-cypress-246a7732ee63) - Web server is down Error code 521

## Steps to reproduce

Go to [DeadLinkChecker.com](https://www.deadlinkchecker.com/) and check the single webpage https://docs.cypress.io/examples/media/blogs-media

## Suggestion

Review the problematic links in [Examples > Media > Blogs](https://docs.cypress.io/examples/media/blogs-media) and remove those which are permanently failing.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 We used to test for broken links but it became prohibitively slow and had a lot of false negatives with GitHub links.
