### ISSUE TITLE
Unused PR template

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5625]
### Description

When I opened a PR I expected the PR template to be used, however no PR template was presented.

### URL of Issue(s)

[.github/PULL_REQUEST_TEMPLATE/pull_request_template.md](https://github.com/cypress-io/cypress-documentation/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)

### Steps to replicate

1. Create a new branch
2. Create a commit in the new branch
3. Push the commit to the repo
4. Open a push request and note that no template is used. The body of the PR is blank.

### Additional Information

The PR template [.github/PULL_REQUEST_TEMPLATE/pull_request_template.md](https://github.com/cypress-io/cypress-documentation/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) is unused.

If it was intended to be the default PR template, then it is in the wrong place.

The template is not automatically used when it is placed in the [.github/PULL_REQUEST_TEMPLATE](https://github.com/cypress-io/cypress-documentation/blob/main/.github/) directory. It would need to be moved to the top level of the [.github](https://github.com/cypress-io/cypress-documentation/) directory to be automatically used. This is the way it works in the main [cypress-io/cypress > .github](https://github.com/cypress-io/cypress/tree/develop/.github) repo.

The directory [.github/PULL_REQUEST_TEMPLATE](https://github.com/cypress-io/cypress-documentation/blob/main/.github/) is only usable if additional GitHub Action workflows are defined which set up appropriate template query parameters. This has not been done for the [cypress-io/cypress-documentation](https://github.com/cypress-io/cypress-documentation/) repo.

#### Suggestion

1. Remove the [.github/PULL_REQUEST_TEMPLATE/pull_request_template.md](https://github.com/cypress-io/cypress-documentation/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) template OR
2. Move the [.github/PULL_REQUEST_TEMPLATE/pull_request_template.md](https://github.com/cypress-io/cypress-documentation/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) to the [.github](https://github.com/cypress-io/cypress-documentation/) AND
3. Review the template for up-to-date usefulness.

#### Reference

GitHub documentation

- [Building communities > Issue & PR templates > Pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates)

> You can store your pull request template in the repository's visible root directory, the docs folder, or the hidden .github directory.

- [Building communities > Issue & PR templates > Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

> You can create a PULL_REQUEST_TEMPLATE/ subdirectory in any of the supported folders to contain multiple pull request templates, **and use the template query parameter to specify the template that will fill the pull request body.**

**Comment by MikeMcC399** [comment]
My preference is to delete the template.

If there is a need to have a default PR template then I think it should be redesigned, taking account also of the preview provided by Netlify.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yah, I would delete this template. I'm not even sure where it came from. 

I'm not sure what we would need for a template in this repo besides `Closes #` and a Description. It's usually pretty self evident what the changes are for the docs changes.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Yah, I would delete this template. I'm not even sure where it came from.
> 
> I'm not sure what we would need for a template in this repo besides `Closes #` and a Description. It's usually pretty self evident what the changes are for the docs changes.

- Thank you very much for your feedback! I stumbled on this issue because the [.github/PULL_REQUEST_TEMPLATE/plugin_template.md](https://github.com/cypress-io/cypress-documentation/blob/main/.github/PULL_REQUEST_TEMPLATE/plugin_template.md) contains a bad link to the tutorial deleted in https://github.com/cypress-io/cypress-documentation/pull/5624. I was going to correct the link, then I realized that the templates in the directory [.github/PULL_REQUEST_TEMPLATE](https://github.com/cypress-io/cypress-documentation/blob/main/.github) were not being used, so there was not much to be gained by correcting the bad link.

I will submit a PR to delete the two templates in [.github/PULL_REQUEST_TEMPLATE](https://github.com/cypress-io/cypress-documentation/tree/main/.github/PULL_REQUEST_TEMPLATE) as neither of them can be used (apart from manually - but most people would not even look for them manually, let alone find them).
