### ISSUE TITLE
Dead anchor link in API cy.origin() to Trade-offs / Multiple tabs

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5685]
### Subject

API > Other Commands > origin

## Issue

On the page [API > Other Commands > origin](https://docs.cypress.io/api/commands/origin) the section [Other limitations](https://docs.cypress.io/api/commands/origin#Other-limitations) contains the statement:

> There are other testing scenarios which are not currently covered by `cy.origin()`:
>
> - It cannot run commands [in a different browser window](https://docs.cypress.io/guides/references/trade-offs#Multiple-browsers-open-at-the-same-time)
> - It cannot run commands [in a different browser tab](https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs)
> - It cannot run commands [inside an `<iframe>` element](https://docs.cypress.io/faq/questions/using-cypress-faq#How-do-I-test-elements-inside-an-iframe)
>
> However, `<iframe>` support is on [our roadmap](/guides/references/roadmap) for inclusion in a future version of Cypress.

The target link `/guides/references/trade-offs#Multiple-tabs` in the statement
> - It cannot run commands [in a different browser tab](https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs)

no longer exists.

- The [References > Trade-offs](https://docs.cypress.io/guides/references/trade-offs) section "Multiple tabs" was removed by https://github.com/cypress-io/cypress-documentation/pull/5565.

Note:

- This issue is also mentioned in https://github.com/cypress-io/cypress-documentation/issues/5630.

## Suggestion

Review the statement that `cy.origin()` cannot run commands in a different browser tab.

- If the statement is no longer true, then remove it and/or add information to explain how to use `cy.origin()` in a multiple tab environment.
- If the statement is still true, then provide an explanation or a link to further information.

cc: @chrisbreiding

**Comment by jennifer-shehane** [comment]
@MikeMcC399 The statement is true, I would just remove the link there.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 
> The statement is true, I would just remove the link there.

Thank you for your advice. I'll submit a PR to implement your suggestion.
