### ISSUE TITLE
Code blocks are unreadable in Chrome 122.0.6261.94 

### ISSUE THREAD

**Issue by illegalnumbers** [cypress-io/cypress-documentation#5733]
### Description

When viewing documentation I expect code blocks to be readable

### URL of Issue(s)

https://docs.cypress.io (any) for instance https://docs.cypress.io/guides/references/configuration

### Steps to replicate

1. Go to https://docs.cypress.io/guides/references/configuration
2. See code blocks like attached
![Screenshot 2024-02-29 at 12 25 39 PM](https://github.com/cypress-io/cypress-documentation/assets/618650/78bb4268-8cb9-4d46-99b9-28000ccdda21)

### Browser

Chrome 122

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Ventura 13.6.2

**Comment by illegalnumbers** [comment]
Yes I have tried incognito, with all extensions removed, etc

**Comment by MikeMcC399** [comment]
@illegalnumbers 

I wonder what is wrong as I'm not seeing your problem. The code blocks are displaying correctly for me with Chrome 122 on Ubuntu 22.04 and Windows 11. I don't have macOS to try on though.

![config](https://github.com/cypress-io/cypress-documentation/assets/66998419/7ed0707f-baa4-4958-b2f5-efb0d215d01f)

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/115a3086-858b-477c-af2c-a12b4938bff7)


Have you been able to try on another system or with another browser?

**Comment by illegalnumbers** [comment]
Yea, firefox worked which was bizarre

**Comment by illegalnumbers** [comment]
I am in dark mode if that makes any difference? not sure why it would

**Comment by MikeMcC399** [comment]
@illegalnumbers 

You might want to try uninstalling and reinstalling Google Chrome. Since nobody else has reported this, it sounds like it's an issue on your machine only.

**Comment by jennifer-shehane** [comment]
We have a `"Fira Code", monospace` font here, so it should fall back to monospace at the minimum. But yah, this looks like a system issue of some kind as I don't see this on Chrome 122 either.

**Comment by illegalnumbers** [comment]
yea resetting all fonts seems to fix it but the fallback clearly didnt happen

**Comment by illegalnumbers** [comment]
i'm surprised firefox worked considering its the same font system

**Comment by illegalnumbers** [comment]
w/e
