### ISSUE TITLE
Misleading argument description in .should('have.been.calledWith', ['arg1, 'arg2'])

### ISSUE THREAD

**Issue by t-benze** [cypress-io/cypress-documentation#5736]
### Subject

guides/references/assertions

### Description

![Screenshot 2024-03-02 181146](https://github.com/cypress-io/cypress-documentation/assets/4394426/81c9a6ed-f427-496c-9012-b66daaa28b6a)

https://docs.cypress.io/guides/references/assertions#Sinon-Chai

The current document states that the arguments should be passed in as an array, while the actual behavior expects a list of arguments.

For example, the following assertion will fail when running the test.

```js
        //wrong assertion with array
        cy.get('@open').should('have.been.calledOnceWithExactly', [
           `${Cypress.config('baseUrl')}/?space=e7bf21ca`,
           `inkstain-e7bf21ca`,
         ]);
```

Changing to argument list will pass.

```ts
        cy.get('@open').should(
          'have.been.calledOnceWithExactly',
          `${Cypress.config('baseUrl')}/?space=e7bf21ca`,
          `inkstain-e7bf21ca`
        );
```

**Comment by jennifer-shehane** [comment]
@t-benze We're open to a pull request to clarify this.

**Comment by t-benze** [comment]
hi @jennifer-shehane i've created a pull request regarding this issue, thanks.
