### ISSUE TITLE
Workflow failures executing "Try it out" for GitHub Actions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5754]
### Subject

[Continuous Integration > GitHub Actions > Basic Setup](https://docs.cypress.io/app/continuous-integration/github-actions#Basic-Setup)

## Issue

[Continuous Integration > GitHub Actions > Basic Setup](https://docs.cypress.io/app/continuous-integration/github-actions#Basic-Setup) advises to "Try it out".

Depending on whether the new suggested workflow `main.yml` is added through a push or via a PR to the `master` branch, the action results in 3 failures from existing workflows (for push) or 16 failed checks (for PR). The added workflow itself works correctly.

The instructions are as follows:

> **Try it out**
>
>To try out the example above yourself, fork the [Cypress Kitchen Sink](https://github.com/cypress-io/cypress-example-kitchensink) example project and place the above GitHub Action configuration in a newly created `main.yml` file within `.github/workflows/`.

### Create `main.yml` in master

1. Open https://github.com/cypress-io/cypress-example-kitchensink in web browser
1. Select Fork > Create a new fork
1. Take defaults, select "Create fork"
1. Select Add file > Create a new file
1. Name your file `.github/workflows/main.yml`.
1. Paste in contents of workflow from https://docs.cypress.io/guides/continuous-integration/github-actions#Basic-Setup
1. Click on Commit changes...
1. Take defaults (Commit directly to the master branch)
1. Click "Commit changes"

6 workflows run. 3 workflows succeed, 3 workflows fail. The failures are:

- Using Cypress GH Action
- Cypress parallel tests
- Cypress single tests

Select Actions > Cypress Tests > ... menu Disable workflow

### Create `main2.yml` in master

1. Select `<> Code`
1. Select Add file > Create a new file
1. Name your file `.github/workflows/main2.yml`.
1. Paste in contents of workflow from https://docs.cypress.io/guides/continuous-integration/github-actions#Basic-Setup
1. Change the name to "Cypress Tests 2"
1. Click on Commit changes...
1. Select "Create a new branch for this commit and start a pull request"
1. Take the default name for the new branch
1. Click "Propose changes"
1. Click "Create pull request"
1. Click "Create pull request"
1. Note the message "Some checks were not successful"
1. Wait until all checks have completed

16 failing and 5 successful checks are reported

In addition to the workflows which fail on push to `master` (see above), the following PR workflows also fail:

- Add issue/PR to Triage Board
- Semantic Pull Request

## Suggestion

1. [x] Temporarily remove the **Try it out** instructions [Continuous Integration > GitHub Actions > Basic Setup](https://docs.cypress.io/guides/continuous-integration/github-actions#Basic-Setup)
2. [x] Open one or more related issues in [Cypress Kitchen Sink](https://github.com/cypress-io/cypress-example-kitchensink) to address the workflow failures
3. [ ] Replace the **Try it out** instructions when the issues in the [Cypress Kitchen Sink](https://github.com/cypress-io/cypress-example-kitchensink) repo are resolved.

**Comment by MikeMcC399** [comment]
See the following issues for workarounds:

- https://github.com/cypress-io/cypress-example-kitchensink/issues/810
- https://github.com/cypress-io/cypress-example-kitchensink/issues/811

**Comment by jennifer-shehane** [comment]
These steps sounds fine.

**Comment by MikeMcC399** [comment]
- Step 1 addressed in PR #5777

**Comment by MikeMcC399** [comment]
Closing, as the documentation no longer says "Try it out"

The following issues are currently open:

- https://github.com/cypress-io/cypress-example-kitchensink/issues/810
- https://github.com/cypress-io/cypress-example-kitchensink/issues/811
