### ISSUE TITLE
macOS 10.9 too low for support

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5769]
### Subject

[Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System)

### Description

- This issue relates to one aspect of #5444.

## Issue

Currently [Getting Started > Installing Cypress > System requirements > Operating System](https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System) specifies macOS 10.9 as the minimum supported version for Cypress.

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/90d819b1-74df-4280-ad5d-1163f351134e)

macOS 10.9 is too low.

## Discussion

The [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) in the section [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades) states:

> Prebuilt binaries for macOS now require macOS 10.15 or later.

so a minimum of macOS 10.15 is required considering this aspect.

[macOS 10.15](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/) was however retired from GitHub runner images on Aug 30, 2022.

macOS 11 is available and deprecated on GitHub. According to [GitHub runner images announcements](https://github.com/actions/runner-images/issues?q=label%3AAnnouncement+is%3Aclosed): "2024 GitHub Actions macOS runner image roadmap" macOS 11 will be retired as a GitHub runner image in Q2 2024. So as far as GitHub runners are concerned, macOS 11 could still be used in the short term, even if deprecated.

Referring to https://endoflife.date/macos only the latest three releases of macOS are supported (currently macOS 12, 13 & 14), so according to this reference, macOS 12 would be the minimum version.

## Suggestion

macOS 10.9 must be replaced as minimum version.

Decide whether to specify "macOS 11" or "macOS 12" as the minimum version for Cypress.

It would also be possible to say "macOS 11 (deprecated), macOS 12 and above".

**Comment by MikeMcC399** [comment]
Since I'm not a macOS user I don't have the experience to judge what the best specification for macOS minimum version would be. If I can have some feedback and guidance then I can submit a PR to implement any decision.

**Comment by jennifer-shehane** [comment]
Updating the minimum seems fine to 10.9. Since it technically could not run with the right deps on the earlier ones.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Updating the minimum seems fine to 10.9. Since it technically could not run with the right deps on the earlier ones.

macOS 10.9 is the current minimum, so that would be making no change. 10.9 is however no longer viable.

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/fd6b7670-6e1f-4fc5-94d1-9d381f149f93)

**Comment by jennifer-shehane** [comment]
Sorry I think I mistyped, lots of numbers 😅 I meant 10.15

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I meant 10.15

You had me a little confused to begin with! I will update to simply "macOS 10.15 and above" in that case.

**Comment by MikeMcC399** [comment]
- Resolved by PR https://github.com/cypress-io/cypress-documentation/pull/5778
