### ISSUE TITLE
Docusaurus links scroll past heading

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#5771]
### Description

Looks like the docusaurus links are all cutting off headers when clicked.

### URL of Issue(s)

https://docs.cypress.io/guides/cloud/branch-review#__docusaurus_skipToContent_fallback

### Steps to replicate

 Examples and screenshots below:

- 
![CF777BCD-2702-4562-92A7-62AD0631DA74](https://github.com/cypress-io/cypress-documentation/assets/1271364/6f577228-5aa5-4b60-9d5b-3cdd2c039326)
![3DB7144E-F8DF-4117-BAE3-D13244FADF19](https://github.com/cypress-io/cypress-documentation/assets/1271364/2a98d00c-db57-4253-b77b-630e0e7e4893)
![3350D72F-C483-45DD-9306-CF18DCAD1AA9](https://github.com/cypress-io/cypress-documentation/assets/1271364/be5ede5c-073d-4441-9622-1cf9b7a39bec)

- https://docs.cypress.io/guides/cloud/integrations/source-control/github#__docusaurus_skipToContent_fallback

The direct hyperlinks all work fine, it's just the docusaurus ones that populate after searching for a term.

### Browser

Chrome

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by elevatebart** [comment]
**Precision/Context**: The way to access these URLs is through the algolia search adapter.

Cmd-K + Review
