### ISSUE TITLE
CT: cypress doesn't recognize "+" symbol in the path to the component

### ISSUE THREAD

**Issue by bobige** [cypress-io/cypress-documentation#5772]
### Description

Importing an angular component into a test file, when the component folder name starts with a "+" symbol, is not possible.

### URL of Issue(s)

https://docs.cypress.io/guides/references/error-messages#No-tests-found

### Steps to replicate

1. Create a new Angular 15 project.
2. Create a component in a folder that has the "+" sign in front of it
3. Create a basic test file for the component and just mount it.

### Browser

Google Chrome 119

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

I am configuring Cypress to test Angular 15 components. We have a naming convention to put the "+" sign in front of the folder name, containing the component files. When I mount the component, cypress gives a "No tests found" error, which according to the documentation could be caused by a syntax error.

It is easily reproduceable. Create a new Angular 15 project and create a component in a folder that has the "+" sign in front of it:

![image](https://github.com/cypress-io/cypress-documentation/assets/81616281/f4b8e892-0ada-414c-8e29-e3b5f2efa3c6)

If I remove the "+" sign or even change the naming to have a different special character, such as "_", it works:

![image](https://github.com/cypress-io/cypress-documentation/assets/81616281/d687c817-8e83-4967-b5eb-9915a016d709)

**Comment by Joao848846** [comment]
Could you share more information? As it stands, it's a bit strange to assert something because I've been using this "+" symbol mapping quite a lot on the platform where I work. It will depend on how it's mapped.

**Comment by bobige** [comment]
@Joao848846 What additional information do you need? It is a new Angular 15 project, in which you add the "+" symbol in front of the folder name of a component and that's it. Cypress doesn't detect the path to the test files and displays "No tests found", as seen in the screenshot. It's reproduceable.

**Comment by senpl** [comment]
Is it documentation issue or just cypress issue ???

**Comment by bobige** [comment]
> Is it documentation issue or just cypress issue ???

It's a cypress issue. I created it here by mistake, but I added the same issue in the other project as well [Link](https://github.com/cypress-io/cypress/issues/29493)

**Comment by jennifer-shehane** [comment]
Closing as duplicate
