### ISSUE TITLE
video for setup test is missing

### ISSUE THREAD

**Issue by warjiang** [cypress-io/cypress-documentation#5782]
### Description

When I  visited document on website expected watching the video of how to setupping the cypress to happen but cannot watch it happened everytime you visited the website

### URL of Issue(s)

https://docs.cypress.io/guides/overview/why-cypress#Setting-up-tests

### Steps to replicate

1. Go to 'https://docs.cypress.io/guides/overview/why-cypress#Setting-up-tests'
2. Open the chrome developer tool
3. See error 'GET https://docs.cypress.io/img/snippets/installing-cli.mp4 net::ERR_ABORTED 404 (Not Found)'

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

![image](https://github.com/cypress-io/cypress-documentation/assets/6478745/fe026115-8cd6-492d-8ebd-e68453df2f3a)

**Comment by MikeMcC399** [comment]
@warjiang 

Thanks for reporting this issue!

- The video was outdated and removed by PR https://github.com/cypress-io/cypress-documentation/pull/5738. Unfortunately the link on the page you reported was overlooked. I will submit an additional PR to remove the link from the section https://docs.cypress.io/guides/overview/why-cypress#Setting-up-tests as well.

Is there anything you need help with to set up tests? or did you just want to report the link failure?

**Comment by MikeMcC399** [comment]
Details of how to proceed can be found on the following pages:

- [End-to-end tests](https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test) or
- [Component tests](https://docs.cypress.io/guides/component-testing/getting-started)

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress-documentation/pull/5783 corrects this issue.

**Comment by warjiang** [comment]
> Details of how to proceed can be found on the following pages:
> 
> * [End-to-end tests](https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test) or
> * [Component tests](https://docs.cypress.io/guides/component-testing/getting-started)

thanks for your reply and suggestions, after the pr merged, the website worked, thanks~
