### ISSUE TITLE
Misaligned cypress cache list tables in CLI guide

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5788]
### Description

The cache tables are displayed misaligned

### URL of Issue(s)

~~https://docs.cypress.io/guides/guides/command-line#cypress-cache-list~~ moved to https://docs.cypress.io/app/references/command-line#cypress-cache-list

### Steps to replicate

Open ~~https://docs.cypress.io/guides/guides/command-line#cypress-cache-list~~ https://docs.cypress.io/app/references/command-line#cypress-cache-list

View the tables
- cypress cache list
- cypress cache list --size

![image](https://github.com/cypress-io/cypress-documentation/assets/66998419/1ec99278-3336-46f5-b525-4100223f4d87)

### Browser

Chrome 123, Firefox 124

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by jennifer-shehane** [comment]
Yah, probably changed the styling at some point and didn't realized this all becomes unaligned.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Yah, probably changed the styling at some point and didn't realized this all becomes unaligned.

- The problem seems to have been introduced by PR https://github.com/cypress-io/cypress-documentation/pull/4590 from Jan 2023.
- https://web.archive.org/web/20221219090325/https://docs.cypress.io/guides/guides/command-line shows an archived page from Dec 19, 2022 displaying aligned cache tables. The next time the page was archived to https://web.archive.org/web/20230119130903/https://docs.cypress.io/guides/guides/command-line on Jan 19, 2023, the table formatting was broken.
