### ISSUE TITLE
Code coverage for swc projects — especially for next.js >=14

### ISSUE THREAD

**Issue by henrikvolmer** [cypress-io/cypress-documentation#5801]
### Subject

examples

### Description

Unfortunately, there is currently no example to integrate Cypress code coverage for next.js with swc. 

Unfortunately, next.js no longer supports the babel build (there's an open issue for server actions https://github.com/vercel/next.js/issues/57966). In order to continue using Cypress, we need a solution for swc projects.

Thanks in advance.

**Comment by MikeMcC399** [comment]
@henrikvolmer 

- This looks like a reference to the open feature request https://github.com/cypress-io/code-coverage/issues/583

**Comment by henrikvolmer** [comment]
@MikeMcC399 : This is true, but the problem has been open for 2 years. In my opinion, Cypress should give us a solution to this problem since next.js and swc are not that unpopular.
