### ISSUE TITLE
Package 'libasound2' has no installation candidate on Ubuntu 24.04

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5816]
### Subject

[Getting Started > Installing Cypress > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites)

### Issue

Following the instructions [Getting Started > Installing Cypress > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) on Ubuntu `24.04` (Noble Numbat) LTS for package installation:

> apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

results in the error:

> E: Package 'libasound2' has no installation candidate

### Steps to reproduce

Clean install [Ubuntu 24.04](https://releases.ubuntu.com/noble/) using a Desktop image and complete setup.

Open a terminal window and execute:

```shell
sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

### Logs

```text
$ sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libgtk2.0-0t64' instead of 'libgtk2.0-0'
Note, selecting 'libgtk-3-0t64' instead of 'libgtk-3-0'
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
You should explicitly select one to install.

E: Package 'libasound2' has no installation candidate
```

### Background

According to the [Ubuntu 24.04 release notes](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890) in the section [Year 2038 support for the armhf architecture](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#year-2038-support-for-the-armhf-architecture-5)

> More than a thousand packages have been updated to handle time using a 64-bit value rather than a 32-bit one, making it possible to handle times up to 292 billion years in the future.

Ubuntu package references show the following

- [Ubuntu alsa-lib package overview](https://launchpad.net/ubuntu/+source/alsa-lib) shows [libasound2t64](https://launchpad.net/ubuntu/noble/+package/libasound2t64): "shared library for ALSA applications"
- [Ubuntu gtk+2.0 package overview](https://launchpad.net/ubuntu/+source/gtk+2.0) shows [libgtk2.0-0t64](https://launchpad.net/ubuntu/noble/+package/libgtk2.0-0t64): "GTK graphical user interface library - old version"
- [Ubuntu gtk+3.0 package overview](https://launchpad.net/ubuntu/+source/gtk+3.0) shows [libgtk-3-0t64](https://launchpad.net/ubuntu/noble/+package/libgtk-3-0t64): "GTK graphical user interface library"

## Suggestion

For Ubuntu `24.04` make the following changes

| Package    | Ubuntu < `24.04` | Ubuntu >= `24.04` |
| ---------- | ---------------- | ----------------- |
| `alsa-lib` | `libasound2`     | `libasound2t64`   |
| `gtk+2.0`  | `libgtk2.0-0`    | `libgtk2.0-0t64`  |
| `gtk+3.0`  | `libgtk-3-0`     | `libgtk-3-0t64`   |

The command for Ubuntu `24.04` and above, listed on [Getting Started > Installing Cypress > Linux Prerequisites > Ubuntu/Debian](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites), would then be:

```shell
apt-get install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
```

## References

- [Ubuntu wiki > List of releases](https://wiki.ubuntu.com/Releases)
- [Ubuntu 24.04 release notes](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890)
- [Ubuntu alsa-lib package overview](https://launchpad.net/ubuntu/+source/alsa-lib)
- [Ubuntu gtk+2.0 package overview](https://launchpad.net/ubuntu/+source/gtk+2.0)
- [Ubuntu gtk+3.0 package overview](https://launchpad.net/ubuntu/+source/gtk+3.0)

**Comment by ermarkar** [comment]
i am using heroku and on migarting heroku to heroku-24 i am getting the same!!

**Comment by ermarkar** [comment]
for heroku 

To fix the issue, update your Aptfile to replace libasound2 and libasound2-dev with libasound2t64
