### ISSUE TITLE
Remove centOS 7 references

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5859]
### Subject

Guides

### What would you like?

Review and remove references to unsupported CentOS Linux 7.

- https://docs.cypress.io/guides/cloud/test-replay#Troubleshooting
- https://docs.cypress.io/guides/getting-started/installing-cypress#CentOS

### Why is this needed?

Open source community support has now ceased:

https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

> **CentOS Linux 7 End of Life: June 30, 2024**
>
> RHEL 7 reaches [End of Maintance on June 30, 2024](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates). After June 30, 2024, there will be no updates published for CentOS Linux 7.

**Comment by MikeMcC399** [comment]
Possibly references to CentOS should be replaced by references to CentOS Stream? Or perhaps it would be better to focus on Fedora and/or RHEL?

Fedora, CentOS Stream and RHEL are interrelated, see [What's Great About CentOS Stream](https://blog.centos.org/2021/12/introducing-centos-stream-9/).

**Comment by MikeMcC399** [comment]
Just as a rough guide to how often each Linux OS is mentioned, here is the result from a search of open issues on https://github.com/cypress-io/cypress/issues:

| OS           | Number |
| ------------ | ------ |
| Linux        | 172    |
| Ubuntu       | 146    |
| Debian       | 36     |
| Arch Linux   | 14     |
| CentOS       | 6      |
| Fedora       | 5      |
| RHEL         | 4      |
| Alpine Linux | 6      |
| Amazon Linux | 1      |
| FreeBSD      | 1      |
| suse         | 0      |

**Comment by jennifer-shehane** [comment]
Yah i haven't seen this centos issue reported in a while. It used to come up a LOT which necessitated adding it to the docs. It's likely ok to remove?

**Comment by MikeMcC399** [comment]
Submitted the following two PRs for removal:

- #5860 - centOS Stream 9 works out of the box with Cypress, so it's not necessary to specify any additional packages to install
- #5861 - the troubleshooting steps only reference CentOS 7 and 8, and both these versions are now unsupported

**Comment by MikeMcC399** [comment]
Resolved
