### ISSUE TITLE
Outdated workshop entries with legacy Cypress versions

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5864]
### Subject

[Examples > Workshops](https://docs.cypress.io/examples/workshop) 

#### Issue

The [Examples > Workshops](https://docs.cypress.io/examples/workshop) page contains 2 outdated workshops:

##### End-to-end Testing with Cypress.io

[Examples > Workshops > End-to-end Testing with Cypress.io](https://docs.cypress.io/examples/workshop#End-to-end-Testing-with-Cypressio)

- The Cypress version used is the legacy Cypress `7.6.0` version
- The associated repository https://github.com/cypress-io/testing-workshop-cypress is archived.

##### ReactJSDay 2019 Testing Course

[Examples > Workshops > ReactJSDay 2019 Testing Course](https://docs.cypress.io/examples/workshop#ReactJSDay-2019-Testing-Course)

- The Cypress version used is the legacy Cypress `5.6.0` version
- The associated repository https://github.com/NoriSte/reactjsday-2019-testing-course was last updated 4 years ago.

#### Suggestion

Consider removing both the above workshops as they use legacy Cypress version [7.6.0](https://docs.cypress.io/guides/references/changelog#7-6-0), released on June 23, 2021 and legacy Cypress version [5.6.0](https://docs.cypress.io/guides/references/changelog#5-6-0), released on November 9, 2020.

**Comment by jennifer-shehane** [comment]
I'm fine with removing both

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress-documentation/pull/5865 submitted to update the page
