### ISSUE TITLE
Debian 10 (Buster) end-of-life June 30, 2024

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5879]
### Subject

https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System

### Description

The supported Linux operating systems are currently listed as:

> Linux Ubuntu 20.04 and above, Fedora 38 and above, and Debian 10 and above (x64 or arm64)

According to https://wiki.debian.org/LTS Debian 10 "Buster" reached End of Life on June 30, 2024. Node.js also has a policy not to support operating systems which are no longer supported by their vendor.

### Suggestion

Update the minimum supported Debian release to `11` (Bullseye). See https://wiki.debian.org/LTS.

**Comment by MikeMcC399** [comment]
- For this issue I also plan to submit a PR (probably combined with https://github.com/cypress-io/cypress-documentation/issues/5878).

**Comment by jennifer-shehane** [comment]
@MikeMcC399 How do you keep up with all these EOL dates? Are you just manually checking all the links? I've found it difficult to manage with so many technologies involved.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> How do you keep up with all these EOL dates? Are you just manually checking all the links? I've found it difficult to manage with so many technologies involved.

I just happened to notice this when I was looking up some `glibc` information. I'm not methodically tracking it, but given that I stumbled across it I thought it was worthwhile to put it right! 😃

**Comment by MikeMcC399** [comment]
- Resolved through PR #5883
