### ISSUE TITLE
cy.intercept history table is malformed

### ISSUE THREAD

**Issue by CoryDanielson** [cypress-io/cypress-documentation#5924]
### Description

When I view the intercept history (bottom of page), I expect to see a table of changes, but instead see malformed markdown and text.

### URL of Issue(s)

https://docs.cypress.io/api/commands/intercept#History

### Steps to replicate

1. Go to [Intercept#history](https://docs.cypress.io/api/commands/intercept#History)
2. See malformed markdown table

### Browser

Chrome 128

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

![Screenshot 2024-09-10 at 4 38 23 PM](https://github.com/user-attachments/assets/94bac23b-b73b-4bde-9f15-ca75ef109f0a)

**Comment by mschile** [comment]
Hi @CoryDanielson 👋, thanks for bringing this to our attention! The [cy.intercept history](https://docs.cypress.io/api/commands/intercept#History) table should be rendering correctly now.
