### ISSUE TITLE
Cypress + Vite 5 + Typescript: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by NormalCrazy000** [cypress-io/cypress-documentation#5940]
### Description

When I try to start cypress in a vite 5 project with typescript the console returns this error: 
![Screenshot 2024-09-28 231716](https://github.com/user-attachments/assets/095b0ba5-db10-4416-90b5-22a1f26f0ddc)
 I think it is due to cypress having problems with the tsconfig.json structure created by vite.

### URL of Issue(s)

https://github.com/NormalCrazy000/vite5-Cypress.git

### Steps to replicate

1. npm install
2. npx cypress open

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by NormalCrazy000** [comment]
I moved bug repo to the cypress repository

**Comment by vikiboss** [comment]
It happened to me, too. It seems to be caused by this line of code:

```jsonc
// package.json
{
  // ...
  "type": "module"
  // ...
}
```

**Comment by MikeMcC399** [comment]
See
- https://github.com/cypress-io/cypress/issues/30313 for workaround
- https://github.com/cypress-io/cypress/issues/27359
