### ISSUE TITLE
Remove deprecated plugins

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5946]
### Subject

[Plugins](https://docs.cypress.io/plugins)

### Description

Remove deprecated plugins from [Plugins](https://docs.cypress.io/plugins)

- which are based on repos which have been archived or which are otherwise declared as unsupported
- which support only legacy versions of Cypress `v9` or lower
- which have not been updated since the release of Cypress `v10` in June 2022

#### Preprocessors

| Plugin                           | Status                                 |
| -------------------------------- | -------------------------------------- |
| cytorus                          | Archived Sep 3, 2024                   |
| cypress-app-watcher-preprocessor | Unmaintained. Last update Feb 2019     |
| cypress-eslint-preprocessor      | Unmaintained. Last update Nov 2018     |
| cy-rollup                        | Unmaintained. Cypress v8               |
| cypress-esbuild-preprocessor     | Unmaintained. Last update Oct 22, 2020 |

#### Development Tools

| Plugin                           | Status                   |
| -------------------------------- | ------------------------ |
| @cypress/instrument-cra          | Archived Jan 31,2023     |
| cypress-dark                     | Unmaintained. Cypress v8 |
| cypress-protobuf                 | Unmaintained. Cypress v4 |
| knapsack-pro-cypress             | Archived Jun 13, 2023    |
| cypress-autostub                 | Unmaintained. Cypress v4 |
| cypress-select-tests             | Archived May 28, 2021    |
| cypress-autorecord               | Unmaintained. Cypress v6 |
| @cypress/fiddle                  | Archived Feb 28, 2023    |
| cypress-extends                  | Unmaintained. Cypress v9 |
| @cypress/browserify-preprocessor | Archived Jan 31, 2023    |

#### Custom Commands

| Plugin                         | Status                   |
| ------------------------------ | ------------------------ |
| cypress-unfetch                | Unmaintained. Cypress v3 |
| cypress-redux                  | Unmaintained. Cypress v3 |
| cypress-pipe                   | Unmaintained. Cypress v4 |
| cypress-plugin-stripe-elements | Unmaintained. Cypress v8 |
| @cypress/skip-test             | Archived Jan 31, 2023    |
| cypress-websocket-testing      | Unmaintained. Cypress v3 |
| cypress-iframe                 | Unmaintained. Cypress v3 |
| cypress-rest-graphql           | Unmaintained. Cypress v7 |
| cypress-dotenv                 | Unmaintained. Cypress v8 |
| @cypress/xpath                 | package deprecated       |

#### Extending other testing frameworks

| Plugin               | Status                                        |
| -------------------- | --------------------------------------------- |
| cypress-capybara     | Archived Dec 13, 2022                         |
| cypress-jest-adapter | Unmaintained. Not compatible with Cypress v10 |

#### Authentication

| Plugin                    | Status                   |
| ------------------------- | ------------------------ |
| cypress-keycloak-commands | Unmaintained. Cypress v3 |
| cypress-otp               | Unmaintained. Cypress v5 |

#### Framework tooling

| Plugin                      | Status                   |
| --------------------------- | ------------------------ |
| @vue/cli-plugin-e2e-cypress | Unmaintained. Cypress v9 |
| elm-batteries               | Unmaintained. Cypress v8 |
| cypress-laravel             | Unmaintained. Cypress v3 |
| cypress-splitio             | Unmaintained. Cypress v5 |

#### Component testing

| Plugin                      | Status                   |
| --------------------------- | ------------------------ |
| cypress-nuxt                | Unmaintained. Cypress v4 |
| cypress-angularjs-unit-test | Unmaintained. Cypress v2 |
| cypress-cycle-unit-test     | Unmaintained. Cypress v3 |
| cypress-hyperapp-unit-test  | Unmaintained. Cypress v3 |
| cypress-svelte-unit-test    | Unmaintained. Cypress v6 |

#### Visual testing

| Plugin                   | Status                              |
| ------------------------ | ----------------------------------- |
| cypress-plugin-snapshots | Unmaintained. Last release Aug 2020 |

#### Reporting

| Plugin                   | Status                   |
| ------------------------ | ------------------------ |
| cypress-msteams-reporter | Unmaintained. Cypress v6 |
| cypress-log-to-output    | Unmaintained. Cypress v6 |

cc: @dingraham

**Comment by MikeMcC399** [comment]
The plugin list should be cleaned up to remove deprecated entries which are no longer relevant and helpful.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I agree and would welcome a PR for this.

Thank you for your confirmation! Purging legacy plugins from the listings seems to fit in with the work being done for Cypress 14 to remove outdated content and support.

- I have submitted PR #5948 to remove the outdated plugin list content.

**Comment by NoelDeMartin** [comment]
Hm you could have pinged me instead of removing my plugin by claiming that it is "unmaintained" 😅. It actually isn't... so I guess I'll have to submit it again. (@jennifer-shehane please, make sure to ping plugin maintainers when their plugins are removed from the directory).
