### ISSUE TITLE
Install cypress link doesn't work

### ISSUE THREAD

**Issue by nnaydenow** [cypress-io/cypress-documentation#5963]
### Description

When I click Installing cypress, the correct page to be opened. Instead of this page not found message is shown.

### URL of Issue(s)

https://www.cypress.io/

### Steps to replicate

1. https://www.cypress.io/
2. Hover Docs link
3. Click Installing cypress link
<img width="1019" alt="Screenshot 2024-10-24 at 12 12 40" src="https://github.com/user-attachments/assets/d9cf6a33-d09c-4dbe-8580-dd964e3d0a92">

### Device

- [ ] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

**Comment by jennifer-shehane** [comment]
Thanks, we just updated this, let me add a reroute
