### ISSUE TITLE
Why are my tests failing in CI and not locally?

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#597]
Write a doc about debugging this process: - add it to the FAQ maybe? 

- Watch the video - we have an amazing dashboard
- Look at screenshots
- Check the CI configuration and build process
- These were run in Electron and the version - so select Electron locally and run it and see if you can reproduce. (maybe open an issue)

Look back at answers in gitter or elsewhere.

**Comment by CypressCecelia** [comment]
This exists here https://docs.cypress.io/faq/questions/using-cypress-faq.html#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Closing issue.
