### ISSUE TITLE
Page Not Found for https://on.cypress.io/opening-the-app

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#6004]
## Current behavior

The link https://on.cypress.io/opening-the-app, which is displayed when executing `cypress install`, no longer works.

It redirects to https://docs.cypress.io/opening-the-app which displays the text "Page Not Found".

## Desired behavior

The vanity link
https://on.cypress.io/opening-the-app

should redirect to the active page

https://docs.cypress.io/app/get-started/open-the-app

## Test code to reproduce

```shell
mkdir cy-test
cd cy-test
git init
npm init -y
CYPRESS_INSTALL_BINARY=0 npm install cypress --save-dev
npx cypress install --force
```

## Cypress Version

`13.15.2`

## Node version

`v22.11.0` LTS

## Operating System

Ubuntu `24.04.1` LTS

## Logs

```text
$ npx cypress install --force
Installing Cypress (version: 13.15.2)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /home/mike/.cache/Cypress/13.15.2

You can now open Cypress by running one of the following, depending on your package manager:

- npx cypress open
- yarn cypress open
- pnpm cypress open

https://on.cypress.io/opening-the-app
```

## Other

This is a regression caused by a reorganization of the documentation site https://docs.cypress.io/ on Oct 22, 2024.

The source page was moved and renamed from

`docs/guides/getting-started/opening-the-app.mdx`

to

[docs/app/get-started/open-the-app.mdx](https://github.com/cypress-io/cypress-documentation/commits/main/docs/app/get-started/open-the-app.mdx)

**Comment by MikeMcC399** [comment]
This is a https://github.com/cypress-io/cypress-documentation/labels/type%3A%20bug rather than a https://github.com/cypress-io/cypress-documentation/labels/content%3A%20rewrite

**Comment by mschile** [comment]
@MikeMcC399, thanks for bringing this to our attention! I updated the vanity url to point to the correct document (this may take a few minutes to deploy).

**Comment by MikeMcC399** [comment]
@mschile 

> thanks for bringing this to our attention! I updated the vanity url to point to the correct document (this may take a few minutes to deploy).

Could you let me know when it is supposed to have deployed? Currently https://on.cypress.io/opening-the-app is still failing.
