### ISSUE TITLE
https://download.cypress.io/desktop.json ID error HTTP 500

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#6007]
### Description

Attempting to access https://download.cypress.io/desktop.json results in  
> {"error":"You must pass either an \"anonymousId\" or a \"userId\"."} 

In the browser network tab, the response is showing HTTP `500 Internal Server Error` 

- https://www.cypressstatus.com/ shows no error 
- https://www.cloudflarestatus.com/ shows no relevant issue

### URL of Issue(s)

https://docs.cypress.io/app/references/advanced-installation#Download-URLs

### Steps to replicate

1. View https://docs.cypress.io/app/references/advanced-installation#Download-URLs
2. Click on link https://download.cypress.io/desktop.json

### Browser

- Google Chrome Version 131.0.6778.85 (Official Build) (64-bit) 
- Mozilla Firefox 132.0.2 (64-bit)

### Device

- [X] PC
- [ ] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

This used to work.

**Comment by ryanthemanuel** [comment]
Thanks for pointing this out @MikeMcC399! There is a fix incoming in the cloud that will make that link work properly again. I'll keep this open until I can verify that it is working again.

**Comment by ryanthemanuel** [comment]
This is now working again. Navigating to `https://download.cypress.io/desktop.json` gives me:

```json
{
  "name": "Cypress",
  "version": "13.16.0",
  "packages": {
    "mac": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/darwin-x64/cypress.zip"
    },
    "linux64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/linux-x64/cypress.zip"
    },
    "darwin": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/darwin-x64/cypress.zip"
    },
    "linux": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/linux-x64/cypress.zip"
    },
    "darwin-x64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/darwin-x64/cypress.zip"
    },
    "darwin-arm64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/darwin-arm64/cypress.zip"
    },
    "linux-x64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/linux-x64/cypress.zip"
    },
    "linux-arm64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/linux-arm64/cypress.zip"
    },
    "win32-x64": {
      "url": "https://cdn.cypress.io/desktop/13.16.0/win32-x64/cypress.zip"
    }
  }
}
```
