### ISSUE TITLE
I want to call Cypress API api.cypress.io to add Tags to a Run. Where can I find documentation of this Backend API?

### ISSUE THREAD

**Issue by ashishmundra** [cypress-io/cypress-documentation#6015]
### Description

I want to call Cypress API api.cypress.io to add Tags to a Run. Where can I find documentation of this Backend API?

E.g. if there is a /runs or /tags Endpoint and what should there Payload be? How to know this documentation? I want to call it from a bash script.

**Comment by ryanthemanuel** [comment]
Hi @ashishmundra. The calls to api.cypress.io are not meant to be called outside of the running Cypress app. If you want the ability to add tags to a run that you're about to kick off via a bash script, you can use the [module API](https://docs.cypress.io/app/references/module-api) and pass in tags as an [option](https://docs.cypress.io/app/references/module-api#Options).

**Comment by ashishmundra** [comment]
I want to add tags to a run after the run has been completed.

I want to do it via my Github action that promotes my QA build to Prod Environment. I like to capture qa lead approved before this promotion happens and want to tag approved by and approval date with Cypress Test Run itself so that later I can show that for this release these are Test Run, and was approved by whom within Cypress Cloud.

How can I achieve that? If there was a cypress api that can add tags to a run, that could be called from Github Action or anywhere else. Is there any other way to achieve what I have mentioned?

If not, I will have to store Test Results in Cypress and Approving Test Results somewhere else.

**Comment by MikeMcC399** [comment]
@ashishmundra 

In case you are not aware, for "how-to" type support you can connect to the Cypress technical community on Discord

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

**Comment by jennifer-shehane** [comment]
@ashishmundra This capability doesn't exist today, but I'll raise it as a feature request to our Cloud team. Thanks for sharing. 

I'll close this issue as it's intended to be used for bugs or features wanted for the cypress-documentation repo.
