### ISSUE TITLE
Name supported Microsoft Windows server operating systems

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#6022]
## What would you like?

Add a description of supported servers, including Microsoft Windows Server, to clarify which server operating systems are supported by Cypress.

## Why is this needed?

The documentation section [Get Started > Install Cypress > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) states:

> Cypress is a desktop application that is installed on your computer. The desktop application supports these operating systems

It does not cover running Cypress on a server, such as in a Continuous Integration (CI) environment.

The separate [Continuous Integration > Overview > Advanced setup](https://docs.cypress.io/app/continuous-integration/overview#Advanced-setup) does not discuss the choice of operating system and refers back to the above [System requirements](https://docs.cypress.io/app/get-started/install-cypress#System-requirements) section which includes [Get Started > Install Cypress > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System).

For macOS and Linux, the core names of the server operating systems are the same as the desktop operating systems, so even though there is no mention of Cypress running on a particular server operating system, it may be deduced or implied.

For Microsoft Windows the Desktop and Server operating systems are only loosely linked. The names are different and there is no 1:1 correspondence between Desktop and Server names and releases.

Currently, [Get Started > Install Cypress > Operating System](https://docs.cypress.io/app/get-started/install-cypress#Operating-System) lists

> Windows 10 and above (x64)

as supported Desktop operating systems without naming any Microsoft Windows Server operating system.

[GitHub Actions - Runner Images](https://github.com/actions/runner-images) offers the following GitHub-hosted Microsoft Windows Server operating systems:

| Image               | YAML Label                         |
| ------------------- | ---------------------------------- |
| Windows Server 2022 | `windows-latest` or `windows-2022` |
| Windows Server 2019 | `windows-2019`                     |

Under [Windows Server major versions by servicing option](https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info#windows-server-major-versions-by-servicing-option--) Microsoft lists also

- Windows Server 2025
- Windows Server 2016

GitHub Actions is planning to introduce a Windows Server 2025 runner.

As a first step, it may be simplest to align with exactly the Microsoft Windows Server operating systems that GitHub Actions currently supports.

**Comment by jennifer-shehane** [comment]
Yah, this sounds reasonable

**Comment by MikeMcC399** [comment]
- PR #6037 submitted
