### ISSUE TITLE
FAQ: Performance testing outdated links for Lighthouse

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#6026]
## Issue

In the FAQ [Can Cypress be used for performance testing?](https://docs.cypress.io/app/faq#Can-Cypress-be-used-for-performance-testing) in the sentence:

> You can also [run Lighthouse audit straight from Cypress](https://www.testingwithmarie.com/post/web-performance-testing-with-google-lighthouse) via [cypress-audit](https://www.npmjs.com/package/cypress-audit) community plugin.

1. The link https://www.testingwithmarie.com/post/web-performance-testing-with-google-lighthouse produces a 404 error.
2. The plugin [cypress-audit](https://www.npmjs.com/package/cypress-audit) has been replaced, according to the documentation on https://mfrachet.github.io/cypress-audit/, which now recommends using:

   - [@cypress-audit/lighthouse](https://www.npmjs.com/package/@cypress-audit/lighthouse) - performance tool
   - [@cypress-audit/pa11y](https://www.npmjs.com/package/@cypress-audit/pa11y) - accessibility audit tool

## Suggestion

Review and update or remove the sentence in [Can Cypress be used for performance testing?](https://docs.cypress.io/app/faq#Can-Cypress-be-used-for-performance-testing) concerning Lighthouse audits.

Also consider the status of the outdated entry for [cypress-audit](https://www.npmjs.com/package/cypress-audit) in the [Plugins list - Development tools](https://docs.cypress.io/app/plugins/plugins-list#development-tools) section.

**Comment by jennifer-shehane** [comment]
Yah I'd probably remove those couple few sentences.

**Comment by MikeMcC399** [comment]
> Also consider the status of the outdated entry for [cypress-audit](https://www.npmjs.com/package/cypress-audit) in the [Plugins list - Development tools](https://docs.cypress.io/app/plugins/plugins-list#development-tools) section.

- Moved to new issue #6036

**Comment by MikeMcC399** [comment]
- PR #6035 submitted to update FAQ
