### ISSUE TITLE
Orphaned Test Replay limitations link

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#6054]
## Issue

The target https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay was removed by PR https://github.com/cypress-io/cypress-documentation/pull/5985. It was last present in 3f2c22c.

It is used in:

- https://docs.cypress.io/accessibility/core-concepts/how-it-works#Powered-by-Test-Replay
  > Because Cypress Accessibility uses data captured through Cypress Test Replay, it is subject [Test Replay limitations](https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay).

- https://docs.cypress.io/ui-coverage/get-started/introduction#How-it-Works
  > Because Cypress Accessibility uses data captured through Cypress Test Replay, it is subject to any [limitations of Test Replay](https://docs.cypress.io/faq/questions/cloud-faq#Is-everything-captured-and-replayed-in-Test-Replay) data captured and browser support.

Clicking on the link leaves the reader stranded with no content discernible which matches the theme: "limitations of Test Replay".

It used to contain the following content:

---

**Is everything captured and replayed in Test Replay?**

Our aim is to create an impactful debugging experience that covers the most ground for users. We will continue to expand support. Currently Test Replay does not support the following:

#### DOM elements

- Video ([see issue](https://github.com/cypress-io/cypress/issues/29903))
- Audio ([see issue](https://github.com/cypress-io/cypress/issues/29905))
- Objects that do not have `type="image/svg+xml"` ([see issue](https://github.com/cypress-io/cypress/issues/29904))
- Shadow DOM with `slotAssignment="manual"` ([see issue](https://github.com/cypress-io/cypress/issues/29107))
- Shadow DOM canvas ([see issue](https://github.com/cypress-io/cypress/issues/30438))

#### Browsers

- WebKit browser (Safari) ([see issue](https://github.com/cypress-io/cypress/issues/28895))
- Firefox browser ([see issue](https://github.com/cypress-io/cypress/issues/28894))

#### Other

- Server sent events ([see issue](https://github.com/cypress-io/cypress/issues/29908))
- Web sockets ([see issue](https://github.com/cypress-io/cypress/issues/29907))
- localStorage & sessionStorage ([see issue](https://github.com/cypress-io/cypress/issues/29909))
- Cookies ([see issue](https://github.com/cypress-io/cypress/issues/29910))
- Console props of Cypress commands outside of `cy.request()` ([see issue](https://github.com/cypress-io/cypress/issues/29911))

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

The alternatives would be:

1. Remove the paragraphs which reference "Test Replay limitations"
2. Add something back which describes limitations

This is more of an editorial decision / action than a simple editing task, so I leave its resolution to the Cypress.io team.

PS Happy holidays!

**Comment by jennifer-shehane** [comment]
@MikeMcC399 These links should link to this content: https://docs.cypress.io/cloud/features/test-replay#How-Test-Replay-Works I'd update the link wording to be 'it is subject to the [data captured in Test Replay]'

**Comment by MikeMcC399** [comment]
- Fixed in PR #6060
