### ISSUE TITLE
How much memory is recommended for the server 

### ISSUE THREAD

**Issue by kongbai-16** [cypress-io/cypress-documentation#6062]
### Description

How much memory does the server recommend? How many scripts can be parallelized at the same time? How many scripts can you run in 8GB?

**Comment by MikeMcC399** [comment]
@kongbai-16 

> How much memory does the server recommend?

Your question about memory recommendations is answered already in https://docs.cypress.io/app/get-started/install-cypress#Memory which says: "4GB minimum, 8GB+ for longer test runs"

> How many scripts can be parallelized at the same time? How many scripts can you run in 8GB?

This issue list is primarily for reporting issues with the documentation, not for asking support or "how-to" type questions. You may however be able to get some feedback and help from the Cypress technical community on Discord regarding the second part of your question.

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

Cypress parallelization is described under https://docs.cypress.io/cloud/features/smart-orchestration/parallelization
