### ISSUE TITLE
Title tags no longer mention Cypress

### ISSUE THREAD

**Issue by tyson-kubota** [cypress-io/cypress-documentation#610]
@jennifer-shehane A minor note, but while browsing the docs today, I noticed the title tags no longer say "Cypress" at all on most pages. I assume https://github.com/cypress-io/cypress-documentation/pull/609 was the cause? 

e.g. 
`Cypress.io Documentation | Assertions`
is now 
`Assertions`

This new format makes some of my bookmarks/browser tabs harder to grok.

If the above change was intentional, what would you think about using 

`Assertions | Cypress.io` or similar, so the pages are still identifiably from Cypress?

Thanks!

**Comment by jennifer-shehane** [comment]
Yes, I did make the change based off of some feedback - thinking it would make it easier. Especially to distinguish tabs between several doc tabs open and also Docs & Dashboard, since they use the same favicon. 

We can definitely add the name afterwards.

**Comment by tyson-kubota** [comment]
@jennifer-shehane Thanks!
