### ISSUE TITLE
replace large .gifs with smaller .mp4s

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-documentation#612]
- all `.gif` references now use `.mp4` and the `<video>` tag
- videos are lazy loaded (yalljs)  when users scroll near them, and have placeholder images of de-scaled first frame images
- mp4s are in the "snippets" folder - `./source/img/snippets/*.mp4`, along with corresponding `.png` placeholder image
- mp4s were from existing .gifs, except for the following, which came from source (so the following are high quality): 
    - debugging.mp4
    - installing-cli.mp4
    - installing-global.mp4
    - running-tests.mp4
    - writing-tests.mp4

we should probably work on getting higher quality videos for the others

- add `add-snippet` npm script, to take an existing gif or mp4 and put it in the source properly, it makes a placeholder image and runs it through ffmpeg

**Comment by Bkucera** [comment]
videos broken on safari and some mobile browsers, reopnening

**Comment by jennifer-shehane** [comment]
@Bkucera Should this be closed? Not sure why it didn't auto-close

**Comment by brian-mann** [comment]
Because it wasn't merged into `develop` I don't think..

Fixed by https://github.com/cypress-io/cypress-documentation/pull/623
