### ISSUE TITLE
Testing the <head> content - possible?

### ISSUE THREAD

**Issue by tivnet** [cypress-io/cypress-documentation#624]
Dear Cypress,

I am having trouble finding any mentioning of testing the HEAD content, besides the `title`. Specifically, check the META DESCRIPTION?

Highly appreciate if you point me to a doc page.

Thank you!

**Comment by Bkucera** [comment]
You should be able to access anything on the document as described here https://docs.cypress.io/api/commands/document.html#Examples

**Comment by tivnet** [comment]
@Bkucera Thank you, Ben, it wasn't clear to me from reading the docs. Now, after your explanation, I've got this working example:

    it("works!", () => {
        cy.visit("/");
        cy.document().get('head meta[name="description"]')
          .should("have.attr", "content", "Here goes the description...");
    });

Maybe you can include such example to the docs.

**Comment by Bkucera** [comment]
@tivnet the `cy.document()` is not actually doing anything in this case, since a `cy.get` will always act as if it is a new chain off of `cy`. You can just change your code to 
```
cy.get('head meta[name="description"]')
      .should("have.attr", "content", "Here goes the description...");
```

**Comment by tivnet** [comment]
Indeed. Do not know why it did not work for me. Do not even need the "head" part.

Thank you!
