### ISSUE TITLE
Add crossorigin attribute to all 3rd party scripts

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#643]
Sometimes e2e tests fail on CI with 3rd party syntax error

```
1) API Catalog of events "before each" hook for "loads catalog of events":
     Uncaught Error: Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the 'crossorigin' attribute and setting a CORS header.

https://on.cypress.io/cross-origin-script-error
```

Example of a failed build https://circleci.com/gh/cypress-io/cypress-documentation/3965#tests/containers/0

We can add `crossorigin` to 3rd party script builds to show the actual error

**Comment by nachocab** [comment]
@bahmutov could you explain how to do this? I keep running into these errors and I don't know how to set that attribute or the CORS headers in my local environment

**Comment by Jelle-vz** [comment]
@nachocab check your code and add 'crossorigin="anonymous"' to the third party script that is giving you problems.

See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes for the full spec
