### ISSUE TITLE
Update `Continuous Integration` doc for `3.0`

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-documentation#657]
- update CI config snippets to cache `~/.npm` and `~/.cache`
- suggest use of `npm ci` and `--prefer-offline`

- also update our repos that have CI configs, related:
  - https://github.com/cypress-io/cypress-example-docker-circle/issues/10
  - 

### stretch goal:
- add more ci provider config examples

**Comment by jnarowski** [comment]
can you share an example config with Cypress 3.0.1? I am not clear on how to set this up. Getting the error:
No version of Cypress is installed in: /home/circleci/.cache/Cypress/3.0.1/Cypress

**Comment by Bkucera** [comment]
@jnarowski we should have this example covered, are you caching `~/.cache` ? 
https://docs.cypress.io/guides/guides/continuous-integration.html#Example-circle-yml-v2-config-file

**Comment by jnarowski** [comment]
Thx, I copied it from here:
https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/.circleci/config.yml

**Comment by Bkucera** [comment]
@jnarowski was there anything missing from our `circleci` example you ended up using?
