### ISSUE TITLE
Move "Cypress Module API" into it's own doc

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#662]
- current: https://docs.cypress.io/guides/guides/command-line.html#Cypress-Module-API
- It's crammed at the bottom of the 'Command Line' even though....it's kind of not the command line
- We could expand on it and show more examples of how you could use it. 

@brian-mann, where would you put this new doc???

**Comment by brian-mann** [comment]
It's a reference unless we want to put like... recipes and examples and "how-tos" then it should be a Guide.
