### ISSUE TITLE
errant punctuation breaking hexo url links

### ISSUE THREAD

**Issue by ValerieThoma** [cypress-io/cypress-documentation#663]
misplaced period breaks hexo links to npm modules

<img width="681" alt="faq" src="https://user-images.githubusercontent.com/31670582/40805978-0574d5aa-64ee-11e8-8e14-91e34e500212.png">

**Comment by ValerieThoma** [comment]
@jennifer-shehane 
I believe this change was merged a few days ago, however, the urls still appear to _not appear_  (i.e., it's not rendering). Have you seen this with hexo before? I found one [issue](https://github.com/hexojs/hexo/issues/3115) in hexo, but could not glean anything from it. 
<img width="715" alt="production" src="https://user-images.githubusercontent.com/31670582/40935782-29488bae-6807-11e8-9192-8e3992de710d.png">
_deployed docs_

<img width="679" alt="local" src="https://user-images.githubusercontent.com/31670582/40935792-2fa4a1d6-6807-11e8-91e2-3bc3e2ec7ff1.png">

_working locally_

**Comment by jennifer-shehane** [comment]
Yeah, this should have gone out 3 days ago...

I'm completely unable to get it to display properly locally though either - I'm on the `develop` branch.

**Comment by ValerieThoma** [comment]
😓drats.

**Comment by ValerieThoma** [comment]
<img width="553" alt="screen shot 2018-06-15 at 11 28 44 am" src="https://user-images.githubusercontent.com/31670582/41476512-c26cf352-708f-11e8-972b-f9c41b57c5e8.png">

🙄Them fighting words. Taking another crack at the link for `wait-on` module.
