### ISSUE TITLE
CSS broken in docs-staging

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#67]
This commit seems to have broken the css in the https://docs-staging.cypress.io page. https://github.com/cypress-io/cypress-documentation/commit/5be5de4c0bc72e187d91f67118369e89944c9119

See the Cypress Test Video of the run, where the css is obviously not loading correctly: https://dashboard.cypress.io/#/projects/ma3dkn/runs/c28f9d36-1eef-4bcf-b4fb-8e9a4732ac4f/videos

And the Cypress Test Video on the commit before, where the css is fine: https://dashboard.cypress.io/#/projects/ma3dkn/runs/480835eb-3b6b-490d-a7c7-259a1275820c/videos

**We need to:**
1. Fix the bug
2. Write a test that ensures css is compiling and loading correctly after the deployment job on CI.

Can recreate locally running `NODE_ENV=staging npm start`. Ensure you are on Node 8 and have run `npm i` first.

**Comment by bahmutov** [comment]
When style.css is bundled correctly it will have rules for things like `#container', which makes it height 100% of the viewport

![screen shot 2017-09-12 at 2 29 02 pm](https://user-images.githubusercontent.com/2212006/30343622-2b1d9f20-97cc-11e7-80fb-81eb1e650f91.png)

we can do two tests:
- make sure the container height is equal to viewport height
- loaded document CSS rules have rules for `#container` element
