### ISSUE TITLE
Update cy.server() with correct Yield information

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#689]
It appears that the documentation is incorrect on what cy.server() yields. https://github.com/cypress-io/cypress/issues/1907

Doc needs to be updated to say server options are yielded from command.

**Comment by ValerieThoma** [comment]
I'm having a difficult time updating this doc. When I try to edit the 
>## Yields {% helper_icon yields %}
>{% yields null cy.server %}

I crash my server. I guess I've got to read more hexo docs for a better understanding of what arguments this format takes, because it is not working like I expect it to.

**Comment by jennifer-shehane** [comment]
Yeah, so we created some tags to help us just print generic 'yields' information, since it was becoming repetitive writing the same things over and over. https://github.com/cypress-io/cypress-documentation/blob/develop/lib/tags/yields.js#L1

Since cy.server() has a specific object it yields, this would actually be more similar to our location doc, where you don't even use the `yield` tag helper and just write it out yourself. https://github.com/cypress-io/cypress-documentation/blob/develop/source/api/commands/location.md#L42

**Comment by ValerieThoma** [comment]
I'm still having trouble discerning what should be listed in the `yields` category. My thinking is it should just say: 
- `cy.server()` yields default options.
- `cy.server()` cannot be chained further.

I don't think we want to list the default options all out again in bullet form, the way the `location` doc does, _because_ all of these default options are listed out in a table under Arguments. This feels redundant. I'm concerned with how to be explicit without creating a lot of extra words on the page. 

**from the server doc**
## Arguments  ...
<img width="606" alt="screen shot 2018-06-14 at 12 50 09 pm" src="https://user-images.githubusercontent.com/31670582/41426515-e5a6bdb2-6fd1-11e8-9767-084b4178bedd.png">

**Comment by jennifer-shehane** [comment]
```
{
  "xhrUrl": "__cypress/xhrs/",
  "method": "GET",
  "delay": 0,
  "status": 200,
  "headers": null,
  "response": null,
  "enable": true,
  "autoRespond": true,
  "waitOnResponses": null,
  "force404": false,
  "urlMatchingOptions": {
    "matchBase": true
  }
}
```
<img width="422" alt="screen shot 2018-06-14 at 2 11 28 pm" src="https://user-images.githubusercontent.com/1271364/41430023-df4736b2-6fdc-11e8-83e2-562987584cfe.png">

**Comment by jennifer-shehane** [comment]
We may be closing this issue in favor of reimplementation yielding `null` from `cy.server()` https://github.com/cypress-io/cypress/issues/1907#issuecomment-397399360

**Comment by jennifer-shehane** [comment]
cy.server() is now deprecated so this doc will be removed soon.
