### ISSUE TITLE
fix broken link in server docs 

### ISSUE THREAD

**Issue by ValerieThoma** [cypress-io/cypress-documentation#696]
<img width="654" alt="screen shot 2018-06-11 at 10 47 01 am" src="https://user-images.githubusercontent.com/31670582/41238794-d3c010ae-6d64-11e8-9cdb-0fc68161fa67.png">

>can change this option permanently 

this is ☝🏻styled as a link but this link goes nowhere

I believe it should go [here](https://docs.cypress.io/api/cypress-api/cypress-server.html#Options)

**Comment by oxmap** [comment]
@ValerieThoma maybe you should paste here a link to page where blnk link located.

**Comment by ValerieThoma** [comment]
@oxmap Thanks. This link was updated but this issue wasn't closed in the PR. ☺️
