### ISSUE TITLE
Add links to download previous versions of Chromium

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#707]
Chromium stores snapshots of every previous build of Chrome - but their system is god awful to search through and it's different for various operating systems.

My idea is that we can have a running list of previous versions of Chrome that we keep somewhere so that users can easily find previous versions and download them and use them in Cypress. It would be especially useful if their current version of Chrome automagically updates, and something is terribly broken in Cypress because of it.

@bahmutov bonus points if we could automate this process. Yes I know we could probably go overboard and all crazy like, and start hosting these ourselves or give you like a `cypress browser:install` command but to start, let's just do a simple list. I know there are services out there that you can be notified when a new browser version is created, and so maybe part 2 would be automatically creating a PR in the docs that updates some markdown.

**Comment by flotwig** [comment]
Jennifer mentioned these resources in Slack:

> Looking up releases: https://omahaproxy.appspot.com/
> Actual binaries: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html
> Current windows dev release example: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/624510/

We could probably create some kind of bot that regularly scrapes these datasources and updates the docs with links, or we could create a tiny web app dedicated to helping users obtain these versions that does the fetching and scraping in-browser.

**Comment by flotwig** [comment]
I built a little React SPA to do this. It scrapes omahaproxy for the latest releases, uses omahaproxy to find the base revision of Chromium, then scrapes chromium-browser-snapshots for the nearest revision to the base revision that is downloadable. It seems to work pretty well.

Check it out: https://chromium-downloads.chary.us/

**Comment by jennifer-shehane** [comment]
@flotwig omg omg omg omg. 😍😍😍😍😍😍😍😍

Not all of the links appear to work for me though.

<img width="690" alt="screen shot 2019-02-14 at 10 27 28 am" src="https://user-images.githubusercontent.com/1271364/52761796-3c0df300-3043-11e9-9186-e43d10d387bb.png">

I would also love if there were a section on the download page to just jump over to the changelog for that version - like https://chromium.googlesource.com/chromium/src/+log/72.0.3626.96..72.0.3626.109?pretty=fuller&n=10000

**Comment by brian-mann** [comment]
@flotwig I think we should either embed this directly in Cypress - or just give you a link/button in the Browser Selection dropdown that opens this up as a new tab in your primary browser. 

It would especially help users find older versions if their primary browser updates and breaks Cypress.

We could then host it as a static site somewhere on Cypress like https://browsers.cypress.io or something and even add more browser combinations as we add support for them.

**Comment by jennifer-shehane** [comment]
I think this would be a bit too much overload for most of our users. I would maybe add a 'troubleshooting' link or something here that goes to the docs where it is linked to download other versions.

**Comment by brian-mann** [comment]
I think we could clean it up and let the users choose chromium, and then their OS as filters and/or version number so it's not a gigantic table.

With a little UX help it won't be so bad.

**Comment by flotwig** [comment]
> Not all of the links appear to work for me though.

Yeah, it's weird. Sometimes the `omaha-proxy` `deps` endpoint just straight up doesn't return the `chromium_base_position` parameter we need. I just tried to load 73.0.3677.0 this morning and it works now. I changed the error messaging a little bit so it's less of a dead end for users.

> I would also love if there were a section on the download page to just jump over to the changelog for that version

I'm not sure to determine what the "previous" version was in order to automatically generate a changelog. For now I've added links to the commit on googlesource.com

> I think we could clean it up and let the users choose chromium, and then their OS as filters and/or version number so it's not a gigantic table.
> 
> With a little UX help it won't be so bad.

I think I'll add a filter bar to the top of the table, so users can choose the OS/release channel/version range they want to filter by. I'll probably default the OS to be the current user agent's OS.

What do you guys think about adding the link to https://browsers.cypress.io/ to the Help application menu in the desktop-gui? That way it's not too far out of the way.

**Comment by flotwig** [comment]
Added a little filter bar:

![peek 2019-02-14 16-48](https://user-images.githubusercontent.com/1151760/52819836-6037f700-3078-11e9-8273-928ba178d65b.gif)

I was thinking about it, and if we maintain the current URL structure, the desktop-gui can just send users to the specific URL for their operating system. e.g. an OS X user would be sent to https://browsers.cypress.io/mac to show only Mac versions by default.
