### ISSUE TITLE
Update cypress.run() yielded object

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#709]
https://docs.cypress.io/guides/guides/command-line.html#cypress-run-1

This has changed in 3.0 and now outputs a much larger, more complex object.

It looks very similar to this, but its deviated a bit from it here: https://github.com/cypress-io/cypress/issues/1248

Just need to run a real project with this and see what is output.

**Comment by jennifer-shehane** [comment]
Already fixed
