### ISSUE TITLE
Include badge / link to Cypress dashboard in readme

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#71]

**Comment by bahmutov** [comment]
Should point to https://dashboard.cypress.io/#/projects/ma3dkn/runs

**Comment by bahmutov** [comment]
Will use badge `https://img.shields.io/badge/cypress-dashboard-brightgreen.svg`
https://img.shields.io/badge/cypress-dashboard-brightgreen.svg
