### ISSUE TITLE
Document cypress.open() in Module API

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#710]
https://docs.cypress.io/guides/guides/command-line.html#Cypress-Module-API

This only has `cypress.run()`

**Comment by ValerieThoma** [comment]
👍🏻Perferct! 
Also another good argument for moving it to it's own [doc](https://github.com/cypress-io/cypress-documentation/issues/662). At this time @brian-mann is still in favor of this moving to a `References` doc.

**Comment by brian-mann** [comment]
I was in favor until I realized that the `cypress.run()` and `cypress.open()` commands allow for the configuration options that match everything on the page.

We could move it out but either have to duplicate explaining all the options or point you back to the command line doc. That's likely why it was created there in the first place.
