### ISSUE TITLE
Add as part of FAQ: 'how do I require a library with fs access'

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#714]
We commonly see users try to do this: https://github.com/cypress-io/cypress/issues/1963

They want to require an npm lib that has `fs` access in it. They can't do that, but it's easy to simply use `cy.task` or something else in order to access the background `node` process.

Need to make it clear / findable / searchable to do this.

**Comment by gelicia** [comment]
I think you'll want to update the docs here too https://docs.cypress.io/api/plugins/configuration-api.html#Promises
