### ISSUE TITLE
No examples on how to validate XHR response (body, content-type and other)

### ISSUE THREAD

**Issue by kapalkat** [cypress-io/cypress-documentation#719]
Like in a title. I have found only this:
https://github.com/cypress-io/cypress/issues/937

But there is only a short info:
```js
cy.route('GET', '/login').as('getLogin')
cy.get('#contactID').type('email@gmail.com')
cy.contains('Login').click()
cy.wait('@getLogin').then(function(xhr){
  // we can now access the low level xhr
  // that contains the request body,
  // response body, status, etc
})
```

How to access low level xhr? I would love to see some examples how to validate response body; for example: my response is:
```json
[{
    "Key": 16176,
    "LineName": "Line A",
    "displayFullName": "A-0300/0350 801"
  },
  {
    "Key": 14567,
    "LineName": "Line B",
    "displayFullName": "C-876867"
  }
]
```
I know that one element name should be A-0300/0350 801, now I want to verify that and also I need to retrieve it's Key.

**Comment by jennifer-shehane** [comment]
After accessing the array, it's mostly a matter of doing some functional programming to assert on what you want. Some examples - 

```js
cy.wait('@getLogin').then(function(xhr){
  const response = xhr.responseBody
  expect(response).to.have.property('LineName', 'Line A')
  
  const obj1Values = Cypress._.values(response[0])
  expect(obj1Values).to.deep.eq([16176, "Line A", "A-0300/0350 801"])
})
```

Hopefully this helps you get started!

**Comment by kapalkat** [comment]
Indeed it helped! Thanks.
BTW....Didn't know that Cypress supports lodash.

**Comment by rizwenbutt01** [comment]
I have the following JSON returned by the api which I am trying to assert the response on for enabled : true
`{"channelId":"C.G1.8R6GTPSQO9","userId":17151,"sendNotificationHour":0,"enabled":true,"lastSentDateTime":null,"lastSentMessageTimestamp":1541603830593}`

I am using the following line of code from your example above to try and assert the API response

`cy.wait('@SummaryNotificationGet').then(function (xhr) {
				const response = xhr.responseBody
				expect(response[0]).to.have.property('enabled', 'true')
			})`

But am getting the following error in cypress
TypeError: Cannot read property 'enabled' of undefined

**Comment by kapalkat** [comment]
> I have the following JSON returned by the api which I am trying to assert the response on for enabled : true
> 
> `{"channelId":"C.G1.8R6GTPSQO9","userId":17151,"sendNotificationHour":0,"enabled":true,"lastSentDateTime":null,"lastSentMessageTimestamp":1541603830593}`
> 
> I am using the following line of code from your example above to try and assert the API response
> 
> `cy.wait('@SummaryNotificationGet').then(function (xhr) { const response = xhr.responseBody expect(response[0]).to.have.property('enabled', 'true') })`
> 
> But am getting the following error in cypress
> TypeError: Cannot read property 'enabled' of undefined

Apart from that, it has nothing to do with the reported issue:) I assume you are trying to validate boolean as a string.

**Comment by rizwenbutt01** [comment]
The question is simply how to validate the response from an API as was in your original post,

I have picked one of the returned response values pairs ie,  enabled : true 
from the response blob and expected it to check if this was contained in it ,

**Comment by snak87** [comment]
> I have the following JSON returned by the api which I am trying to assert the response on for enabled : true
> 
> `{"channelId":"C.G1.8R6GTPSQO9","userId":17151,"sendNotificationHour":0,"enabled":true,"lastSentDateTime":null,"lastSentMessageTimestamp":1541603830593}`
> 
> I am using the following line of code from your example above to try and assert the API response
> 
> `cy.wait('@SummaryNotificationGet').then(function (xhr) { const response = xhr.responseBody expect(response[0]).to.have.property('enabled', 'true') })`
> 
> But am getting the following error in cypress
> TypeError: Cannot read property 'enabled' of undefined

It seems you trying to get the first element from a list; but the response is not a list.

try something like:
```
cy.wait('@SummaryNotificationGet').then(function (xhr) { const response = xhr.responseBody expect(response).to.have.property('enabled', 'true') })
```

**Comment by MarioPuzzo** [comment]
what  if I want to retrieve values from the response if it's a text/Html format?

**Comment by soomro12** [comment]
We have similar issue. How we validate values from the xhr response. waiting for answer

**Comment by bahmutov** [comment]
you can find examples here https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/#api-testing which is linked from https://on.cypress.io/network-requests page. The Network Requests page could use a couple of examples right under https://on.cypress.io/network-requests#Assertions section

**Comment by Kishorekumar2789** [comment]
Hi @jennifer-shehane, How can I verify an email id in api response which is created from UI.

Response return as an array but how to compare the created email id with response data?

**Sample Code:**
 cy.server();
    cy.route('GET', 'ENDPOINT').as('userlist');
/**email id created in UI*/
cy.wait('@userlist').then(function(res) {
       cy.log('Response: ' + res.responseBody);
    });

Sample Response:
[
{"id":"id1",
"emailid":"emailid1"
},
{"id":"id2",
"emailid":"emailid2"
}
]

![image](https://user-images.githubusercontent.com/42167657/73646587-0dd15b00-467a-11ea-96ac-f0c58a54ebd9.png)

**Comment by pranawaKumar** [comment]
I am new to cypress I want to value of the response from xhr and save it in fixture file
<img width="1761" alt="Screenshot 2021-04-22 at 4 27 47 PM" src="https://user-images.githubusercontent.com/60701846/115704054-7fcdb700-a388-11eb-9e99-2f409bd3cf2d.png">
how can i achive this
