### ISSUE TITLE
More clearly explain the async nature of aliases

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#722]
There's confusion about how to utilize defined aliases, due to the async nature of Cypress, which is understandable. There should be more examples/explanation of this clearly in the alias doc.

https://github.com/cypress-io/cypress/issues/948

**Comment by jimsmith1562** [comment]
i looked at "Fixtures aliasing not working as expected? #948"  and i am still confused as to what is the correct way to get to data in a jason file in the fixture directory. I tried multiple ways based on the comments in 984, but without success. My example does not work. Could anyone give me an example to explain what i am doing wrong?

Trying to get the json data from StyleData.json into an array called elements:

it('Gets the data', function() {
   //tried this
      cy.fixture('StyleData.json').as('Style')
      elements = Style.StyleData
  // and tried this
       cy.get('@Style').then((Style) => 
           let elements = Style.StyleData
        )
   ...

StyleData.json file contains:
 {
    "StyleData": [
        {
            "identifier": "Square",
            "border": "yes"
         }, {
            "identifier": "Square",
            "border": "yes"
         } ]}

**Comment by jimsmith1562** [comment]
Thanks @jennifer-shehane  and @richdouglasevans; much clearer for me now, and got it working.

**Comment by richdouglasevans** [comment]
I had a bash at this one Jennifer. Hopefully the PR more clearly explains the async nature of aliases, with added examples.

**Comment by richdouglasevans** [comment]
Can this ticket be `Closed` in light of the merge of #850 ?

**Comment by aaditya-kumar-harness** [comment]
@brian-mann @richdouglasevans Any idea why this is not working (v3.1.0):

describe('Knowledge Base Application', () => {
  before(() => {
    cy.fixture('users/admin').as('adminData')
  })

  it('test1', () => {
    cy.get('@adminData')
      .then(adminData => { // able to read adminData
        cy.log(adminData)
      })
  })

  it('test2', () => {
    cy.get('@adminData')
      .then(adminData => { // **throws exception: CypressError: cy.get() could not find a registered alias for: '@adminData'. You have not aliased anything yet.**
        cy.log(adminData)
      })
  })
})
This works fine if I move the fixture setup from before to beforeEach.

**Comment by jennifer-shehane** [comment]
@aaditya-kumar-harness Code in a `before` hook only runs once and once only. When it reaches the 2nd test: the `fixture` has been reset and needs to be reinvoked.

Replace the notion of `cy.fixture` with anything else in the `before` hook - whether its another cypress command, or other javascript code. It only makes sense to run once and will not affect nor have anything to do with the execution of test 2.

You just need to move the `before` hook to `beforeEach` since you intend it to run before each test and not just before the first test.
