### ISSUE TITLE
Small error on eq documentation

### ISSUE THREAD

**Issue by sampwil** [cypress-io/cypress-documentation#744]
The docs says 2nd row when it should say 3rd row: 

Make an assertion on the 2nd row of a table

https://docs.cypress.io/api/commands/eq.html#

![cypress eq documentation](https://user-images.githubusercontent.com/7925278/42046652-56e17044-7acc-11e8-91ab-b7ea74fb5d10.PNG)

**Comment by whitneyseiler** [comment]
Hey there - I'd love to take this! It'll be my first ever contribution :)

**Comment by richdouglasevans** [comment]
I think this one can be closed too Jennifer 👍

**Comment by richdouglasevans** [comment]
Hi @whitneyseiler

Pipped to the post on this one 

There are [lots of other open issues](https://github.com/cypress-io/cypress-documentation/labels/first-timers-only) for first timers only: your contribution on any of those would be super welcome 👍
