### ISSUE TITLE
Add/update docs with 'after:screenshot' plugin event

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-documentation#748]
* Add to [Writing a Plugin API doc](https://docs.cypress.io/api/plugins/writing-a-plugin.html#)
* Add a new API doc under Plugins
* Add to [Plugins guide](https://docs.cypress.io/guides/tooling/plugins-guide.html#Use-Cases)
* Reference it in the [cy.screenshot() doc](https://docs.cypress.io/api/commands/screenshot.html#Syntax)

**Comment by jennifer-shehane** [comment]
Need to add new page to cypress-on manifest https://github.com/cypress-io/cypress-on/issues/79
