### ISSUE TITLE
Issues while installing from zip file

### ISSUE THREAD

**Issue by abygeorgea** [cypress-io/cypress-documentation#761]
I am behind a corporate proxy which doesnt allow to download/installation from outside LAN.

I tried to install Cypress from Zip file ( 3.0.2) and it fails with below error.  How can I fix this issue?

Note: Unzipping the file and using directly is working fine. But I need to get this installation also to work 

Logs as below

```
D:\tmp>set CYPRESS_INSTALL_BINARY=D:/tmp/Installer/cypress.zip && npm install cypress -D

> cypress@3.0.2 postinstall D:\tmp\node_modules\cypress
> node index.js --exec install

 ×  Downloading Cypress
   → Cypress Version: 3.0.2
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/D:/tmp/Installer/cypress.zip?platform=win32&arch=x64
Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
----------

Platform: win32 (6.3.9600)
Cypress Version: 3.0.2
npm WARN enoent ENOENT: no such file or directory, open 'D:\tmp\package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.0.2 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.0.2 postinstall script 'node index.js --exec install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cypress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js --exec install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cypress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cypress
npm ERR! There is likely additional logging output above.
```

**Comment by Bkucera** [comment]
This is probably happening because `D:/tmp/Installer/cypress.zip` is not recognized as a valid path to the Cypress zip. Can you try downloading to a different directory and setting the env var to that?

**Comment by jennifer-shehane** [comment]
Hi @abygeorgea, were you able to try as @Bkucera recommended?

**Comment by abygeorgea** [comment]
I tried the solution by changing the folder. I still get same error. It tries to download from "https://download.cypress.io/desktop/" + The path where zip file is kept.  Error below.

I will try the same from my personal laptop outside of corporate network and restrictions and see how it go

### Error ###
Please check network connectivity and try again:
URL: https://download.cypress.io/desktop/C:/CypressInstaller/cypress.zip?platform=win32&arch=x64
Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
Platform: win32 (10.0.16299)
Cypress Version: 3.0.2

### Error ###
Please check network connectivity and try again:
URL: https://download.cypress.io/desktop/cypress.zip?platform=win32&arch=x64
Error: getaddrinfo ENOTFOUND download.cypress.io download.cypress.io:443
Platform: win32 (10.0.16299)
Cypress Version: 3.0.2

**Comment by sysleaf** [comment]
is there any update on this? on windows cmd, it try to concate the value of CYPRESS_INSTALL_BINARY to existing cypress download url(https://download.cypress.io).

it seems to be a problem with the way environment value is being read on windows... please note, on same windows..if we use git bash(linux based) terminal then it works perfectly fine

**Comment by sysleaf** [comment]
Got it work...by setting unix like path on windows cmd
```
SET CYPRESS_INSTALL_BINARY=C:/Users/vikash72.kumar/Downloads/cypress.zip
```

**Comment by Chinmayans44** [comment]
Same issue I am facing as sysleaf, but concatanation of url not solved for me :(

**Comment by jonasohrn** [comment]
Found a bug when you set a relative path for the binary at line 245 of lib/tasks/install.js: 
`var absolutePath = path.resolve(needVersion);
`
should not use variable 'neededVersion' so fix is this:
`var absolutePath = path.resolve(pathToLocalFile);
`

**Comment by jennifer-shehane** [comment]
Hey @jonasohrn, can you open an issue for this in our main repo [here](https://github.com/cypress-io/cypress/issues/new).
