### ISSUE TITLE
Update Installing Cypress doc and mention HTTP_PROXY env vars to download when behind corporate proxy

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#764]
I am really surprised to see this documented in an issue here https://github.com/cypress-io/cypress/issues/1469 yet not be mentioned in a single place in our primary docs.

Fixing the "corporate proxy issues" of the Desktop Application won't do anything to help people download and install it. No matter what, they'll need to set those environment variables in order to use us. This should be mentioned in the primary documentation with examples provided.

Also - most users behind a corporate proxy have already configured `npm` to get through the proxy, so it's likely useful to read through the npm docs on those best practices and ensure our users are doing that. If they are, then it likely already works. The http client we use: https://github.com/request/request already supports these out of the box.

It's worth mentioning that to users to point them to those docs - and to also read through them on setting up those proxies.

**Comment by jennifer-shehane** [comment]
Yes, this could definitely be mentioned in the Advanced section. Good idea. 👍
