### ISSUE TITLE
Algolia search is missing "changelog" page again

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#765]
Nothing meaningful when searching for "changelog"

<img width="1350" alt="screen shot 2018-07-06 at 8 25 47 pm" src="https://user-images.githubusercontent.com/2212006/42394584-e8215418-815a-11e8-8f06-fa646a526207.png">

Roadmap is there in the top search result

<img width="1379" alt="screen shot 2018-07-06 at 8 25 57 pm" src="https://user-images.githubusercontent.com/2212006/42394600-f905e050-815a-11e8-9f31-1d6c20815b04.png">

**Comment by jennifer-shehane** [comment]
Closing as outdated
