### ISSUE TITLE
Can we please add '$' before every terminal command

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#766]
The docs look so confusing and bad without the `$` being prefixed before every terminal command.

<img width="399" alt="screen shot 2018-07-09 at 12 17 36 pm" src="https://user-images.githubusercontent.com/1268976/42462772-30962cfa-8372-11e8-9dcb-c2ce6cc1fd43.png">

The `$` needs to be on every line. I'm not sure how you can do this in CSS, maybe we need to update the doc build process or something to give you a `<div>` or some other wrapper for each line number that you can target.

**Comment by jennifer-shehane** [comment]
some of the bash printout is actual printout, instead of command prompts, I'll have to review how many there are of these first before update all bash code blocks to look like this.

**Comment by jennifer-shehane** [comment]
There might not actually be an example of this - that's why I'd like to check
