### ISSUE TITLE
Update cy.log to note that markdown is accepted

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-documentation#778]
[cy.log()](https://docs.cypress.io/api/commands/log.html) can accept a markdown formatted message, but we don't document that.

**Comment by jennifer-shehane** [comment]
```javascript
cy.log('normal')
cy.log('**bold**')
cy.log('_italic_')
cy.log('[blue](http://example.com)')
```

![cy.log markdown example output](https://user-images.githubusercontent.com/1157043/42763758-f6b41ae0-88e1-11e8-8f60-28b4f651772c.png)

**Comment by richdouglasevans** [comment]
Can this issue be closed Jennifer? I can see Will's change [live on the site](https://docs.cypress.io/api/commands/log.html#Arguments).

**Comment by coler-j** [comment]
Seems like this was removed.

**Comment by Nuthan-hue** [comment]
If I need to give that color ,bold for a Variable.Then how can I do.

**Comment by bvandercar-vt** [comment]
This should definitely be re-opened, there's currently no documentation on it.

**Comment by jennifer-shehane** [comment]
The docs mention:

>Accepts a Markdown formatted message.

What more would you like documented?

**Comment by bvandercar-vt** [comment]
I see. Yes, that works.
