### ISSUE TITLE
FAQ - explain command chain retry logic

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#809]
https://github.com/cypress-io/cypress/issues/1210#issuecomment-359075731

**Comment by gabbersepp** [comment]
@jennifer-shehane 
There is no commit referenced. Had anyone documented this anywhere?

**Comment by jennifer-shehane** [comment]
@bahmutov wrote up an entire document about this. https://docs.cypress.io/guides/core-concepts/retry-ability.html
