### ISSUE TITLE
Update 'videoUploadOnPasses' to specify that processing and compression is skipped as well as upload.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#815]
https://docs.cypress.io/guides/references/configuration.html#Videos

Related: https://github.com/cypress-io/cypress/issues/2217#issue-345019128

**Comment by sendittokeith** [comment]
Thank you ...
It would be nice if there was an option not to save the video locally on success as well (or auto remove it on success or separate videos into a pass/fail folder).  :-)
