### ISSUE TITLE
Public API for start/end of all tests run

### ISSUE THREAD

**Issue by amitzur** [cypress-io/cypress-documentation#818]
Not sure this is a documentation issue, but the feature does exist in Cypress.
There's a need for listening to an event that fires when tests start running. I see 3 cases where this can happen when running `cypress open`:
1. Launch browser
2. Click on "run all tests" button
3. Reload the browser tab

When running `cypress run` this should happen only once, of course.

From inspecting the events that Cypress emits, I see `run:start` and `run:end` answer exactly this need. So the question is, can these be used as a public API for this hook? If so, I was right to think it's a documentation issue.

**Comment by amitzur** [comment]
I'm reopening this since root level `before` and `after` hook doesn't answer my need. I'm not sure if Cypress changed behavior between v2 and v3. I suspect parallelism might have affected it.
When running `cypress run`, every spec file is being run separately and root level `before` and `after` hooks that were defined in the `supportsFile` happen once for each file.

There is a need to have a way to run a hook one time at the beginning and one time at the end of the whole run of all the files

**Comment by jennifer-shehane** [comment]
@amitzur Yes, this behavior did change in the 3.0 release - that `before` and `after` run for each spec file. 

Perhaps our [Module API](https://docs.cypress.io/guides/guides/module-api.html#cypress-run) would suit your needs better. You can run any code before the `cypress.run()` and any code after in the resolved Promise.

**Comment by amitzur** [comment]
I cannot use the module API since we run Cypress in a straight forward and I wouldn't want to complicate that.
I do think this is an important hook, and can be achieved by providing plugins with the following API:
```
module.exports = (on, config) => {
  on('run:start', () => {...});
  on('run:end', () => {...});
}
```

By running localStorage.debug=* I noticed the events `run:start` and `run:end` provide this functionality. So I think the road to providing this functionality is short.

**Comment by jennifer-shehane** [comment]
Hey @amitzur, we agree. In fact the work for adding this hook has mostly been done and will be part of a future release. You can see those changes in these doc updates here: https://github.com/cypress-io/cypress-documentation/issues/890

**Comment by amitzur** [comment]
Thanks, that's great to know!
I only wonder if `run:before` and `run:after` are going to be available also in interactive mode. I believe there's no reason for them not to.

**Comment by jennifer-shehane** [comment]
@amitzur No, those would not be available in interactive mode. The run technically never 'ends' when in interactive mode since the browser stays open.

**Comment by gilgold** [comment]
Is there any update on this issue? I could really use those events right about now.. (all other solutions do not work / not relevant to my needs)

**Comment by jennifer-shehane** [comment]
@gilgold This issue is about documentation, not the Cypress product itself. See this issue for any actual events feature: https://github.com/cypress-io/cypress/issues/2840

I'm going to close this documentation issue - as the behavior of `before` and `after has been documented correctly now. The rest of the comments seem related to actually wanting new features in Cypress covered in https://github.com/cypress-io/cypress/issues/2840
