### ISSUE TITLE
Docs for dash app

### ISSUE THREAD

**Issue by James-E-Adams** [cypress-io/cypress-documentation#819]
Has anyone considered migrating the docs to [dash](https://kapeli.com/dash) format?

I guess I'd also like to gage interest for this - to see if it would be worth my time or anyone else's time to do this.

**Comment by jennifer-shehane** [comment]
Some of us internally use Dash, so I see some worth in this just from a personal perspective. I don't have any experience or knowledge of what it involved in this migration though.

**Comment by James-E-Adams** [comment]
Yeah I've never personally done it but there are enough docsets on there that I can't imagine it's crazy hard!

**Comment by t0lkman** [comment]
Would be really cool to have the docs in Dash

**Comment by chuckienorton** [comment]
+1
