### ISSUE TITLE
Add example of testing `datalist` to `.next()` and `.type()`

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#824]
From: https://github.com/cypress-io/cypress/issues/445#issuecomment-411432996

Can add example to `next.md` and `type.md`.

Testing a datalist:

```html
  <input list="fruit" />
  <datalist id="fruit">
    <option>Apple</option>
    <option>Banana</option>
    <option>Cantaloupe</option>
  </datalist>
```

```javascript
  cy.get('#fruit option').should('have.length', 3)
    .first().should('have.text', 'Apple')
    .next().should('have.text', 'Banana')
    .next().should('have.text', 'Cantaloupe')
  cy.get('input').type('Apple')
```

**Comment by malydok** [comment]
I'd like to contribute on this but after taking some time reading through the original issue and the docs of both `.next()` and `.type()` I can't really understand how this particular case is relevant to these pages. How would adding this example in both of the function pages make sense? The use cases of both functions in this `datalist` example are explained clearly in their respective docs. Where would the example fit inside the docs?

**Comment by jennifer-shehane** [comment]
I think this would just be another example to have in `.next()` doc under https://on.cypress.io/next#Examples:

```html  
<input list="fruit" />
  <datalist id="fruit">
    <option>Apple</option>
    <option>Banana</option>
    <option>Cantaloupe</option>
  </datalist>
```

```js
  cy.get('#fruit option')
    .first().should('have.text', 'Apple')
    .next().should('have.text', 'Banana')
    .next().should('have.text', 'Cantaloupe')
```

And this could be an example for testing datalist in `.type()` doc under https://on.cypress.io/type#Examples:

```html
  <input list="fruit" />
  <datalist id="fruit">
    <option>Apple</option>
    <option>Banana</option>
    <option>Cantaloupe</option>
  </datalist>
```

```js
 cy.get('input').type('Apple')
```
