### ISSUE TITLE
Be Explicit About The Scope Of Cypress.env

### ISSUE THREAD

**Issue by richdouglasevans** [cypress-io/cypress-documentation#828]
The documentation for [`Cypress.env()`](https://docs.cypress.io/api/cypress-api/env.html#Notes) states:

> We chose to use Cypress because changes to your environment variables take effect for the remainder of ALL tests.

Just clarify what is meant by _"ALL tests"_ in light of the breaking change to 3.0; from [the changelog](https://docs.cypress.io/guides/references/changelog.html#3-0-0) for that release:

> We now run each spec file in isolation from one another. This shouldn’t technically break anything, but if you have set up your tests in a way that requires the state of a previous spec file, this could potentially break your tests.

Raising this issue in response to [this comment](https://gitter.im/cypress-io/cypress?at=5b6dc386b3cbd23ffc23a074) on the Cypress Gitter:

> Shouldnt Cypress.env(k,v) persist between tests?
>
> i specs file1.js and file2.js, I run them both and file2.js cannot see file1.js environment

**Comment by richdouglasevans** [comment]
@jennifer-shehane I'm happy to do this one if you approve it 👍

**Comment by brian-mann** [comment]
The scope of this is now just the current spec file (since we exit the browser between specs).

**Comment by richdouglasevans** [comment]
Yes.

The isolation doesn't look to be in effect when you're running the `__all` spec... the isolation _is_ in effect but this requires knowing about the `_all` spec to explain the behaviour.

> I know, you're not meant to run all of the specs in interactive mode... but the button is there so it gets used.

I have distinct spec files that set and read environment variables set by `Cypress.env`.

```js
// first.spec
it("can set an env variable using Cypress.env.", function () {
    cy.log('Setting "bar" to "Bwahaha" using Cypress.env.')
    Cypress.env('bar', 'Bwahaha')
    
    cy.wrap(Cypress.env(bar)).should("eq", 'Bwahaha')
});

it("can see an env variable set in the same spec file using Cypress.env.", () => {
    cy.wrap(Cypress.env('bar')).should("eq", 'Bwahaha')
});
```
```js
// later.spec
it("cannot see env variable set in another spec using Cypress.env.", function () {
    cy.log(Cypress.env('bar')) // undefined
    cy.log(Cypress.env())      // {}
    cy.wrap(Cypress.env('bar')).should('be.undefined')
});
```

Running in headless mode demonstrates the isolation nicely.

<img width="738" alt="screen shot 2018-08-11 at 15 04 23" src="https://user-images.githubusercontent.com/1855109/43992858-c1625a14-9d7c-11e8-91a0-22a239c10344.png">

Running each spec individually in interactive mode again demonstrates the isolation.

<img width="942" alt="screen shot 2018-08-11 at 15 25 08" src="https://user-images.githubusercontent.com/1855109/43992861-c80ffa42-9d7c-11e8-97d4-e878724db92f.png">

Running all of the specs in interactive mode "breaks" the isolation. (I grok that it's not broken but the behaviour "looks" to be at odds right?)

<img width="951" alt="screen shot 2018-08-11 at 15 25 58" src="https://user-images.githubusercontent.com/1855109/43992866-ce5e75d6-9d7c-11e8-8b87-c9d3b253d5e8.png">

> I'm using `v3.0.3` of Cypress.

Anyways, just sharing. I'll submit a PR for this sometime next week.

**Comment by brian-mann** [comment]
Yes there is another issue open regarding running all the tests. It serves all the specs together

At some point we will update it to behave like running `cypress run`.
