### ISSUE TITLE
Document returning electron options from before:browser:launch

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-documentation#866]
In the [Browser Launching doc](https://docs.cypress.io/api/plugins/browser-launch-api.html), we should mention Electron and point to the [possible options you can return](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions).

**Comment by ertrzyiks** [comment]
This issue itself is already a treasure 🙇Thanks for that useful link. Is the doc update something I could help with maybe?

**Comment by jennifer-shehane** [comment]
Hey @ertrzyiks, yes, the link is actually within the "Electron" bullet point on the page already, but maybe it could be made clearer: https://github.com/cypress-io/cypress-documentation/edit/develop/source/api/plugins/browser-launch-api.md
