### ISSUE TITLE
Image-Fixture code example not working 

### ISSUE THREAD

**Issue by FrontendSophie** [cypress-io/cypress-documentation#880]
https://docs.cypress.io/api/utilities/blob.html#Image-Fixture
```js
// programmatically upload the logo
cy.fixture("images/logo.png").as("logo")
cy.get("input[type=file]").then(($input) => {

  // convert the logo base64 string to a blob
  return Cypress.Blob.base64StringToBlob(this.logo, "image/png").then((blob) => {

    // pass the blob to the fileupload jQuery plugin
    // used in your application's code
    // which initiates a programmatic upload
    $input.fileupload("add", { files: blob })
  })
})
```
Firstly, `this.logo` cannot be visited directly after declaration as https://github.com/cypress-io/cypress/issues/948  

Then, `$input.fileupload()` also cannot work directly here unless the plugin is there I think.  

So I open this issue as this part is a little confusing. Anyway, thanks for such a detailed documentation.  

BTW, I tried to find a workaround for upload and finally got a solution from here:  https://github.com/cypress-io/cypress/issues/170

**Comment by richdouglasevans** [comment]
Good one Sophie 🤔 I just had a wee go at that example and yeah, what you said 😄 👍 

@jennifer-shehane That example _could_ be rewritten to have a link to the relevant JQuery plugin and to call out to [the workarounds](https://github.com/cypress-io/cypress/issues/170) but.. phew, it feels like an example that should be about blobbing would be drowned out by all that extra gubbins.

Maybe a completely fresh example could replace the existing one? One that is an example of blobbing but nothing to do with file uploading? Then, when the file upload work is sorted an example could be added that showcases blobbing in the context of a sweet file upload.

Thoughts?

**Comment by jennifer-shehane** [comment]
I think the overwhelming amount of workarounds in [this issue](https://github.com/cypress-io/cypress/issues/170) has been the main blocker for not adding a fresh example the docs - it was going to take time to review people's solutions and choose the ones that make sense. 

I'm up for documenting any of those examples as long as they work and are clear about the circumstances that it works in - even updating the current one. I used the blob example from the docs years ago, so it's not even in use in our code anywhere today.

**Comment by FrontendSophie** [comment]
@richdouglasevans  @jennifer-shehane  Thanks for all of you kind responses 😃
