### ISSUE TITLE
Add/update docs for 6.0 changes

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-documentation#890]
* [Renaming pluginsFile to backgroundFile](https://github.com/cypress-io/cypress/pull/2408). Also restructure the API docs around plugins to fall in line with the new nomenclature.
* [cy.task handler merging](https://github.com/cypress-io/cypress/pull/2289)
* [New background events](https://github.com/cypress-io/cypress/pull/2331)
* [Background events that mirror driver events](https://github.com/cypress-io/cypress/pull/2309)
* Write a migration guide for the breaking changes

**Comment by jennifer-shehane** [comment]
Notes from recent discussion over changes:
![screen shot 2018-09-06 at 2 46 13 pm](https://user-images.githubusercontent.com/1271364/45178802-b0b34a80-b1e4-11e8-896f-af7925f4f3aa.png)

**Comment by chrisbreiding** [comment]
For each event, either in the table or in its own page, should communicate whether or not and how the event handler blocks.

* synchronously?
* promise-aware?
* do errors bubble up?
