### ISSUE TITLE
Fix the <h3> styles being displayed in the top and right aligned menus

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#907]
@jennifer-shehane Do you mind please fixing the best practices guide? the CSS is completely borked because you changed the `***` headings to `###` which turned them into `h3`. I believe you did this due to being able to link to them. 

I understand that part, but the content for those headings was never written to ever be displayed in either the top menu or the right aligned menus. I guess you could either change them back to `***` or update the menus to never display `<h3>` items. That way they would still be linkable, but would not affect menus. 

Right now it looks like a CSS bug at best. The varying degrees of white space are inconsistent, and there is no size or icon emphasis of sub items. Some are numbered, others are complete sentences, some are a single word, some repeat, and some have colons at the end of them.

https://docs.cypress.io/guides/references/best-practices.html 

EDIT: the error messages also have the same problem: https://docs.cypress.io/guides/references/error-messages.html

It's probably best just to fix all the menus in one shot. I remember updating other pages to revert them **back** to using `***` after I saw this messed up in right aligned menus. Let's just get them **all** to be consistent, and then either always use `###` or always use `***`. I vote for `###` because it has the upside of linking, and I believe the CSS styles were the same but they cannot display in the menus...

<img width="1102" alt="screen shot 2018-09-05 at 11 42 52 pm" src="https://user-images.githubusercontent.com/1268976/45133845-73f43e80-b165-11e8-8dc3-3fc48629b236.png">

<img width="1219" alt="screen shot 2018-09-05 at 11 43 01 pm" src="https://user-images.githubusercontent.com/1268976/45133846-75be0200-b165-11e8-9731-2219c7618875.png">

**Comment by jennifer-shehane** [comment]
@richdouglasevans already fixed the main issue we had with the H3 headings before. See https://github.com/cypress-io/cypress-documentation/pull/858/files#diff-98ecf18d30da3ccb073f95ab1f568bee

But, it looks like the page layouts with the table of contents at the top need to have their depth level updated as well.

**Comment by richdouglasevans** [comment]
My bad: I didn't apply the fix consistently across all the pages. Apologies.
