### ISSUE TITLE
Add cypress-app-watcher-preprocessor to the plugins page

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#909]
Great little utility

Github repo: https://github.com/TheBrainFamily/cypress-app-watcher-preprocessor
tweet: https://twitter.com/lgandecki/status/1037377760044503040

Need to try it on some project that has reload server

**Comment by lgandecki** [comment]
Hey @bahmutov Did you have a chance to test? 
I could make a simple repo (create-react-app + express with apollojs) for you if you wanted to play around.

**Comment by bahmutov** [comment]
Hi @lgandecki I actually forgot it I tried it :) I think I did though, let me actually include it in our docs
