### ISSUE TITLE
setup -> set up

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#91]
**It's grammatically correct to say 'Set up tests'**
- 'set up' is two words when describing a verb/action. *'To set up your project'*
- 'setup' = one word when it is an adjective or noun, e.g. *'Complete the setup process'*, *'During setup of the Dashboard Service'*

There are likely many instances of our documentation using 'setup' when we really mean 'set up'. These should be updated.

**Comment by nsuchy** [comment]
@jennifer-shehane What is preferred in this project as branch names when doing a PR? E.g. patch-1, issue-fix-1, etc.

**Comment by brian-mann** [comment]
Is this done? Can this be closed. I see the PR merged. @jennifer-shehane was there any more work that needed to be done for this?
