### ISSUE TITLE
Set no-verify link by default

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#931]
When we run locally with `npm start` we should skip link validation by default - it is taking too long

```
$ npm start

> cypress-documentation@0.0.0 start /Users/gleb/git/cypress-documentation
> node --stack-size=8192 ./index.js server --port 2222

disabling filter cleanup for environment development
in environment development site url is https://docs.cypress.io
NODE_ENV is: development
INFO  Start processing
Request to: https://vimeo.com/242961930#t=264s failed.
Request to: https://www.npmjs.com/ failed.
...
```

**Comment by richdouglasevans** [comment]
Yes please.

I always run it with the validation off anyway... I used to run the validation once right at the end of the documentation process just before pushing... but whew, I stopped doing even that 'cos it took too long 😊

**Comment by jennifer-shehane** [comment]
Aww, am I the only one that runs the validator. 😢
