### ISSUE TITLE
Extra word in sentence

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#951]
> I just wanted to inform you all of trivial grammar error on the page: https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Snapshots. I've highlighted the sentence in the attached snapshot, which should read "you may still see the same
page" rather than "you may see still see the same page". Just wanted to point that out in case you wanted to correct it.

<img width="1440" alt="screen-shot-2018-09-14-at-2-00-14-pm" src="https://user-images.githubusercontent.com/1271364/45571045-f9957f80-b832-11e8-9a0f-f1e9b0a35c05.png">

**Comment by vidushi4** [comment]
Hey @jennifer-shehane 
I fixed the issue in PR #956 . Please review. 
Thanks!
