### ISSUE TITLE
Parallelization Polish Updates

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#958]
- [x] Add headers to info boxes
- [x] Run completion delay should refer to "past history" as "recent history"
- [x] Improve clarity of images by remove possibly confusing box shadows
- [x] Connections showing CI boxes share a common CI build ID should directly touch the box and not be spaced slightly away from the box.

**Comment by jennifer-shehane** [comment]
Can we have an example of 'grouping' via environment --staging and --dev? I was explaining this to someone and had nowhere to link them to an example.

**Comment by amirrustam** [comment]
Isn't the `--dev` CLI flag an internal thing? Or do you mean naming groups based on environment?

**Comment by jennifer-shehane** [comment]
Yeah naming groups off of environment, sorry meant to write `--group staging` and `--group dev`

**Comment by jennifer-shehane** [comment]
Point out where the groups are in the photos - like add arrows pointing them out.
