### ISSUE TITLE
Parallelization doc should reference blog posts of ours in the "Notes" section at the bottom for further reading

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-documentation#968]
Whenever we have good external content that helps show and provide a use case such as a blog, or a example recipe, repo, etc - we need to be sure to reference that in each doc. This is typically done as a "Note" at the bottom.

Also - although I realize this is circular - we should do the same thing for the other way around. The external content (like blogs, repos, etc) should also point inwards to the doc.

Anyone can take this, its low hanging fruit.

@amirrustam @anjanab96 @lilaconlee @jennifer-shehane

**Comment by amirrustam** [comment]
I'll take care of this as I've made an issue for some parallelization doc polish updates: https://github.com/cypress-io/cypress-documentation/issues/958

**Comment by jennifer-shehane** [comment]
No longer needed
