### ISSUE TITLE
File watching behavior vs Expectations

### ISSUE THREAD

**Issue by avanslaars** [cypress-io/cypress-documentation#97]
After splitting some tests up into multiple files and using "Run All Tests", I lost the watch behavior. I now understand that this is the designed behavior but it isn't obvious from the docs. 

When it stopped watching and I thought it should be, I first searched the docs for "watch" and I ended up on the configuration page. Maybe we could call this out in the `watchForFileChanges` part of the config documentation?

**Comment by richdouglasevans** [comment]
In light of #829 being merged can this ticket be `Closed`? Or is there more work to do?

**Comment by jennifer-shehane** [comment]
Yes
