### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress-documentation#976]
Your framework is awesome! And it would be really cool to have a document on how to setup autocompletion in vim. For example for youcompleteme plugin. And thank you for your great job!

**Comment by bahmutov** [comment]
@lilaconlee see what you can do, and if there is something (or nothing) that can be done, add notes to https://docs.cypress.io/guides/tooling/intelligent-code-completion.html page

**Comment by ranjithnori** [comment]
@lilaconlee Is vim auto completion going to be supported any soon ?

**Comment by lilaconlee** [comment]
@ranjithnori I haven't figured out a good way to do autocompletion yet, but it should be doable at the moment without any changes to Cypress. I'm not sure when I'll get a chance to figure out a solution and document it, but we'd definitely be open to community contributions here if you'd like to give it a go!

**Comment by conradob** [comment]
With [coc.nvim](https://github.com/neoclide/coc.nvim) you can have intellisense for not only Cypress but for any other JS and TS project/library.

It's possible also to configure the project's eslint to use https://github.com/cypress-io/eslint-plugin-cypress.

Here is an screenshot in vim.
![pic-selected-201130-1625-25](https://user-images.githubusercontent.com/1469697/100636324-7f754680-3329-11eb-9cce-b65fddf13bd2.png)
