### ISSUE TITLE
Content overlaps right nav

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress-documentation#996]
Looks like we need a lil media query tweaking. Could be a duplicate, but didn't see an obvious similar issue. 

This is on https://docs.cypress.io/guides/references/configuration.html#Options
<img width="454" alt="screen shot 2018-09-28 at 4 16 03 pm" src="https://user-images.githubusercontent.com/7514489/46233920-228d3880-c33a-11e8-98c8-316632bae813.png">

**Comment by lilaconlee** [comment]
The look in the PR is: ![screen shot 2018-09-28 at 5 07 14 pm](https://user-images.githubusercontent.com/7514489/46236010-8a478180-c342-11e8-8064-78262888721f.png)

Not sure if that's preferable to just making the jump to mobile sooner.

**Comment by richdouglasevans** [comment]
> Not sure if that's preferable to just making the jump to mobile sooner.

+1 for jumping to mobile sooner 😄

**Comment by lilaconlee** [comment]
Gonna hold off on this until #971 is out
